import Mathlib
import Mathlib.NumberTheory.NumberField.ClassNumber
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem

/-!
# The cubic field in the Billing--Mahler order-11 descent

This file develops the explicit cubic field generated by an element `alpha`
with

`alpha^3 - 4 * alpha^2 + 4 * alpha - 2 = 0`.

If `theta^3 - 4 * theta - 4 = 0`, then `alpha = theta^2 / 2` and
`theta = alpha^2 - 2 * alpha`.  The power basis `1, alpha, alpha^2`
is therefore the integral basis `1, theta, theta^2 / 2` used by Billing
and Mahler, only in a more convenient order.
-/

namespace MazurProof.BillingMahlerField

open Polynomial
open Module
open NumberField.InfinitePlace
open scoped NumberField

noncomputable def cubicPolyInt : ℤ[X] :=
  X ^ 3 - 4 * X ^ 2 + 4 * X - 2

noncomputable def cubicPoly : ℚ[X] :=
  cubicPolyInt.map (algebraMap ℤ ℚ)

private lemma cubicPolyInt_monic : cubicPolyInt.Monic := by
  unfold cubicPolyInt
  monicity!

private lemma cubicPolyInt_natDegree : cubicPolyInt.natDegree = 3 := by
  unfold cubicPolyInt
  compute_degree!

private lemma cubicPolyInt_eisenstein_two :
    cubicPolyInt.IsEisensteinAt (Ideal.span ({(2 : ℤ)} : Set ℤ)) := by
  let P : Ideal ℤ := Ideal.span ({(2 : ℤ)} : Set ℤ)
  have hPne : P ≠ ⊤ := by
    rw [ne_eq, Ideal.span_singleton_eq_top]
    norm_num [Int.isUnit_iff]
  refine cubicPolyInt_monic.isEisensteinAt_of_mem_of_notMem hPne ?_ ?_
  · intro n hn
    rw [cubicPolyInt_natDegree] at hn
    interval_cases n <;>
      norm_num [cubicPolyInt, coeff_X_pow, coeff_X, P, Ideal.mem_span_singleton]
  · rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    norm_num [cubicPolyInt]

private lemma cubicPolyInt_irreducible : Irreducible cubicPolyInt := by
  apply cubicPolyInt_eisenstein_two.irreducible
  · exact (Ideal.span_singleton_prime (by norm_num)).2 (by norm_num)
  · exact cubicPolyInt_monic.isPrimitive
  · rw [cubicPolyInt_natDegree]
    norm_num

theorem cubicPoly_irreducible : Irreducible cubicPoly := by
  exact (cubicPolyInt_monic.isPrimitive.irreducible_iff_irreducible_map_fraction_map).mp
    cubicPolyInt_irreducible

instance cubicPolyIrreducibleFact : Fact (Irreducible cubicPoly) :=
  ⟨cubicPoly_irreducible⟩

theorem cubicPoly_monic : cubicPoly.Monic := by
  rw [cubicPoly]
  exact cubicPolyInt_monic.map (algebraMap ℤ ℚ)

theorem cubicPoly_natDegree : cubicPoly.natDegree = 3 := by
  rw [cubicPoly, cubicPolyInt_monic.natDegree_map (algebraMap ℤ ℚ)]
  exact cubicPolyInt_natDegree

abbrev K : Type := AdjoinRoot cubicPoly

noncomputable def alpha : K := AdjoinRoot.root cubicPoly

noncomputable def powerBasis : PowerBasis ℚ K :=
  AdjoinRoot.powerBasis cubicPolyIrreducibleFact.out.ne_zero

noncomputable def basis : Basis (Fin 3) ℚ K :=
  powerBasis.basis.reindex (finCongr (by simpa [powerBasis] using cubicPoly_natDegree))

@[simp] theorem powerBasis_gen : powerBasis.gen = alpha := rfl

theorem basis_apply (i : Fin 3) : basis i = alpha ^ (i : ℕ) := by
  simp [basis, powerBasis, alpha]

theorem finrank_K : Module.finrank ℚ K = 3 := by
  rw [PowerBasis.finrank powerBasis]
  simpa [powerBasis] using cubicPoly_natDegree

theorem cubicPoly_eq : cubicPoly = X ^ 3 - 4 * X ^ 2 + 4 * X - 2 := by
  ext n
  simp [cubicPoly, cubicPolyInt]

theorem alpha_relation : alpha ^ 3 - 4 * alpha ^ 2 + 4 * alpha - 2 = 0 := by
  change AdjoinRoot.mk cubicPoly (X ^ 3 - 4 * X ^ 2 + 4 * X - 2) = 0
  rw [← cubicPoly_eq, AdjoinRoot.mk_self]

theorem alpha_cubed : alpha ^ 3 = 4 * alpha ^ 2 - 4 * alpha + 2 := by
  linear_combination alpha_relation

theorem alpha_fourth : alpha ^ 4 = 12 * alpha ^ 2 - 14 * alpha + 8 := by
  calc
    alpha ^ 4 = alpha * alpha ^ 3 := by ring
    _ = alpha * (4 * alpha ^ 2 - 4 * alpha + 2) := by rw [alpha_cubed]
    _ = 4 * alpha ^ 3 - 4 * alpha ^ 2 + 2 * alpha := by ring
    _ = 12 * alpha ^ 2 - 14 * alpha + 8 := by
      rw [alpha_cubed]
      ring

noncomputable def ofCoords (a b c : ℚ) : K :=
  algebraMap ℚ K a + algebraMap ℚ K b * alpha + algebraMap ℚ K c * alpha ^ 2

private theorem ofCoords_eq_basis_sum (a b c : ℚ) :
    ofCoords a b c =
      a • basis (0 : Fin 3) + b • basis (1 : Fin 3) + c • basis (2 : Fin 3) := by
  simp [ofCoords, basis_apply, Algebra.smul_def]

@[simp] theorem basis_repr_ofCoords_zero (a b c : ℚ) :
    basis.repr (ofCoords a b c) (0 : Fin 3) = a := by
  rw [ofCoords_eq_basis_sum]
  simp

@[simp] theorem basis_repr_ofCoords_one (a b c : ℚ) :
    basis.repr (ofCoords a b c) (1 : Fin 3) = b := by
  rw [ofCoords_eq_basis_sum]
  simp

@[simp] theorem basis_repr_ofCoords_two (a b c : ℚ) :
    basis.repr (ofCoords a b c) (2 : Fin 3) = c := by
  rw [ofCoords_eq_basis_sum]
  simp

theorem exists_ofCoords (u : K) : ∃ a b c : ℚ, u = ofCoords a b c := by
  let a := basis.repr u (0 : Fin 3)
  let b := basis.repr u (1 : Fin 3)
  let c := basis.repr u (2 : Fin 3)
  refine ⟨a, b, c, ?_⟩
  apply basis.repr.injective
  ext i
  fin_cases i <;> simp [a, b, c]

theorem ofCoords_injective : Function.Injective (fun p : ℚ × ℚ × ℚ ↦
    ofCoords p.1 p.2.1 p.2.2) := by
  rintro ⟨a, b, c⟩ ⟨a', b', c'⟩ h
  have hrepr := congrArg basis.repr h
  have hzero := congrArg (fun f ↦ f (0 : Fin 3)) hrepr
  have hone := congrArg (fun f ↦ f (1 : Fin 3)) hrepr
  have htwo := congrArg (fun f ↦ f (2 : Fin 3)) hrepr
  exact Prod.ext (by simpa using hzero) <| Prod.ext (by simpa using hone) (by simpa using htwo)

theorem ofCoords_sq (a b c : ℚ) :
    ofCoords a b c ^ 2 = ofCoords
      (a ^ 2 + 4 * b * c + 8 * c ^ 2)
      (2 * a * b - 8 * b * c - 14 * c ^ 2)
      (b ^ 2 + 2 * a * c + 8 * b * c + 12 * c ^ 2) := by
  unfold ofCoords
  push_cast
  ring_nf
  rw [alpha_fourth, alpha_cubed]
  norm_num
  ring

noncomputable def epsilon : K := alpha - 1

theorem epsilon_mul_inverse :
    epsilon * (alpha ^ 2 - 3 * alpha + 1) = 1 := by
  unfold epsilon
  linear_combination alpha_relation

theorem alpha_isIntegral : IsIntegral ℤ alpha := by
  refine ⟨cubicPolyInt, cubicPolyInt_monic, ?_⟩
  simpa [cubicPolyInt, alpha] using alpha_relation

theorem epsilon_isIntegral : IsIntegral ℤ epsilon :=
  alpha_isIntegral.sub isIntegral_one

noncomputable def epsilonInteger : NumberField.RingOfIntegers K :=
  ⟨epsilon, epsilon_isIntegral⟩

@[simp] theorem epsilonInteger_coe_K :
    ((epsilonInteger : NumberField.RingOfIntegers K) : K) = epsilon :=
  rfl

noncomputable def epsilonUnit : (NumberField.RingOfIntegers K)ˣ where
  val := epsilonInteger
  inv := ⟨alpha ^ 2 - 3 * alpha + 1,
    by
      have h : IsIntegral ℤ (alpha ^ 2 - 3 • alpha + 1) :=
        (alpha_isIntegral.pow 2).sub (alpha_isIntegral.nsmul 3) |>.add isIntegral_one
      exact (mem_integralClosure_iff ℤ K).mpr (by simpa [nsmul_eq_mul] using h)⟩
  val_inv := Subtype.ext epsilon_mul_inverse
  inv_val := Subtype.ext (by rw [mul_comm]; exact epsilon_mul_inverse)

@[simp] theorem epsilonUnit_coe_integer :
    ((epsilonUnit : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K) = epsilonInteger :=
  rfl

@[simp] theorem epsilonUnit_coe_K :
    ((epsilonUnit : (NumberField.RingOfIntegers K)ˣ) : K) = epsilon := by
  simp [epsilonUnit, epsilonInteger]

/-! ## The power-basis discriminant -/

noncomputable def minpolyDerivativeValue : K :=
  3 * alpha ^ 2 - 8 * alpha + 4

private theorem minpolyDerivativeValue_mul_basis_zero :
    minpolyDerivativeValue * basis (0 : Fin 3) = ofCoords 4 (-8) 3 := by
  simp [minpolyDerivativeValue, basis_apply, ofCoords]
  ring

private theorem minpolyDerivativeValue_mul_basis_one :
    minpolyDerivativeValue * basis (1 : Fin 3) = ofCoords 6 (-8) 4 := by
  rw [basis_apply]
  norm_num
  unfold minpolyDerivativeValue ofCoords
  push_cast
  ring_nf
  rw [alpha_cubed]
  norm_num
  ring

private theorem minpolyDerivativeValue_mul_basis_two :
    minpolyDerivativeValue * basis (2 : Fin 3) = ofCoords 8 (-10) 8 := by
  rw [basis_apply]
  norm_num
  unfold minpolyDerivativeValue ofCoords
  push_cast
  ring_nf
  rw [alpha_fourth, alpha_cubed]
  norm_num
  ring

private theorem repr_minpolyDerivativeValue_mul_basis_zero (i : Fin 3) :
    basis.repr (minpolyDerivativeValue * basis (0 : Fin 3)) i =
      ![(4 : ℚ), -8, 3] i := by
  rw [minpolyDerivativeValue_mul_basis_zero]
  fin_cases i
  · simpa using basis_repr_ofCoords_zero (4 : ℚ) (-8) 3
  · simpa using basis_repr_ofCoords_one (4 : ℚ) (-8) 3
  · simpa using basis_repr_ofCoords_two (4 : ℚ) (-8) 3

private theorem repr_minpolyDerivativeValue_mul_basis_one (i : Fin 3) :
    basis.repr (minpolyDerivativeValue * basis (1 : Fin 3)) i =
      ![(6 : ℚ), -8, 4] i := by
  rw [minpolyDerivativeValue_mul_basis_one]
  fin_cases i
  · simpa using basis_repr_ofCoords_zero (6 : ℚ) (-8) 4
  · simpa using basis_repr_ofCoords_one (6 : ℚ) (-8) 4
  · simpa using basis_repr_ofCoords_two (6 : ℚ) (-8) 4

private theorem repr_minpolyDerivativeValue_mul_basis_two (i : Fin 3) :
    basis.repr (minpolyDerivativeValue * basis (2 : Fin 3)) i =
      ![(8 : ℚ), -10, 8] i := by
  rw [minpolyDerivativeValue_mul_basis_two]
  fin_cases i
  · simpa using basis_repr_ofCoords_zero (8 : ℚ) (-10) 8
  · simpa using basis_repr_ofCoords_one (8 : ℚ) (-10) 8
  · simpa using basis_repr_ofCoords_two (8 : ℚ) (-10) 8

private theorem leftMulMatrix_entry_zero_zero :
    Algebra.leftMulMatrix basis minpolyDerivativeValue (0 : Fin 3) (0 : Fin 3) = 4 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul]
  exact repr_minpolyDerivativeValue_mul_basis_zero 0

private theorem leftMulMatrix_entry_one_zero :
    Algebra.leftMulMatrix basis minpolyDerivativeValue (1 : Fin 3) (0 : Fin 3) = -8 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul]
  exact repr_minpolyDerivativeValue_mul_basis_zero 1

private theorem leftMulMatrix_entry_two_zero :
    Algebra.leftMulMatrix basis minpolyDerivativeValue (2 : Fin 3) (0 : Fin 3) = 3 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul]
  exact repr_minpolyDerivativeValue_mul_basis_zero 2

private theorem leftMulMatrix_entry_zero_one :
    Algebra.leftMulMatrix basis minpolyDerivativeValue (0 : Fin 3) (1 : Fin 3) = 6 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul]
  exact repr_minpolyDerivativeValue_mul_basis_one 0

private theorem leftMulMatrix_entry_one_one :
    Algebra.leftMulMatrix basis minpolyDerivativeValue (1 : Fin 3) (1 : Fin 3) = -8 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul]
  exact repr_minpolyDerivativeValue_mul_basis_one 1

private theorem leftMulMatrix_entry_two_one :
    Algebra.leftMulMatrix basis minpolyDerivativeValue (2 : Fin 3) (1 : Fin 3) = 4 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul]
  exact repr_minpolyDerivativeValue_mul_basis_one 2

private theorem leftMulMatrix_entry_zero_two :
    Algebra.leftMulMatrix basis minpolyDerivativeValue (0 : Fin 3) (2 : Fin 3) = 8 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul]
  exact repr_minpolyDerivativeValue_mul_basis_two 0

private theorem leftMulMatrix_entry_one_two :
    Algebra.leftMulMatrix basis minpolyDerivativeValue (1 : Fin 3) (2 : Fin 3) = -10 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul]
  exact repr_minpolyDerivativeValue_mul_basis_two 1

private theorem leftMulMatrix_entry_two_two :
    Algebra.leftMulMatrix basis minpolyDerivativeValue (2 : Fin 3) (2 : Fin 3) = 8 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul]
  exact repr_minpolyDerivativeValue_mul_basis_two 2

theorem norm_minpolyDerivativeValue :
    Algebra.norm ℚ minpolyDerivativeValue = 44 := by
  rw [Algebra.norm_eq_matrix_det basis, Matrix.det_fin_three,
    leftMulMatrix_entry_zero_zero, leftMulMatrix_entry_zero_one,
    leftMulMatrix_entry_zero_two, leftMulMatrix_entry_one_zero,
    leftMulMatrix_entry_one_one, leftMulMatrix_entry_one_two,
    leftMulMatrix_entry_two_zero, leftMulMatrix_entry_two_one,
    leftMulMatrix_entry_two_two]
  norm_num

private theorem alpha_mul_basis_zero :
    alpha * basis (0 : Fin 3) = ofCoords 0 1 0 := by
  simp [basis_apply, ofCoords]

private theorem alpha_mul_basis_one :
    alpha * basis (1 : Fin 3) = ofCoords 0 0 1 := by
  simp [basis_apply, ofCoords]
  norm_num
  ring_nf

private theorem alpha_mul_basis_two :
    alpha * basis (2 : Fin 3) = ofCoords 2 (-4) 4 := by
  rw [basis_apply]
  norm_num
  unfold ofCoords
  push_cast
  ring_nf
  rw [alpha_cubed]
  norm_num
  ring_nf

private theorem alpha_sq_mul_basis_zero :
    alpha ^ 2 * basis (0 : Fin 3) = ofCoords 0 0 1 := by
  simp [basis_apply, ofCoords]

private theorem alpha_sq_mul_basis_one :
    alpha ^ 2 * basis (1 : Fin 3) = ofCoords 2 (-4) 4 := by
  rw [basis_apply]
  norm_num
  unfold ofCoords
  push_cast
  ring_nf
  rw [alpha_cubed]
  norm_num
  ring_nf

private theorem alpha_sq_mul_basis_two :
    alpha ^ 2 * basis (2 : Fin 3) = ofCoords 8 (-14) 12 := by
  rw [basis_apply]
  norm_num
  unfold ofCoords
  push_cast
  ring_nf
  rw [alpha_fourth]
  norm_num
  ring_nf

private theorem leftMulMatrix_alpha_zero_zero :
    Algebra.leftMulMatrix basis alpha (0 : Fin 3) (0 : Fin 3) = 0 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul, alpha_mul_basis_zero]
  exact basis_repr_ofCoords_zero 0 1 0

private theorem leftMulMatrix_alpha_one_one :
    Algebra.leftMulMatrix basis alpha (1 : Fin 3) (1 : Fin 3) = 0 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul, alpha_mul_basis_one]
  exact basis_repr_ofCoords_one 0 0 1

private theorem leftMulMatrix_alpha_two_two :
    Algebra.leftMulMatrix basis alpha (2 : Fin 3) (2 : Fin 3) = 4 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul, alpha_mul_basis_two]
  exact basis_repr_ofCoords_two 2 (-4) 4

private theorem leftMulMatrix_alpha_sq_zero_zero :
    Algebra.leftMulMatrix basis (alpha ^ 2) (0 : Fin 3) (0 : Fin 3) = 0 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul, alpha_sq_mul_basis_zero]
  exact basis_repr_ofCoords_zero 0 0 1

private theorem leftMulMatrix_alpha_sq_one_one :
    Algebra.leftMulMatrix basis (alpha ^ 2) (1 : Fin 3) (1 : Fin 3) = -4 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul, alpha_sq_mul_basis_one]
  exact basis_repr_ofCoords_one 2 (-4) 4

private theorem leftMulMatrix_alpha_sq_two_two :
    Algebra.leftMulMatrix basis (alpha ^ 2) (2 : Fin 3) (2 : Fin 3) = 12 := by
  rw [Algebra.leftMulMatrix_eq_repr_mul, alpha_sq_mul_basis_two]
  exact basis_repr_ofCoords_two 8 (-14) 12

private theorem trace_one : Algebra.trace ℚ K 1 = 3 := by
  simpa using Algebra.trace_algebraMap_of_basis basis (1 : ℚ)

private theorem trace_alpha : Algebra.trace ℚ K alpha = 4 := by
  rw [Algebra.trace_eq_matrix_trace basis, Matrix.trace_fin_three,
    leftMulMatrix_alpha_zero_zero, leftMulMatrix_alpha_one_one,
    leftMulMatrix_alpha_two_two]
  norm_num

private theorem trace_alpha_sq : Algebra.trace ℚ K (alpha ^ 2) = 8 := by
  rw [Algebra.trace_eq_matrix_trace basis, Matrix.trace_fin_three,
    leftMulMatrix_alpha_sq_zero_zero, leftMulMatrix_alpha_sq_one_one,
    leftMulMatrix_alpha_sq_two_two]
  norm_num

private theorem trace_alpha_cubed : Algebra.trace ℚ K (alpha ^ 3) = 22 := by
  rw [alpha_cubed]
  have hrewrite : 4 * alpha ^ 2 - 4 * alpha + 2 =
      (4 : ℚ) • alpha ^ 2 - (4 : ℚ) • alpha + (2 : ℚ) • (1 : K) := by
    simp [Algebra.smul_def]
  rw [hrewrite, map_add, map_sub, map_smul, map_smul, map_smul,
    trace_alpha_sq, trace_alpha, trace_one]
  norm_num

private theorem trace_alpha_fourth : Algebra.trace ℚ K (alpha ^ 4) = 64 := by
  rw [alpha_fourth]
  have hrewrite : 12 * alpha ^ 2 - 14 * alpha + 8 =
      (12 : ℚ) • alpha ^ 2 - (14 : ℚ) • alpha + (8 : ℚ) • (1 : K) := by
    simp [Algebra.smul_def]
  rw [hrewrite, map_add, map_sub, map_smul, map_smul, map_smul,
    trace_alpha_sq, trace_alpha, trace_one]
  norm_num

private theorem traceMatrix_zero_zero : Algebra.traceMatrix ℚ basis 0 0 = 3 := by
  change Algebra.trace ℚ K (basis 0 * basis 0) = 3
  simpa [basis_apply] using trace_one

private theorem traceMatrix_zero_one : Algebra.traceMatrix ℚ basis 0 1 = 4 := by
  change Algebra.trace ℚ K (basis 0 * basis 1) = 4
  simpa [basis_apply] using trace_alpha

private theorem traceMatrix_zero_two : Algebra.traceMatrix ℚ basis 0 2 = 8 := by
  change Algebra.trace ℚ K (basis 0 * basis 2) = 8
  simpa [basis_apply] using trace_alpha_sq

private theorem traceMatrix_one_zero : Algebra.traceMatrix ℚ basis 1 0 = 4 := by
  change Algebra.trace ℚ K (basis 1 * basis 0) = 4
  simpa [basis_apply] using trace_alpha

private theorem traceMatrix_one_one : Algebra.traceMatrix ℚ basis 1 1 = 8 := by
  change Algebra.trace ℚ K (basis 1 * basis 1) = 8
  simpa [basis_apply, pow_two] using trace_alpha_sq

private theorem traceMatrix_one_two : Algebra.traceMatrix ℚ basis 1 2 = 22 := by
  change Algebra.trace ℚ K (basis 1 * basis 2) = 22
  convert trace_alpha_cubed using 1 <;> simp [basis_apply] <;> ring_nf

private theorem traceMatrix_two_zero : Algebra.traceMatrix ℚ basis 2 0 = 8 := by
  change Algebra.trace ℚ K (basis 2 * basis 0) = 8
  simpa [basis_apply] using trace_alpha_sq

private theorem traceMatrix_two_one : Algebra.traceMatrix ℚ basis 2 1 = 22 := by
  change Algebra.trace ℚ K (basis 2 * basis 1) = 22
  convert trace_alpha_cubed using 1 <;> simp [basis_apply] <;> ring_nf

private theorem traceMatrix_two_two : Algebra.traceMatrix ℚ basis 2 2 = 64 := by
  change Algebra.trace ℚ K (basis 2 * basis 2) = 64
  convert trace_alpha_fourth using 1 <;> simp [basis_apply] <;> ring_nf

theorem basis_discr : Algebra.discr ℚ basis = -44 := by
  rw [Algebra.discr_def, Matrix.det_fin_three,
    traceMatrix_zero_zero, traceMatrix_zero_one, traceMatrix_zero_two,
    traceMatrix_one_zero, traceMatrix_one_one, traceMatrix_one_two,
    traceMatrix_two_zero, traceMatrix_two_one, traceMatrix_two_two]
  norm_num

/-! ## Bounding the field discriminant and the class number -/

noncomputable def integralIndexEquiv :
    Free.ChooseBasisIndex ℤ (NumberField.RingOfIntegers K) ≃ Fin 3 :=
  Fintype.equivOfCardEq (by
    rw [← Module.finrank_eq_card_basis (NumberField.RingOfIntegers.basis K),
      NumberField.RingOfIntegers.rank, finrank_K, Fintype.card_fin])

noncomputable def integralBasisFin : Basis (Fin 3) ℚ K :=
  (NumberField.integralBasis K).reindex integralIndexEquiv

theorem integralBasisFin_discr :
    Algebra.discr ℚ integralBasisFin = (NumberField.discr K : ℚ) := by
  simp only [integralBasisFin, Basis.coe_reindex]
  rw [Algebra.discr_reindex, ← NumberField.coe_discr]

noncomputable def basisInteger (i : Fin 3) : NumberField.RingOfIntegers K :=
  ⟨basis i, (mem_integralClosure_iff ℤ K).mpr <| by
    rw [basis_apply]
    exact alpha_isIntegral.pow i⟩

@[simp] theorem basisInteger_coe_K (i : Fin 3) :
    ((basisInteger i : NumberField.RingOfIntegers K) : K) = basis i :=
  rfl

private theorem integralBasisFin_repr_basis (i j : Fin 3) :
    integralBasisFin.repr (basis j) i =
      algebraMap ℤ ℚ
        ((NumberField.RingOfIntegers.basis K).repr (basisInteger j)
          (integralIndexEquiv.symm i)) := by
  rw [integralBasisFin, Basis.repr_reindex_apply]
  simpa [basisInteger] using
    NumberField.integralBasis_repr_apply K (basisInteger j) (integralIndexEquiv.symm i)

private theorem integral_toMatrix_entries (i j : Fin 3) :
    IsIntegral ℤ (integralBasisFin.toMatrix basis i j) := by
  rw [Basis.toMatrix_apply, integralBasisFin_repr_basis]
  exact isIntegral_algebraMap

private theorem basis_discr_index_relation :
    ∃ d : ℤ, (-44 : ℤ) = d ^ 2 * NumberField.discr K := by
  let A : Matrix (Fin 3) (Fin 3) ℚ := integralBasisFin.toMatrix basis
  have hdetInt : IsIntegral ℤ A.det :=
    IsIntegral.det fun i j ↦ integral_toMatrix_entries i j
  obtain ⟨d, hd⟩ := IsIntegrallyClosed.isIntegral_iff.mp hdetInt
  refine ⟨d, ?_⟩
  have hdisc := Algebra.discr_of_matrix_vecMul
    (A := ℚ) (B := K) (integralBasisFin : Fin 3 → K) A
  have hfamily :
      Matrix.vecMul (integralBasisFin : Fin 3 → K) (A.map (algebraMap ℚ K)) =
        (basis : Fin 3 → K) := by
    exact integralBasisFin.toMatrix_map_vecMul basis
  rw [hfamily, basis_discr, integralBasisFin_discr, ← hd] at hdisc
  apply Int.cast_injective (α := ℚ)
  push_cast
  exact hdisc

theorem natAbs_discr_le_44 : (NumberField.discr K).natAbs ≤ 44 := by
  obtain ⟨d, hd⟩ := basis_discr_index_relation
  have hdvd : NumberField.discr K ∣ (-44 : ℤ) := by
    refine ⟨d ^ 2, ?_⟩
    simpa [mul_comm] using hd
  exact Int.natAbs_le_of_dvd_ne_zero hdvd (by norm_num)

theorem abs_discr_le_44 : |NumberField.discr K| ≤ (44 : ℤ) := by
  have h : ((NumberField.discr K).natAbs : ℤ) ≤ (44 : ℤ) := by
    exact_mod_cast natAbs_discr_le_44
  simpa using h

theorem discr_neg : NumberField.discr K < 0 := by
  obtain ⟨d, hd⟩ := basis_discr_index_relation
  have hdne : d ≠ 0 := by
    intro hd0
    rw [hd0] at hd
    norm_num at hd
  have hdsq : 0 < d ^ 2 := sq_pos_of_ne_zero hdne
  nlinarith

theorem nrComplexPlaces_eq_one : nrComplexPlaces K = 1 := by
  have hsign := NumberField.sign_discr K
  rw [Int.sign_eq_neg_one_of_neg discr_neg] at hsign
  have hodd : Odd (nrComplexPlaces K) := by
    exact (neg_one_pow_eq_neg_one_iff_odd (R := ℤ) (by norm_num)).mp hsign.symm
  have hdegree := NumberField.InfinitePlace.card_add_two_mul_card_eq_rank K
  rw [finrank_K] at hdegree
  rcases hodd with ⟨r, hr⟩
  omega

theorem nrRealPlaces_eq_one : nrRealPlaces K = 1 := by
  have hdegree := NumberField.InfinitePlace.card_add_two_mul_card_eq_rank K
  rw [finrank_K, nrComplexPlaces_eq_one] at hdegree
  omega

theorem infinitePlace_card_eq_two :
    Fintype.card (NumberField.InfinitePlace K) = 2 := by
  rw [NumberField.InfinitePlace.card_eq_nrRealPlaces_add_nrComplexPlaces,
    nrRealPlaces_eq_one, nrComplexPlaces_eq_one]

theorem unitRank_eq_one : NumberField.Units.rank K = 1 := by
  rw [NumberField.Units.rank, infinitePlace_card_eq_two]

theorem abs_discr_gt_eleven :
    (11 : ℝ) < |(NumberField.discr K : ℝ)| := by
  have hbound := NumberField.abs_discr_ge' K
  rw [finrank_K, nrComplexPlaces_eq_one] at hbound
  have hrewrite :
      (((3 : ℕ) : ℝ) ^ (2 * 3) /
          ((4 / Real.pi) ^ (2 * 1) * (Nat.factorial 3 : ℝ) ^ 2)) =
        81 * Real.pi ^ 2 / 64 := by
    norm_num [div_pow]
    field_simp [Real.pi_ne_zero]
    ring
  rw [hrewrite] at hbound
  rw [Int.cast_abs] at hbound
  have hpiSq : (9 : ℝ) < Real.pi ^ 2 := by
    have hprod : 0 < (Real.pi - 3) * (Real.pi + 3) :=
      mul_pos (sub_pos.mpr Real.pi_gt_three) (by linarith [Real.pi_pos])
    nlinarith
  linarith

theorem discr_eq_neg_44 : NumberField.discr K = -44 := by
  obtain ⟨d, hd⟩ := basis_discr_index_relation
  have hdne : d ≠ 0 := by
    intro hd0
    rw [hd0] at hd
    norm_num at hd
  have hdsqpos : 0 < d ^ 2 := sq_pos_of_ne_zero hdne
  have habsLower : (11 : ℤ) < |NumberField.discr K| := by
    exact_mod_cast abs_discr_gt_eleven
  have habsEq : (44 : ℤ) = d ^ 2 * |NumberField.discr K| := by
    rw [abs_of_neg discr_neg]
    nlinarith
  have hdsqLt : d ^ 2 < 4 := by
    by_contra hnot
    have hfour : (4 : ℤ) ≤ d ^ 2 := by omega
    have htwelve : (12 : ℤ) ≤ |NumberField.discr K| := by omega
    have hprod : 4 * 12 ≤ d ^ 2 * |NumberField.discr K| :=
      mul_le_mul hfour htwelve (by norm_num) (by positivity)
    rw [← habsEq] at hprod
    norm_num at hprod
  have hdLower : -2 < d := by nlinarith
  have hdUpper : d < 2 := by nlinarith
  have hdCases : d = -1 ∨ d = 1 := by omega
  rcases hdCases with rfl | rfl <;> norm_num at hd ⊢ <;> exact hd.symm

/-! The power basis is the full integral basis. -/

noncomputable def ringOfIntegersBasisFin :
    Basis (Fin 3) ℤ (NumberField.RingOfIntegers K) :=
  (NumberField.RingOfIntegers.basis K).reindex integralIndexEquiv

noncomputable def basisIntegerMatrix : Matrix (Fin 3) (Fin 3) ℤ :=
  fun i j ↦ ringOfIntegersBasisFin.repr (basisInteger j) i

private theorem ringOfIntegersBasisFin_repr_basisInteger (i j : Fin 3) :
    ringOfIntegersBasisFin.repr (basisInteger j) i =
      (NumberField.RingOfIntegers.basis K).repr (basisInteger j)
        (integralIndexEquiv.symm i) := by
  rw [ringOfIntegersBasisFin, Basis.repr_reindex_apply]

private theorem basisIntegerMatrix_map :
    basisIntegerMatrix.map (algebraMap ℤ ℚ) = integralBasisFin.toMatrix basis := by
  ext i j
  rw [Matrix.map_apply, basisIntegerMatrix, Basis.toMatrix_apply,
    ringOfIntegersBasisFin_repr_basisInteger]
  exact (integralBasisFin_repr_basis i j).symm

theorem basisIntegerMatrix_det_isUnit : IsUnit basisIntegerMatrix.det := by
  let A : Matrix (Fin 3) (Fin 3) ℚ := integralBasisFin.toMatrix basis
  have hdisc := Algebra.discr_of_matrix_vecMul
    (A := ℚ) (B := K) (integralBasisFin : Fin 3 → K) A
  have hfamily :
      Matrix.vecMul (integralBasisFin : Fin 3 → K) (A.map (algebraMap ℚ K)) =
        (basis : Fin 3 → K) := by
    exact integralBasisFin.toMatrix_map_vecMul basis
  rw [hfamily, basis_discr, integralBasisFin_discr, discr_eq_neg_44] at hdisc
  norm_num at hdisc
  have hAdet : A.det ^ 2 = 1 := sq_eq_one_iff.mpr hdisc
  have hmapDet : algebraMap ℤ ℚ basisIntegerMatrix.det = A.det := by
    calc
      algebraMap ℤ ℚ basisIntegerMatrix.det =
          (basisIntegerMatrix.map (algebraMap ℤ ℚ)).det := by
            exact (algebraMap ℤ ℚ).map_det basisIntegerMatrix
      _ = A.det := by rw [basisIntegerMatrix_map]
  have hdetSq : basisIntegerMatrix.det ^ 2 = 1 := by
    apply Int.cast_injective (α := ℚ)
    change algebraMap ℤ ℚ (basisIntegerMatrix.det ^ 2) = algebraMap ℤ ℚ 1
    rw [map_pow, map_one, hmapDet, hAdet]
  rw [Int.isUnit_iff, ← sq_eq_one_iff]
  exact hdetSq

noncomputable def integralPowerBasis :
    Basis (Fin 3) ℤ (NumberField.RingOfIntegers K) :=
  ringOfIntegersBasisFin.map
    (Matrix.toLinearEquiv ringOfIntegersBasisFin basisIntegerMatrix
      basisIntegerMatrix_det_isUnit)

@[simp] theorem integralPowerBasis_apply (i : Fin 3) :
    integralPowerBasis i = basisInteger i := by
  simp only [integralPowerBasis, Basis.map_apply]
  change Matrix.toLin ringOfIntegersBasisFin ringOfIntegersBasisFin
      basisIntegerMatrix (ringOfIntegersBasisFin i) = basisInteger i
  rw [Matrix.toLin_self]
  simpa [basisIntegerMatrix] using
    ringOfIntegersBasisFin.sum_repr (basisInteger i)

@[simp] theorem integralPowerBasis_coe_K (i : Fin 3) :
    ((integralPowerBasis i : NumberField.RingOfIntegers K) : K) = basis i := by
  rw [integralPowerBasis_apply]
  rfl

theorem ringOfIntegers_exists_integer_coords
    (u : NumberField.RingOfIntegers K) :
    ∃ a b c : ℤ, (u : K) = ofCoords a b c := by
  let a := integralPowerBasis.repr u (0 : Fin 3)
  let b := integralPowerBasis.repr u (1 : Fin 3)
  let c := integralPowerBasis.repr u (2 : Fin 3)
  refine ⟨a, b, c, ?_⟩
  have hsum := integralPowerBasis.sum_repr u
  rw [Fin.sum_univ_three] at hsum
  have hsumK := congrArg (fun v : NumberField.RingOfIntegers K ↦ (v : K)) hsum
  simpa [a, b, c, ofCoords, Algebra.smul_def, basis_apply] using hsumK.symm

/-! ## The explicit cubic factor in the Mordell equation -/

private theorem ofCoords_linear_mul_basis_zero (r q : ℚ) :
    ofCoords r q 0 * basis (0 : Fin 3) = ofCoords r q 0 := by
  simp [basis_apply]

private theorem ofCoords_linear_mul_basis_one (r q : ℚ) :
    ofCoords r q 0 * basis (1 : Fin 3) = ofCoords 0 r q := by
  simp [basis_apply, ofCoords]
  ring

private theorem ofCoords_linear_mul_basis_two (r q : ℚ) :
    ofCoords r q 0 * basis (2 : Fin 3) = ofCoords (2 * q) (-4 * q) (r + 4 * q) := by
  rw [basis_apply]
  norm_num
  unfold ofCoords
  push_cast
  ring_nf
  rw [alpha_cubed]
  norm_num
  ring

theorem norm_ofCoords_linear (r q : ℚ) :
    Algebra.norm ℚ (ofCoords r q 0) =
      r ^ 3 + 4 * r ^ 2 * q + 4 * r * q ^ 2 + 2 * q ^ 3 := by
  rw [Algebra.norm_eq_matrix_det basis, Matrix.det_fin_three]
  simp_rw [Algebra.leftMulMatrix_eq_repr_mul]
  rw [ofCoords_linear_mul_basis_zero, ofCoords_linear_mul_basis_one,
    ofCoords_linear_mul_basis_two]
  simp
  ring

theorem norm_epsilon : Algebra.norm ℚ epsilon = 1 := by
  have hepsilon : epsilon = ofCoords (-1) 1 0 := by
    unfold epsilon ofCoords
    norm_num
    ring
  rw [hepsilon, norm_ofCoords_linear]
  norm_num

noncomputable def descentElement (x z : ℤ) : K :=
  ofCoords (x - 24 * z ^ 2) (18 * z ^ 2) 0

noncomputable def descentInteger (x z : ℤ) :
    NumberField.RingOfIntegers K :=
  (x - 24 * z ^ 2) • basisInteger (0 : Fin 3) +
    (18 * z ^ 2) • basisInteger (1 : Fin 3)

@[simp] theorem descentInteger_coe_K (x z : ℤ) :
    ((descentInteger x z : NumberField.RingOfIntegers K) : K) =
      descentElement x z := by
  simp [descentInteger, descentElement, ofCoords, basis_apply, Algebra.smul_def]
  norm_num [map_ofNat]

noncomputable def thetaBasisElement (a b c : ℤ) : K :=
  ofCoords a (c - 2 * b) b

theorem ringOfIntegers_exists_thetaBasis_coords
    (u : NumberField.RingOfIntegers K) :
    ∃ a b c : ℤ, (u : K) = thetaBasisElement a b c := by
  obtain ⟨p, q, r, hu⟩ := ringOfIntegers_exists_integer_coords u
  refine ⟨p, r, q + 2 * r, ?_⟩
  calc
    (u : K) = ofCoords p q r := hu
    _ = thetaBasisElement p r (q + 2 * r) := by
      unfold thetaBasisElement
      push_cast
      congr 1 <;> ring

theorem norm_descentElement (x z : ℤ) :
    Algebra.norm ℚ (descentElement x z) =
      ((x ^ 3 - 432 * x * z ^ 4 + 8208 * z ^ 6 : ℤ) : ℚ) := by
  rw [descentElement, norm_ofCoords_linear]
  push_cast
  ring

private theorem epsilon_mul_descentElement (x z : ℤ) :
    epsilon * descentElement x z =
      ofCoords (-x + 24 * z ^ 2) (x - 42 * z ^ 2) (18 * z ^ 2) := by
  unfold epsilon descentElement ofCoords
  push_cast
  norm_num
  ring_nf

private theorem thetaBasisElement_sq (a b c : ℤ) :
    thetaBasisElement a b c ^ 2 =
      ofCoords (a ^ 2 + 4 * b * c)
        (2 * a * c - 4 * a * b - 8 * b * c + 2 * b ^ 2)
        (c ^ 2 + 2 * a * b + 4 * b * c) := by
  unfold thetaBasisElement
  rw [ofCoords_sq]
  push_cast
  congr 1 <;> ring

/-- Expanding the Billing--Mahler square identity in the integral basis gives
the three integer equations used by the parity obstruction. -/
theorem coefficient_system_of_epsilon_mul_descentElement_eq_sq
    (x z a b c : ℤ)
    (h : epsilon * descentElement x z = thetaBasisElement a b c ^ 2) :
    -x + 24 * z ^ 2 = a ^ 2 + 4 * b * c ∧
      18 * z ^ 2 = c ^ 2 + 2 * a * b + 4 * b * c ∧
      x = 2 * (b ^ 2 + c ^ 2 + a * c + 3 * z ^ 2) := by
  rw [epsilon_mul_descentElement, thetaBasisElement_sq] at h
  have hzero := congrArg (fun u : K ↦ basis.repr u (0 : Fin 3)) h
  have hone := congrArg (fun u : K ↦ basis.repr u (1 : Fin 3)) h
  have htwo := congrArg (fun u : K ↦ basis.repr u (2 : Fin 3)) h
  simp only [basis_repr_ofCoords_zero] at hzero
  simp only [basis_repr_ofCoords_one] at hone
  simp only [basis_repr_ofCoords_two] at htwo
  have hzeroInt : -x + 24 * z ^ 2 = a ^ 2 + 4 * b * c := by
    exact_mod_cast hzero
  have htwoInt : 18 * z ^ 2 = c ^ 2 + 2 * a * b + 4 * b * c := by
    exact_mod_cast htwo
  refine ⟨hzeroInt, htwoInt, ?_⟩
  have honeInt : x - 42 * z ^ 2 =
      2 * a * c - 4 * a * b - 8 * b * c + 2 * b ^ 2 := by
    exact_mod_cast hone
  nlinarith

theorem ringOfIntegers_isPrincipalIdealRing :
    IsPrincipalIdealRing (NumberField.RingOfIntegers K) := by
  apply RingOfIntegers.isPrincipalIdealRing_of_abs_discr_lt
  rw [finrank_K, nrComplexPlaces_eq_one]
  have habs : (|NumberField.discr K| : ℝ) ≤ 44 := by
    exact_mod_cast abs_discr_le_44
  have hpi := Real.pi_gt_three
  norm_num at ⊢
  nlinarith [sq_nonneg (Real.pi - 3)]

theorem classNumber_eq_one : NumberField.classNumber K = 1 :=
  NumberField.classNumber_eq_one_iff.mpr ringOfIntegers_isPrincipalIdealRing

/-- In a PID, a principal ideal that is an ideal square has a generator equal
to a unit times an element square. -/
theorem unit_mul_square_of_principal_ideal_square
    (d : NumberField.RingOfIntegers K)
    (I : Ideal (NumberField.RingOfIntegers K))
    (h : Ideal.span ({d} : Set (NumberField.RingOfIntegers K)) = I ^ 2) :
    ∃ u : (NumberField.RingOfIntegers K)ˣ,
      ∃ a : NumberField.RingOfIntegers K, d = (u : NumberField.RingOfIntegers K) * a ^ 2 := by
  letI : IsPrincipalIdealRing (NumberField.RingOfIntegers K) :=
    ringOfIntegers_isPrincipalIdealRing
  obtain ⟨a, ha⟩ := IsPrincipalIdealRing.principal I
  have hspan : Ideal.span ({d} : Set (NumberField.RingOfIntegers K)) =
      Ideal.span ({a ^ 2} : Set (NumberField.RingOfIntegers K)) := by
    calc
      Ideal.span ({d} : Set (NumberField.RingOfIntegers K)) = I ^ 2 := h
      _ = (Ideal.span ({a} : Set (NumberField.RingOfIntegers K))) ^ 2 := by rw [ha]
      _ = Ideal.span ({a ^ 2} : Set (NumberField.RingOfIntegers K)) := by
        rw [Ideal.span_singleton_pow]
  obtain ⟨u, hu⟩ := Ideal.span_singleton_eq_span_singleton.mp hspan
  refine ⟨u⁻¹, a, ?_⟩
  calc
    d = (d * (u : NumberField.RingOfIntegers K)) *
        (u⁻¹ : (NumberField.RingOfIntegers K)ˣ) := by simp
    _ = a ^ 2 * (u⁻¹ : (NumberField.RingOfIntegers K)ˣ) := by rw [hu]
    _ = ((u⁻¹ : (NumberField.RingOfIntegers K)ˣ) :
        NumberField.RingOfIntegers K) * a ^ 2 := by rw [mul_comm]

/-! ## The Billing--Mahler unit represents the nontrivial free squareclass -/

noncomputable def epsilonSquareShiftPolyInt : ℤ[X] :=
  X ^ 6 + 6 * X ^ 5 + 14 * X ^ 4 + 16 * X ^ 3 + 8 * X ^ 2 - 2

noncomputable def negEpsilonSquareShiftPolyInt : ℤ[X] :=
  X ^ 6 + 6 * X ^ 5 + 16 * X ^ 4 + 24 * X ^ 3 + 20 * X ^ 2 + 8 * X + 2

noncomputable def epsilonSquareShiftPoly : ℚ[X] :=
  epsilonSquareShiftPolyInt.map (algebraMap ℤ ℚ)

noncomputable def negEpsilonSquareShiftPoly : ℚ[X] :=
  negEpsilonSquareShiftPolyInt.map (algebraMap ℤ ℚ)

private theorem epsilonSquareShiftPolyInt_monic : epsilonSquareShiftPolyInt.Monic := by
  unfold epsilonSquareShiftPolyInt
  monicity!

private theorem negEpsilonSquareShiftPolyInt_monic : negEpsilonSquareShiftPolyInt.Monic := by
  unfold negEpsilonSquareShiftPolyInt
  monicity!

private theorem epsilonSquareShiftPolyInt_natDegree :
    epsilonSquareShiftPolyInt.natDegree = 6 := by
  unfold epsilonSquareShiftPolyInt
  compute_degree!

private theorem negEpsilonSquareShiftPolyInt_natDegree :
    negEpsilonSquareShiftPolyInt.natDegree = 6 := by
  unfold negEpsilonSquareShiftPolyInt
  compute_degree!

private theorem epsilonSquareShiftPolyInt_eisenstein_two :
    epsilonSquareShiftPolyInt.IsEisensteinAt
      (Ideal.span ({(2 : ℤ)} : Set ℤ)) := by
  let P : Ideal ℤ := Ideal.span ({(2 : ℤ)} : Set ℤ)
  have hPne : P ≠ ⊤ := by
    rw [ne_eq, Ideal.span_singleton_eq_top]
    norm_num [Int.isUnit_iff]
  refine epsilonSquareShiftPolyInt_monic.isEisensteinAt_of_mem_of_notMem hPne ?_ ?_
  · intro n hn
    rw [epsilonSquareShiftPolyInt_natDegree] at hn
    interval_cases n <;>
      norm_num [epsilonSquareShiftPolyInt, coeff_X_pow, coeff_X, P,
        Ideal.mem_span_singleton]
  · rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    norm_num [epsilonSquareShiftPolyInt]

private theorem negEpsilonSquareShiftPolyInt_eisenstein_two :
    negEpsilonSquareShiftPolyInt.IsEisensteinAt
      (Ideal.span ({(2 : ℤ)} : Set ℤ)) := by
  let P : Ideal ℤ := Ideal.span ({(2 : ℤ)} : Set ℤ)
  have hPne : P ≠ ⊤ := by
    rw [ne_eq, Ideal.span_singleton_eq_top]
    norm_num [Int.isUnit_iff]
  refine negEpsilonSquareShiftPolyInt_monic.isEisensteinAt_of_mem_of_notMem hPne ?_ ?_
  · intro n hn
    rw [negEpsilonSquareShiftPolyInt_natDegree] at hn
    interval_cases n <;>
      norm_num [negEpsilonSquareShiftPolyInt, coeff_X_pow, coeff_X, P,
        Ideal.mem_span_singleton]
  · rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    norm_num [negEpsilonSquareShiftPolyInt]

private theorem epsilonSquareShiftPolyInt_irreducible :
    Irreducible epsilonSquareShiftPolyInt := by
  apply epsilonSquareShiftPolyInt_eisenstein_two.irreducible
  · exact (Ideal.span_singleton_prime (by norm_num)).2 (by norm_num)
  · exact epsilonSquareShiftPolyInt_monic.isPrimitive
  · rw [epsilonSquareShiftPolyInt_natDegree]
    norm_num

private theorem negEpsilonSquareShiftPolyInt_irreducible :
    Irreducible negEpsilonSquareShiftPolyInt := by
  apply negEpsilonSquareShiftPolyInt_eisenstein_two.irreducible
  · exact (Ideal.span_singleton_prime (by norm_num)).2 (by norm_num)
  · exact negEpsilonSquareShiftPolyInt_monic.isPrimitive
  · rw [negEpsilonSquareShiftPolyInt_natDegree]
    norm_num

theorem epsilonSquareShiftPoly_irreducible : Irreducible epsilonSquareShiftPoly := by
  exact
    (epsilonSquareShiftPolyInt_monic.isPrimitive.irreducible_iff_irreducible_map_fraction_map).mp
      epsilonSquareShiftPolyInt_irreducible

theorem negEpsilonSquareShiftPoly_irreducible :
    Irreducible negEpsilonSquareShiftPoly := by
  exact
    (negEpsilonSquareShiftPolyInt_monic.isPrimitive.irreducible_iff_irreducible_map_fraction_map).mp
      negEpsilonSquareShiftPolyInt_irreducible

theorem epsilonSquareShiftPoly_monic : epsilonSquareShiftPoly.Monic := by
  rw [epsilonSquareShiftPoly]
  exact epsilonSquareShiftPolyInt_monic.map (algebraMap ℤ ℚ)

theorem negEpsilonSquareShiftPoly_monic : negEpsilonSquareShiftPoly.Monic := by
  rw [negEpsilonSquareShiftPoly]
  exact negEpsilonSquareShiftPolyInt_monic.map (algebraMap ℤ ℚ)

theorem epsilonSquareShiftPoly_natDegree : epsilonSquareShiftPoly.natDegree = 6 := by
  rw [epsilonSquareShiftPoly,
    epsilonSquareShiftPolyInt_monic.natDegree_map (algebraMap ℤ ℚ)]
  exact epsilonSquareShiftPolyInt_natDegree

theorem negEpsilonSquareShiftPoly_natDegree : negEpsilonSquareShiftPoly.natDegree = 6 := by
  rw [negEpsilonSquareShiftPoly,
    negEpsilonSquareShiftPolyInt_monic.natDegree_map (algebraMap ℤ ℚ)]
  exact negEpsilonSquareShiftPolyInt_natDegree

theorem epsilonSquareShiftPoly_eq : epsilonSquareShiftPoly =
    X ^ 6 + 6 * X ^ 5 + 14 * X ^ 4 + 16 * X ^ 3 + 8 * X ^ 2 - 2 := by
  ext n
  simp [epsilonSquareShiftPoly, epsilonSquareShiftPolyInt]

theorem negEpsilonSquareShiftPoly_eq : negEpsilonSquareShiftPoly =
    X ^ 6 + 6 * X ^ 5 + 16 * X ^ 4 + 24 * X ^ 3 + 20 * X ^ 2 + 8 * X + 2 := by
  ext n
  simp [negEpsilonSquareShiftPoly, negEpsilonSquareShiftPolyInt]

theorem epsilon_not_isSquare : ¬ IsSquare epsilon := by
  rintro ⟨u, hu⟩
  have hu2 : u ^ 2 = epsilon := by simpa [pow_two] using hu.symm
  have huAlpha : u ^ 2 + 1 = alpha := by
    rw [hu2]
    simp [epsilon]
  have hbase : u ^ 6 - u ^ 4 - u ^ 2 - 1 = 0 := by
    calc
      u ^ 6 - u ^ 4 - u ^ 2 - 1 =
          (u ^ 2 + 1) ^ 3 - 4 * (u ^ 2 + 1) ^ 2 + 4 * (u ^ 2 + 1) - 2 := by ring
      _ = alpha ^ 3 - 4 * alpha ^ 2 + 4 * alpha - 2 := by rw [huAlpha]
      _ = 0 := alpha_relation
  have hroot : aeval (u - 1) epsilonSquareShiftPoly = 0 := by
    calc
      aeval (u - 1) epsilonSquareShiftPoly =
          (u - 1) ^ 6 + 6 * (u - 1) ^ 5 + 14 * (u - 1) ^ 4 +
            16 * (u - 1) ^ 3 + 8 * (u - 1) ^ 2 - 2 := by
        rw [epsilonSquareShiftPoly_eq]
        simp only [map_sub, map_add, map_mul, map_pow, map_ofNat, aeval_X]
      _ = u ^ 6 - u ^ 4 - u ^ 2 - 1 := by ring
      _ = 0 := hbase
  have hmin := minpoly.eq_of_irreducible_of_monic
    epsilonSquareShiftPoly_irreducible hroot epsilonSquareShiftPoly_monic
  have hdegree : epsilonSquareShiftPoly.natDegree ≤ Module.finrank ℚ K := by
    rw [hmin]
    exact minpoly.natDegree_le (A := ℚ) (B := K) (u - 1)
  rw [epsilonSquareShiftPoly_natDegree, finrank_K] at hdegree
  omega

theorem neg_epsilon_not_isSquare : ¬ IsSquare (-epsilon) := by
  rintro ⟨u, hu⟩
  have hu2 : u ^ 2 = -epsilon := by simpa [pow_two] using hu.symm
  have huAlpha : 1 - u ^ 2 = alpha := by
    rw [hu2]
    simp [epsilon]
  have hbase : u ^ 6 + u ^ 4 - u ^ 2 + 1 = 0 := by
    calc
      u ^ 6 + u ^ 4 - u ^ 2 + 1 =
          -((1 - u ^ 2) ^ 3 - 4 * (1 - u ^ 2) ^ 2 + 4 * (1 - u ^ 2) - 2) := by ring
      _ = -(alpha ^ 3 - 4 * alpha ^ 2 + 4 * alpha - 2) := by rw [huAlpha]
      _ = 0 := by rw [alpha_relation]; ring
  have hroot : aeval (u - 1) negEpsilonSquareShiftPoly = 0 := by
    calc
      aeval (u - 1) negEpsilonSquareShiftPoly =
          (u - 1) ^ 6 + 6 * (u - 1) ^ 5 + 16 * (u - 1) ^ 4 +
            24 * (u - 1) ^ 3 + 20 * (u - 1) ^ 2 + 8 * (u - 1) + 2 := by
        rw [negEpsilonSquareShiftPoly_eq]
        simp only [map_sub, map_add, map_mul, map_pow, map_ofNat, aeval_X]
      _ = u ^ 6 + u ^ 4 - u ^ 2 + 1 := by ring
      _ = 0 := hbase
  have hmin := minpoly.eq_of_irreducible_of_monic
    negEpsilonSquareShiftPoly_irreducible hroot negEpsilonSquareShiftPoly_monic
  have hdegree : negEpsilonSquareShiftPoly.natDegree ≤ Module.finrank ℚ K := by
    rw [hmin]
    exact minpoly.natDegree_le (A := ℚ) (B := K) (u - 1)
  rw [negEpsilonSquareShiftPoly_natDegree, finrank_K] at hdegree
  omega

/-! ## Unit squareclasses -/

def fundamentalIndex : Fin (NumberField.Units.rank K) :=
  ⟨0, by simpa [unitRank_eq_one]⟩

noncomputable def fundamentalUnit :
    (NumberField.RingOfIntegers K)ˣ :=
  NumberField.Units.fundSystem K fundamentalIndex

private theorem unit_eq_torsion_mul_fundamental_zpow
    (u : (NumberField.RingOfIntegers K)ˣ) :
    ∃ ζ : NumberField.Units.torsion K, ∃ n : ℤ,
      u = (ζ : (NumberField.RingOfIntegers K)ˣ) * fundamentalUnit ^ n := by
  obtain ⟨⟨ζ, f⟩, hu, _hunique⟩ :=
    NumberField.Units.exist_unique_eq_mul_prod K u
  refine ⟨ζ, f fundamentalIndex, ?_⟩
  letI : Subsingleton (Fin (NumberField.Units.rank K)) :=
    Fintype.card_le_one_iff_subsingleton.mp (by simp [unitRank_eq_one])
  have hprod :
      ∏ i, NumberField.Units.fundSystem K i ^ f i =
        NumberField.Units.fundSystem K fundamentalIndex ^ f fundamentalIndex := by
    apply Fintype.prod_eq_single fundamentalIndex
    intro i hi
    exact (hi (Subsingleton.elim i fundamentalIndex)).elim
  rw [hprod] at hu
  simpa [fundamentalUnit] using hu

private theorem torsion_unit_eq_one_or_neg_one
    (ζ : NumberField.Units.torsion K) :
    (ζ : (NumberField.RingOfIntegers K)ˣ) = 1 ∨
      (ζ : (NumberField.RingOfIntegers K)ˣ) = -1 := by
  apply NumberField.Units.torsion_eq_one_or_neg_one_of_odd_finrank
  rw [finrank_K]
  norm_num [Odd]

private theorem isSquare_coe_K_of_unit
    {u : (NumberField.RingOfIntegers K)ˣ} (hu : IsSquare u) :
    IsSquare (((u : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K) : K) := by
  rcases hu with ⟨v, hv⟩
  refine ⟨(((v : (NumberField.RingOfIntegers K)ˣ) :
    NumberField.RingOfIntegers K) : K), ?_⟩
  simpa using congrArg
    (fun q : (NumberField.RingOfIntegers K)ˣ ↦
      (((q : (NumberField.RingOfIntegers K)ˣ) :
        NumberField.RingOfIntegers K) : K)) hv

theorem epsilon_fundamental_exponent_odd :
    ∃ ζ : NumberField.Units.torsion K, ∃ n : ℤ,
      Odd n ∧
        epsilonUnit = (ζ : (NumberField.RingOfIntegers K)ˣ) * fundamentalUnit ^ n := by
  obtain ⟨ζ, n, hepsilon⟩ := unit_eq_torsion_mul_fundamental_zpow epsilonUnit
  refine ⟨ζ, n, ?_, hepsilon⟩
  rcases Int.even_or_odd n with hnEven | hnOdd
  · have hfundSquare : IsSquare (fundamentalUnit ^ n) :=
      hnEven.isSquare_zpow fundamentalUnit
    rcases torsion_unit_eq_one_or_neg_one ζ with hζ | hζ
    · have hepsilonSquare : IsSquare epsilonUnit := by
        rw [hepsilon, hζ, one_mul]
        exact hfundSquare
      exact (epsilon_not_isSquare
        (by simpa using isSquare_coe_K_of_unit hepsilonSquare)).elim
    · have hnegEpsilonSquare : IsSquare (-epsilonUnit) := by
        rw [hepsilon, hζ]
        simpa using hfundSquare
      exact (neg_epsilon_not_isSquare
        (by simpa using isSquare_coe_K_of_unit hnegEpsilonSquare)).elim
  · exact hnOdd

/-- Every unit is represented modulo squares by one of
`1`, `-1`, `epsilon`, or `-epsilon`. -/
theorem unit_squareclass_classification
    (u : (NumberField.RingOfIntegers K)ˣ) :
    ∃ v : (NumberField.RingOfIntegers K)ˣ,
      u = v ^ 2 ∨ u = -(v ^ 2) ∨
        u = epsilonUnit * v ^ 2 ∨ u = -epsilonUnit * v ^ 2 := by
  obtain ⟨ζ, n, hu⟩ := unit_eq_torsion_mul_fundamental_zpow u
  obtain ⟨ζε, k, hkOdd, hε⟩ := epsilon_fundamental_exponent_odd
  rcases Int.even_or_odd n with hnEven | hnOdd
  · rcases hnEven.isSquare_zpow fundamentalUnit with ⟨v, hv⟩
    refine ⟨v, ?_⟩
    rcases torsion_unit_eq_one_or_neg_one ζ with hζ | hζ
    · left
      rw [hu, hζ, one_mul]
      simpa [pow_two] using hv
    · right; left
      rw [hu, hζ]
      simpa [pow_two] using congrArg Neg.neg hv
  · let τ : NumberField.Units.torsion K :=
      ⟨(ζ : (NumberField.RingOfIntegers K)ˣ) *
          (ζε : (NumberField.RingOfIntegers K)ˣ)⁻¹,
        ζ.property.mul ζε.property.inv⟩
    have hratio : u * epsilonUnit⁻¹ =
        (τ : (NumberField.RingOfIntegers K)ˣ) *
          fundamentalUnit ^ (n - k) := by
      rw [hu, hε]
      dsimp [τ]
      group
      exact mul_right_comm
        (ζ : (NumberField.RingOfIntegers K)ˣ)
        (fundamentalUnit ^ (n - k))
        ((ζε : (NumberField.RingOfIntegers K)ˣ) ^ (-1 : ℤ))
    have hdiffEven : Even (n - k) := hnOdd.sub_odd hkOdd
    rcases hdiffEven.isSquare_zpow fundamentalUnit with ⟨v, hv⟩
    refine ⟨v, ?_⟩
    rcases torsion_unit_eq_one_or_neg_one τ with hτ | hτ
    · right; right; left
      calc
        u = (u * epsilonUnit⁻¹) * epsilonUnit := by group
        _ = v ^ 2 * epsilonUnit := by rw [hratio, hτ, one_mul, hv, pow_two]
        _ = epsilonUnit * v ^ 2 := by ac_rfl
    · right; right; right
      calc
        u = (u * epsilonUnit⁻¹) * epsilonUnit := by group
        _ = -(v ^ 2) * epsilonUnit := by
          rw [hratio, hτ, hv, pow_two]
          simp
        _ = -epsilonUnit * v ^ 2 := by
          simp only [neg_mul, mul_neg]
          rw [mul_comm]

theorem unit_coe_K_squareclass_classification
    (u : (NumberField.RingOfIntegers K)ˣ) :
    ∃ v : K,
      (((u : (NumberField.RingOfIntegers K)ˣ) :
          NumberField.RingOfIntegers K) : K) = v ^ 2 ∨
      (((u : (NumberField.RingOfIntegers K)ˣ) :
          NumberField.RingOfIntegers K) : K) = -(v ^ 2) ∨
      (((u : (NumberField.RingOfIntegers K)ˣ) :
          NumberField.RingOfIntegers K) : K) = epsilon * v ^ 2 ∨
      (((u : (NumberField.RingOfIntegers K)ˣ) :
          NumberField.RingOfIntegers K) : K) = -epsilon * v ^ 2 := by
  obtain ⟨v, hv | hv | hv | hv⟩ := unit_squareclass_classification u
  all_goals
    refine ⟨(((v : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K) : K), ?_⟩
  · left
    simpa using congrArg
      (fun q : (NumberField.RingOfIntegers K)ˣ ↦
        (((q : (NumberField.RingOfIntegers K)ˣ) :
          NumberField.RingOfIntegers K) : K)) hv
  · right; left
    simpa using congrArg
      (fun q : (NumberField.RingOfIntegers K)ˣ ↦
        (((q : (NumberField.RingOfIntegers K)ˣ) :
          NumberField.RingOfIntegers K) : K)) hv
  · right; right; left
    simpa using congrArg
      (fun q : (NumberField.RingOfIntegers K)ˣ ↦
        (((q : (NumberField.RingOfIntegers K)ˣ) :
          NumberField.RingOfIntegers K) : K)) hv
  · right; right; right
    simpa using congrArg
      (fun q : (NumberField.RingOfIntegers K)ˣ ↦
        (((q : (NumberField.RingOfIntegers K)ˣ) :
          NumberField.RingOfIntegers K) : K)) hv

theorem descentInteger_four_squareclasses_of_ideal_square
    (x z : ℤ) (I : Ideal (NumberField.RingOfIntegers K))
    (h : Ideal.span ({descentInteger x z} :
      Set (NumberField.RingOfIntegers K)) = I ^ 2) :
    ∃ w : NumberField.RingOfIntegers K,
      descentInteger x z = w ^ 2 ∨
      descentInteger x z = -(w ^ 2) ∨
      descentInteger x z = epsilonInteger * w ^ 2 ∨
      descentInteger x z = -epsilonInteger * w ^ 2 := by
  obtain ⟨u, a, hd⟩ :=
    unit_mul_square_of_principal_ideal_square (descentInteger x z) I h
  obtain ⟨v, hu | hu | hu | hu⟩ := unit_squareclass_classification u
  · refine ⟨(v : NumberField.RingOfIntegers K) * a, Or.inl ?_⟩
    have huO : (u : NumberField.RingOfIntegers K) =
        (v : NumberField.RingOfIntegers K) ^ 2 := by
      simpa using congrArg
        (fun q : (NumberField.RingOfIntegers K)ˣ ↦
          (q : NumberField.RingOfIntegers K)) hu
    calc
      descentInteger x z = (u : NumberField.RingOfIntegers K) * a ^ 2 := hd
      _ = (v : NumberField.RingOfIntegers K) ^ 2 * a ^ 2 := by rw [huO]
      _ = ((v : NumberField.RingOfIntegers K) * a) ^ 2 := by ring
  · refine ⟨(v : NumberField.RingOfIntegers K) * a, Or.inr (Or.inl ?_)⟩
    have huO : (u : NumberField.RingOfIntegers K) =
        -((v : NumberField.RingOfIntegers K) ^ 2) := by
      simpa using congrArg
        (fun q : (NumberField.RingOfIntegers K)ˣ ↦
          (q : NumberField.RingOfIntegers K)) hu
    calc
      descentInteger x z = (u : NumberField.RingOfIntegers K) * a ^ 2 := hd
      _ = -((v : NumberField.RingOfIntegers K) ^ 2) * a ^ 2 := by rw [huO]
      _ = -(((v : NumberField.RingOfIntegers K) * a) ^ 2) := by ring
  · refine ⟨(v : NumberField.RingOfIntegers K) * a,
      Or.inr (Or.inr (Or.inl ?_))⟩
    have huO : (u : NumberField.RingOfIntegers K) =
        epsilonInteger * (v : NumberField.RingOfIntegers K) ^ 2 := by
      simpa using congrArg
        (fun q : (NumberField.RingOfIntegers K)ˣ ↦
          (q : NumberField.RingOfIntegers K)) hu
    calc
      descentInteger x z = (u : NumberField.RingOfIntegers K) * a ^ 2 := hd
      _ = (epsilonInteger * (v : NumberField.RingOfIntegers K) ^ 2) * a ^ 2 := by
        rw [huO]
      _ = epsilonInteger * ((v : NumberField.RingOfIntegers K) * a) ^ 2 := by ring
  · refine ⟨(v : NumberField.RingOfIntegers K) * a,
      Or.inr (Or.inr (Or.inr ?_))⟩
    have huO : (u : NumberField.RingOfIntegers K) =
        -epsilonInteger * (v : NumberField.RingOfIntegers K) ^ 2 := by
      simpa using congrArg
        (fun q : (NumberField.RingOfIntegers K)ˣ ↦
          (q : NumberField.RingOfIntegers K)) hu
    calc
      descentInteger x z = (u : NumberField.RingOfIntegers K) * a ^ 2 := hd
      _ = (-epsilonInteger * (v : NumberField.RingOfIntegers K) ^ 2) * a ^ 2 := by
        rw [huO]
      _ = -epsilonInteger * ((v : NumberField.RingOfIntegers K) * a) ^ 2 := by ring

/-- Once the principal ideal generated by the cubic factor is an ideal
square, the factor lies in one of the four unit squareclasses. -/
theorem descentElement_four_squareclasses_of_ideal_square
    (x z : ℤ) (I : Ideal (NumberField.RingOfIntegers K))
    (h : Ideal.span ({descentInteger x z} :
      Set (NumberField.RingOfIntegers K)) = I ^ 2) :
    ∃ w : K,
      descentElement x z = w ^ 2 ∨
      descentElement x z = -(w ^ 2) ∨
      descentElement x z = epsilon * w ^ 2 ∨
      descentElement x z = -epsilon * w ^ 2 := by
  obtain ⟨u, a, hd⟩ :=
    unit_mul_square_of_principal_ideal_square (descentInteger x z) I h
  have hdK : descentElement x z =
      (((u : (NumberField.RingOfIntegers K)ˣ) :
          NumberField.RingOfIntegers K) : K) *
        ((a : NumberField.RingOfIntegers K) : K) ^ 2 := by
    simpa using congrArg
      (fun q : NumberField.RingOfIntegers K ↦ (q : K)) hd
  obtain ⟨v, hu | hu | hu | hu⟩ := unit_coe_K_squareclass_classification u
  · refine ⟨v * (a : K), Or.inl ?_⟩
    calc
      descentElement x z =
          (((u : (NumberField.RingOfIntegers K)ˣ) :
              NumberField.RingOfIntegers K) : K) * (a : K) ^ 2 := hdK
      _ = v ^ 2 * (a : K) ^ 2 := by rw [hu]
      _ = (v * (a : K)) ^ 2 := by ring
  · refine ⟨v * (a : K), Or.inr (Or.inl ?_)⟩
    calc
      descentElement x z =
          (((u : (NumberField.RingOfIntegers K)ˣ) :
              NumberField.RingOfIntegers K) : K) * (a : K) ^ 2 := hdK
      _ = -(v ^ 2) * (a : K) ^ 2 := by rw [hu]
      _ = -((v * (a : K)) ^ 2) := by ring
  · refine ⟨v * (a : K), Or.inr (Or.inr (Or.inl ?_))⟩
    calc
      descentElement x z =
          (((u : (NumberField.RingOfIntegers K)ˣ) :
              NumberField.RingOfIntegers K) : K) * (a : K) ^ 2 := hdK
      _ = (epsilon * v ^ 2) * (a : K) ^ 2 := by rw [hu]
      _ = epsilon * (v * (a : K)) ^ 2 := by ring
  · refine ⟨v * (a : K), Or.inr (Or.inr (Or.inr ?_))⟩
    calc
      descentElement x z =
          (((u : (NumberField.RingOfIntegers K)ˣ) :
              NumberField.RingOfIntegers K) : K) * (a : K) ^ 2 := hdK
      _ = (-epsilon * v ^ 2) * (a : K) ^ 2 := by rw [hu]
      _ = -epsilon * (v * (a : K)) ^ 2 := by ring

private theorem norm_neg_square_nonpos (w : K) :
    Algebra.norm ℚ (-(w ^ 2)) ≤ 0 := by
  have hnorm : Algebra.norm ℚ (-(w ^ 2)) =
      -(Algebra.norm ℚ w) ^ 2 := by
    rw [show -(w ^ 2) = algebraMap ℚ K (-1) * w ^ 2 by simp,
      map_mul, Algebra.norm_algebraMap, map_pow, finrank_K]
    norm_num
  rw [hnorm]
  exact neg_nonpos.mpr (sq_nonneg _)

private theorem norm_neg_epsilon_square_nonpos (w : K) :
    Algebra.norm ℚ (-epsilon * w ^ 2) ≤ 0 := by
  have hnorm : Algebra.norm ℚ (-epsilon * w ^ 2) =
      -(Algebra.norm ℚ w) ^ 2 := by
    rw [show -epsilon = algebraMap ℚ K (-1) * epsilon by simp,
      mul_assoc, map_mul, map_mul, Algebra.norm_algebraMap, norm_epsilon,
      map_pow, finrank_K]
    norm_num
  rw [hnorm]
  exact neg_nonpos.mpr (sq_nonneg _)

theorem descentElement_eq_epsilon_mul_integral_sq_of_ideal_square
    (x z : ℤ) (I : Ideal (NumberField.RingOfIntegers K))
    (hideal : Ideal.span ({descentInteger x z} :
      Set (NumberField.RingOfIntegers K)) = I ^ 2)
    (hnonsquare : ¬ IsSquare (descentElement x z))
    (hnorm : 0 < Algebra.norm ℚ (descentElement x z)) :
    ∃ w : NumberField.RingOfIntegers K,
      descentElement x z = epsilon * ((w : NumberField.RingOfIntegers K) : K) ^ 2 := by
  obtain ⟨w, hw | hw | hw | hw⟩ :=
    descentInteger_four_squareclasses_of_ideal_square x z I hideal
  · have hwK : descentElement x z = ((w : NumberField.RingOfIntegers K) : K) ^ 2 := by
      simpa using congrArg
        (fun q : NumberField.RingOfIntegers K ↦ (q : K)) hw
    exact (hnonsquare ⟨(w : K), by simpa [pow_two] using hwK⟩).elim
  · have hwK : descentElement x z = -(((w : NumberField.RingOfIntegers K) : K) ^ 2) := by
      simpa using congrArg
        (fun q : NumberField.RingOfIntegers K ↦ (q : K)) hw
    have hnonpos := norm_neg_square_nonpos (w : K)
    rw [← hwK] at hnonpos
    linarith
  · refine ⟨w, ?_⟩
    simpa using congrArg
      (fun q : NumberField.RingOfIntegers K ↦ (q : K)) hw
  · have hwK : descentElement x z =
        -epsilon * ((w : NumberField.RingOfIntegers K) : K) ^ 2 := by
      simpa using congrArg
        (fun q : NumberField.RingOfIntegers K ↦ (q : K)) hw
    have hnonpos := norm_neg_epsilon_square_nonpos (w : K)
    rw [← hwK] at hnonpos
    linarith

/-- A positive-norm nonsquare cubic factor whose principal ideal is an ideal
square is necessarily in the `epsilon` squareclass. -/
theorem descentElement_eq_epsilon_mul_sq_of_ideal_square
    (x z : ℤ) (I : Ideal (NumberField.RingOfIntegers K))
    (hideal : Ideal.span ({descentInteger x z} :
      Set (NumberField.RingOfIntegers K)) = I ^ 2)
    (hnonsquare : ¬ IsSquare (descentElement x z))
    (hnorm : 0 < Algebra.norm ℚ (descentElement x z)) :
    ∃ w : K, descentElement x z = epsilon * w ^ 2 := by
  obtain ⟨w, hw | hw | hw | hw⟩ :=
    descentElement_four_squareclasses_of_ideal_square x z I hideal
  · exact (hnonsquare ⟨w, by simpa [pow_two] using hw⟩).elim
  · have hnonpos := norm_neg_square_nonpos w
    rw [← hw] at hnonpos
    linarith
  · exact ⟨w, hw⟩
  · have hnonpos := norm_neg_epsilon_square_nonpos w
    rw [← hw] at hnonpos
    linarith

end MazurProof.BillingMahlerField
