import Mathlib.RingTheory.Discriminant
import Mathlib.RingTheory.Polynomial.Eisenstein.IsIntegral

/-!
# A discriminant--Eisenstein criterion for a monogenic integral closure

Let `R` be an integrally closed domain with fraction field `K`, and let
`L / K` have an integral power basis generated by `θ`.  If the discriminant
of that basis is a power of a prime `p` and the minimal polynomial of `θ`
is Eisenstein at `p`, then every element of the integral closure belongs to
`R[θ]`.

The proof has two structural steps.  The trace discriminant first puts
`p ^ n • z` in `R[θ]`; Eisenstein denominator removal then divides out the
entire power of `p`.  There is no local valuation enumeration.
-/

open Algebra Polynomial

namespace MazurProof

noncomputable section

universe u v w

theorem integralClosure_eq_adjoin_of_discr_eq_prime_pow
    {R : Type u} {K : Type v} {L : Type w}
    [CommRing R] [Field K] [Field L]
    [Algebra R K] [Algebra K L] [Algebra R L]
    [IsScalarTower R K L]
    [IsDomain R] [IsIntegrallyClosed R] [IsFractionRing R K]
    [Module.Finite K L] [Algebra.IsSeparable K L]
    {B : PowerBasis K L}
    {p : R} {n : ℕ}
    (hp : Prime p)
    (hBint : IsIntegral R B.gen)
    (hdisc : Algebra.discr K B.basis = algebraMap R K (p ^ n))
    (hei : (minpoly R B.gen).IsEisensteinAt
      (Submodule.span R {p})) :
    integralClosure R L = Algebra.adjoin R ({B.gen} : Set L) := by
  apply le_antisymm
  · intro z hz
    change IsIntegral R z at hz
    have hzDisc :
        Algebra.discr K B.basis • z ∈
          Algebra.adjoin R ({B.gen} : Set L) :=
      Algebra.discr_mul_isIntegral_mem_adjoin K hBint hz
    have hpz :
        p ^ n • z ∈ Algebra.adjoin R ({B.gen} : Set L) := by
      rw [hdisc] at hzDisc
      simpa only [IsScalarTower.algebraMap_smul] using hzDisc
    exact
      mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt
        hp hBint hz hpz hei
  · exact adjoin_le_integralClosure hBint

end

end MazurProof
