import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# Cross-quadratic errors in two disjoint variable blocks

For a polynomial ring whose variables are split into a left and a right
block, the two coordinate-axis ideals have intersection equal to their
product.  Consequently a polynomial that vanishes on both axes has a
mixed factor.

The proof is by monomial support.  It is independent of N13 and performs no
coefficient expansion.
-/

namespace MazurProof.N13CrossQuadraticPolynomial

noncomputable section

open MvPolynomial

universe u

variable (R : Type u) [CommRing R]

abbrev Var : Type :=
  Sum (Fin 2) (Fin 2)

abbrev BiPoly : Type u :=
  MvPolynomial Var R

def leftIndices : Set Var :=
  Set.range Sum.inl

def rightIndices : Set Var :=
  Set.range Sum.inr

def leftVar (i : Fin 2) : BiPoly R :=
  X (Sum.inl i)

def rightVar (i : Fin 2) : BiPoly R :=
  X (Sum.inr i)

def leftIdeal : Ideal (BiPoly R) :=
  Ideal.span (X '' leftIndices)

def rightIdeal : Ideal (BiPoly R) :=
  Ideal.span (X '' rightIndices)

theorem mem_leftIdeal_iff (p : BiPoly R) :
    p ∈ leftIdeal R ↔
      ∀ m ∈ p.support,
        ∃ i : Fin 2, m (Sum.inl i) ≠ 0 := by
  rw [leftIdeal, MvPolynomial.mem_ideal_span_X_image]
  constructor
  · intro h m hm
    obtain ⟨i, hi, hmi⟩ := h m hm
    obtain ⟨j, rfl⟩ := hi
    exact ⟨j, hmi⟩
  · intro h m hm
    obtain ⟨i, hmi⟩ := h m hm
    exact ⟨Sum.inl i, ⟨i, rfl⟩, hmi⟩

theorem mem_rightIdeal_iff (p : BiPoly R) :
    p ∈ rightIdeal R ↔
      ∀ m ∈ p.support,
        ∃ i : Fin 2, m (Sum.inr i) ≠ 0 := by
  rw [rightIdeal, MvPolynomial.mem_ideal_span_X_image]
  constructor
  · intro h m hm
    obtain ⟨i, hi, hmi⟩ := h m hm
    obtain ⟨j, rfl⟩ := hi
    exact ⟨j, hmi⟩
  · intro h m hm
    obtain ⟨i, hmi⟩ := h m hm
    exact ⟨Sum.inr i, ⟨i, rfl⟩, hmi⟩

private theorem crossExponent_le
    (m : Var →₀ ℕ) (i j : Fin 2)
    (hi : m (Sum.inl i) ≠ 0)
    (hj : m (Sum.inr j) ≠ 0) :
    Finsupp.single (Sum.inl i) 1 +
        Finsupp.single (Sum.inr j) 1 ≤ m := by
  intro k
  by_cases hki : k = Sum.inl i
  · subst k
    simp [Nat.one_le_iff_ne_zero.mpr hi]
  · by_cases hkj : k = Sum.inr j
    · subst k
      simp [Nat.one_le_iff_ne_zero.mpr hj]
    · simp [hki, hkj]

private theorem crossMonomial_eq
    (i j : Fin 2) :
    monomial
        (Finsupp.single (Sum.inl i) 1 +
          Finsupp.single (Sum.inr j) 1)
        (1 : R) =
      leftVar R i * rightVar R j := by
  rw [monomial_add_single, ← X_pow_eq_monomial]
  simp [leftVar, rightVar]

private theorem monomial_mem_axis_product
    (p : BiPoly R) (m : Var →₀ ℕ)
    (i j : Fin 2)
    (hi : m (Sum.inl i) ≠ 0)
    (hj : m (Sum.inr j) ≠ 0) :
    monomial m (p.coeff m) ∈ leftIdeal R * rightIdeal R := by
  have hleft : leftVar R i ∈ leftIdeal R := by
    apply Ideal.subset_span
    exact ⟨Sum.inl i, ⟨i, rfl⟩, rfl⟩
  have hright : rightVar R j ∈ rightIdeal R := by
    apply Ideal.subset_span
    exact ⟨Sum.inr j, ⟨j, rfl⟩, rfl⟩
  have hcross :
      leftVar R i * rightVar R j ∈
        leftIdeal R * rightIdeal R :=
    Ideal.mul_mem_mul hleft hright
  have hdvd :
      monomial
          (Finsupp.single (Sum.inl i) 1 +
            Finsupp.single (Sum.inr j) 1)
          (1 : R) ∣
        monomial m (p.coeff m) := by
    apply MvPolynomial.monomial_dvd_monomial.mpr
    exact
      ⟨Or.inr (crossExponent_le m i j hi hj),
        one_dvd (p.coeff m)⟩
  rw [crossMonomial_eq] at hdvd
  obtain ⟨q, hq⟩ := hdvd
  rw [hq]
  exact (leftIdeal R * rightIdeal R).mul_mem_right q hcross

/-- The ideals generated by the two disjoint coordinate blocks meet
transversely. -/
theorem leftIdeal_inf_rightIdeal :
    leftIdeal R ⊓ rightIdeal R =
      leftIdeal R * rightIdeal R := by
  apply le_antisymm
  · intro p hp
    rw [MvPolynomial.as_sum p]
    apply Submodule.sum_mem
    intro m hm
    obtain ⟨i, hi⟩ :=
      (mem_leftIdeal_iff R p).mp hp.1 m hm
    obtain ⟨j, hj⟩ :=
      (mem_rightIdeal_iff R p).mp hp.2 m hm
    exact monomial_mem_axis_product R p m i j hi hj
  · exact Ideal.mul_le_inf

/-- Set the left coordinate block to zero. -/
def killLeft : BiPoly R →+* BiPoly R :=
  eval₂Hom
    (C : R →+* BiPoly R)
    (Sum.elim (fun _ => 0) (rightVar R))

/-- Set the right coordinate block to zero. -/
def killRight : BiPoly R →+* BiPoly R :=
  eval₂Hom
    (C : R →+* BiPoly R)
    (Sum.elim (leftVar R) (fun _ => 0))

private theorem sub_killLeft_mem
    (p : BiPoly R) :
    p - killLeft R p ∈ leftIdeal R := by
  induction p using MvPolynomial.induction_on with
  | C a =>
      simp [killLeft]
  | add p q hp hq =>
      simpa only [map_add, add_sub_add_comm] using
        (leftIdeal R).add_mem hp hq
  | mul_X p n hp =>
      rcases n with i | j
      · have hx : leftVar R i ∈ leftIdeal R := by
          apply Ideal.subset_span
          exact ⟨Sum.inl i, ⟨i, rfl⟩, rfl⟩
        simpa [killLeft, leftVar] using
          (leftIdeal R).mul_mem_left p hx
      · simpa [killLeft, rightVar, sub_mul] using
          (leftIdeal R).mul_mem_right (rightVar R j) hp

private theorem sub_killRight_mem
    (p : BiPoly R) :
    p - killRight R p ∈ rightIdeal R := by
  induction p using MvPolynomial.induction_on with
  | C a =>
      simp [killRight]
  | add p q hp hq =>
      simpa only [map_add, add_sub_add_comm] using
        (rightIdeal R).add_mem hp hq
  | mul_X p n hp =>
      rcases n with i | j
      · simpa [killRight, leftVar, sub_mul] using
          (rightIdeal R).mul_mem_right (leftVar R i) hp
      · have hx : rightVar R j ∈ rightIdeal R := by
          apply Ideal.subset_span
          exact ⟨Sum.inr j, ⟨j, rfl⟩, rfl⟩
        simpa [killRight, rightVar] using
          (rightIdeal R).mul_mem_left p hx

theorem ker_killLeft :
    RingHom.ker (killLeft R) = leftIdeal R := by
  apply le_antisymm
  · intro p hp
    have h := sub_killLeft_mem R p
    rw [RingHom.mem_ker.mp hp, sub_zero] at h
    exact h
  · rw [leftIdeal, Ideal.span_le]
    rintro _ ⟨x, ⟨i, rfl⟩, rfl⟩
    change killLeft R (X (Sum.inl i)) = 0
    simp [killLeft]

theorem ker_killRight :
    RingHom.ker (killRight R) = rightIdeal R := by
  apply le_antisymm
  · intro p hp
    have h := sub_killRight_mem R p
    rw [RingHom.mem_ker.mp hp, sub_zero] at h
    exact h
  · rw [rightIdeal, Ideal.span_le]
    rintro _ ⟨x, ⟨i, rfl⟩, rfl⟩
    change killRight R (X (Sum.inr i)) = 0
    simp [killRight]

def error
    (F : Fin 2 → BiPoly R) (i : Fin 2) : BiPoly R :=
  F i - leftVar R i - rightVar R i

/-- Once the two axis restrictions are the identity, the universal
addition error is cross-quadratic. -/
private theorem error_mem_cross_of_kernels
    (F : Fin 2 → BiPoly R)
    (hkerL : RingHom.ker (killLeft R) = leftIdeal R)
    (hkerR : RingHom.ker (killRight R) = rightIdeal R)
    (hAxisL : ∀ i, killLeft R (F i) = rightVar R i)
    (hAxisR : ∀ i, killRight R (F i) = leftVar R i)
    (i : Fin 2) :
    error R F i ∈ leftIdeal R * rightIdeal R := by
  rw [← leftIdeal_inf_rightIdeal R]
  constructor
  · rw [← hkerL]
    change killLeft R (error R F i) = 0
    simp only [error, map_sub, hAxisL i]
    simp [killLeft, leftVar, rightVar]
  · rw [← hkerR]
    change killRight R (error R F i) = 0
    simp only [error, map_sub, hAxisR i]
    simp [killRight, leftVar, rightVar]

/-- A polynomial addition law whose restrictions to both coordinate axes
are the identity differs from coordinatewise addition only by mixed terms. -/
theorem error_mem_cross
    (F : Fin 2 → BiPoly R)
    (hAxisL : ∀ i, killLeft R (F i) = rightVar R i)
    (hAxisR : ∀ i, killRight R (F i) = leftVar R i)
    (i : Fin 2) :
    error R F i ∈ leftIdeal R * rightIdeal R :=
  error_mem_cross_of_kernels R F
    (ker_killLeft R) (ker_killRight R) hAxisL hAxisR i

end

end MazurProof.N13CrossQuadraticPolynomial
