import Mathlib.Algebra.Group.Int.Even
import Mathlib.RingTheory.DedekindDomain.AdicValuation
import Mathlib.RingTheory.DedekindDomain.Factorization
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Localization.Ideal
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.Tactic

/-!
# From a square ideal on a good order to even height-one counts

The N13 Mumford relation gives an ideal-square identity only after
inverting the derivative of the sextic.  At every maximal-order prime
where that derivative is a unit, this file maps the identity to the
corresponding DVR and proves that the principal fractional-ideal count
of the Kummer value is even.

The argument is local and structural.  It does not factor any ideal or
enumerate any primes.
-/

open scoped nonZeroDivisors

open IsDedekindDomain
open IsDedekindDomain.HeightOneSpectrum
open Submodule.IsPrincipal
open WithZero Multiplicative

noncomputable section

namespace MazurProof.GoodOrderSquareToCount

variable {O L : Type*}
variable [CommRing O] [IsDedekindDomain O]
variable [Field L] [Algebra O L] [IsFractionRing O L]

abbrev AtPrime (P : HeightOneSpectrum O) :=
  P.valuationSubringAtPrime L

/-- The height-one count of the principal fractional ideal generated by
`x`. -/
noncomputable def principalCount
    (P : HeightOneSpectrum O) (x : L) : ℤ :=
  FractionalIdeal.count L P
    (FractionalIdeal.spanSingleton O⁰ x)

@[simp] theorem principalCount_one (P : HeightOneSpectrum O) :
    principalCount P (1 : L) = 0 := by
  simp [principalCount, FractionalIdeal.count_one]

theorem principalCount_mul
    (P : HeightOneSpectrum O)
    {x y : L} (hx : x ≠ 0) (hy : y ≠ 0) :
    principalCount P (x * y) =
      principalCount P x + principalCount P y := by
  unfold principalCount
  rw [← FractionalIdeal.spanSingleton_mul_spanSingleton]
  exact FractionalIdeal.count_mul L P
    (FractionalIdeal.spanSingleton_ne_zero_iff.mpr hx)
    (FractionalIdeal.spanSingleton_ne_zero_iff.mpr hy)

theorem principalCount_pow
    (P : HeightOneSpectrum O) (x : L) (n : ℕ) :
    principalCount P (x ^ n) =
      (n : ℤ) * principalCount P x := by
  unfold principalCount
  rw [← FractionalIdeal.spanSingleton_pow]
  exact FractionalIdeal.count_pow L P n
    (FractionalIdeal.spanSingleton O⁰ x)

/-- The multiplicative adic valuation and the principal fractional-ideal
count use opposite sign conventions. -/
theorem valuation_eq_exp_neg_principalCount
    (P : HeightOneSpectrum O)
    {x : L} (hx : x ≠ 0) :
    P.valuation L x = WithZero.exp (-principalCount P x) := by
  obtain ⟨n, d, hnd⟩ :=
    IsLocalization.exists_mk'_eq O⁰ x

  have hmk : IsLocalization.mk' L n d ≠ 0 := by
    simpa only [hnd] using hx

  have hn : n ≠ 0 :=
    IsLocalization.ne_zero_of_mk'_ne_zero hmk

  have hd : (d : O) ≠ 0 :=
    nonZeroDivisors.ne_zero d.property

  have hspan :
      FractionalIdeal.spanSingleton O⁰
          (IsLocalization.mk' L n d) =
        FractionalIdeal.spanSingleton O⁰
            (algebraMap O L (d : O))⁻¹ *
          (Ideal.span {n} : FractionalIdeal O⁰ L) := by
    rw [FractionalIdeal.coeIdeal_span_singleton,
      FractionalIdeal.spanSingleton_mul_spanSingleton]
    apply congrArg
    rw [IsFractionRing.mk'_eq_div, div_eq_mul_inv, mul_comm]

  have hspan0 :
      FractionalIdeal.spanSingleton O⁰
          (IsLocalization.mk' L n d) ≠ 0 :=
    FractionalIdeal.spanSingleton_ne_zero_iff.mpr hmk

  have hcount :=
    FractionalIdeal.count_well_defined L P hspan0 hspan

  rw [← hnd, P.valuation_of_mk',
    P.intValuation_if_neg hn,
    P.intValuation_if_neg hd,
    principalCount, hcount, ← exp_sub]
  congr 1
  ring

theorem principalCount_nonneg_of_mem_atPrime
    (P : HeightOneSpectrum O)
    (x : AtPrime (O := O) (L := L) P)
    (hx : (x : L) ≠ 0) :
    0 ≤ principalCount (O := O) P (x : L) := by
  have hxmem :
      (x : L) ∈ (P.valuation L).valuationSubring := by
    rw [← P.valuationSubringAtPrime_eq_valuationSubring
      (K := L)]
    exact x.property

  have hv : P.valuation L (x : L) ≤ 1 :=
    (Valuation.mem_valuationSubring_iff
      (P.valuation L) (x : L)).mp hxmem

  rw [valuation_eq_exp_neg_principalCount P hx,
    ← exp_zero, exp_le_exp] at hv
  omega

/-- A unit in the local ring at `P` has zero full-ring `P`-count. -/
theorem principalCount_eq_zero_of_isUnit_atPrime
    (P : HeightOneSpectrum O)
    (x : AtPrime (O := O) (L := L) P)
    (hx : IsUnit x) :
    principalCount (O := O) P (x : L) = 0 := by
  rcases hx with ⟨u, rfl⟩

  let y : AtPrime (O := O) (L := L) P :=
    (u⁻¹ : (AtPrime (O := O) (L := L) P)ˣ)

  have hu0 :
      (((u : AtPrime (O := O) (L := L) P) : L)) ≠ 0 := by
    intro h
    exact Units.ne_zero u (Subtype.ext h)

  have hy0 :
      ((y : AtPrime (O := O) (L := L) P) : L) ≠ 0 := by
    intro h
    exact Units.ne_zero (u⁻¹) (Subtype.ext h)

  have hu_nonneg :=
    principalCount_nonneg_of_mem_atPrime P
      (u : AtPrime (O := O) (L := L) P) hu0

  have hy_nonneg :=
    principalCount_nonneg_of_mem_atPrime P y hy0

  have hmul :
      (((u : AtPrime (O := O) (L := L) P) : L)) *
          ((y : AtPrime (O := O) (L := L) P) : L) = 1 := by
    have hlocal :
        (u : AtPrime (O := O) (L := L) P) *
            ((u⁻¹ : (AtPrime (O := O) (L := L) P)ˣ) :
              AtPrime (O := O) (L := L) P) = 1 := by
      simp
    dsimp [y]
    exact congrArg Subtype.val hlocal

  have hsum :
      principalCount (O := O)
          P (((u : AtPrime (O := O) (L := L) P) : L)) +
        principalCount (O := O)
          P ((y : AtPrime (O := O) (L := L) P) : L) = 0 := by
    calc
      principalCount (O := O)
          P (((u : AtPrime (O := O) (L := L) P) : L)) +
          principalCount (O := O)
            P ((y : AtPrime (O := O) (L := L) P) : L) =
        principalCount (O := O) P
          ((((u : AtPrime (O := O) (L := L) P) : L)) *
            ((y : AtPrime (O := O) (L := L) P) : L)) :=
        (principalCount_mul P hu0 hy0).symm
      _ = principalCount (O := O) P (1 : L) := by rw [hmul]
      _ = 0 := principalCount_one P

  omega

/-- Mapping an ideal-square identity through a ring homomorphism. -/
theorem map_sq_eq_span
    {A B : Type*} [CommRing A] [CommRing B]
    (φ : A →+* B)
    (J : Ideal A) (a : A)
    (hJ : J ^ 2 = Ideal.span ({a} : Set A)) :
    (J.map φ) ^ 2 = Ideal.span ({φ a} : Set B) := by
  have h := congrArg (Ideal.map φ) hJ
  simpa only [Ideal.map_pow, Ideal.map_span,
    Set.image_singleton] using h

/-- If an ideal in the DVR at `P` has square `(a)`, the full-ring
height-one count of `a` is even. -/
theorem even_principalCount_of_local_ideal_sq
    (P : HeightOneSpectrum O)
    [IsPrincipalIdealRing (AtPrime (O := O) (L := L) P)]
    (J : Ideal (AtPrime (O := O) (L := L) P))
    (a : AtPrime (O := O) (L := L) P)
    (hJ : J ^ 2 =
      Ideal.span
        ({a} : Set (AtPrime (O := O) (L := L) P))) :
    Even (principalCount (O := O) P (a : L)) := by
  let y : AtPrime (O := O) (L := L) P :=
    Submodule.IsPrincipal.generator J

  have hyspan :
      Ideal.span
        ({y} : Set (AtPrime (O := O) (L := L) P)) = J :=
    Ideal.span_singleton_generator J

  have hspanSq :
      Ideal.span
          ({y ^ 2} : Set (AtPrime (O := O) (L := L) P)) =
        Ideal.span
          ({a} : Set (AtPrime (O := O) (L := L) P)) := by
    calc
      Ideal.span
          ({y ^ 2} : Set (AtPrime (O := O) (L := L) P)) =
          Ideal.span
              ({y} : Set (AtPrime (O := O) (L := L) P)) *
            Ideal.span
              ({y} : Set (AtPrime (O := O) (L := L) P)) := by
        simp [Ideal.span_singleton_mul_span_singleton, pow_two]
      _ = J ^ 2 := by rw [hyspan, pow_two]
      _ = Ideal.span
          ({a} : Set (AtPrime (O := O) (L := L) P)) := hJ

  have hspanFI :
      FractionalIdeal.spanSingleton
          (AtPrime (O := O) (L := L) P)⁰
          (algebraMap (AtPrime (O := O) (L := L) P) L
            (y ^ 2)) =
        FractionalIdeal.spanSingleton
          (AtPrime (O := O) (L := L) P)⁰
          (algebraMap (AtPrime (O := O) (L := L) P) L a) := by
    simpa only [FractionalIdeal.coeIdeal_span_singleton] using
      congrArg
        (fun I : Ideal (AtPrime (O := O) (L := L) P) =>
          (I : FractionalIdeal
            (AtPrime (O := O) (L := L) P)⁰ L))
        hspanSq

  obtain ⟨ε, hε⟩ :=
    (FractionalIdeal.spanSingleton_eq_spanSingleton).mp hspanFI

  have ha :
      (a : L) =
        (((ε : AtPrime (O := O) (L := L) P) : L)) *
          ((y : AtPrime (O := O) (L := L) P) : L) ^ 2 := by
    simpa [Units.smul_def, Algebra.smul_def] using hε.symm

  by_cases hy :
      ((y : AtPrime (O := O) (L := L) P) : L) = 0
  · have ha0 : (a : L) = 0 := by simp [ha, hy]
    rw [ha0, principalCount,
      FractionalIdeal.spanSingleton_zero,
      FractionalIdeal.count_zero]
    exact ⟨0, by simp⟩
  · have hε0 :
        (((ε : AtPrime (O := O) (L := L) P) : L)) ≠ 0 := by
      intro h
      exact Units.ne_zero ε (Subtype.ext h)

    have hεcount :
        principalCount (O := O)
            P (((ε : AtPrime (O := O) (L := L) P) : L)) = 0 :=
      principalCount_eq_zero_of_isUnit_atPrime
        P (ε : AtPrime (O := O) (L := L) P) ε.isUnit

    have hcount :
        principalCount (O := O) P (a : L) =
          2 * principalCount (O := O)
            P ((y : AtPrime (O := O) (L := L) P) : L) := by
      rw [ha,
        principalCount_mul P hε0 (pow_ne_zero 2 hy),
        hεcount,
        principalCount_pow,
        zero_add]
      norm_num

    exact ⟨principalCount (O := O)
        P ((y : AtPrime (O := O) (L := L) P) : L), by
      simpa [two_mul] using hcount⟩

variable {A : Type*} [CommRing A]

/-- Universal map from a localization away from `d` into the local ring
at `P`, once the image of `d` is a unit there. -/
noncomputable def awayToAtPrime
    (d : A)
    (P : HeightOneSpectrum O)
    (ρ : A →+* AtPrime (O := O) (L := L) P)
    (hd : IsUnit (ρ d)) :
    Localization.Away d →+* AtPrime (O := O) (L := L) P :=
  IsLocalization.Away.lift d hd

@[simp] theorem awayToAtPrime_algebraMap
    (d : A)
    (P : HeightOneSpectrum O)
    (ρ : A →+* AtPrime (O := O) (L := L) P)
    (hd : IsUnit (ρ d))
    (a : A) :
    awayToAtPrime d P ρ hd
        (algebraMap A (Localization.Away d) a) = ρ a :=
  IsLocalization.Away.lift_eq d hd a

/-- An ideal-square identity on `A[1/d]` forces even full-ring count at
every maximal-order prime where `d` is a unit. -/
theorem even_principalCount_of_away_ideal_sq
    (d : A)
    (P : HeightOneSpectrum O)
    (ρ : A →+* AtPrime (O := O) (L := L) P)
    (hd : IsUnit (ρ d))
    (J : Ideal (Localization.Away d))
    (a : Localization.Away d)
    (hJ : J ^ 2 =
      Ideal.span ({a} : Set (Localization.Away d))) :
    Even
      (principalCount (O := O) P
        (((awayToAtPrime d P ρ hd a :
          AtPrime (O := O) (L := L) P) : L))) := by
  letI : P.asIdeal.IsPrime := P.isPrime
  letI : IsDiscreteValuationRing
      (AtPrime (O := O) (L := L) P) :=
    IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain
      O P.ne_bot (AtPrime (O := O) (L := L) P)

  exact even_principalCount_of_local_ideal_sq
    P
    (J.map (awayToAtPrime d P ρ hd))
    (awayToAtPrime d P ρ hd a)
    (map_sq_eq_span
      (awayToAtPrime d P ρ hd) J a hJ)

end MazurProof.GoodOrderSquareToCount
