import FLT.Assumptions.MazurProof.N13MumfordAbelJacobi
import FLT.Assumptions.MazurProof.N13ProjectiveModel
import FLT.Assumptions.MazurProof.N13MumfordInfinityBalance
import FLT.Assumptions.MazurProof.N13InfinityMinusAPI
import Mathlib.Tactic

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open Polynomial
open scoped LaurentSeries nonZeroDivisors

namespace MazurProof.N13Arithmetic

/-!
Rational points on the N13 sextic curve and the Abel-Jacobi map.
-/

/-!
Point types and cusp definitions are in N13ProjectiveModel.lean.
This module provides the Abel-Jacobi map and divisor arithmetic.
-/

/-- Identify the proposed point type with the repository's existing
projective sextic point type, preserving both infinity branches. -/
def point13EquivCurvePoint :
    Point13 ≃ SexticMumford.CurvePoint (N13Mumford.model ℚ) where
  toFun := fun
    | Sum.inl ⟨⟨x, y⟩, h⟩ => N13Mumford.affineCurvePoint x y h
    | Sum.inr false => .infinityPlus
    | Sum.inr true => .infinityMinus
  invFun := fun
    | .infinityPlus => Sum.inr false
    | .infinityMinus => Sum.inr true
    | .affine x y h => Sum.inl ⟨(x, y), by
        change y ^ 2 = N13CurveModel.sexticF13 x
        change y ^ 2 = (N13Mumford.f ℚ).eval x at h
        exact h.trans (N13Mumford.f_eval_eq_sexticF13 x)⟩
  left_inv P := by
    cases P with
    | inl P =>
        rcases P with ⟨⟨x, y⟩, h⟩
        rfl
    | inr b =>
        cases b <;> rfl
  right_inv P := by
    cases P <;> rfl


@[simp]
theorem point13EquivCurvePoint_inr_false :
    point13EquivCurvePoint (Sum.inr false) =
      SexticMumford.CurvePoint.infinityPlus := rfl


@[simp]
theorem point13EquivCurvePoint_inr_true :
    point13EquivCurvePoint (Sum.inr true) =
      SexticMumford.CurvePoint.infinityMinus := rfl


/-- The existing oriented fractional-ideal presentation of the
characteristic-zero N13 Picard group, with the positive infinity chosen. -/
abbrev J13 : Type := N13MumfordAbelJacobi.ConcretePic ℚ


/-- The abelian-group structure is inherited from the actual quotient. -/
example : AddCommGroup J13 := inferInstance


/-- Abel--Jacobi with O = infinityPlus as base point, expressed on Point13. -/
def AJ13 (P : Point13) : J13 :=
  N13MumfordAbelJacobi.abelJacobi ℚ (point13EquivCurvePoint P)


/-- B01: the Abel--Jacobi map separates all rational projective points. -/
theorem AJ13_injective : Function.Injective AJ13 := by
  intro P Q h
  apply point13EquivCurvePoint.injective
  exact N13MumfordAbelJacobi.abelJacobi_injective ℚ h


/-- The chosen base point maps to the identity class. -/
@[simp]
theorem AJ13_infinityPlus : AJ13 (Sum.inr false) = 0 := by
  change SexticMumford.classOf (N13Mumford.model ℚ)
      (N13Infinity.positiveInfinityOrder ℚ)
      (SexticMumford.zero (N13Mumford.model ℚ)) = 0
  exact SexticMumford.classOf_zero
    (N13Mumford.model ℚ) (N13Infinity.positiveInfinityOrder ℚ)


/-!
For the smooth two-infinity sextic, a projective Cartier divisor is encoded
by its invertible fractional ideal on the affine chart together with its two
orders at the omitted infinity points.  This carrier uses arbitrary
invertible fractional ideals, not merely the subgroup generated by rational
points.
-/

abbrev RatFun13 := N13Mumford.FunctionField ℚ

abbrev AffineDiv13 :=
  Additive (SexticMumford.InvFrac (N13Mumford.model ℚ))

abbrev Div13 := AffineDiv13 × (ℤ × ℤ)

/-- An affine rational point, viewed on the actual sextic Mumford model. -/
private theorem affinePoint13_on_mumford (P : AffinePoint13) :
    P.1.2 ^ 2 = (N13Mumford.model ℚ).f.eval P.1.1 := by
  rw [N13Mumford.model_f, N13Mumford.f_eval_eq_sexticF13]
  simpa [N13CurveModel.C13SexticEq] using P.2

/-- The degree-one semi-Mumford datum of an affine rational point. -/
private def affinePointSemi13 (P : AffinePoint13) :
    SexticMumford.SemiMumford (N13Mumford.model ℚ) :=
  (SexticMumford.affinePointMumford
      (N13Mumford.model ℚ)
      P.1.1 P.1.2 (affinePoint13_on_mumford P)).toSemi

@[simp] private theorem affinePointSemi13_u (P : AffinePoint13) :
    (affinePointSemi13 P).u =
      Polynomial.X - Polynomial.C P.1.1 := rfl

@[simp] private theorem affinePointSemi13_v (P : AffinePoint13) :
    (affinePointSemi13 P).v = Polynomial.C P.1.2 := rfl

/-- The invertible fractional ideal of an affine rational point. -/
private def affinePointIdeal13 (P : AffinePoint13) :
    SexticMumford.InvFrac (N13Mumford.model ℚ) :=
  SexticMumford.mumfordIdealUnit
    (N13Mumford.model ℚ) (affinePointSemi13 P)

/-- Point divisors in the two-chart projective divisor carrier. -/
def pt13 : Point13 → Div13
  | Sum.inl P =>
      (Additive.ofMul (affinePointIdeal13 P), (0, 0))
  | Sum.inr false =>
      (0, (1, 0))
  | Sum.inr true =>
      (0, (0, 1))

/-- Principal divisor of a nonzero rational function. -/
def ratDiv13 (f : RatFun13ˣ) : Div13 :=
  (Additive.ofMul
      (toPrincipalIdeal
        (N13Mumford.CoordinateRing ℚ)
        (N13Mumford.FunctionField ℚ) f),
    (Multiplicative.toAdd
        ((N13Infinity.positiveInfinityOrder ℚ).ordPlus f),
      Multiplicative.toAdd
        ((N13InfinityMinus.negativeInfinityOrder ℚ).ordPlus f)))

/-- The constant unit `-1`. -/
private def negOneQ13 : ℚˣ :=
  Units.mk0 (-1 : ℚ) (by norm_num)

/-- The sextic coordinate `X`, as a nonzero rational function. -/
private def xFn13 : RatFun13ˣ :=
  SexticMumford.xClassFunctionUnit
    (N13Mumford.model ℚ)
    (Polynomial.X : ℚ[X]) (by simp)

/-- In optimized coordinates `u = -X-1`, hence `u+1=-X`. -/
def uPlusOneFn13 : RatFun13ˣ :=
  N13Infinity.functionConstUnit ℚ negOneQ13 * xFn13

/-! The two affine points above `X=0`. -/

private def cAffine13 : AffinePoint13 :=
  ⟨(0, 1),
    N13CurveModel.affine_cusp_mem (Or.inl rfl) (Or.inl rfl)⟩

private def dAffine13 : AffinePoint13 :=
  ⟨(0, -1),
    N13CurveModel.affine_cusp_mem (Or.inl rfl) (Or.inr rfl)⟩

@[simp] private theorem pt13_C :
    pt13 C =
      (Additive.ofMul (affinePointIdeal13 cAffine13), (0, 0)) := rfl

@[simp] private theorem pt13_D :
    pt13 D =
      (Additive.ofMul (affinePointIdeal13 dAffine13), (0, 0)) := rfl

@[simp] private theorem pt13_O :
    pt13 O = (0, (1, 0)) := rfl

@[simp] private theorem pt13_T :
    pt13 T = (0, (0, 1)) := rfl

/-!
On the affine chart the ideals of C and D are respectively
`(X,Y-1)` and `(X,Y+1)`; their product is the principal ideal `(X)`.
-/
private theorem affinePointIdeal_C_mul_D :
    affinePointIdeal13 cAffine13 * affinePointIdeal13 dAffine13 =
      toPrincipalIdeal
        (N13Mumford.CoordinateRing ℚ)
        (N13Mumford.FunctionField ℚ) xFn13 := by
  apply Units.ext
  simp only [affinePointIdeal13, Units.val_mul,
    SexticMumford.coe_mumfordIdealUnit,
    coe_toPrincipalIdeal, xFn13,
    SexticMumford.coe_xClassFunctionUnit]
  have h :=
    SexticMumford.mumfordIdeal_mul_conj_fractional
      (N13Mumford.model ℚ) (affinePointSemi13 cAffine13)
  simpa [cAffine13, dAffine13,
    FractionalIdeal.coeIdeal_span_singleton] using h

/-- Multiplying by the scalar unit `-1` does not alter the affine
principal fractional ideal. -/
private theorem principal_uPlusOneFn13 :
    toPrincipalIdeal
        (N13Mumford.CoordinateRing ℚ)
        (N13Mumford.FunctionField ℚ) uPlusOneFn13 =
      toPrincipalIdeal
        (N13Mumford.CoordinateRing ℚ)
        (N13Mumford.FunctionField ℚ) xFn13 := by
  simp [uPlusOneFn13]

private theorem principal_uPlusOneFn13_eq_C_mul_D :
    toPrincipalIdeal
        (N13Mumford.CoordinateRing ℚ)
        (N13Mumford.FunctionField ℚ) uPlusOneFn13 =
      affinePointIdeal13 cAffine13 * affinePointIdeal13 dAffine13 := by
  rw [principal_uPlusOneFn13]
  exact affinePointIdeal_C_mul_D.symm

/-! Exact pole orders at the two infinity branches. -/

private theorem ordPlus_xFn13 :
    Multiplicative.toAdd
        ((N13Infinity.positiveInfinityOrder ℚ).ordPlus xFn13) =
      -1 := by
  simpa [xFn13] using
    (N13MumfordInfinityBalance.ordPlus_xClassFunctionUnit
      (K := ℚ) (Polynomial.X : ℚ[X]) (by simp))

private theorem ordMinus_xFn13 :
    Multiplicative.toAdd
        ((N13InfinityMinus.negativeInfinityOrder ℚ).ordPlus xFn13) =
      -1 := by
  change
    (N13InfinityMinus.functionFieldToLaurentMinus ℚ
      (algebraMap
        (N13Mumford.CoordinateRing ℚ)
        (N13Mumford.FunctionField ℚ)
        (SexticMumford.xClass
          (N13Mumford.model ℚ) (Polynomial.X : ℚ[X])))).order = -1
  rw [N13InfinityMinus.functionFieldToLaurentMinus_algebraMap,
    N13InfinityMinus.coordinateToLaurentMinus_xClass]
  simpa using
    (N13BranchNorm.evalPoly_order ℚ
      (Polynomial.X : ℚ[X]) (by simp))

private theorem ordMinus_negOneConst13 :
    (N13InfinityMinus.negativeInfinityOrder ℚ).ordPlus
        (N13Infinity.functionConstUnit ℚ negOneQ13) = 1 := by
  simpa [N13Infinity.functionConstUnit,
    N13Infinity.coordinateConstUnit,
    N13InfinityMinus.functionConstUnitMinus,
    N13InfinityMinus.coordinateConstUnitMinus] using
      (N13InfinityMinus.ordPlus_functionConstUnitMinus ℚ negOneQ13)

private theorem ordPlus_uPlusOneFn13 :
    Multiplicative.toAdd
        ((N13Infinity.positiveInfinityOrder ℚ).ordPlus uPlusOneFn13) =
      -1 := by
  rw [uPlusOneFn13, map_mul,
    N13Infinity.ordPlus_functionConstUnit]
  simpa using ordPlus_xFn13

private theorem ordMinus_uPlusOneFn13 :
    Multiplicative.toAdd
        ((N13InfinityMinus.negativeInfinityOrder ℚ).ordPlus uPlusOneFn13) =
      -1 := by
  rw [uPlusOneFn13, map_mul, ordMinus_negOneConst13]
  simpa using ordMinus_xFn13

/-- B03: divisor of `u+1`. -/
theorem divisor_uPlusOne13 :
    ratDiv13 uPlusOneFn13 = pt13 C + pt13 D - pt13 O - pt13 T := by
  have hAffine :
      Additive.ofMul
          (toPrincipalIdeal
            (N13Mumford.CoordinateRing ℚ)
            (N13Mumford.FunctionField ℚ) uPlusOneFn13) =
        Additive.ofMul (affinePointIdeal13 cAffine13) +
          Additive.ofMul (affinePointIdeal13 dAffine13) := by
    change
      Additive.ofMul
          (toPrincipalIdeal
            (N13Mumford.CoordinateRing ℚ)
            (N13Mumford.FunctionField ℚ) uPlusOneFn13) =
        Additive.ofMul
          (affinePointIdeal13 cAffine13 * affinePointIdeal13 dAffine13)
    exact congrArg Additive.ofMul principal_uPlusOneFn13_eq_C_mul_D
  rw [pt13_C, pt13_D, pt13_O, pt13_T]
  apply Prod.ext
  · simpa [ratDiv13] using hAffine
  · apply Prod.ext
    · simpa [ratDiv13] using ordPlus_uPlusOneFn13
    · simpa [ratDiv13] using ordMinus_uPlusOneFn13

end MazurProof.N13Arithmetic
