import Mathlib.LinearAlgebra.Charpoly.ToMatrix
import Mathlib.LinearAlgebra.FreeModule.Finite.Basic
import Mathlib.LinearAlgebra.Matrix.Charpoly.Minpoly
import Mathlib.RingTheory.PowerBasis

/-!
# Rank-two quotient algebras for the N13 integral graph

Once a relative degree-two divisor has been shown finite and flat, its
affine coordinate quotient is free of rank two with the literal basis
`{1,x}`.  This file records the structural algebra needed to recover its
Mumford equation.

A basis `{1,x}` is a power basis.  Over an arbitrary nontrivial
commutative base ring, evaluation at its generator has kernel generated by
the power-basis relation polynomial.  That polynomial is also the
characteristic polynomial of multiplication by the generator.
-/

open Module
open Polynomial

namespace MazurProof.N13RankTwoQuotientAlgebra

noncomputable section

universe u v

variable {R : Type u} {B : Type v}

section PowerBasisKernel

variable [CommRing R] [Nontrivial R]
variable [Ring B] [Algebra R B]

/-- A power basis presents its algebra as the polynomial quotient by the
relation polynomial of its generator.  The proof uses monic division and
linear independence of the power basis, so no domain hypothesis is needed. -/
theorem ker_aeval_eq_span_minpolyGen
    (pb : PowerBasis R B) :
    RingHom.ker (aeval pb.gen) =
      Ideal.span ({pb.minpolyGen} : Set R[X]) := by
  apply le_antisymm
  · intro p hp
    rw [Ideal.mem_span_singleton]
    have hpRoot : aeval pb.gen p = 0 :=
      RingHom.mem_ker.mp hp
    have hremRoot :
        aeval pb.gen (p %ₘ pb.minpolyGen) = 0 := by
      have hdiv :=
        modByMonic_add_div p pb.minpolyGen
      calc
        aeval pb.gen (p %ₘ pb.minpolyGen) =
            aeval pb.gen
              (p - pb.minpolyGen * (p /ₘ pb.minpolyGen)) := by
          congr 1
          exact eq_sub_of_add_eq hdiv
        _ =
            aeval pb.gen p -
              aeval pb.gen pb.minpolyGen *
                aeval pb.gen (p /ₘ pb.minpolyGen) := by
          simp only [map_sub, map_mul]
        _ = 0 := by
          rw [hpRoot, pb.aeval_minpolyGen, zero_mul, sub_zero]
    have hrem :
        p %ₘ pb.minpolyGen = 0 := by
      by_contra hne
      have hle :=
        pb.dim_le_degree_of_root hne hremRoot
      have hlt :
          degree (p %ₘ pb.minpolyGen) < pb.dim := by
        simpa [pb.degree_minpolyGen] using
          degree_modByMonic_lt p pb.minpolyGen_monic
      exact (not_le_of_gt hlt) hle
    exact
      (modByMonic_eq_zero_iff_dvd pb.minpolyGen_monic).mp hrem
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    exact RingHom.mem_ker.mpr pb.aeval_minpolyGen

end PowerBasisKernel

section CharacteristicPolynomial

variable [CommRing R]
variable [Ring B] [Algebra R B]
variable [Module.Free R B] [Module.Finite R B]

/-- The characteristic polynomial of multiplication by the generator is
the power-basis relation polynomial. -/
theorem charpoly_lmul_eq_minpolyGen
    (pb : PowerBasis R B) :
    (Algebra.lmul R B pb.gen).charpoly =
      pb.minpolyGen := by
  rw [← LinearMap.charpoly_toMatrix
      (Algebra.lmul R B pb.gen) pb.basis,
    ← Algebra.leftMulMatrix_apply,
    charpoly_leftMulMatrix,
    ← pb.minpolyGen_eq]

/-- Hence the evaluation kernel is generated by the characteristic
polynomial of multiplication by the power-basis generator. -/
theorem ker_aeval_eq_span_charpoly
    [Nontrivial R]
    (pb : PowerBasis R B) :
    RingHom.ker (aeval pb.gen) =
      Ideal.span
        ({(Algebra.lmul R B pb.gen).charpoly} : Set R[X]) := by
  rw [charpoly_lmul_eq_minpolyGen]
  exact ker_aeval_eq_span_minpolyGen pb

end CharacteristicPolynomial

section LiteralOneXBasis

variable [CommRing R]
variable [Ring B] [Algebra R B]

/-- A literal rank-two basis `{1,x}` is a power basis generated by `x`. -/
def powerBasisOfOneX
    (x : B) (b : Basis (Fin 2) R B)
    (hb0 : b 0 = 1) (hb1 : b 1 = x) :
    PowerBasis R B where
  gen := x
  dim := 2
  basis := b
  basis_eq_pow i := by
    fin_cases i
    · simpa using hb0
    · simpa using hb1

@[simp] theorem powerBasisOfOneX_gen
    (x : B) (b : Basis (Fin 2) R B)
    (hb0 : b 0 = 1) (hb1 : b 1 = x) :
    (powerBasisOfOneX x b hb0 hb1).gen = x := rfl

@[simp] theorem powerBasisOfOneX_dim
    (x : B) (b : Basis (Fin 2) R B)
    (hb0 : b 0 = 1) (hb1 : b 1 = x) :
    (powerBasisOfOneX x b hb0 hb1).dim = 2 := rfl

/-- Kernel presentation specialized to a literal rank-two basis `{1,x}`. -/
theorem ker_aeval_eq_span_charpoly_of_one_x
    [Nontrivial R]
    [Module.Free R B] [Module.Finite R B]
    (x : B) (b : Basis (Fin 2) R B)
    (hb0 : b 0 = 1) (hb1 : b 1 = x) :
    RingHom.ker (aeval x) =
      Ideal.span
        ({(Algebra.lmul R B x).charpoly} : Set R[X]) := by
  simpa using
    ker_aeval_eq_span_charpoly
      (powerBasisOfOneX x b hb0 hb1)

/-- The multiplication characteristic polynomial is monic. -/
theorem charpoly_lmul_monic_of_one_x
    [Module.Free R B] [Module.Finite R B]
    (x : B) :
    (Algebra.lmul R B x).charpoly.Monic :=
  LinearMap.charpoly_monic _

/-- For a rank-two power basis, the multiplication characteristic
polynomial has degree exactly two. -/
theorem charpoly_lmul_natDegree_of_one_x
    [Nontrivial R]
    [Module.Free R B] [Module.Finite R B]
    (x : B) (b : Basis (Fin 2) R B)
    (hb0 : b 0 = 1) (hb1 : b 1 = x) :
    (Algebra.lmul R B x).charpoly.natDegree = 2 := by
  let pb := powerBasisOfOneX x b hb0 hb1
  calc
    (Algebra.lmul R B x).charpoly.natDegree =
        pb.minpolyGen.natDegree := by
      rw [show x = pb.gen by rfl,
        charpoly_lmul_eq_minpolyGen]
    _ = pb.dim := pb.natDegree_minpolyGen
    _ = 2 := rfl

/-- Cayley--Hamilton gives the defining quadratic relation at `x`. -/
theorem aeval_charpoly_lmul_eq_zero
    [Module.Free R B] [Module.Finite R B]
    (x : B) :
    aeval x (Algebra.lmul R B x).charpoly = 0 :=
  Algebra.aeval_self_charpoly_lmul x

/-- Every element of a rank-two algebra with basis `{1,x}` has a unique
linear-polynomial expression in `x`; only existence is needed downstream. -/
theorem exists_eq_algebraMap_add_algebraMap_mul
    [Nontrivial R] [Nontrivial B]
    (x y : B) (b : Basis (Fin 2) R B)
    (hb0 : b 0 = 1) (hb1 : b 1 = x) :
    ∃ a c : R,
      y = algebraMap R B a + algebraMap R B c * x := by
  let pb := powerBasisOfOneX x b hb0 hb1
  obtain ⟨f, hf, hy⟩ := pb.exists_eq_aeval y
  have hf' : f.natDegree ≤ 1 := by
    simpa [pb] using Nat.le_of_lt_succ hf
  refine ⟨f.coeff 0, f.coeff 1, ?_⟩
  rw [Polynomial.eq_X_add_C_of_natDegree_le_one hf'] at hy
  have hy' :
      y =
        algebraMap R B (f.coeff 1) * x +
          algebraMap R B (f.coeff 0) := by
    simpa [pb] using hy
  calc
    y =
        algebraMap R B (f.coeff 1) * x +
          algebraMap R B (f.coeff 0) := hy'
    _ =
        algebraMap R B (f.coeff 0) +
          algebraMap R B (f.coeff 1) * x := by
      rw [add_comm]

end LiteralOneXBasis

end

end MazurProof.N13RankTwoQuotientAlgebra
