import FLT.Assumptions.MazurProof.N13TwoAdicAbelChartData
import Mathlib.RingTheory.Nakayama

/-!
# Relative square Nakayama for the N13 two-adic chart

A first-order comparison between two disk pairs naturally lives modulo the
square of the ideal generated by both pairs of coordinates.  This file
proves that such a symmetric comparison is already one-sided over the local
ring `ℤ₂`.

The key commutative-algebra step is relative Nakayama: if
`K = I ⊔ J` lies in the maximal ideal and `J ≤ I ⊔ K²`, then finite
generation forces `J ≤ I`.  Applied to the two coordinate ideals, this
turns a congruence modulo `(I_P ⊔ I_Q)²` into the exact
`I_P²` congruence required by the unary kernel chart.
-/

namespace MazurProof.N13TwoAdicCoordinateNakayama

noncomputable section

local instance : Fact (Nat.Prime 2) :=
  ⟨Nat.prime_two⟩

abbrev R₂ : Type :=
  N13TwoAdicAbelChartData.R₂

abbrev DiskPair : Type :=
  N13TwoAdicAbelChartData.DiskPair

abbrev maximal : Ideal R₂ :=
  N13TwoAdicAbelChartData.maximal

abbrev coordIdeal (P : DiskPair) : Ideal R₂ :=
  N13TwoAdicKernelChart.coordIdeal
    N13TwoAdicAbelChartData.DiskPair.coord P

/-- Relative square Nakayama for two ideals in a local ring. -/
theorem le_left_of_le_left_sup_sq
    {R : Type*} [CommRing R] [IsLocalRing R]
    (I J : Ideal R)
    (hI : I ≤ IsLocalRing.maximalIdeal R)
    (hJ : J ≤ IsLocalRing.maximalIdeal R)
    (hKfg : (I ⊔ J : Ideal R).FG)
    (hmod : J ≤ I ⊔ (I ⊔ J) ^ 2) :
    J ≤ I := by
  have hKmax :
      I ⊔ J ≤ IsLocalRing.maximalIdeal R :=
    sup_le hI hJ
  have hKsq :
      (I ⊔ J) ^ 2 ≤
        IsLocalRing.maximalIdeal R • (I ⊔ J) := by
    rw [pow_two, Ideal.smul_eq_mul]
    exact mul_le_mul' hKmax le_rfl
  have hKstepSq :
      I ⊔ J ≤ I ⊔ (I ⊔ J) ^ 2 :=
    sup_le le_sup_left hmod
  have hKstep :
      I ⊔ J ≤
        I ⊔ IsLocalRing.maximalIdeal R • (I ⊔ J) :=
    hKstepSq.trans (sup_le_sup le_rfl hKsq)
  have hKI : I ⊔ J ≤ I :=
    Submodule.le_of_le_smul_of_le_jacobson_bot
      hKfg
      (IsLocalRing.maximalIdeal_le_jacobson (⊥ : Ideal R))
      hKstep
  exact le_sup_right.trans hKI

theorem coordIdeal_le_maximal (P : DiskPair) :
    coordIdeal P ≤ maximal := by
  rw [coordIdeal, N13TwoAdicKernelChart.coordIdeal,
    Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  exact
    N13TwoAdicAbelChartData.DiskPair.coord_mem_maximal P i

theorem coordIdeal_fg (P : DiskPair) :
    (coordIdeal P).FG := by
  exact Submodule.fg_span (Set.finite_range _)

/-- A symmetric first-order doubling comparison forces the doubled
coordinate ideal to lie in the original coordinate ideal. -/
theorem coordIdeal_le_of_double_sub_mem_sup_sq
    (P Q : DiskPair)
    (hfirst :
      ∀ i : Fin 2,
        N13TwoAdicAbelChartData.DiskPair.coord Q i -
            (N13TwoAdicAbelChartData.DiskPair.coord P i +
              N13TwoAdicAbelChartData.DiskPair.coord P i) ∈
          (coordIdeal P ⊔ coordIdeal Q) ^ 2) :
    coordIdeal Q ≤ coordIdeal P := by
  have hmod :
      coordIdeal Q ≤
        coordIdeal P ⊔
          (coordIdeal P ⊔ coordIdeal Q) ^ 2 := by
    apply (Ideal.span_le).2
    rintro _ ⟨i, rfl⟩
    have hp :
        N13TwoAdicAbelChartData.DiskPair.coord P i ∈
          coordIdeal P := by
      apply Ideal.subset_span
      exact Set.mem_range_self i
    have hdouble :
        N13TwoAdicAbelChartData.DiskPair.coord P i +
            N13TwoAdicAbelChartData.DiskPair.coord P i ∈
          coordIdeal P :=
      (coordIdeal P).add_mem hp hp
    have hdiff :
        N13TwoAdicAbelChartData.DiskPair.coord Q i -
              (N13TwoAdicAbelChartData.DiskPair.coord P i +
                N13TwoAdicAbelChartData.DiskPair.coord P i) ∈
            coordIdeal P ⊔
              (coordIdeal P ⊔ coordIdeal Q) ^ 2 :=
      (show
        (coordIdeal P ⊔ coordIdeal Q) ^ 2 ≤
          coordIdeal P ⊔
            (coordIdeal P ⊔ coordIdeal Q) ^ 2 from
        le_sup_right) (hfirst i)
    have hlin :
        N13TwoAdicAbelChartData.DiskPair.coord P i +
              N13TwoAdicAbelChartData.DiskPair.coord P i ∈
            coordIdeal P ⊔
              (coordIdeal P ⊔ coordIdeal Q) ^ 2 :=
      (show
        coordIdeal P ≤
          coordIdeal P ⊔
            (coordIdeal P ⊔ coordIdeal Q) ^ 2 from
        le_sup_left) hdouble
    rw [← sub_add_cancel
      (N13TwoAdicAbelChartData.DiskPair.coord Q i)
      (N13TwoAdicAbelChartData.DiskPair.coord P i +
        N13TwoAdicAbelChartData.DiskPair.coord P i)]
    exact
      (coordIdeal P ⊔
        (coordIdeal P ⊔ coordIdeal Q) ^ 2).add_mem
        hdiff hlin
  exact
    le_left_of_le_left_sup_sq
      (coordIdeal P) (coordIdeal Q)
      (coordIdeal_le_maximal P)
      (coordIdeal_le_maximal Q)
      (Submodule.FG.sup (coordIdeal_fg P) (coordIdeal_fg Q))
      hmod

/-- The symmetric square-zero comparison already gives the one-sided
quadratic estimate used by the unary doubling chart. -/
theorem double_sub_mem_coordIdeal_sq_of_sup_sq
    (P Q : DiskPair)
    (hfirst :
      ∀ i : Fin 2,
        N13TwoAdicAbelChartData.DiskPair.coord Q i -
            (N13TwoAdicAbelChartData.DiskPair.coord P i +
              N13TwoAdicAbelChartData.DiskPair.coord P i) ∈
          (coordIdeal P ⊔ coordIdeal Q) ^ 2)
    (i : Fin 2) :
    N13TwoAdicAbelChartData.DiskPair.coord Q i -
          (N13TwoAdicAbelChartData.DiskPair.coord P i +
            N13TwoAdicAbelChartData.DiskPair.coord P i) ∈
        coordIdeal P * coordIdeal P := by
  have hle :=
    coordIdeal_le_of_double_sub_mem_sup_sq P Q hfirst
  have hsup :
      coordIdeal P ⊔ coordIdeal Q = coordIdeal P :=
    sup_eq_left.mpr hle
  simpa only [hsup, pow_two] using hfirst i

end

end MazurProof.N13TwoAdicCoordinateNakayama
