import Mathlib.Algebra.Algebra.Tower
import Mathlib.LinearAlgebra.Basis.Defs
import Mathlib.LinearAlgebra.Isomorphisms
import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.LocalRing.Module
import Mathlib.RingTheory.LocalRing.ResidueField.Basic
import Mathlib.RingTheory.TensorProduct.Basic

/-!
# Identifying a tensor special fibre from its quotient map

Suppose a surjective quotient-reduction map has kernel generated by the
image of a uniformizer.  Tensoring with the residue field then gives the
target quotient exactly.  The proof uses pure tensors and moves the
uniformizer to the residue-field factor; it does not identify a separate
quotient of the source ideal.
-/

open scoped TensorProduct
open Module

namespace MazurProof.N13TensorSpecialFiber

noncomputable section

universe uR uk uB uC uι

variable {R : Type uR} {k : Type uk}
variable {B : Type uB} {C : Type uC}
variable [CommRing R] [CommRing k]
variable [CommRing B] [CommRing C]
variable [Algebra R k] [Algebra R B] [Algebra R C]
variable [Algebra k C] [IsScalarTower R k C]

/-- Regard a ring homomorphism as an `R`-algebra homomorphism through the
supplied scalar factorization. -/
def factoredAlgHom
    (g : B →+* C)
    (hfactor :
      g.comp (algebraMap R B) =
        (algebraMap k C).comp (algebraMap R k)) :
    B →ₐ[R] C where
  toRingHom := g
  commutes' r := by
    calc
      g (algebraMap R B r) =
          algebraMap k C (algebraMap R k r) := by
        simpa only [RingHom.comp_apply] using
          DFunLike.congr_fun hfactor r
      _ = algebraMap R C r :=
        (IsScalarTower.algebraMap_apply R k C r).symm

@[simp] theorem factoredAlgHom_apply
    (g : B →+* C)
    (hfactor :
      g.comp (algebraMap R B) =
        (algebraMap k C).comp (algebraMap R k))
    (b : B) :
    factoredAlgHom g hfactor b = g b :=
  rfl

/-- The canonical map `a ⊗ b ↦ a • g(b)`. -/
def tensorLinearMap
    (g : B →+* C)
    (hfactor :
      g.comp (algebraMap R B) =
        (algebraMap k C).comp (algebraMap R k)) :
    k ⊗[R] B →ₗ[k] C :=
  (factoredAlgHom g hfactor).toLinearMap.liftBaseChange k

@[simp] theorem tensorLinearMap_tmul
    (g : B →+* C)
    (hfactor :
      g.comp (algebraMap R B) =
        (algebraMap k C).comp (algebraMap R k))
    (a : k) (b : B) :
    tensorLinearMap g hfactor (a ⊗ₜ[R] b) =
      a • g b := by
  simp [tensorLinearMap]

private theorem tensorLinearMap_eq_zero
    (g : B →+* C)
    (hfactor :
      g.comp (algebraMap R B) =
        (algebraMap k C).comp (algebraMap R k))
    (hq : Function.Surjective (algebraMap R k))
    (π : R)
    (hπ : algebraMap R k π = 0)
    (hker :
      RingHom.ker g =
        Ideal.span ({algebraMap R B π} : Set B))
    {z : k ⊗[R] B}
    (hz : tensorLinearMap g hfactor z = 0) :
    z = 0 := by
  obtain ⟨b, rfl⟩ :=
    (TensorProduct.mk_surjective R B k hq) z
  change
    tensorLinearMap g hfactor
        ((1 : k) ⊗ₜ[R] b) = 0 at hz
  change (1 : k) ⊗ₜ[R] b = 0
  have hgb : g b = 0 := by
    simpa only [tensorLinearMap_tmul, one_smul] using hz
  have hbker : b ∈ RingHom.ker g :=
    RingHom.mem_ker.mpr hgb
  rw [hker, Ideal.mem_span_singleton] at hbker
  obtain ⟨c, rfl⟩ := hbker
  calc
    (1 : k) ⊗ₜ[R] (algebraMap R B π * c) =
        (1 : k) ⊗ₜ[R] (π • c) := by
      rw [Algebra.smul_def]
    _ = (π • (1 : k)) ⊗ₜ[R] c :=
      (TensorProduct.smul_tmul
        (R := R) π (1 : k) c).symm
    _ = 0 := by
      simp only [Algebra.smul_def, hπ, zero_mul,
        TensorProduct.zero_tmul]

theorem tensorLinearMap_injective
    (g : B →+* C)
    (hfactor :
      g.comp (algebraMap R B) =
        (algebraMap k C).comp (algebraMap R k))
    (hq : Function.Surjective (algebraMap R k))
    (π : R)
    (hπ : algebraMap R k π = 0)
    (hker :
      RingHom.ker g =
        Ideal.span ({algebraMap R B π} : Set B)) :
    Function.Injective (tensorLinearMap g hfactor) := by
  intro z₁ z₂ hz
  have hzero :
      tensorLinearMap g hfactor (z₁ - z₂) = 0 := by
    simpa only [map_sub, hz, sub_self]
  exact sub_eq_zero.mp
    (tensorLinearMap_eq_zero
      (g := g) (hfactor := hfactor)
      (hq := hq) (π := π) (hπ := hπ)
      (hker := hker) hzero)

theorem tensorLinearMap_surjective
    (g : B →+* C)
    (hfactor :
      g.comp (algebraMap R B) =
        (algebraMap k C).comp (algebraMap R k))
    (hg : Function.Surjective g) :
    Function.Surjective (tensorLinearMap g hfactor) := by
  intro c
  obtain ⟨b, rfl⟩ := hg c
  exact ⟨(1 : k) ⊗ₜ[R] b, by simp⟩

/-- The explicit linear equivalence between the tensor special fibre and
the target quotient. -/
def tensorLinearEquiv
    (g : B →+* C)
    (hfactor :
      g.comp (algebraMap R B) =
        (algebraMap k C).comp (algebraMap R k))
    (hq : Function.Surjective (algebraMap R k))
    (π : R)
    (hπ : algebraMap R k π = 0)
    (hg : Function.Surjective g)
    (hker :
      RingHom.ker g =
        Ideal.span ({algebraMap R B π} : Set B)) :
    k ⊗[R] B ≃ₗ[k] C :=
  LinearEquiv.ofBijective (tensorLinearMap g hfactor)
    ⟨tensorLinearMap_injective
        (g := g) (hfactor := hfactor)
        (hq := hq) (π := π) (hπ := hπ)
        (hker := hker),
      tensorLinearMap_surjective
        (g := g) (hfactor := hfactor) hg⟩

@[simp] theorem tensorLinearEquiv_tmul
    (g : B →+* C)
    (hfactor :
      g.comp (algebraMap R B) =
        (algebraMap k C).comp (algebraMap R k))
    (hq : Function.Surjective (algebraMap R k))
    (π : R)
    (hπ : algebraMap R k π = 0)
    (hg : Function.Surjective g)
    (hker :
      RingHom.ker g =
        Ideal.span ({algebraMap R B π} : Set B))
    (a : k) (b : B) :
    tensorLinearEquiv g hfactor hq π hπ hg hker
        (a ⊗ₜ[R] b) =
      a • g b := by
  exact tensorLinearMap_tmul g hfactor a b

section ResidueField

variable [IsLocalRing R]

local notation "κ" => IsLocalRing.ResidueField R

variable [Algebra (IsLocalRing.ResidueField R) C]
variable [IsScalarTower R (IsLocalRing.ResidueField R) C]

theorem residueFactor
    (g : B →+* C)
    (hfactor :
      g.comp (algebraMap R B) =
        (algebraMap κ C).comp (IsLocalRing.residue R)) :
    g.comp (algebraMap R B) =
      (algebraMap κ C).comp (algebraMap R κ) := by
  simpa only [IsLocalRing.ResidueField.algebraMap_eq R] using hfactor

theorem residueAlgebraMap_surjective :
    Function.Surjective (algebraMap R κ) := by
  simpa only [IsLocalRing.ResidueField.algebraMap_eq R] using
    (IsLocalRing.residue_surjective (R := R))

theorem residueElement_eq_zero
    (π : R)
    (hπ : π ∈ IsLocalRing.maximalIdeal R) :
    algebraMap R κ π = 0 := by
  rw [IsLocalRing.ResidueField.algebraMap_eq R,
    IsLocalRing.residue_eq_zero_iff]
  exact hπ

/-- Residue-field specialization of `tensorLinearEquiv`. -/
def residueLinearEquiv
    (g : B →+* C)
    (hfactor :
      g.comp (algebraMap R B) =
        (algebraMap κ C).comp (IsLocalRing.residue R))
    (π : R)
    (hπ : π ∈ IsLocalRing.maximalIdeal R)
    (hg : Function.Surjective g)
    (hker :
      RingHom.ker g =
        Ideal.span ({algebraMap R B π} : Set B)) :
    κ ⊗[R] B ≃ₗ[κ] C :=
  tensorLinearEquiv
    (g := g)
    (hfactor := residueFactor g hfactor)
    (hq := residueAlgebraMap_surjective (R := R))
    (π := π)
    (hπ := residueElement_eq_zero π hπ)
    (hg := hg)
    (hker := hker)

@[simp] theorem residueLinearEquiv_tmul
    (g : B →+* C)
    (hfactor :
      g.comp (algebraMap R B) =
        (algebraMap κ C).comp (IsLocalRing.residue R))
    (π : R)
    (hπ : π ∈ IsLocalRing.maximalIdeal R)
    (hg : Function.Surjective g)
    (hker :
      RingHom.ker g =
        Ideal.span ({algebraMap R B π} : Set B))
    (a : κ) (b : B) :
    residueLinearEquiv g hfactor π hπ hg hker
        (a ⊗ₜ[R] b) =
      a • g b := by
  exact
    tensorLinearEquiv_tmul
      (g := g)
      (hfactor := residueFactor g hfactor)
      (hq := residueAlgebraMap_surjective (R := R))
      (π := π)
      (hπ := residueElement_eq_zero π hπ)
      (hg := hg)
      (hker := hker)
      a b

end ResidueField

section BasisTransport

variable {ι : Type uι}

/-- Pull a target basis back through the special-fibre equivalence. -/
def pullbackBasis
    (e : k ⊗[R] B ≃ₗ[k] C)
    (bC : Basis ι k C) :
    Basis ι k (k ⊗[R] B) :=
  bC.map e.symm

@[simp] theorem pullbackBasis_apply
    (e : k ⊗[R] B ≃ₗ[k] C)
    (bC : Basis ι k C)
    (i : ι) :
    pullbackBasis e bC i = e.symm (bC i) := by
  simp [pullbackBasis]

theorem mk_eq_pullbackBasis
    (e : k ⊗[R] B ≃ₗ[k] C)
    (v : ι → B)
    (bC : Basis ι k C)
    (heval :
      ∀ i : ι,
        e (TensorProduct.mk R k B 1 (v i)) = bC i) :
    ∀ i : ι,
      TensorProduct.mk R k B 1 (v i) =
        pullbackBasis e bC i := by
  intro i
  apply e.injective
  simpa [pullbackBasis] using heval i

end BasisTransport

end

end MazurProof.N13TensorSpecialFiber
