import FLT.Assumptions.MazurProof.N18RouteC_LocalThreeLargeTable

/-!
# The large positive-valuation chart modulo `pi^5`

When the weight exponent is at least two, both terms containing `pi` vanish
modulo `pi^5`.  The remaining equation is solved algebraically in cube
classes; no additional exhaustive table is needed.
-/

namespace MazurProof.N18RouteC.LocalThree

/-- If `W * (2D^3) = U^3` and all three coordinates are local units, then
the class of `W` belongs to the line generated by `2`. -/
theorem large_scaled_unit_value_in_dual_line
    (U D W : R5)
    (hU : IsUnit5 U) (hD : IsUnit5 D) (hW : IsUnit5 W)
    (hcurve : W * (2 * D ^ 3) = U ^ 3) :
    InDualLine W := by
  obtain ⟨s, hDs⟩ := exists_right_inverse5 D hD
  have hs : IsUnit5 s := isUnit5_of_mul_eq_one D s hDs
  have hscaled : (W * s ^ 3) * 2 = (U * s ^ 2) ^ 3 := by
    calc
      W * s ^ 3 * 2 = W * 2 * s ^ 3 := by ring
      _ = W * 2 * (D * s) ^ 3 * s ^ 3 := by rw [hDs]; simp
      _ = (W * (2 * D ^ 3)) * s ^ 6 := by ring
      _ = U ^ 3 * s ^ 6 := by rw [hcurve]
      _ = (U * s ^ 2) ^ 3 := by ring
  apply inDualLine_unscale W s hs
  exact large_scaled_d_one (W * s ^ 3)
    (isUnit5_mul hW (isUnit5_pow hs 3))
    ⟨U * s ^ 2, isUnit5_mul hU (isUnit5_pow hs 2), hscaled⟩

theorem pi5_pow_eq_zero_of_five_le {n : ℕ} (hn : 5 ≤ n) :
    pi5 ^ n = 0 := by
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hn
  rw [pow_add]
  have hpi5 : pi5 ^ 5 = 0 := pi5_fifth
  rw [hpi5, zero_mul]

theorem three_mul_pi5_pow_eq_zero_of_two_le {n : ℕ} (hn : 2 ≤ n) :
    (3 : R5) * pi5 ^ n = 0 := by
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hn
  rw [pow_add]
  have hbase : (3 : R5) * pi5 ^ 2 = 0 := by decide
  rw [← mul_assoc, hbase, zero_mul]

end MazurProof.N18RouteC.LocalThree
