import FLT.Assumptions.MazurProof.N18RouteC_LocalThree

/-! Executable certificates used by the homogeneous `pi^5` solubility proof. -/

namespace MazurProof.N18RouteC.LocalThree

set_option maxRecDepth 4000

def OnHomogeneous (U D W : R5) : Prop :=
  W * (W - 3 * U * D + 2 * D ^ 3) = U ^ 3

def InDualLine (W : R5) : Prop :=
  ∃ m : F3, CubeEq5 W (pow two5 m.val)

instance (U D W : R5) : Decidable (OnHomogeneous U D W) := by
  unfold OnHomogeneous
  infer_instance

instance (W : R5) : Decidable (InDualLine W) := by
  unfold InDualLine
  exact Fintype.decidableExistsFintype

/-- Precomputed dual-line witness table: for each `W` in the line generated by
the class of `2`, a pair `(m, r)` with `W = two5^m * r^3` and `r` a unit.
Slots for `W` not in the line hold a dummy value and are never used. -/
private def dualTable : List (F3 × R5) := [
(0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨1, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (1, ⟨2, 2, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (2, ⟨1, 2, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (1, ⟨1, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨2, 1, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (2, ⟨2, 2, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (2, ⟨1, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨1, 1, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (1, ⟨2, 1, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (2, ⟨2, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (1, ⟨1, 2, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨2, 2, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (1, ⟨2, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (2, ⟨1, 1, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨1, 2, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨2, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (2, ⟨2, 1, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (1, ⟨1, 1, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩),
  (0, ⟨0, 0, 0⟩)]

/-- The dual-line witness `(m, r)` of `W`, read off the table. -/
def dualData (w : R5) : F3 × R5 :=
  dualTable.getD (w.c0.val * 27 + w.c1.val * 3 + w.c2.val) (0, 0)

theorem one_isUnit5 : IsUnit5 (1 : R5) := by decide

-- The right inverse is read off the precomputed `inv5` table, so this is a
-- 243-case equality check rather than a `243 × 243` search.
set_option maxHeartbeats 0 in
theorem exists_right_inverse5 :
    ∀ x : R5, IsUnit5 x → ∃ y : R5, x * y = 1 := by
  intro x hx
  refine ⟨inv5 x, ?_⟩
  revert x; decide

theorem isUnit5_of_mul_eq_one :
    ∀ x y : R5, x * y = 1 → IsUnit5 y := by
  intro x y h
  rw [isUnit5_iff]
  intro hy0
  have h1 : red3 (1 : R5) = 1 := red3_one
  have h2 : red3 (x * y) = red3 x * red3 y := red3_mul x y
  rw [h, h1, hy0, mul_zero] at h2
  exact one_ne_zero h2

theorem isUnit5_mul {x y : R5}
    (hx : IsUnit5 x) (hy : IsUnit5 y) : IsUnit5 (x * y) := by
  rw [isUnit5_iff] at hx hy ⊢
  rw [red3_mul]
  exact mul_ne_zero hx hy

-- The dual-line membership witness is read off `dualData`, so the only search
-- left is over the hypothesis `∃ U`; kernel-checked, unbounded heartbeats.
set_option maxHeartbeats 0 in
theorem homogeneous_d_one :
    ∀ W : R5, IsUnit5 W →
      (∃ U : R5, OnHomogeneous U 1 W) → InDualLine W := by
  intro W hW hU
  refine ⟨(dualData W).1, (dualData W).2, ?_, ?_⟩
  · revert W; decide
  · revert W; decide

theorem homogeneous_nonunit_d_rep_coordinates :
    ∀ i j k : F3, ∀ U D : R5,
      IsUnit5 U → ¬IsUnit5 D →
      OnHomogeneous U D (unitRep i j k) → i = 0 ∧ j = 0 := by
  native_decide +revert

def OnScaledOne (U D W : R5) : Prop :=
  W * (pi5 ^ 3 * W - 3 * pi5 * U * D + 2 * D ^ 3) = U ^ 3

instance (U D W : R5) : Decidable (OnScaledOne U D W) := by
  unfold OnScaledOne
  infer_instance

set_option maxHeartbeats 0 in
theorem scaled_one_d_one :
    ∀ W : R5, IsUnit5 W →
      (∃ U : R5, IsUnit5 U ∧ OnScaledOne U 1 W) → InDualLine W := by
  intro W hW hU
  refine ⟨(dualData W).1, (dualData W).2, ?_, ?_⟩
  · revert W; decide
  · revert W; decide

end MazurProof.N18RouteC.LocalThree
