import FLT.Assumptions.MazurProof.N18RouteC_Split

/-!
# Concrete algebra for the N18 rational 3-isogeny

This file closes the marked order-three point and the affine equation
preservation of the Vélu map.  Totalization at the kernel and the proof that
the resulting point map is additive are kept as the remaining structural
isogeny seam.
-/

open scoped WeierstrassCurve.Affine

namespace MazurProof.N18RouteC.Isogeny

noncomputable section

instance E0_isElliptic : E0.IsElliptic where
  isUnit := by
    apply isUnit_iff_ne_zero.mpr
    norm_num [E0, WeierstrassCurve.Δ, WeierstrassCurve.b₂,
      WeierstrassCurve.b₄, WeierstrassCurve.b₆, WeierstrassCurve.b₈]

instance Ehat0_isElliptic : Ehat0.IsElliptic where
  isUnit := by
    apply isUnit_iff_ne_zero.mpr
    norm_num [Ehat0, WeierstrassCurve.Δ, WeierstrassCurve.b₂,
      WeierstrassCurve.b₄, WeierstrassCurve.b₆, WeierstrassCurve.b₈]

abbrev E0Point := WeierstrassCurve.Affine.Point E0
abbrev Ehat0Point := WeierstrassCurve.Affine.Point Ehat0

def T : E0Point :=
  .some 1 0 <| by
    apply WeierstrassCurve.Affine.equation_iff_nonsingular.mp
    rw [WeierstrassCurve.Affine.equation_iff]
    norm_num [E0]

def negT : E0Point :=
  .some 1 (-2) <| by
    apply WeierstrassCurve.Affine.equation_iff_nonsingular.mp
    rw [WeierstrassCurve.Affine.equation_iff]
    norm_num [E0]

theorem neg_T : -T = negT := by
  rw [T, negT, WeierstrassCurve.Affine.Point.neg_some,
    WeierstrassCurve.Affine.Point.some.injEq]
  constructor
  · rfl
  · norm_num [WeierstrassCurve.Affine.negY, E0]

theorem two_nsmul_T : (2 : ℕ) • T = negT := by
  rw [two_nsmul]
  have hy : (0 : L) ≠ WeierstrassCurve.Affine.negY E0 1 0 := by
    norm_num [WeierstrassCurve.Affine.negY, E0]
  change
    WeierstrassCurve.Affine.Point.some 1 0 _ +
      WeierstrassCurve.Affine.Point.some 1 0 _ = negT
  rw [WeierstrassCurve.Affine.Point.add_self_of_Y_ne hy]
  unfold negT
  rw [WeierstrassCurve.Affine.Point.some.injEq]
  constructor
  · rw [WeierstrassCurve.Affine.slope_of_Y_ne rfl hy]
    norm_num [WeierstrassCurve.Affine.addX,
      WeierstrassCurve.Affine.negY, E0]
  · rw [WeierstrassCurve.Affine.slope_of_Y_ne rfl hy]
    norm_num [WeierstrassCurve.Affine.addX,
      WeierstrassCurve.Affine.addY,
      WeierstrassCurve.Affine.negAddY,
      WeierstrassCurve.Affine.negY, E0]

theorem three_nsmul_T : (3 : ℕ) • T = 0 := by
  rw [show (3 : ℕ) = 2 + 1 by norm_num, add_nsmul, one_nsmul, two_nsmul_T]
  change
    WeierstrassCurve.Affine.Point.some 1 (-2) _ +
      WeierstrassCurve.Affine.Point.some 1 0 _ = 0
  rw [WeierstrassCurve.Affine.Point.add_of_Y_eq rfl]
  norm_num [WeierstrassCurve.Affine.negY, E0]

theorem addOrderOf_T : addOrderOf T = 3 := by
  apply addOrderOf_eq_prime three_nsmul_T
  exact WeierstrassCurve.Affine.Point.some_ne_zero _

/-! ## The rational cyclic kernel -/

/-- The order-three subgroup generated by the marked point `T`. -/
def H3 : AddSubgroup E0Point := AddSubgroup.zmultiples T

/-- The marked generator, regarded as an element of its cyclic subgroup. -/
def T3 : H3 := ⟨T, AddSubgroup.mem_zmultiples T⟩

theorem card_H3 : Nat.card H3 = 3 := by
  rw [H3, Nat.card_zmultiples, addOrderOf_T]

theorem three_nsmul_H3 (h : H3) : (3 : ℕ) • h = 0 := by
  have hcard : Nat.card H3 • h = 0 := card_nsmul_eq_zero'
  rwa [card_H3] at hcard

theorem three_nsmul_H3_coe (h : H3) : (3 : ℕ) • (h : E0Point) = 0 := by
  exact congrArg Subtype.val (three_nsmul_H3 h)

theorem T3_ne_zero : T3 ≠ 0 := by
  intro h
  have := congrArg Subtype.val h
  exact WeierstrassCurve.Affine.Point.some_ne_zero _ this

theorem addOrderOf_T3 : addOrderOf T3 = 3 := by
  apply addOrderOf_eq_prime (three_nsmul_H3 T3)
  exact T3_ne_zero

/-! ## Affine Vélu coordinates -/

def tateU (x : L) : L := x - 1
def tateW (x y : L) : L := y + 2 * x - 2

def tateResidual (u w : L) : L :=
  w ^ 2 - 3 * u * w + 2 * w - u ^ 3

def affineResidual (W : WeierstrassCurve L) (x y : L) : L :=
  y ^ 2 + W.a₁ * x * y + W.a₃ * y -
    (x ^ 3 + W.a₂ * x ^ 2 + W.a₄ * x + W.a₆)

theorem tate_change_identity (x y : L) :
    tateResidual (tateU x) (tateW x y) = affineResidual E0 x y := by
  unfold tateResidual tateU tateW affineResidual E0
  ring

def C (u : L) : L := u ^ 3 - 6 * u + 4
def A (u : L) : L := u ^ 3 + 6 * u - 8
def B (u : L) : L := -18 * u ^ 2 + 24 * u - 8
def N (u w : L) : L := A u * w + B u

def phiXi (x : L) : L := C (tateU x) / tateU x ^ 2
def phiEta (x y : L) : L := N (tateU x) (tateW x y) / tateU x ^ 3

theorem velu_ring_identity (u w : L) :
    N u w ^ 2 - 3 * u * C u * N u w + 2 * u ^ 3 * N u w -
        C u ^ 3 - 30 * u ^ 4 * C u - 26 * u ^ 6 =
      A u ^ 2 * tateResidual u w := by
  unfold N A B C tateResidual
  ring

theorem phi_affine_residual
    (x y : L) (hu : tateU x ≠ 0) :
    affineResidual Ehat0 (phiXi x) (phiEta x y) =
      A (tateU x) ^ 2 * tateResidual (tateU x) (tateW x y) /
        tateU x ^ 6 := by
  unfold affineResidual Ehat0 phiXi phiEta
  field_simp [hu]
  convert velu_ring_identity (tateU x) (tateW x y) using 1 <;> ring

theorem phi_preserves_curve
    {x y : L} (hC : affineResidual E0 x y = 0)
    (hu : tateU x ≠ 0) :
    affineResidual Ehat0 (phiXi x) (phiEta x y) = 0 := by
  rw [phi_affine_residual x y hu, tate_change_identity, hC, mul_zero, zero_div]

/-! ## Affine dual-isogeny coordinates -/

def dualX (xi : L) : L := xi + 3
def dualZ (xi eta : L) : L := eta - (3 / 2 : L) * xi + 1

def U (X : L) : L := X ^ 3 - 9 * X ^ 2 + 81 * X - 243
def V (X : L) : L := X ^ 3 - 81 * X + 486

def phihatU (xi : L) : L := U (dualX xi) / (9 * dualX xi ^ 2)

def phihatCompletedY (xi eta : L) : L :=
  V (dualX xi) * dualZ xi eta / (27 * dualX xi ^ 3)

def phihatX0 (xi : L) : L := phihatU xi + 1

def phihatY0 (xi eta : L) : L :=
  phihatCompletedY xi eta - phihatU xi / 2 - 1

def veluCompletedResidual (X Z : L) : L :=
  4 * Z ^ 2 - (4 * X ^ 3 - 27 * X ^ 2 + 162 * X - 243)

def tateCompletedResidual (u Y : L) : L :=
  4 * Y ^ 2 - (4 * u ^ 3 + 9 * u ^ 2 - 12 * u + 4)

theorem velu_completed_change_identity (xi eta : L) :
    veluCompletedResidual (dualX xi) (dualZ xi eta) =
      4 * affineResidual Ehat0 xi eta := by
  unfold veluCompletedResidual dualX dualZ affineResidual Ehat0
  ring

theorem tate_completed_change_identity (u w : L) :
    tateCompletedResidual u (w - (3 / 2 : L) * u + 1) =
      4 * tateResidual u w := by
  unfold tateCompletedResidual tateResidual
  ring

theorem dual_velu_ring_identity (X Z : L) (hX : X ≠ 0) :
    tateCompletedResidual
        (U X / (9 * X ^ 2))
        (V X * Z / (27 * X ^ 3)) =
      V X ^ 2 * veluCompletedResidual X Z / (729 * X ^ 6) := by
  unfold tateCompletedResidual veluCompletedResidual U V
  field_simp [hX]
  ring

theorem phihat_affine_residual
    (xi eta : L) (hX : dualX xi ≠ 0) :
    affineResidual E0 (phihatX0 xi) (phihatY0 xi eta) =
      V (dualX xi) ^ 2 * affineResidual Ehat0 xi eta /
        (729 * dualX xi ^ 6) := by
  have hdual := dual_velu_ring_identity (dualX xi) (dualZ xi eta) hX
  have hsource := velu_completed_change_identity xi eta
  have hu : tateU (phihatX0 xi) = phihatU xi := by
    unfold tateU phihatX0
    ring
  have hw :
      tateW (phihatX0 xi) (phihatY0 xi eta) =
        phihatCompletedY xi eta + (3 / 2 : L) * phihatU xi - 1 := by
    unfold tateW phihatX0 phihatY0
    ring
  rw [← tate_change_identity, hu, hw]
  have htarget' :
      tateCompletedResidual (phihatU xi) (phihatCompletedY xi eta) =
        4 * tateResidual (phihatU xi)
          (phihatCompletedY xi eta + (3 / 2 : L) * phihatU xi - 1) := by
    convert tate_completed_change_identity
      (phihatU xi)
      (phihatCompletedY xi eta + (3 / 2 : L) * phihatU xi - 1) using 1 <;>
      ring
  have hdual' :
      tateCompletedResidual (phihatU xi) (phihatCompletedY xi eta) =
        V (dualX xi) ^ 2 *
          veluCompletedResidual (dualX xi) (dualZ xi eta) /
            (729 * dualX xi ^ 6) := by
    simpa only [phihatU, phihatCompletedY] using hdual
  calc
    tateResidual (phihatU xi)
        (phihatCompletedY xi eta + (3 / 2 : L) * phihatU xi - 1) =
      tateCompletedResidual (phihatU xi) (phihatCompletedY xi eta) / 4 := by
        rw [htarget']
        ring
    _ = (V (dualX xi) ^ 2 *
          veluCompletedResidual (dualX xi) (dualZ xi eta) /
            (729 * dualX xi ^ 6)) / 4 := by rw [hdual']
    _ = V (dualX xi) ^ 2 * affineResidual Ehat0 xi eta /
          (729 * dualX xi ^ 6) := by rw [hsource]; ring

theorem phihat_preserves_curve
    {xi eta : L} (hC : affineResidual Ehat0 xi eta = 0)
    (hX : dualX xi ≠ 0) :
    affineResidual E0 (phihatX0 xi) (phihatY0 xi eta) = 0 := by
  rw [phihat_affine_residual xi eta hX, hC, mul_zero, zero_div]

end

end MazurProof.N18RouteC.Isogeny
