import FLT.Assumptions.MazurProof.N18RouteC_Cyclotomic

/-!
# Anti-invariant unit cube classes in `Q(zeta_9)`

Complex conjugation reduces every unit occurring in a norm-cube equation to
the single root-of-unity direction.  Squaring a root of unity lands in the
order-nine subgroup generated by `zeta_9`; reducing its exponent modulo three
gives the three forward-descent candidates.
-/

open scoped NumberField

namespace MazurProof.N18RouteC.CyclotomicUnits

open NumberField Cyclotomic

noncomputable section

theorem torsionOrder_M : NumberField.Units.torsionOrder M = 18 := by
  simpa [show ¬Even 9 by decide] using
    (IsCyclotomicExtension.Rat.torsionOrder_eq (n := 9) (K := M))

theorem zetaUnit_primitive : IsPrimitiveRoot zetaUnit 9 := by
  simpa [zetaUnit] using IsPrimitiveRoot.isUnit_unit
    (by norm_num) zeta_primitive.toInteger_isPrimitiveRoot

theorem torsion_square_zeta
    (τ : NumberField.Units.torsion M) :
    ∃ i < 9, zetaUnit ^ i = (τ.val : OMˣ) ^ 2 := by
  apply zetaUnit_primitive.eq_pow_of_mem_rootsOfUnity
  have ht : τ ^ 18 = 1 := by
    have hcard : τ ^ Fintype.card (NumberField.Units.torsion M) = 1 :=
      pow_card_eq_one
    have hc : Fintype.card (NumberField.Units.torsion M) = 18 := by
      change NumberField.Units.torsionOrder M = 18
      exact torsionOrder_M
    rw [hc] at hcard
    exact hcard
  have htval := congrArg Subtype.val ht
  rw [mem_rootsOfUnity]
  calc
    ((τ.val : OMˣ) ^ 2) ^ 9 = (τ.val : OMˣ) ^ 18 := by rw [← pow_mul]
    _ = 1 := by simpa using htval

theorem torsion_square_normal_form
    (τ : NumberField.Units.torsion M) :
    ∃ e : Fin 3, ∃ v : OMˣ,
      (τ.val : OMˣ) ^ 2 = zetaUnit ^ e.val * v ^ 3 := by
  obtain ⟨i, hi, hpow⟩ := torsion_square_zeta τ
  let e : Fin 3 := ⟨i % 3, Nat.mod_lt _ (by norm_num)⟩
  let k : ℕ := i / 3
  have hik : e.val + 3 * k = i := by
    dsimp [e, k]
    exact Nat.mod_add_div i 3
  refine ⟨e, zetaUnit ^ k, ?_⟩
  rw [← hpow, ← hik, pow_add]
  congr 1
  rw [← pow_mul]
  congr 1
  omega

/-- If a unit times its conjugate is a cube in the field, then its field
cube class is represented by one of `1`, `zeta`, or `zeta^2`. -/
theorem unit_norm_cube_classification
    (eps : OMˣ) (d : M)
    (hnorm : ((eps : OM) : M) *
      NumberField.IsCMField.complexConj M ((eps : OM) : M) = d ^ 3) :
    ∃ e : Fin 3, ∃ c : M,
      ((eps : OM) : M) = zeta ^ e.val * c ^ 3 := by
  let tau : NumberField.Units.torsion M :=
    NumberField.IsCMField.unitsMulComplexConjInv M eps
  obtain ⟨e, v, hv⟩ := torsion_square_normal_form tau
  let epsM : M := ((eps : OM) : M)
  let epsC : M := NumberField.IsCMField.complexConj M epsM
  have hepsM : epsM ≠ 0 := by simp [epsM]
  have hepsC : epsC ≠ 0 := by
    intro hzero
    apply hepsM
    have h := congrArg (NumberField.IsCMField.complexConj M) hzero
    simpa [epsC] using h
  have hd : d ≠ 0 := by
    intro hd0
    rw [hd0, zero_pow (by norm_num : (3 : ℕ) ≠ 0)] at hnorm
    exact (mul_ne_zero hepsM hepsC) hnorm
  have htau : (((tau.val : OMˣ) : OM) : M) = epsM * epsC⁻¹ := by
    dsimp [tau, epsM, epsC]
    rw [NumberField.IsCMField.unitsMulComplexConjInv_apply]
    simp only [Units.val_mul, map_mul, map_units_inv]
    congr 1
  have hvM := congrArg (fun u : OMˣ ↦ (((u : OM) : M))) hv
  refine ⟨e, (((v : OM) : M)) * (epsC / d), ?_⟩
  have hnorm' : epsM * epsC = d ^ 3 := hnorm
  have htauSq : (epsM * epsC⁻¹) ^ 2 =
      zeta ^ e.val * (((v : OM) : M)) ^ 3 := by
    calc
      (epsM * epsC⁻¹) ^ 2 =
          ((((tau.val : OMˣ) : OM) : M)) ^ 2 := by rw [htau]
      _ = zeta ^ e.val * (((v : OM) : M)) ^ 3 := by simpa using hvM
  change epsM = zeta ^ e.val *
    ((((v : OM) : M)) * (epsC / d)) ^ 3
  calc
    epsM = (epsM * epsC⁻¹) ^ 2 * (epsC / d) ^ 3 := by
      field_simp [hd, hepsC]
      rw [← hnorm']
    _ = (zeta ^ e.val * (((v : OM) : M)) ^ 3) *
        (epsC / d) ^ 3 := by rw [htauSq]
    _ = zeta ^ e.val *
        ((((v : OM) : M)) * (epsC / d)) ^ 3 := by ring

end

end MazurProof.N18RouteC.CyclotomicUnits
