import FLT.Assumptions.MazurProof.TorsionDefs

/-!
# `PrimeTailPackage p` — a precise, citable replacement for the opaque prime-tail axiom

For the Mazur `|T| ≤ 16` campaign the composite orders and small primes are excluded by
explicit fixed-curve arithmetic.  The *prime tail* `p ≥ 23` is the genuinely deep part.
Historically it was carried by one opaque axiom (`mazur_prime_torsion_bound`).  This file
replaces that axiom by a two-layer, standard, citable contract:

* `PrimeTail.PrimeTailLevelData p` — *reusable geometric/local-algebra infrastructure* for the
  degree-one (over `ℚ`) formal-immersion argument on `X₀(p)` and its winding quotient `A_p`.
  It is an interface to be discharged once per prime family; it contains **no** deep arithmetic
  input and, crucially, **not** the conclusion `¬ HasRationalPointOfOrder E p`.

* `PrimeTail.PrimeTailPackage p` — the two genuinely deep per-level inputs, and nothing else:
  1. `A_p(ℚ)` is finite (winding-quotient / Kato–Kolyvagin analytic-rank-zero);
  2. `[e] ≠ 0` in `T·e / 3(T·e)` (the mod-`3` winding-element nonvanishing certificate).

The theorem `no_order_p_of_primeTailPackage` derives `¬ HasRationalPointOfOrder E p` for
`19 < p` from these by pure formal-immersion / unique-lift bookkeeping (local linear algebra):
no Mordell–Weil finite generation and no opaque prime-torsion theorem appear.

Design source: campaign corpus `scratch/layer2/Q4499_prime_tail_package.md`.  The public
`HasRationalPointOfOrder` used here is the campaign's affine definition from `TorsionDefs`
(`∃ P : (E⁄ℚ).Point, addOrderOf P = n`), *not* an ad-hoc adapter.
-/

set_option autoImplicit false

namespace MazurProof
namespace PrimeTail

universe u

/-- A small bundled additive commutative group, to avoid dependent instance-plumbing in
`PrimeTailLevelData`. -/
structure AddCommGroupObj where
  carrier : Type u
  str : AddCommGroup carrier

namespace AddCommGroupObj

instance : CoeSort (AddCommGroupObj.{u}) (Type u) where
  coe G := G.carrier

instance (G : AddCommGroupObj.{u}) : AddCommGroup G := G.str

end AddCommGroupObj

/--
Reusable geometry and local algebra for the degree-one prime-tail argument.

This is *not* the deep per-prime assumption package; it is an implementation interface to be
proved once for the family `X₀(p)` and its winding quotient.  Intended meanings:

* `X0Q`, `X0F3` — the `ℚ`- and `𝔽₃`-point types of the proper integral model of `X₀(p)`;
* `AQ`, `AF3` — the `ℚ`- and special-fibre point groups of the winding quotient `A_p`;
* `Te` — the integral Hecke lattice `T · e` dual to the cotangent lattice of `A_p`;
* `tailPoint` — the image on `X₀(p)` of the rational order-`p` subgroup, after applying the
  Atkin–Lehner involution when necessary so that it reduces to `∞` modulo `3`.
-/
class PrimeTailLevelData (p : ℕ) [Fact p.Prime] where
  X0Q : Type u
  X0F3 : Type u
  AQ : AddCommGroupObj.{u}
  AF3 : AddCommGroupObj.{u}
  Te : AddCommGroupObj.{u}
  infinityQ : X0Q
  infinityF3 : X0F3
  redX : X0Q → X0F3
  redA : AQ →+ AF3
  /-- The normalized map `x ↦ π([x] - [∞])` to the winding quotient. -/
  windingMapQ : X0Q → AQ
  windingMapF3 : X0F3 → AF3
  red_infinity : redX infinityQ = infinityF3
  windingMapQ_infinity : windingMapQ infinityQ = 0
  windingMapF3_infinity : windingMapF3 infinityF3 = 0
  windingMap_reduce :
    ∀ x : X0Q, redA (windingMapQ x) = windingMapF3 (redX x)
  /-- The integral winding element `e = {0, ∞}` in the correct Hecke lattice. -/
  windingElement : Te
  /-- Pointwise formal-immersion predicate at `∞` (abstract until a completed-local-ring API
  is available). -/
  formalImmersionAtInfinity : Prop
  /-- The modular-symbol / `q`-expansion criterion: for a one-dimensional source, nonvanishing
  of the winding class implies formal immersion. -/
  formalImmersion_of_windingClass :
    (¬ ∃ t : Te, (3 : ℕ) • t = windingElement) → formalImmersionAtInfinity
  /-- Good reduction at `3`: the reduction kernel on `A_p(ℚ₃)` has no nonzero torsion. -/
  reductionKernel_torsionFree :
    ∀ a : AQ, IsOfFinAddOrder a → redA a = 0 → a = 0
  /-- Generic formal-immersion unique-lift lemma: two `ℤ₃`-sections with the same special point
  and the same image in `A_p` agree, when the map is a formal immersion there. -/
  uniqueLiftAtInfinity :
    formalImmersionAtInfinity →
    ∀ x : X0Q,
      redX x = infinityF3 →
      windingMapQ x = windingMapQ infinityQ →
      x = infinityQ
  /-- Modular interpretation + local orientation: the `X₀(p)` point of the cyclic subgroup
  generated by the rational torsion point (possibly after `w_p`). -/
  tailPoint :
    ∀ (E : WeierstrassCurve ℚ) [E.IsElliptic], HasRationalPointOfOrder E p → X0Q
  /-- The modular point of a genuine elliptic curve is not the cusp `∞`. -/
  tailPoint_ne_infinity :
    ∀ (E : WeierstrassCurve ℚ) [E.IsElliptic] (hP : HasRationalPointOfOrder E p),
      tailPoint E hP ≠ infinityQ
  /-- Uniform local reduction theorem for `p > 19`: one Atkin–Lehner orientation reduces to `∞`
  modulo `3`. -/
  tailPoint_reduces :
    ∀ (E : WeierstrassCurve ℚ) [E.IsElliptic] (hP : HasRationalPointOfOrder E p),
      19 < p → redX (tailPoint E hP) = infinityF3

/--
The membership-free form of `[e] ≠ 0` in `(T·e) / 3(T·e)`: the winding element is not in the
image of multiplication by `3` on the chosen integral Hecke lattice.
-/
def WindingClassNonzeroModThree
    {p : ℕ} [Fact p.Prime] [L : PrimeTailLevelData p] : Prop :=
  ¬ ∃ t : L.Te, (3 : ℕ) • t = L.windingElement

/--
The sharp deep-input bundle for one prime level.  Exactly two fields:

1. finiteness of the rational points of the winding quotient `A_p`;
2. the mod-`3` winding-element nonvanishing certificate.

Everything else lives in the reusable `PrimeTailLevelData` layer.  This class does **not**
contain the conclusion `¬ HasRationalPointOfOrder E p` nor anything equivalent to it.
-/
class PrimeTailPackage (p : ℕ) [Fact p.Prime] [L : PrimeTailLevelData p] : Prop where
  windingQuotientFinite : Finite L.AQ
  windingClassNeZeroModThree : WindingClassNonzeroModThree (p := p)

/-- A finite additive group consists entirely of finite-order elements. -/
private theorem finitePoint_isOfFinAddOrder
    {G : Type u} [AddCommGroup G] [Finite G] (x : G) : IsOfFinAddOrder x :=
  isOfFinAddOrder_of_finite x

/--
Formal-immersion prime tail.  For `19 < p`, the two package fields plus the reusable level
infrastructure exclude a rational point of exact order `p`.  No Mordell–Weil finite-generation
argument and no opaque prime-torsion theorem appear — only composition of the interface.
-/
theorem no_order_p_of_primeTailPackage
    {p : ℕ} [Fact p.Prime] [L : PrimeTailLevelData p]
    (pkg : PrimeTailPackage p) (hp : 19 < p)
    (E : WeierstrassCurve ℚ) [E.IsElliptic] :
    ¬ HasRationalPointOfOrder E p := by
  intro hP
  -- Deep input (a): `A_p(ℚ)` is finite.
  letI : Finite L.AQ := pkg.windingQuotientFinite
  -- Choose the `X₀(p)` orientation that reduces to `∞` at 3.
  let x : L.X0Q := L.tailPoint E hP
  have hxred : L.redX x = L.infinityF3 := by
    simpa [x] using L.tailPoint_reduces E hP hp
  have hxne : x ≠ L.infinityQ := by
    simpa [x] using L.tailPoint_ne_infinity E hP
  -- The normalized winding-map image reduces to zero.
  have hred0 : L.redA (L.windingMapQ x) = 0 := by
    calc
      L.redA (L.windingMapQ x) = L.windingMapF3 (L.redX x) := L.windingMap_reduce x
      _ = L.windingMapF3 L.infinityF3 := by rw [hxred]
      _ = 0 := L.windingMapF3_infinity
  -- Finiteness makes the image torsion; the good-reduction formal kernel is torsion-free.
  have htor : IsOfFinAddOrder (L.windingMapQ x) :=
    finitePoint_isOfFinAddOrder (L.windingMapQ x)
  have hmap0 : L.windingMapQ x = 0 :=
    L.reductionKernel_torsionFree (L.windingMapQ x) htor hred0
  have hsame : L.windingMapQ x = L.windingMapQ L.infinityQ := by
    calc
      L.windingMapQ x = 0 := hmap0
      _ = L.windingMapQ L.infinityQ := L.windingMapQ_infinity.symm
  -- Deep input (b): `[e]` nonzero mod 3 → formal immersion (generic q-expansion criterion).
  have hformal : L.formalImmersionAtInfinity :=
    L.formalImmersion_of_windingClass pkg.windingClassNeZeroModThree
  -- Formal immersion gives uniqueness of the lift of the cusp.
  have hxinf : x = L.infinityQ :=
    L.uniqueLiftAtInfinity hformal x hxred hsame
  exact hxne hxinf

end PrimeTail
end MazurProof
