import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoWOpenEvaluation
import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoClosedPointResidueDegree

/-!
# Residue degree on the canonical binary curve's `W != 0` open

The three ratios by the fourth homogeneous coordinate generate the residue
field of evaluation on the fixed `w = 1` chart.  Because one coordinate of
the canonical first-nonzero representative is one, fixing all these ratios
also fixes the original normalized projective point.  Exact Frobenius period
therefore equals the binary extension degree of the ratio field.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoWOpenResidueDegree

open Function
open CurveZetaFrobeniusOrbitGrading
open FiniteFieldFrobeniusDescent
open NormalizedProjectiveCurveFrobenius
open RationalPointsN25QuotientF2
open RationalPointsN25QuotientBaseChange
open RationalPointsN25QuotientSmoothF2
open RationalPointsN25QuotientWeil
open RationalPointsN25QuotientBinaryFieldSemantics
open RationalPointsN25QuotientTwoAffineCharts
open RationalPointsN25QuotientTwoAffineChartsSmooth
open RationalPointsN25QuotientTwoBaseChange
open RationalPointsN25QuotientTwoClosedPointEvaluation
open RationalPointsN25QuotientTwoConormal
open RationalPointsN25QuotientTwoFrobeniusOrbits
open RationalPointsN25QuotientTwoFullClosedPoints
open RationalPointsN25QuotientTwoWOpenEvaluation

/-- If a coefficient-field endomorphism fixes all three `W`-ratios, it
fixes the underlying canonical normalized projective point. -/
theorem normalizedProjective4_map_eq_of_wOpenCoordinates_fixed
    {K : Type} [Field K] (f : K →+* K)
    (P : CurvePointOnWOpen K)
    (hfix : ∀ j : Fin 4,
      f (coordinates4ToFun (wOpenCoordinates P) j) =
        coordinates4ToFun (wOpenCoordinates P) j) :
    NormalizedProjective4.map f P.point.1 = P.point.1 := by
  rcases P with ⟨⟨P, hcurve⟩, hw⟩
  cases P with
  | xChart y z w =>
      have hi := hfix (0 : Fin 4)
      have hwf : f w = w := by
        apply inv_injective
        simpa [wOpenCoordinates, normalizeAtW, scaleCoordinates4,
          normalizedCoordinates25, NormalizedProjective4.coordinates,
          fieldBinaryOperations, coordinates4ToFun] using hi
      have hy := hfix (1 : Fin 4)
      have hz := hfix (2 : Fin 4)
      simp [wOpenCoordinates, normalizeAtW, scaleCoordinates4,
        normalizedCoordinates25, NormalizedProjective4.coordinates,
        fieldBinaryOperations, coordinates4ToFun, hwf] at hy hz
      have hyf : f y = y := hy.resolve_right hw
      have hzf : f z = z := hz.resolve_right hw
      simp [NormalizedProjective4.map, hyf, hzf, hwf]
  | yChart z w =>
      have hi := hfix (1 : Fin 4)
      have hwf : f w = w := by
        apply inv_injective
        simpa [wOpenCoordinates, normalizeAtW, scaleCoordinates4,
          normalizedCoordinates25, NormalizedProjective4.coordinates,
          fieldBinaryOperations, coordinates4ToFun] using hi
      have hz := hfix (2 : Fin 4)
      simp [wOpenCoordinates, normalizeAtW, scaleCoordinates4,
        normalizedCoordinates25, NormalizedProjective4.coordinates,
        fieldBinaryOperations, coordinates4ToFun, hwf] at hz
      have hzf : f z = z := hz.resolve_right hw
      simp [NormalizedProjective4.map, hzf, hwf]
  | zChart w =>
      have hi := hfix (2 : Fin 4)
      have hwf : f w = w := by
        apply inv_injective
        simpa [wOpenCoordinates, normalizeAtW, scaleCoordinates4,
          normalizedCoordinates25, NormalizedProjective4.coordinates,
          fieldBinaryOperations, coordinates4ToFun] using hi
      simp [NormalizedProjective4.map, hwf]
  | wChart =>
      rfl

/-- The intermediate field generated by evaluation on the fixed `W` chart. -/
def wOpenPointCoordinateField
    (d : ℕ) (P : CurvePointOnWOpen (CommonField 2 d)) :
    IntermediateField (ZMod 2) (CommonField 2 d) := by
  let S := (wOpenChartQuotientEvalAlgHom P).range
  letI : Finite S := Finite.of_injective Subtype.val Subtype.val_injective
  exact S.toIntermediateField' (Finite.isField_of_domain S)

/-- Membership in the ratio coordinate field is membership in the
evaluation range. -/
theorem mem_wOpenPointCoordinateField_iff
    (d : ℕ) (P : CurvePointOnWOpen (CommonField 2 d))
    (x : CommonField 2 d) :
    x ∈ wOpenPointCoordinateField d P ↔
      x ∈ (wOpenChartQuotientEvalAlgHom P).range := by
  rfl

/-- Every `W`-normalized homogeneous coordinate belongs to the evaluation
coordinate field. -/
theorem wOpenCoordinate_mem_coordinateField
    (d : ℕ) (P : CurvePointOnWOpen (CommonField 2 d)) (j : Fin 4) :
    coordinates4ToFun (wOpenCoordinates P) j ∈
      wOpenPointCoordinateField d P := by
  rw [mem_wOpenPointCoordinateField_iff]
  by_cases hj : j = 3
  · subst j
    rw [show coordinates4ToFun (wOpenCoordinates P) 3 = 1 by
      change (wOpenCoordinates P).w = 1
      exact wOpenCoordinates_w P]
    exact (wOpenChartQuotientEvalAlgHom P).range.one_mem
  · let j' : OtherCoordinate (3 : Fin 4) := ⟨j, hj⟩
    refine ⟨Ideal.Quotient.mk (chartAffineEquationIdeal 3)
      (MvPolynomial.X j'), ?_⟩
    change wOpenChartQuotientEval P
        (Ideal.Quotient.mk (chartAffineEquationIdeal 3)
          (MvPolynomial.X j')) =
      coordinates4ToFun (wOpenCoordinates P) j
    rw [wOpenChartQuotientEval_mk]
    simp [wOpenAffineEval, j']

/-- The ratio coordinate field has cardinality two to its binary extension
degree. -/
theorem wOpenPointCoordinateField_card
    (d : ℕ) (P : CurvePointOnWOpen (CommonField 2 d)) :
    Nat.card (wOpenPointCoordinateField d P) =
      2 ^ Module.finrank (ZMod 2) (wOpenPointCoordinateField d P) := by
  simpa using
    (Module.natCard_eq_pow_finrank
      (K := ZMod 2) (V := wOpenPointCoordinateField d P))

/-- Frobenius to the ratio-field degree fixes every element of that field
inside the ambient common field. -/
theorem commonFrobenius_pow_wOpenCoordinateFieldDegree_apply
    (d : ℕ) (P : CurvePointOnWOpen (CommonField 2 d))
    (x : CommonField 2 d) (hx : x ∈ wOpenPointCoordinateField d P) :
    (commonFrobenius 2 d ^
        Module.finrank (ZMod 2) (wOpenPointCoordinateField d P)) x = x := by
  rw [commonFrobenius_pow_apply]
  let y : wOpenPointCoordinateField d P := ⟨x, hx⟩
  letI := Fintype.ofFinite (wOpenPointCoordinateField d P)
  have hy := FiniteField.pow_card y
  rw [← Nat.card_eq_fintype_card,
    wOpenPointCoordinateField_card d P] at hy
  exact congrArg Subtype.val hy

/-- Frobenius to the ratio-field degree fixes the underlying curve point. -/
theorem pointFrobenius_wOpenCoordinateFieldDegree_fixed
    (d : ℕ) (P : CurvePointOnWOpen (CommonField 2 d)) :
    ((pointFrobeniusFun canonicalTwoModel 2 d : _ → _)^[
        Module.finrank (ZMod 2) (wOpenPointCoordinateField d P)]) P.point =
      P.point := by
  apply Subtype.ext
  rw [pointFrobenius_iterate_val]
  apply normalizedProjective4_map_eq_of_wOpenCoordinates_fixed
  intro j
  exact commonFrobenius_pow_wOpenCoordinateFieldDegree_apply d P _
    (wOpenCoordinate_mem_coordinateField d P j)

/-- Exact period divides the binary degree of the `W`-ratio field. -/
theorem exactPeriod_dvd_wOpenCoordinateFieldDegree
    (d : ℕ) (Q : ExactPeriodicPoint (degreePointFrobeniusTwo d) d)
    (hW : (normalizedCoordinates25 Q.1.1).w ≠ 0) :
    d ∣ Module.finrank (ZMod 2)
      (wOpenPointCoordinateField d ⟨Q.1, hW⟩) := by
  let P : CurvePointOnWOpen (CommonField 2 d) := ⟨Q.1, hW⟩
  have hfix := pointFrobenius_wOpenCoordinateFieldDegree_fixed d P
  have hperiodic : IsPeriodicPt (degreePointFrobeniusTwo d)
      (Module.finrank (ZMod 2) (wOpenPointCoordinateField d P)) Q.1 := by
    change ((pointFrobeniusFun canonicalTwoModel 2 d : _ → _)^[
        Module.finrank (ZMod 2) (wOpenPointCoordinateField d P)]) Q.1 = Q.1
    exact hfix
  simpa only [Q.2] using hperiodic.minimalPeriod_dvd

/-- The binary degree of the `W`-ratio field divides the ambient degree. -/
theorem wOpenCoordinateFieldDegree_dvd
    (d : ℕ) (hd : 0 < d)
    (P : CurvePointOnWOpen (CommonField 2 d)) :
    Module.finrank (ZMod 2) (wOpenPointCoordinateField d P) ∣ d := by
  refine ⟨Module.finrank (wOpenPointCoordinateField d P)
    (CommonField 2 d), ?_⟩
  rw [Module.finrank_mul_finrank, GaloisField.finrank 2 hd.ne']

/-- For an exact-period point on the `W` open, the ratio-field degree is
exactly the orbit degree. -/
theorem wOpenCoordinateFieldDegree_eq_exactPeriod
    (d : ℕ) (hd : 0 < d)
    (Q : ExactPeriodicPoint (degreePointFrobeniusTwo d) d)
    (hW : (normalizedCoordinates25 Q.1.1).w ≠ 0) :
    Module.finrank (ZMod 2)
      (wOpenPointCoordinateField d ⟨Q.1, hW⟩) = d := by
  apply Nat.dvd_antisymm
  · exact wOpenCoordinateFieldDegree_dvd d hd ⟨Q.1, hW⟩
  · exact exactPeriod_dvd_wOpenCoordinateFieldDegree d Q hW

/-- The evaluation range and its intermediate-field packaging have the same
underlying elements. -/
def wOpenEvalRangeEquivCoordinateField
    (d : ℕ) (P : CurvePointOnWOpen (CommonField 2 d)) :
    (wOpenChartQuotientEval P).range ≃
      wOpenPointCoordinateField d P where
  toFun x := ⟨x.1, by
    rw [mem_wOpenPointCoordinateField_iff]
    rcases x.2 with ⟨a, ha⟩
    exact ⟨a, ha⟩⟩
  invFun x := ⟨x.1, by
    have hx := x.2
    rw [mem_wOpenPointCoordinateField_iff] at hx
    rcases hx with ⟨a, ha⟩
    exact ⟨a, ha⟩⟩
  left_inv x := Subtype.ext rfl
  right_inv x := Subtype.ext rfl

/-- The fixed-chart evaluation range of an exact-period `W`-open point has
cardinality exactly `2^d`. -/
theorem exactPeriodicWOpen_eval_range_card
    (d : ℕ) (hd : 0 < d)
    (Q : ExactPeriodicPoint (degreePointFrobeniusTwo d) d)
    (hW : (normalizedCoordinates25 Q.1.1).w ≠ 0) :
    Nat.card (wOpenChartQuotientEval
      (⟨Q.1, hW⟩ : CurvePointOnWOpen (CommonField 2 d))).range =
      2 ^ d := by
  calc
    Nat.card (wOpenChartQuotientEval
        (⟨Q.1, hW⟩ : CurvePointOnWOpen (CommonField 2 d))).range =
        Nat.card (wOpenPointCoordinateField d ⟨Q.1, hW⟩) :=
      Nat.card_congr (wOpenEvalRangeEquivCoordinateField d ⟨Q.1, hW⟩)
    _ = 2 ^ d := by
      rw [wOpenPointCoordinateField_card,
        wOpenCoordinateFieldDegree_eq_exactPeriod d hd Q hW]

end MazurProof.RationalPointsN25QuotientTwoWOpenResidueDegree
