import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoAffineChartsSmooth
import Mathlib.AlgebraicGeometry.Morphisms.Smooth

/-!
# Smoothness of the N25 binary projective quotient

The four coordinate basic opens cover the projective quadric--cubic curve.
On each open, the structure morphism is the spectrum map attached to the
degree-zero localization ring, whose smoothness was proved by the structural
Jacobian argument.  Zariski locality on the source then glues the four affine
statements into smoothness of the projective structure morphism.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false
set_option maxSynthPendingDepth 3

noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoSmooth

open AlgebraicGeometry
open CategoryTheory
open RationalPointsN25QuotientTwoConormal
open RationalPointsN25QuotientTwoGradedKoszul
open RationalPointsN25QuotientTwoQuotientGrading
open RationalPointsN25QuotientTwoChartIdeal
open RationalPointsN25QuotientTwoProj
open RationalPointsN25QuotientTwoAffineChartsSmooth
open HomogeneousIdeal

attribute [local instance] MvPolynomial.gradedAlgebra

/-! ## The four coordinate opens cover the quotient -/

set_option maxHeartbeats 800000 in
-- Expanding homogeneous-ideal membership makes elaboration exceed Mathlib's
-- default heartbeat budget, but the proof term remains a short structural map.
/-- Every positive-degree homogeneous class in the quotient lies in the ideal
generated by the four coordinate classes.  The proof lifts the class to a
positive-degree homogeneous polynomial, where every occurring monomial is
divisible by at least one variable, and then maps that ideal membership to the
quotient. -/
theorem canonicalCone_irrelevant_le_coordinate_span :
    (literalConePiece₊).toIdeal ≤
      Ideal.span (Set.range fun i : Fin 4 ↦
        canonicalConeGradedProjection (MvPolynomial.X i)) := by
  rw [HomogeneousIdeal.toIdeal_irrelevant_le]
  intro n hn x hx
  rcases hx with ⟨p, hp, rfl⟩
  have hpVariables : p ∈ Ideal.span (Set.range (MvPolynomial.X : Fin 4 → S)) := by
    rw [show Set.range (MvPolynomial.X : Fin 4 → S) =
        MvPolynomial.X '' (Set.univ : Set (Fin 4)) by
      ext q
      simp]
    apply MvPolynomial.mem_ideal_span_X_image.mpr
    intro m hm
    have hpHomogeneous : p.IsHomogeneous n := by
      simpa [shiftedPiece] using
        (shiftedPiece_isHomogeneous (⟨p, hp⟩ : shiftedPiece 0 n))
    have hmDegree : ∑ i ∈ m.support, m i = n := by
      simpa only [Finsupp.weight_apply, Pi.one_apply, smul_eq_mul, mul_one,
        Finsupp.sum] using
          hpHomogeneous (MvPolynomial.mem_support_iff.mp hm)
    have hmne : m ≠ 0 := by
      intro hzero
      subst m
      simp at hmDegree
      omega
    obtain ⟨i, hi⟩ := Finsupp.ne_iff.mp hmne
    exact ⟨i, Set.mem_univ i, hi⟩
  have hmap :
      (Ideal.span (Set.range (MvPolynomial.X : Fin 4 → S))).map
          canonicalConeGradedProjection ≤
        Ideal.span (Set.range fun i : Fin 4 ↦
          canonicalConeGradedProjection (MvPolynomial.X i)) := by
    rw [Ideal.map_span]
    apply Ideal.span_mono
    rintro y ⟨x, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, rfl⟩
  exact hmap (Ideal.mem_map_of_mem canonicalConeGradedProjection hpVariables)

/-- The four spectra of degree-zero coordinate localizations form the
standard affine cover of the projective quotient. -/
noncomputable def coordinateAffineOpenCover :
    CanonicalProjectiveCurve25Two.AffineOpenCover :=
  Proj.affineOpenCoverOfIrrelevantLESpan literalConePiece
    (fun i : Fin 4 ↦ canonicalConeGradedProjection (MvPolynomial.X i))
    (m := fun _ ↦ 1)
    (fun i ↦ canonicalConeGradedProjection.map_mem (coordinate_isHomogeneous i))
    (fun _ ↦ by norm_num)
    canonicalCone_irrelevant_le_coordinate_span

/-! ## Identification and gluing of the local structure maps -/

/-- On a coordinate chart, the projective structure morphism is the spectrum
map of the natural coefficient homomorphism from `F₂` to the degree-zero
homogeneous localization.  Since a unital ring homomorphism out of `ZMod 2`
is unique, this is exactly the algebra map used in the affine Jacobian proof. -/
theorem coordinateChart_toSpec_smooth (i : Fin 4) :
    Smooth ((coordinateAffineOpenCover.f i) ≫ canonicalProjectiveCurveToSpec) := by
  change Smooth
    (Proj.awayι literalConePiece
        (canonicalConeGradedProjection (MvPolynomial.X i))
        (canonicalConeGradedProjection.map_mem (coordinate_isHomogeneous i))
        (by norm_num) ≫ canonicalProjectiveCurveToSpec)
  rw [canonicalProjectiveCurveToSpec, Proj.awayι_toSpecZero_assoc,
    ← Spec.map_comp]
  rw [HasRingHomProperty.Spec_iff (P := @Smooth)]
  have hCoefficientMap :
      (CommRingCat.ofHom literalConePieceZeroRingEquiv.toRingHom ≫
        CommRingCat.ofHom
          (HomogeneousLocalization.fromZeroRingHom literalConePiece
            (Submonoid.powers
              (canonicalConeGradedProjection (MvPolynomial.X i))))).hom =
        algebraMap k (ChartCoordinateRing i) :=
    @RingHom.ext_zmod 2 (ChartCoordinateRing i) _ _ _
  rw [hCoefficientMap]
  exact chartCoordinateRing_smooth i

/-- The projective quadric--cubic quotient is smooth over the binary base
field.  This is the Zariski gluing of the four structurally proved affine
chart statements. -/
instance canonicalProjectiveCurveToSpec_smooth :
    Smooth canonicalProjectiveCurveToSpec := by
  apply IsZariskiLocalAtSource.of_openCover coordinateAffineOpenCover.openCover
  intro i
  exact coordinateChart_toSpec_smooth i

end MazurProof.RationalPointsN25QuotientTwoSmooth
