import FLT.Assumptions.MazurProof.RationalPointsN25QuotientSmoothF2
import Mathlib.RingTheory.Kaehler.Polynomial
import Mathlib.RingTheory.MvPolynomial.Homogeneous

/-!
# Conormal sequence for the binary canonical complete intersection

This file realizes the characteristic-two canonical model as the quotient of
the four-variable homogeneous coordinate ring by its quadric and cubic.  It
then specializes Mathlib's conormal exact sequence to that quotient and
computes the two equation differentials in the standard polynomial basis.

These are the affine-cone algebraic inputs to adjunction.  No claim about
Proj, twisting sheaves, determinants, or the dualizing sheaf is made here.
-/

noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoConormal

open MazurProof.RationalPointsN25QuotientF2
open MazurProof.RationalPointsN25QuotientSmoothF2
open Module
open scoped TensorProduct

/-! ## The homogeneous coordinate quotient -/

/-- The homogeneous coordinate ring `F₂[x,y,z,w]`. -/
abbrev BinaryHomogeneousRing := MvPolynomial (Fin 4) (ZMod 2)

/-- The characteristic-two canonical quadric as a homogeneous polynomial. -/
def canonicalQuadricPolynomial25Two : BinaryHomogeneousRing :=
  MvPolynomial.X 0 * MvPolynomial.X 2 +
    MvPolynomial.X 0 * MvPolynomial.X 3 +
    MvPolynomial.X 1 ^ 2 +
    MvPolynomial.X 1 * MvPolynomial.X 2 +
    MvPolynomial.X 2 * MvPolynomial.X 3

/-- The characteristic-two canonical cubic as a homogeneous polynomial. -/
def canonicalCubicPolynomial25Two : BinaryHomogeneousRing :=
  MvPolynomial.X 0 ^ 2 * MvPolynomial.X 3 +
    MvPolynomial.X 0 * MvPolynomial.X 1 * MvPolynomial.X 2 +
    MvPolynomial.X 0 * MvPolynomial.X 1 * MvPolynomial.X 3 +
    MvPolynomial.X 0 * MvPolynomial.X 2 * MvPolynomial.X 3 +
    MvPolynomial.X 1 * MvPolynomial.X 2 * MvPolynomial.X 3 +
    MvPolynomial.X 2 ^ 2 * MvPolynomial.X 3 +
    MvPolynomial.X 2 * MvPolynomial.X 3 ^ 2

/-- The first defining equation is genuinely homogeneous of degree two. -/
theorem canonicalQuadricPolynomial25Two_isHomogeneous :
    canonicalQuadricPolynomial25Two.IsHomogeneous 2 := by
  have hMul (i j : Fin 4) :
      (MvPolynomial.X i * MvPolynomial.X j :
        BinaryHomogeneousRing).IsHomogeneous 2 := by
    simpa using
      (MvPolynomial.isHomogeneous_X (ZMod 2) i).mul
        (MvPolynomial.isHomogeneous_X (ZMod 2) j)
  have hSq (i : Fin 4) :
      (MvPolynomial.X i ^ 2 : BinaryHomogeneousRing).IsHomogeneous 2 :=
    MvPolynomial.isHomogeneous_X_pow i 2
  simpa only [canonicalQuadricPolynomial25Two] using
    ((((hMul 0 2).add (hMul 0 3)).add (hSq 1)).add
      (hMul 1 2)).add (hMul 2 3)

/-- The second defining equation is genuinely homogeneous of degree three. -/
theorem canonicalCubicPolynomial25Two_isHomogeneous :
    canonicalCubicPolynomial25Two.IsHomogeneous 3 := by
  have hTriple (i j k : Fin 4) :
      (MvPolynomial.X i * MvPolynomial.X j * MvPolynomial.X k :
        BinaryHomogeneousRing).IsHomogeneous 3 := by
    simpa [Nat.add_assoc] using
      ((MvPolynomial.isHomogeneous_X (ZMod 2) i).mul
        (MvPolynomial.isHomogeneous_X (ZMod 2) j)).mul
          (MvPolynomial.isHomogeneous_X (ZMod 2) k)
  have hSqMul (i j : Fin 4) :
      (MvPolynomial.X i ^ 2 * MvPolynomial.X j :
        BinaryHomogeneousRing).IsHomogeneous 3 := by
    simpa using
      (MvPolynomial.isHomogeneous_X_pow i 2).mul
        (MvPolynomial.isHomogeneous_X (ZMod 2) j)
  simpa only [canonicalCubicPolynomial25Two] using
    ((((((hSqMul 0 3).add (hTriple 0 1 2)).add
      (hTriple 0 1 3)).add (hTriple 0 2 3)).add
        (hTriple 1 2 3)).add (hSqMul 2 3)).add (by
          simpa [mul_comm] using hSqMul 3 2)

/-- The homogeneous ideal generated by the canonical quadric and cubic. -/
def canonicalCurveIdeal25Two : Ideal BinaryHomogeneousRing :=
  Ideal.span {canonicalQuadricPolynomial25Two, canonicalCubicPolynomial25Two}

/-- The affine-cone homogeneous coordinate quotient of the canonical model. -/
abbrev CanonicalConeRing25Two :=
  BinaryHomogeneousRing ⧸ canonicalCurveIdeal25Two

/-- The quotient map from the homogeneous coordinate ring is surjective. -/
theorem canonicalCone_algebraMap_surjective :
    Function.Surjective
      (algebraMap BinaryHomogeneousRing CanonicalConeRing25Two) := by
  exact Ideal.Quotient.mk_surjective

/-- The kernel of the quotient map is exactly the quadric-cubic ideal. -/
theorem canonicalCone_algebraMap_ker :
    RingHom.ker (algebraMap BinaryHomogeneousRing CanonicalConeRing25Two) =
      canonicalCurveIdeal25Two := by
  change RingHom.ker (Ideal.Quotient.mk canonicalCurveIdeal25Two) =
    canonicalCurveIdeal25Two
  exact Ideal.mk_ker

/-! ## Compatibility with the coordinate formulas -/

/-- Evaluating the homogeneous quadric polynomial recovers the coordinate
formula used by the geometric smoothness certificates. -/
theorem eval_canonicalQuadricPolynomial25Two
    {K : Type*} [CommRing K] [Algebra (ZMod 2) K]
    (P : Coordinates4 K) :
    MvPolynomial.aeval ![P.x, P.y, P.z, P.w]
        canonicalQuadricPolynomial25Two =
      canonicalQuadric25CharTwo P := by
  simp [canonicalQuadricPolynomial25Two, canonicalQuadric25CharTwo]

/-- Evaluating the homogeneous cubic polynomial recovers the coordinate
formula used by the geometric smoothness certificates. -/
theorem eval_canonicalCubicPolynomial25Two
    {K : Type*} [CommRing K] [Algebra (ZMod 2) K]
    (P : Coordinates4 K) :
    MvPolynomial.aeval ![P.x, P.y, P.z, P.w]
        canonicalCubicPolynomial25Two =
      canonicalCubic25CharTwo P := by
  simp [canonicalCubicPolynomial25Two, canonicalCubic25CharTwo]

/-! ## The two Jacobian rows as universal differentials -/

/-- The standard basis `dx,dy,dz,dw` of differentials of the ambient
four-variable polynomial algebra. -/
def ambientDifferentialBasis25Two :
    Basis (Fin 4) BinaryHomogeneousRing
      Ω[BinaryHomogeneousRing⁄ZMod 2] :=
  KaehlerDifferential.mvPolynomialBasis (ZMod 2) (Fin 4)

/-- The quadric differential has the gradient coordinates
`(z+w,z,x+y+w,x+z)` in characteristic two. -/
theorem quadricDifferential_coordinates :
    ((ambientDifferentialBasis25Two.repr
      (KaehlerDifferential.D (ZMod 2) BinaryHomogeneousRing
        canonicalQuadricPolynomial25Two) : Fin 4 →₀ BinaryHomogeneousRing) :
        Fin 4 → BinaryHomogeneousRing) =
      ![MvPolynomial.X 2 + MvPolynomial.X 3,
        MvPolynomial.X 2,
        MvPolynomial.X 0 + MvPolynomial.X 1 + MvPolynomial.X 3,
        MvPolynomial.X 0 + MvPolynomial.X 2] := by
  have htwo : (2 : BinaryHomogeneousRing) = 0 :=
    CharP.cast_eq_zero BinaryHomogeneousRing 2
  funext i
  change (KaehlerDifferential.mvPolynomialBasis
    (ZMod 2) (Fin 4)).repr
      (KaehlerDifferential.D (ZMod 2) BinaryHomogeneousRing
        canonicalQuadricPolynomial25Two) i = _
  rw [KaehlerDifferential.mvPolynomialBasis_repr_apply]
  fin_cases i <;> simp [canonicalQuadricPolynomial25Two, htwo]

/-- The cubic differential has the second Jacobian row used in the smoothness
certificates. -/
theorem cubicDifferential_coordinates :
    ((ambientDifferentialBasis25Two.repr
      (KaehlerDifferential.D (ZMod 2) BinaryHomogeneousRing
        canonicalCubicPolynomial25Two) : Fin 4 →₀ BinaryHomogeneousRing) :
        Fin 4 → BinaryHomogeneousRing) =
      ![MvPolynomial.X 1 * MvPolynomial.X 2 +
          MvPolynomial.X 1 * MvPolynomial.X 3 +
          MvPolynomial.X 2 * MvPolynomial.X 3,
        MvPolynomial.X 0 * MvPolynomial.X 2 +
          MvPolynomial.X 0 * MvPolynomial.X 3 +
          MvPolynomial.X 2 * MvPolynomial.X 3,
        MvPolynomial.X 0 * MvPolynomial.X 1 +
          MvPolynomial.X 0 * MvPolynomial.X 3 +
          MvPolynomial.X 1 * MvPolynomial.X 3 +
          MvPolynomial.X 3 ^ 2,
        MvPolynomial.X 0 ^ 2 +
          MvPolynomial.X 0 * MvPolynomial.X 1 +
          MvPolynomial.X 0 * MvPolynomial.X 2 +
          MvPolynomial.X 1 * MvPolynomial.X 2 +
          MvPolynomial.X 2 ^ 2] := by
  have htwo : (2 : BinaryHomogeneousRing) = 0 :=
    CharP.cast_eq_zero BinaryHomogeneousRing 2
  funext i
  change (KaehlerDifferential.mvPolynomialBasis
    (ZMod 2) (Fin 4)).repr
      (KaehlerDifferential.D (ZMod 2) BinaryHomogeneousRing
        canonicalCubicPolynomial25Two) i = _
  rw [KaehlerDifferential.mvPolynomialBasis_repr_apply]
  fin_cases i <;> simp [canonicalCubicPolynomial25Two, htwo] <;> ring

/-- View a four-coordinate structure as a function on the four polynomial
variables, in the order `x,y,z,w`. -/
def coordinates4ToFun {K : Type*} (P : Coordinates4 K) : Fin 4 → K :=
  ![P.x, P.y, P.z, P.w]

/-- After evaluation at a point, the coordinate vector of the universal
quadric differential is exactly the geometric quadric gradient. -/
theorem eval_quadricDifferential_coordinate
    {K : Type*} [CommRing K] [Algebra (ZMod 2) K]
    (P : Coordinates4 K) (i : Fin 4) :
    MvPolynomial.aeval ![P.x, P.y, P.z, P.w]
        ((ambientDifferentialBasis25Two.repr
          (KaehlerDifferential.D (ZMod 2) BinaryHomogeneousRing
            canonicalQuadricPolynomial25Two)) i) =
      coordinates4ToFun (canonicalQuadricGradient25CharTwo P) i := by
  have h := congrFun quadricDifferential_coordinates i
  rw [h]
  fin_cases i <;>
    simp [coordinates4ToFun, canonicalQuadricGradient25CharTwo]

/-- After evaluation at a point, the coordinate vector of the universal
cubic differential is exactly the geometric cubic gradient. -/
theorem eval_cubicDifferential_coordinate
    {K : Type*} [CommRing K] [Algebra (ZMod 2) K]
    (P : Coordinates4 K) (i : Fin 4) :
    MvPolynomial.aeval ![P.x, P.y, P.z, P.w]
        ((ambientDifferentialBasis25Two.repr
          (KaehlerDifferential.D (ZMod 2) BinaryHomogeneousRing
            canonicalCubicPolynomial25Two)) i) =
      coordinates4ToFun (canonicalCubicGradient25CharTwo P) i := by
  have h := congrFun cubicDifferential_coordinates i
  rw [h]
  fin_cases i <;>
    simp [coordinates4ToFun, canonicalCubicGradient25CharTwo]

/-! ## The concrete conormal exact sequence -/

/-- For the explicit quadric-cubic quotient, the image of `I/I²` in the
base-changed ambient differentials is exactly the kernel of the map to the
differentials of the quotient ring. -/
theorem canonicalCone_conormal_exact :
    Function.Exact
      (KaehlerDifferential.kerCotangentToTensor
        (ZMod 2) BinaryHomogeneousRing CanonicalConeRing25Two)
      (KaehlerDifferential.mapBaseChange
        (ZMod 2) BinaryHomogeneousRing CanonicalConeRing25Two) := by
  exact KaehlerDifferential.exact_kerCotangentToTensor_mapBaseChange
    (ZMod 2) BinaryHomogeneousRing CanonicalConeRing25Two
      canonicalCone_algebraMap_surjective

/-- The ambient differential map in the conormal sequence surjects onto the
Kähler differentials of the canonical cone quotient. -/
theorem canonicalCone_mapBaseChange_surjective :
    Function.Surjective
      (KaehlerDifferential.mapBaseChange
        (ZMod 2) BinaryHomogeneousRing CanonicalConeRing25Two) := by
  exact KaehlerDifferential.mapBaseChange_surjective
    (ZMod 2) BinaryHomogeneousRing CanonicalConeRing25Two
      canonicalCone_algebraMap_surjective

end MazurProof.RationalPointsN25QuotientTwoConormal
