import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoChartIdeal
import Mathlib.AlgebraicGeometry.IdealSheaf.Basic

/-!
# The ideal sheaf of the N25 projective closed immersion

The closed immersion from the canonical quadric-cubic quotient into binary
projective three-space already has a global kernel ideal sheaf in Mathlib.
This module identifies its restriction on every standard coordinate chart.
After transporting sections along the canonical `Away`-to-sections
isomorphism, that restriction is exactly the ideal generated by the
dehomogenized quadric and cubic.
-/

noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoIdealSheaf

open RationalPointsN25QuotientTwoConormal
open RationalPointsN25QuotientTwoGradedKoszul
open RationalPointsN25QuotientTwoQuotientGrading
open RationalPointsN25QuotientTwoProj
open RationalPointsN25QuotientTwoChartIdeal
open HomogeneousLocalization
open AlgebraicGeometry
open CategoryTheory
open Graded

attribute [local instance] MvPolynomial.gradedAlgebra

/-- Transporting the kernel of the section map on a standard affine open back
along the canonical `Away`-to-sections isomorphism recovers the explicit chart
equation ideal.  Functoriality of `Proj` identifies the composite section map
with homogeneous localization of the original graded quotient. -/
theorem chartEquationIdeal_eq_comap_appLE_kernel (i : Fin 4) :
    Ideal.comap
        (Proj.awayToSection standardConePiece (MvPolynomial.X i)).hom
        (RingHom.ker
          (Scheme.Hom.appLE canonicalProjectiveCurveMap
            (Proj.basicOpen standardConePiece (MvPolynomial.X i))
            (Proj.basicOpen literalConePiece
              (canonicalConeGradedProjection (MvPolynomial.X i)))
            (by rfl)).hom) =
      chartEquationIdeal i := by
  rw [RingHom.comap_ker, ← CommRingCat.hom_comp]
  have hsection :
      Proj.awayToSection standardConePiece (MvPolynomial.X i) ≫
          Scheme.Hom.appLE canonicalProjectiveCurveMap
            (Proj.basicOpen standardConePiece (MvPolynomial.X i))
            (Proj.basicOpen literalConePiece
              (canonicalConeGradedProjection (MvPolynomial.X i))) (by rfl) =
        CommRingCat.ofHom (canonicalConeChartMap i) ≫
          Proj.awayToSection literalConePiece
            (canonicalConeGradedProjection (MvPolynomial.X i)) := by
    simpa only [standardConePiece, canonicalProjectiveCurveMap,
      canonicalConeChartMap] using
        (Proj.awayToSection_comp_appLE canonicalConeGradedProjection
          canonicalCone_irrelevant_le_map (coordinate_isHomogeneous i))
  rw [hsection, CommRingCat.hom_comp]
  have htargetInjective : Function.Injective
      (Proj.awayToSection literalConePiece
        (canonicalConeGradedProjection (MvPolynomial.X i))).hom := by
    rw [← Proj.basicOpenIsoAway_hom literalConePiece
      (canonicalConeGradedProjection (MvPolynomial.X i))
      (map_mem canonicalConeGradedProjection (coordinate_isHomogeneous i))
      (by norm_num)]
    exact (ConcreteCategory.bijective_of_isIso
      (Proj.basicOpenIsoAway literalConePiece
        (canonicalConeGradedProjection (MvPolynomial.X i))
        (map_mem canonicalConeGradedProjection (coordinate_isHomogeneous i))
        (by norm_num)).hom).1
  rw [RingHom.ker_comp_of_injective _ htargetInjective]
  exact (chartKernel_eq_equationIdeal i).trans rfl

/-- The ambient coordinate basic open, bundled with its affine-open proof. -/
def ambientCoordinateAffineOpen (i : Fin 4) :
    BinaryProjectiveThreeSpace.affineOpens :=
  ⟨Proj.basicOpen standardConePiece (MvPolynomial.X i),
    Proj.isAffineOpen_basicOpen (𝒜 := standardConePiece)
      (f := MvPolynomial.X i)
      (coordinate_isHomogeneous i) (by norm_num)⟩

/-- The global kernel ideal sheaf of the closed immersion restricts on each
standard affine chart to the explicit dehomogenized equation ideal. -/
theorem canonicalProjectiveCurveMap_ker_coordinateChart (i : Fin 4) :
    Ideal.comap
        (Proj.awayToSection standardConePiece (MvPolynomial.X i)).hom
        (canonicalProjectiveCurveMap.ker.ideal
          (ambientCoordinateAffineOpen i)) =
      chartEquationIdeal i := by
  rw [Scheme.Hom.ker_apply]
  change Ideal.comap
      (Proj.awayToSection standardConePiece (MvPolynomial.X i)).hom
      (RingHom.ker
        (canonicalProjectiveCurveMap.app
          (Proj.basicOpen standardConePiece (MvPolynomial.X i))).hom) = _
  rw [canonicalProjectiveCurveMap.app_eq_appLE]
  exact chartEquationIdeal_eq_comap_appLE_kernel i

end MazurProof.RationalPointsN25QuotientTwoIdealSheaf
