import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoAffineChartsSmooth
import FLT.Mathlib.LinearAlgebra.UnimodularCrossProduct

/-!
# Canonical differentials on the affine charts of the N25 curve

On each standard affine chart the canonical curve is cut out by two
equations in affine three-space.  Their two gradient rows have a unimodular
cross product because the three selected Jacobian minors generate the unit
ideal.  This file turns that certificate into a canonical free generator of
the relative Kahler differentials of the chart quotient.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoAffineCanonicalDifferentials

open Matrix
open RationalPointsN25QuotientTwoAffineCharts
open RationalPointsN25QuotientTwoAffineChartsSmooth
open RationalPointsN25QuotientTwoGradedKoszul
open RationalPointsN25QuotientTwoStructuralJacobian

/-- The two rows of the affine Jacobian matrix, expressed in the canonical
ordering of the three non-pivot coordinates. -/
def chartJacobianRow (pivot : Fin 4) (r : Fin 2) :
    Fin 3 → ChartQuotient pivot :=
  fun i ↦
    algebraMap (AffineChart pivot) (ChartQuotient pivot)
      (MvPolynomial.pderiv (affineCoordinate pivot i)
        (chartAffineRelation pivot r))

/-- The cross product of the two affine Jacobian rows. -/
def chartJacobianCross (pivot : Fin 4) :
    Fin 3 → ChartQuotient pivot :=
  chartJacobianRow pivot 0 ⨯₃ chartJacobianRow pivot 1

/-- The first cross-product component is the Jacobian obtained by omitting
the first affine coordinate. -/
theorem chartJacobianCross_zero (pivot : Fin 4) :
    chartJacobianCross pivot 0 = (chartPreSubmersive pivot 0).jacobian := by
  change
    chartJacobianRow pivot 0 1 * chartJacobianRow pivot 1 2 -
      chartJacobianRow pivot 0 2 * chartJacobianRow pivot 1 1 = _
  rw [Algebra.PreSubmersivePresentation.jacobian_eq_jacobiMatrix_det,
    Matrix.det_fin_two, chartPreSubmersive_algebraMap]
  simp only [chartJacobianRow,
    chartPreSubmersive_jacobiMatrix, selectedChartVariable, affineCoordinate,
    map_mul, map_sub]
  norm_num [Fin.succAbove]
  ring

/-- The middle cross-product component is the negative of the Jacobian
obtained by omitting the middle affine coordinate. -/
theorem chartJacobianCross_one (pivot : Fin 4) :
    chartJacobianCross pivot 1 = -(chartPreSubmersive pivot 1).jacobian := by
  change
    chartJacobianRow pivot 0 2 * chartJacobianRow pivot 1 0 -
      chartJacobianRow pivot 0 0 * chartJacobianRow pivot 1 2 = -_
  rw [Algebra.PreSubmersivePresentation.jacobian_eq_jacobiMatrix_det,
    Matrix.det_fin_two, chartPreSubmersive_algebraMap]
  simp only [chartJacobianRow,
    chartPreSubmersive_jacobiMatrix, selectedChartVariable, affineCoordinate,
    map_mul, map_sub]
  norm_num [Fin.succAbove]
  ring

/-- The final cross-product component is the Jacobian obtained by omitting
the final affine coordinate. -/
theorem chartJacobianCross_two (pivot : Fin 4) :
    chartJacobianCross pivot 2 = (chartPreSubmersive pivot 2).jacobian := by
  change
    chartJacobianRow pivot 0 0 * chartJacobianRow pivot 1 1 -
      chartJacobianRow pivot 0 1 * chartJacobianRow pivot 1 0 = _
  rw [Algebra.PreSubmersivePresentation.jacobian_eq_jacobiMatrix_det,
    Matrix.det_fin_two, chartPreSubmersive_algebraMap]
  simp only [chartJacobianRow,
    chartPreSubmersive_jacobiMatrix, selectedChartVariable, affineCoordinate,
    map_mul, map_sub,
    show (2 : Fin 3).succAbove (0 : Fin 2) = 0 by decide,
    show (2 : Fin 3).succAbove (1 : Fin 2) = 1 by decide]
  norm_num [Fin.succAbove]
  ring

/-- Changing the sign of the middle selected minor does not change the ideal
generated by the three Jacobian components. -/
theorem chartJacobianCross_span (pivot : Fin 4) :
    Ideal.span (Set.range (chartJacobianCross pivot)) = ⊤ := by
  rw [← chartPreSubmersive_jacobian_span pivot]
  apply le_antisymm
  · apply Ideal.span_le.mpr
    rintro x ⟨i, rfl⟩
    fin_cases i
    · change chartJacobianCross pivot 0 ∈ _
      rw [chartJacobianCross_zero]
      exact Ideal.subset_span ⟨(0 : Fin 3), rfl⟩
    · change chartJacobianCross pivot 1 ∈ _
      rw [chartJacobianCross_one]
      exact
        (Ideal.span (Set.range fun omitted ↦
          (chartPreSubmersive pivot omitted).jacobian)).neg_mem
            (Ideal.subset_span ⟨(1 : Fin 3), rfl⟩)
    · change chartJacobianCross pivot 2 ∈ _
      rw [chartJacobianCross_two]
      exact Ideal.subset_span ⟨(2 : Fin 3), rfl⟩
  · apply Ideal.span_le.mpr
    rintro x ⟨i, rfl⟩
    fin_cases i
    · change (chartPreSubmersive pivot 0).jacobian ∈ _
      rw [← chartJacobianCross_zero pivot]
      exact Ideal.subset_span ⟨(0 : Fin 3), rfl⟩
    · change (chartPreSubmersive pivot 1).jacobian ∈ _
      rw [show (chartPreSubmersive pivot 1).jacobian =
          -chartJacobianCross pivot 1 by
        rw [chartJacobianCross_one]
        simp]
      exact
        (Ideal.span (Set.range (chartJacobianCross pivot))).neg_mem
          (Ideal.subset_span ⟨(1 : Fin 3), rfl⟩)
    · change (chartPreSubmersive pivot 2).jacobian ∈ _
      rw [← chartJacobianCross_two pivot]
      exact Ideal.subset_span ⟨(2 : Fin 3), rfl⟩

/-- The unit-ideal certificate supplies coefficients for the three
components of the Jacobian cross product. -/
theorem exists_chartJacobianBezoutVector (pivot : Fin 4) :
    ∃ c : Fin 3 → ChartQuotient pivot,
      ∑ i, c i * chartJacobianCross pivot i = 1 := by
  apply Ideal.mem_span_range_iff_exists_fun.mp
  rw [chartJacobianCross_span pivot]
  trivial

/-- Coefficients of a Bezout identity for the three Jacobian minors. -/
def chartJacobianBezoutVector (pivot : Fin 4) :
    Fin 3 → ChartQuotient pivot :=
  Classical.choose (exists_chartJacobianBezoutVector pivot)

/-- The chosen Bezout vector pairs to one with the Jacobian cross product. -/
theorem chartJacobianBezoutVector_dot (pivot : Fin 4) :
    chartJacobianBezoutVector pivot ⬝ᵥ chartJacobianCross pivot = 1 := by
  simpa only [dotProduct, chartJacobianBezoutVector] using
    (Classical.choose_spec (exists_chartJacobianBezoutVector pivot))

/-! ## The unimodular Jacobian functional -/

/-- Dot product with the Jacobian cross product.  This is the residue
functional that will descend from ambient differentials to the quotient
curve. -/
def chartJacobianFunctional (pivot : Fin 4) :
    (Fin 3 → ChartQuotient pivot) →ₗ[ChartQuotient pivot]
      ChartQuotient pivot :=
  LinearMap.crossProductFunctional
    (chartJacobianRow pivot 0) (chartJacobianRow pivot 1)

/-- The Jacobian residue functional is onto because its coefficient vector
is unimodular. -/
theorem chartJacobianFunctional_surjective (pivot : Fin 4) :
    Function.Surjective (chartJacobianFunctional pivot) := by
  exact LinearMap.crossProductFunctional_surjective
    (chartJacobianBezoutVector_dot pivot)

/-- The kernel of the Jacobian residue functional is precisely the span of
the two relation gradients. -/
theorem chartJacobianFunctional_ker (pivot : Fin 4) :
    LinearMap.ker (chartJacobianFunctional pivot) =
      Submodule.span (ChartQuotient pivot)
        (Set.range ![chartJacobianRow pivot 0, chartJacobianRow pivot 1]) := by
  exact LinearMap.ker_crossProductFunctional
    (chartJacobianBezoutVector_dot pivot)

/-! ## Coordinates on the ambient cotangent space -/

/-- The base-changed ambient cotangent space of the naive affine
presentation. -/
abbrev ChartCotangentSpace (pivot : Fin 4) :=
  (chartPreSubmersive pivot 0).toExtension.CotangentSpace

/-- The polynomial differential basis, reindexed by the canonical order of
the three non-pivot coordinates. -/
def chartCotangentSpaceBasis (pivot : Fin 4) :
    Module.Basis (Fin 3) (ChartQuotient pivot)
      (ChartCotangentSpace pivot) :=
  (chartPreSubmersive pivot 0).cotangentSpaceBasis.reindex
    (finSuccAboveEquiv pivot).symm

/-- Coordinate equivalence from ambient differentials to three-component
vectors over the chart quotient. -/
def chartCotangentCoordinates (pivot : Fin 4) :
    ChartCotangentSpace pivot ≃ₗ[ChartQuotient pivot]
      (Fin 3 → ChartQuotient pivot) :=
  (chartCotangentSpaceBasis pivot).repr.trans
    (Finsupp.linearEquivFunOnFinite
      (ChartQuotient pivot) (ChartQuotient pivot) (Fin 3))

/-- The two distinguished classes in the conormal module represented by the
two defining equations. -/
abbrev chartRelationCotangent (pivot : Fin 4) (r : Fin 2) :
    (chartPreSubmersive pivot 0).toExtension.Cotangent :=
  Algebra.Extension.Cotangent.mk
    ⟨(chartPreSubmersive pivot 0).relation r,
      (chartPreSubmersive pivot 0).relation_mem_ker r⟩

/-- Under ambient differential coordinates, the cotangent-complex image of
a defining equation is its corresponding Jacobian row. -/
theorem chartCotangentCoordinates_cotangentComplex_relation
    (pivot : Fin 4) (r : Fin 2) :
    chartCotangentCoordinates pivot
        ((chartPreSubmersive pivot 0).toExtension.cotangentComplex
          (chartRelationCotangent pivot r)) =
      chartJacobianRow pivot r := by
  funext i
  change
    (chartPreSubmersive pivot 0).cotangentSpaceBasis.repr
        ((chartPreSubmersive pivot 0).toExtension.cotangentComplex
          (chartRelationCotangent pivot r)) (affineCoordinate pivot i) = _
  rw [chartRelationCotangent, Algebra.Extension.cotangentComplex_mk]
  rw [Algebra.Generators.cotangentSpaceBasis_repr_one_tmul]
  change
    MvPolynomial.aeval (chartPreSubmersive pivot 0).val
        (MvPolynomial.pderiv (affineCoordinate pivot i)
          (chartAffineRelation pivot r)) =
      algebraMap (AffineChart pivot) (ChartQuotient pivot)
        (MvPolynomial.pderiv (affineCoordinate pivot i)
          (chartAffineRelation pivot r))
  rw [← Algebra.Generators.algebraMap_apply,
    chartPreSubmersive_algebraMap]
  rw [Ideal.Quotient.algebraMap_eq]

/-- The two defining relations span the conormal module of the naive
presentation. -/
theorem chartRelationCotangent_span (pivot : Fin 4) :
    Submodule.span (ChartQuotient pivot)
        (Set.range (chartRelationCotangent pivot)) = ⊤ := by
  simpa only using
    (Algebra.Extension.Cotangent.span_eq_top_of_span_eq_ker
      (P := (chartPreSubmersive pivot 0).toExtension)
      (fun r ↦ (chartPreSubmersive pivot 0).relation r)
      (chartPreSubmersive pivot 0).span_range_relation_eq_ker)

/-- Consequently, the range of the cotangent-complex differential is
spanned by the two displayed relation differentials. -/
theorem chartCotangentComplex_range (pivot : Fin 4) :
    LinearMap.range
        (chartPreSubmersive pivot 0).toExtension.cotangentComplex =
      Submodule.span (ChartQuotient pivot)
        (Set.range fun r ↦
          (chartPreSubmersive pivot 0).toExtension.cotangentComplex
            (chartRelationCotangent pivot r)) := by
  rw [← Submodule.map_top]
  nth_rw 1 [← chartRelationCotangent_span pivot]
  rw [Submodule.map_span, ← Set.range_comp]
  rfl

/-- Ambient cotangent coordinates carry the cotangent-complex range to the
span of the two Jacobian rows. -/
theorem chartCotangentCoordinates_map_cotangentComplex_range
    (pivot : Fin 4) :
    Submodule.map (chartCotangentCoordinates pivot).toLinearMap
        (LinearMap.range
          (chartPreSubmersive pivot 0).toExtension.cotangentComplex) =
      Submodule.span (ChartQuotient pivot)
        (Set.range ![chartJacobianRow pivot 0, chartJacobianRow pivot 1]) := by
  rw [chartCotangentComplex_range]
  rw [Submodule.map_span, ← Set.range_comp]
  have hfun :
      ((chartCotangentCoordinates pivot).toLinearMap ∘
          fun r ↦ (chartPreSubmersive pivot 0).toExtension.cotangentComplex
            (chartRelationCotangent pivot r)) =
        ![chartJacobianRow pivot 0, chartJacobianRow pivot 1] := by
    funext r
    simp only [Function.comp_apply, LinearEquiv.coe_coe]
    rw [chartCotangentCoordinates_cotangentComplex_relation]
    fin_cases r <;> rfl
  rw [hfun]

/-- Pull the Jacobian residue functional back to the base-changed ambient
cotangent space. -/
def chartCotangentResidueFunctional (pivot : Fin 4) :
    ChartCotangentSpace pivot →ₗ[ChartQuotient pivot]
      ChartQuotient pivot :=
  (chartJacobianFunctional pivot).comp
    (chartCotangentCoordinates pivot).toLinearMap

/-- The pulled-back residue functional remains surjective. -/
theorem chartCotangentResidueFunctional_surjective (pivot : Fin 4) :
    Function.Surjective (chartCotangentResidueFunctional pivot) :=
  (chartJacobianFunctional_surjective pivot).comp
    (chartCotangentCoordinates pivot).surjective

/-- The residue functional and the projection to relative Kahler
differentials have the same kernel. -/
theorem chartCotangentResidueFunctional_ker (pivot : Fin 4) :
    LinearMap.ker (chartCotangentResidueFunctional pivot) =
      LinearMap.ker
        (chartPreSubmersive pivot 0).toExtension.toKaehler := by
  rw [chartCotangentResidueFunctional, LinearMap.ker_comp]
  rw [chartJacobianFunctional_ker]
  rw [← chartCotangentCoordinates_map_cotangentComplex_range]
  rw [Submodule.comap_map_eq_of_injective
    (chartCotangentCoordinates pivot).injective]
  rw [← LinearMap.exact_iff.mp
    (chartPreSubmersive pivot 0).toExtension.exact_cotangentComplex_toKaehler]

/-! ## The rank-one module of canonical differentials -/

/-- The first isomorphism theorem, applied to the two surjections with the
same kernel, identifies the actual relative Kahler differentials with the
free rank-one chart module. -/
def chartKaehlerDifferentialEquiv (pivot : Fin 4) :
    Ω[ChartQuotient pivot⁄k] ≃ₗ[ChartQuotient pivot]
      ChartQuotient pivot :=
  (LinearMap.quotKerEquivOfSurjective
      (chartPreSubmersive pivot 0).toExtension.toKaehler
        (chartPreSubmersive pivot 0).toExtension.toKaehler_surjective).symm |>.trans
    ((Submodule.quotEquivOfEq
        (LinearMap.ker
          (chartPreSubmersive pivot 0).toExtension.toKaehler)
        (LinearMap.ker (chartCotangentResidueFunctional pivot))
        (chartCotangentResidueFunctional_ker pivot).symm).trans
      (LinearMap.quotKerEquivOfSurjective
        (chartCotangentResidueFunctional pivot)
          (chartCotangentResidueFunctional_surjective pivot)))

/-- The chart equivalence sends the class of an ambient differential to its
Jacobian residue.  This characterizes the resulting canonical generator. -/
theorem chartKaehlerDifferentialEquiv_toKaehler
    (pivot : Fin 4) (x : ChartCotangentSpace pivot) :
    chartKaehlerDifferentialEquiv pivot
        ((chartPreSubmersive pivot 0).toExtension.toKaehler x) =
      chartCotangentResidueFunctional pivot x := by
  simp [chartKaehlerDifferentialEquiv]

/-- A singleton basis of the actual relative Kahler differentials on each
ordinary affine chart. -/
def chartKaehlerDifferentialBasis (pivot : Fin 4) :
    Module.Basis Unit (ChartQuotient pivot)
      Ω[ChartQuotient pivot⁄k] :=
  (Module.Basis.singleton Unit (ChartQuotient pivot)).map
    (chartKaehlerDifferentialEquiv pivot).symm

/-- In particular the differential module on every ordinary affine chart is
free, with one explicit basis vector supplied by the Jacobian residue. -/
theorem chartKaehlerDifferential_free (pivot : Fin 4) :
    Module.Free (ChartQuotient pivot)
      Ω[ChartQuotient pivot⁄k] :=
  Module.Free.of_basis (chartKaehlerDifferentialBasis pivot)

end MazurProof.RationalPointsN25QuotientTwoAffineCanonicalDifferentials
