import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoAmbientKoszulPullback
import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoTwistingSheafGluing

/-!
# Restricting ambient N25 twists to the canonical curve

There are two independently meaningful twist constructions on the binary
canonical curve.  The ambient Koszul calculation produces the actual
pullback `i^* O_{ℙ³}(-d)`, while the curve-side Čech construction glues
rank-one chart modules with the coordinate-ratio transition for `O_C(-d)`.

This file begins their comparison at the algebraic and local geometric
levels.  The homogeneous quotient map carries every ambient coordinate ratio,
and hence every integral-power transition, to its curve-side counterpart.
On each standard chart, pullback base change identifies the actual ambient
restriction with the same rank-one affine module used by curve-side descent.
-/

noncomputable section

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false

namespace MazurProof.RationalPointsN25QuotientTwoAmbientTwistRestriction

open RationalPointsN25QuotientTwoAmbientKoszulPullback
open RationalPointsN25QuotientTwoAmbientKoszulGeometry
open RationalPointsN25QuotientTwoAmbientTwistingDescent
open RationalPointsN25QuotientTwoAmbientTwistingSheafCharts
open RationalPointsN25QuotientTwoAmbientTwistingSheafGluing
open RationalPointsN25QuotientTwoChartIdeal
open RationalPointsN25QuotientTwoProj
open RationalPointsN25QuotientTwoQuotientGrading
open RationalPointsN25QuotientTwoTwistingTransition
open RationalPointsN25QuotientTwoTwistingDescent
open RationalPointsN25QuotientTwoTwistingSheafCharts
open RationalPointsN25QuotientTwoTwistingSheafGluing
open HomogeneousLocalization
open AlgebraicGeometry CategoryTheory
open CategoryTheory.Limits

attribute [local instance] MvPolynomial.gradedAlgebra

/-- The affine structure map carries the section generated by `r` on an open
to the section generated by `g r` on its inverse image. -/
theorem specMap_app_tildeSelf_toOpen_apply
    {R S : CommRingCat} (g : R ⟶ S) (U : (Spec R).Opens) (r : R) :
    (Spec.map g).app U
        ((AlgebraicGeometry.tilde.toOpen (ModuleCat.of R R) U) r) =
      (AlgebraicGeometry.tilde.toOpen (ModuleCat.of S S)
        ((Spec.map g) ⁻¹ᵁ U)) (g r) := by
  rw [Scheme.Modules.tildeSelf_toOpen_apply,
    Scheme.Modules.tildeSelf_toOpen_apply]
  have hnat :
      (Scheme.ΓSpecIso S).inv (g r) =
        (Spec.map g).appTop ((Scheme.ΓSpecIso R).inv r) := by
    exact ConcreteCategory.congr_hom
      (Scheme.ΓSpecIso_inv_naturality g) r
  rw [hnat]
  exact ConcreteCategory.congr_hom
    ((Spec.map g).naturality (homOfLE le_top).op)
    ((Scheme.ΓSpecIso R).inv r)

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 800000 in
-- The adjunction transpose exposes affine tilde and structure-sheaf terms,
-- whose definitional equality normalization exceeds the default budget.
/-- Pullback of a scalar automorphism of an affine structure module maps the
scalar through the affine ring homomorphism.  This is naturality of the
pullback--pushforward adjunction applied to the canonical comparison
`g^* O_{Spec R} ≅ O_{Spec S}`. -/
theorem pullbackUnitIsoOfScheme_tildeUnit_naturality
    {R S : CommRingCat} (g : R ⟶ S) (u : Rˣ) :
    (Scheme.Modules.pullback (Spec.map g)).map
          ((AlgebraicGeometry.tilde.functor R).mapIso
            (DistribMulAction.toLinearEquiv R R u).toModuleIso).hom ≫
        (Scheme.Modules.pullbackUnitIsoOfScheme (Spec.map g)).hom =
      (Scheme.Modules.pullbackUnitIsoOfScheme (Spec.map g)).hom ≫
        ((AlgebraicGeometry.tilde.functor S).mapIso
          (DistribMulAction.toLinearEquiv S S
            (Units.map g.hom.toMonoidHom u)).toModuleIso).hom := by
  apply ((Scheme.Modules.pullbackPushforwardAdjunction
    (Spec.map g)).homEquiv _ _).injective
  rw [Adjunction.homEquiv_naturality_left,
    Adjunction.homEquiv_naturality_right]
  have hunit :
      ((Scheme.Modules.pullbackPushforwardAdjunction
          (Spec.map g)).homEquiv
            ((AlgebraicGeometry.tilde.functor R).obj (ModuleCat.of R R))
            (SheafOfModules.unit (Spec S).ringCatSheaf))
          (Scheme.Modules.pullbackUnitIsoOfScheme (Spec.map g)).hom =
        Scheme.Modules.unitToPushforwardUnit (Spec.map g) := by
    change
      (SheafOfModules.pullbackPushforwardAdjunction
          (Spec.map g).toRingCatSheafHom).homEquiv _ _
          (SheafOfModules.pullbackObjUnitToUnit
            (Spec.map g).toRingCatSheafHom) =
        SheafOfModules.unitToPushforwardObjUnit
          (Spec.map g).toRingCatSheafHom
    exact
      SheafOfModules.pullbackPushforwardAdjunction_homEquiv_pullbackObjUnitToUnit
        (Spec.map g).toRingCatSheafHom
  rw [hunit]
  apply ((Scheme.Modules.pushforward (Spec.map g)).obj
    (SheafOfModules.unit (Spec S).ringCatSheaf)).unitHomEquiv.injective
  ext U
  simp only [SheafOfModules.unitHomEquiv_apply_coe]
  change
    (Spec.map g).app U.unop
        (((AlgebraicGeometry.tilde.functor R).mapIso
          (DistribMulAction.toLinearEquiv R R u).toModuleIso).hom.val.app U
            ((AlgebraicGeometry.tildeSelf (R := R)).inv.val.app U
              (1 : Γ(Spec R, U.unop)))) =
      (((AlgebraicGeometry.tilde.functor S).mapIso
        (DistribMulAction.toLinearEquiv S S
          (Units.map g.hom.toMonoidHom u)).toModuleIso).hom.val.app
            (Opposite.op ((Spec.map g) ⁻¹ᵁ U.unop)))
        ((AlgebraicGeometry.tildeSelf (R := S)).inv.val.app
          (Opposite.op ((Spec.map g) ⁻¹ᵁ U.unop))
          ((Spec.map g).app U.unop (1 : Γ(Spec R, U.unop))))
  simp only [AlgebraicGeometry.tildeSelf, Iso.refl_inv]
  have hOneR :
      (AlgebraicGeometry.tilde.toOpen (ModuleCat.of R R) U.unop) (1 : R) =
        (1 : Γ(Spec R, U.unop)) := by
    rw [Scheme.Modules.tildeSelf_toOpen_apply]
    simp
  rw [← hOneR, specMap_app_tildeSelf_toOpen_apply g U.unop (1 : R)]
  simp only [map_one]
  change
    (Spec.map g).app U.unop
        (((AlgebraicGeometry.tilde.functor R).mapIso
          (DistribMulAction.toLinearEquiv R R u).toModuleIso).hom.app U.unop
            ((AlgebraicGeometry.tilde.toOpen
              (ModuleCat.of R R) U.unop) (1 : R))) =
      (((AlgebraicGeometry.tilde.functor S).mapIso
        (DistribMulAction.toLinearEquiv S S
          (Units.map g.hom.toMonoidHom u)).toModuleIso).hom.app
            ((Spec.map g) ⁻¹ᵁ U.unop))
        ((AlgebraicGeometry.tilde.toOpen (ModuleCat.of S S)
          ((Spec.map g) ⁻¹ᵁ U.unop)) (1 : S))
  simp only [Functor.mapIso_hom]
  erw [Scheme.Modules.tildeMap_toOpen_apply,
    Scheme.Modules.tildeMap_toOpen_apply]
  have hApplyR :
      (DistribMulAction.toLinearEquiv R R u).toModuleIso.hom (1 : R) =
        (u : R) := by
    change u • (1 : R) = (u : R)
    simp [Units.smul_def]
  have hApplyS :
      (DistribMulAction.toLinearEquiv S S
          (Units.map g.hom.toMonoidHom u)).toModuleIso.hom (1 : S) =
        (Units.map g.hom.toMonoidHom u : S) := by
    change (Units.map g.hom.toMonoidHom u) • (1 : S) = _
    simp [Units.smul_def]
  rw [hApplyR, hApplyS]
  simpa using specMap_app_tildeSelf_toOpen_apply g U.unop (u : R)

/-- The homogeneous quotient induces the ring map from an ambient ordered
pair overlap to the corresponding overlap on the closed curve. -/
def canonicalConeOverlapMap (i j : Fin 4) :
    Away standardConePiece (MvPolynomial.X i * MvPolynomial.X j) →+*
      Away literalConePiece (coordinateClass i * coordinateClass j) := by
  have hi : canonicalConeGradedProjection (MvPolynomial.X i) =
      coordinateClass i := rfl
  have hj : canonicalConeGradedProjection (MvPolynomial.X j) =
      coordinateClass j := rfl
  rw [← hi, ← hj, ← map_mul]
  exact Away.map canonicalConeGradedProjection
    (MvPolynomial.X i * MvPolynomial.X j)

/-- The overlap quotient commutes with restriction from the left chart. -/
theorem canonicalConeOverlapMap_comp_left (i j : Fin 4) :
    (canonicalConeOverlapMap i j).comp
        (HomogeneousLocalization.awayMap standardConePiece
          (coordinate_isHomogeneous j) rfl) =
      (HomogeneousLocalization.awayMap literalConePiece
        (coordinateClass_mem_degreeOne j) rfl).comp
        (canonicalConeChartMap i) := by
  apply RingHom.ext
  intro x
  apply eq_of_heq
  have hnat :
      Away.map canonicalConeGradedProjection
          (MvPolynomial.X i * MvPolynomial.X j)
          (HomogeneousLocalization.awayMap standardConePiece
            (coordinate_isHomogeneous j) rfl x) ≍
        HomogeneousLocalization.awayMap literalConePiece
          (coordinateClass_mem_degreeOne j) rfl
          (Away.map canonicalConeGradedProjection (MvPolynomial.X i) x) := by
    obtain ⟨n, p, hp, rfl⟩ := Away.mk_surjective standardConePiece
      (coordinate_isHomogeneous i) x
    rw [HomogeneousLocalization.awayMap_mk, Away.map_mk,
      Away.map_mk, HomogeneousLocalization.awayMap_mk]
    congr 1
  exact hnat

/-- The overlap quotient also commutes with restriction from the right
chart. -/
theorem canonicalConeOverlapMap_comp_right (i j : Fin 4) :
    (canonicalConeOverlapMap i j).comp
        (HomogeneousLocalization.awayMap standardConePiece
          (coordinate_isHomogeneous i) (mul_comm _ _)) =
      (HomogeneousLocalization.awayMap literalConePiece
        (coordinateClass_mem_degreeOne i) (mul_comm _ _)).comp
        (canonicalConeChartMap j) := by
  apply RingHom.ext
  intro x
  apply eq_of_heq
  have hnat :
      Away.map canonicalConeGradedProjection
          (MvPolynomial.X i * MvPolynomial.X j)
          (HomogeneousLocalization.awayMap standardConePiece
            (coordinate_isHomogeneous i) (mul_comm _ _) x) ≍
        HomogeneousLocalization.awayMap literalConePiece
          (coordinateClass_mem_degreeOne i) (mul_comm _ _)
          (Away.map canonicalConeGradedProjection (MvPolynomial.X j) x) := by
    obtain ⟨n, p, hp, rfl⟩ := Away.mk_surjective standardConePiece
      (coordinate_isHomogeneous j) x
    rw [HomogeneousLocalization.awayMap_mk, Away.map_mk,
      Away.map_mk, HomogeneousLocalization.awayMap_mk]
    congr 1
  exact hnat

/-- The affine map from a curve overlap to the corresponding ambient
overlap is induced by the localized homogeneous quotient. -/
def localOverlapCurveMap (i j : Fin 4) :
    Spec (.of (coordinateOverlapRing i j)) ⟶
      Spec (.of (ambientOverlapRing i j)) :=
  Spec.map (CommRingCat.ofHom (canonicalConeOverlapMap i j))

/-- The quotient map on a curve chart, written with the chart type used by
the independently glued curve twist.  This is definitionally the same map
as `localCurveMap`; the separate name prevents a harmless abbreviation
boundary from obscuring the source object in overlap compositions. -/
def coordinateLocalCurveMap (i : Fin 4) :
    coordinateChartScheme i ⟶ ambientChartScheme i :=
  Spec.map (CommRingCat.ofHom (canonicalConeChartMap i))

/-- The overlap quotient followed by the left ambient projection is the
left curve projection followed by the chart quotient. -/
theorem localOverlapCurveMap_comp_left (i j : Fin 4) :
    localOverlapCurveMap i j ≫ ambientOverlapToLeft i j =
      coordinateOverlapToLeft i j ≫ coordinateLocalCurveMap i := by
  unfold localOverlapCurveMap ambientOverlapToLeft coordinateOverlapToLeft
  rw [coordinateChosenPullbackIso_inv_p₁]
  unfold coordinateLocalCurveMap
  rw [← Spec.map_comp, ← Spec.map_comp]
  congr 1
  change CommRingCat.ofHom
      ((canonicalConeOverlapMap i j).comp
        (HomogeneousLocalization.awayMap standardConePiece
          (coordinate_isHomogeneous j) rfl)) =
    CommRingCat.ofHom
      ((HomogeneousLocalization.awayMap literalConePiece
        (coordinateClass_mem_degreeOne j) rfl).comp
        (canonicalConeChartMap i))
  exact congrArg CommRingCat.ofHom
    (canonicalConeOverlapMap_comp_left i j)

/-- The analogous square commutes for the right chart projection. -/
theorem localOverlapCurveMap_comp_right (i j : Fin 4) :
    localOverlapCurveMap i j ≫ ambientOverlapToRight i j =
      coordinateOverlapToRight i j ≫ coordinateLocalCurveMap j := by
  unfold localOverlapCurveMap ambientOverlapToRight coordinateOverlapToRight
  rw [coordinateChosenPullbackIso_inv_p₂]
  unfold coordinateLocalCurveMap
  rw [← Spec.map_comp, ← Spec.map_comp]
  congr 1
  change CommRingCat.ofHom
      ((canonicalConeOverlapMap i j).comp
        (HomogeneousLocalization.awayMap standardConePiece
          (coordinate_isHomogeneous i) (mul_comm _ _))) =
    CommRingCat.ofHom
      ((HomogeneousLocalization.awayMap literalConePiece
        (coordinateClass_mem_degreeOne i) (mul_comm _ _)).comp
        (canonicalConeChartMap j))
  exact congrArg CommRingCat.ofHom
    (canonicalConeOverlapMap_comp_right i j)

/-- The curve overlap is obtained by pulling the ambient overlap back along
the quotient map on the left chart.  The range calculation is the geometric
form of the fact that the quotient sends `X j / X i` to `x j / x i`. -/
theorem localOverlapCurveMap_left_square_isPullback (i j : Fin 4) :
    IsPullback (localOverlapCurveMap i j) (coordinateOverlapToLeft i j)
      (ambientOverlapToLeft i j) (coordinateLocalCurveMap i) := by
  apply IsOpenImmersion.isPullback
  · exact (localOverlapCurveMap_comp_left i j).symm
  · rw [ambientOverlapToLeft_opensRange,
      coordinateOverlapToLeft_opensRange]
    unfold coordinateLocalCurveMap
    rw [SpecMap_preimage_basicOpen]
    rfl

/-- In the right ambient chart, the ordered overlap is the principal open
where the left coordinate ratio is nonzero. -/
theorem ambientOverlapToRight_opensRange_local (i j : Fin 4) :
    (ambientOverlapToRight i j).opensRange =
      PrimeSpectrum.basicOpen
        (Away.isLocalizationElem (coordinate_isHomogeneous j)
          (coordinate_isHomogeneous i)) := by
  letI := (awayMap standardConePiece (f := MvPolynomial.X j)
    (coordinate_isHomogeneous i) (mul_comm _ _)).toAlgebra
  letI : IsLocalization.Away
      (Away.isLocalizationElem (coordinate_isHomogeneous j)
        (coordinate_isHomogeneous i))
      (ambientOverlapRing i j) :=
    Away.isLocalization_mul (coordinate_isHomogeneous j)
      (coordinate_isHomogeneous i) (mul_comm _ _) (by norm_num)
  apply TopologicalSpace.Opens.ext
  rw [Scheme.Hom.coe_opensRange]
  have hmap : ambientOverlapToRight i j =
      Spec.map (CommRingCat.ofHom (algebraMap
        (ambientChartRing j) (ambientOverlapRing i j))) := by
    rfl
  rw [hmap]
  exact PrimeSpectrum.localization_away_comap_range
    (ambientOverlapRing i j) _

/-- The right curve overlap has the analogous principal-open range. -/
theorem coordinateOverlapToRight_opensRange_local (i j : Fin 4) :
    (coordinateOverlapToRight i j).opensRange =
      PrimeSpectrum.basicOpen
        (Away.isLocalizationElem (coordinateClass_mem_degreeOne j)
          (coordinateClass_mem_degreeOne i)) := by
  letI := (awayMap literalConePiece (f := coordinateClass j)
    (coordinateClass_mem_degreeOne i) (mul_comm _ _)).toAlgebra
  letI : IsLocalization.Away
      (Away.isLocalizationElem (coordinateClass_mem_degreeOne j)
        (coordinateClass_mem_degreeOne i))
      (coordinateOverlapRing i j) :=
    Away.isLocalization_mul (coordinateClass_mem_degreeOne j)
      (coordinateClass_mem_degreeOne i) (mul_comm _ _) (by norm_num)
  apply TopologicalSpace.Opens.ext
  rw [Scheme.Hom.coe_opensRange]
  have hmap : coordinateOverlapToRight i j =
      Spec.map (CommRingCat.ofHom (algebraMap
        (coordinateChartRing j) (coordinateOverlapRing i j))) := by
    dsimp [coordinateOverlapToRight]
    exact coordinateChosenPullbackIso_inv_p₂ i j
  rw [hmap]
  exact PrimeSpectrum.localization_away_comap_range
    (coordinateOverlapRing i j) _

/-- The same curve overlap is also the pullback of the ambient overlap from
the right chart.  Keeping both cartesian squares avoids choosing a preferred
side when comparing the two transition maps. -/
theorem localOverlapCurveMap_right_square_isPullback (i j : Fin 4) :
    IsPullback (localOverlapCurveMap i j) (coordinateOverlapToRight i j)
      (ambientOverlapToRight i j) (coordinateLocalCurveMap j) := by
  apply IsOpenImmersion.isPullback
  · exact (localOverlapCurveMap_comp_right i j).symm
  · rw [ambientOverlapToRight_opensRange_local,
      coordinateOverlapToRight_opensRange_local]
    unfold coordinateLocalCurveMap
    rw [SpecMap_preimage_basicOpen]
    rfl

/-- Passing to the homogeneous quotient carries the ambient coordinate
ratio to the curve coordinate ratio. -/
theorem canonicalConeOverlapMap_degreeOneRatio (i j : Fin 4) :
    canonicalConeOverlapMap i j
        (Away.degreeOneRatio standardConePiece
          (coordinate_isHomogeneous i) (coordinate_isHomogeneous j)) =
      Away.degreeOneRatio literalConePiece
        (coordinateClass_mem_degreeOne i)
        (coordinateClass_mem_degreeOne j) := by
  apply eq_of_heq
  exact Away.map_degreeOneRatio_heq canonicalConeGradedProjection
    (coordinate_isHomogeneous i) (coordinate_isHomogeneous j)

/-- Naturality of the coordinate ratio upgrades from elements to units. -/
theorem canonicalConeOverlapMap_degreeOneRatioUnit (i j : Fin 4) :
    Units.map (canonicalConeOverlapMap i j).toMonoidHom
        (Away.degreeOneRatioUnit standardConePiece
          (coordinate_isHomogeneous i) (coordinate_isHomogeneous j)) =
      Away.degreeOneRatioUnit literalConePiece
        (coordinateClass_mem_degreeOne i)
        (coordinateClass_mem_degreeOne j) := by
  apply Units.ext
  exact canonicalConeOverlapMap_degreeOneRatio i j

/-- The quotient map intertwines every integral-power transition on an
ordered pair overlap.  Thus positive and negative twists are handled by the
same structural statement. -/
theorem canonicalConeOverlapMap_ratioPowerTransition
    (d : ℤ) (i j : Fin 4)
    (x : Away standardConePiece (MvPolynomial.X i * MvPolynomial.X j)) :
    canonicalConeOverlapMap i j
        (Away.ratioPowerTransition standardConePiece
          (coordinate_isHomogeneous i) (coordinate_isHomogeneous j) d x) =
      Away.ratioPowerTransition literalConePiece
        (coordinateClass_mem_degreeOne i)
        (coordinateClass_mem_degreeOne j) d
        (canonicalConeOverlapMap i j x) := by
  change canonicalConeOverlapMap i j
      (((Away.degreeOneRatioUnit standardConePiece
        (coordinate_isHomogeneous i) (coordinate_isHomogeneous j) : _) ^ d : _) * x) =
    ((Away.degreeOneRatioUnit literalConePiece
      (coordinateClass_mem_degreeOne i)
      (coordinateClass_mem_degreeOne j) : _) ^ d : _) *
      canonicalConeOverlapMap i j x
  rw [map_mul]
  congr 1
  have hz :
      Units.map (canonicalConeOverlapMap i j).toMonoidHom
          ((Away.degreeOneRatioUnit standardConePiece
            (coordinate_isHomogeneous i) (coordinate_isHomogeneous j)) ^ d) =
        (Away.degreeOneRatioUnit literalConePiece
          (coordinateClass_mem_degreeOne i)
          (coordinateClass_mem_degreeOne j)) ^ d := by
    rw [map_zpow, canonicalConeOverlapMap_degreeOneRatioUnit]
  exact congrArg Units.val hz

/-- Pulling the ambient overlap model to the curve overlap gives the curve
overlap model through their canonical structure-module identifications. -/
def curvePullbackTwistOverlapIso (d : ℤ) (i j : Fin 4) :
    (Scheme.Modules.pullback (localOverlapCurveMap i j)).obj
        (ambientOverlapTwistModule d i j) ≅
      coordinateOverlapTwistModule d i j :=
  (Scheme.Modules.pullback (localOverlapCurveMap i j)).mapIso
      (ambientOverlapTwistUnitIso d i j) ≪≫
    Scheme.Modules.pullbackUnitIsoOfScheme (localOverlapCurveMap i j) ≪≫
    (coordinateOverlapTwistUnitIso d i j).symm

set_option maxHeartbeats 800000 in
-- Normalizing both rank-one trivializations and the pullback comparison
-- requires unfolding large homogeneous-localization sheaf instances.
/-- The overlap comparison intertwines the pulled-back ambient transition
with the curve transition.  This is the sheaf-level naturality statement
that makes the two Čech descent data agree after restricting to the curve. -/
theorem curvePullbackTwistOverlapIso_transition
    (d : ℤ) (i j : Fin 4) :
    (Scheme.Modules.pullback (localOverlapCurveMap i j)).map
          (ambientOverlapTwistIso d i j).hom ≫
        (curvePullbackTwistOverlapIso d i j).hom =
      (curvePullbackTwistOverlapIso d i j).hom ≫
        (coordinateOverlapTwistIso d i j).hom := by
  have hz :
      Units.map (canonicalConeOverlapMap i j).toMonoidHom
          ((Away.degreeOneRatioUnit standardConePiece
            (coordinate_isHomogeneous i) (coordinate_isHomogeneous j)) ^ d) =
        (Away.degreeOneRatioUnit literalConePiece
          (coordinateClass_mem_degreeOne i)
          (coordinateClass_mem_degreeOne j)) ^ d := by
    rw [map_zpow, canonicalConeOverlapMap_degreeOneRatioUnit]
  simp only [curvePullbackTwistOverlapIso, Iso.trans_hom,
    Functor.mapIso_hom, ambientOverlapTwistUnitIso,
    coordinateOverlapTwistUnitIso, AlgebraicGeometry.tildeSelf,
    Category.assoc]
  simp only [Iso.refl_hom, Iso.symm_hom, Iso.refl_inv]
  have hmap := (Scheme.Modules.pullback
    (localOverlapCurveMap i j)).map_id (ambientOverlapTwistModule d i j)
  erw [hmap]
  simp only [Category.id_comp]
  unfold localOverlapCurveMap ambientOverlapTwistIso
    coordinateOverlapTwistIso
  change
    (Scheme.Modules.pullback
      (Spec.map (CommRingCat.ofHom (canonicalConeOverlapMap i j)))).map
        ((AlgebraicGeometry.tilde.functor
          (.of (ambientOverlapRing i j))).mapIso
            (DistribMulAction.toLinearEquiv _ _
              ((Away.degreeOneRatioUnit standardConePiece
                (coordinate_isHomogeneous i)
                (coordinate_isHomogeneous j)) ^ d)).toModuleIso).hom ≫
      (Scheme.Modules.pullbackUnitIsoOfScheme
        (Spec.map (CommRingCat.ofHom
          (canonicalConeOverlapMap i j)))).hom =
    (Scheme.Modules.pullbackUnitIsoOfScheme
      (Spec.map (CommRingCat.ofHom
        (canonicalConeOverlapMap i j)))).hom ≫
      ((AlgebraicGeometry.tilde.functor
        (.of (coordinateOverlapRing i j))).mapIso
          (DistribMulAction.toLinearEquiv _ _
            ((Away.degreeOneRatioUnit literalConePiece
              (coordinateClass_mem_degreeOne i)
              (coordinateClass_mem_degreeOne j)) ^ d)).toModuleIso).hom
  rw [pullbackUnitIsoOfScheme_tildeUnit_naturality]
  have hz' :
      Units.map
          (CommRingCat.ofHom (canonicalConeOverlapMap i j)).hom.toMonoidHom
          ((Away.degreeOneRatioUnit standardConePiece
            (coordinate_isHomogeneous i) (coordinate_isHomogeneous j)) ^ d) =
        (Away.degreeOneRatioUnit literalConePiece
          (coordinateClass_mem_degreeOne i)
          (coordinateClass_mem_degreeOne j)) ^ d := by
    exact hz
  rw [hz']

/-- On one standard curve chart, both twist constructions use the same
rank-one affine module after passing through their canonical unit
trivializations. -/
def curvePullbackTwistChartIso (d : ℤ) (i : Fin 4) :
    (Scheme.Modules.restrictFunctor (coordinateChartMap i)).obj
        (curvePullbackTwist d) ≅
      coordinateLocalTwistModule d i :=
  curvePullbackTwistLocalIso d i ≪≫
    (coordinateLocalTwistUnitIso d i).symm

end MazurProof.RationalPointsN25QuotientTwoAmbientTwistRestriction
