import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoClosedPointEvaluation
import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoClosedPointPrime
import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoFullClosedPoints
import Mathlib.FieldTheory.IntermediateField.Algebraic

/-!
# Residue degree of a canonical binary closed point

The residue field of chart evaluation is the subfield generated by the
non-pivot normalized coordinates.  Its binary extension degree controls a
Frobenius iterate fixing every coordinate, and exact periodicity will force
that degree to equal the closed-point degree.
-/

noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoClosedPointResidueDegree

open Function
open CurveZetaFrobeniusOrbitGrading
open FiniteFieldFrobeniusDescent
open NormalizedProjectiveCurveFrobenius
open RationalPointsN25QuotientF2
open RationalPointsN25QuotientBaseChange
open RationalPointsN25QuotientSmoothF2
open RationalPointsN25QuotientWeil
open RationalPointsN25QuotientTwoAffineCharts
open RationalPointsN25QuotientTwoAffineChartsSmooth
open RationalPointsN25QuotientTwoBaseChange
open RationalPointsN25QuotientBinaryFieldSemantics
open RationalPointsN25QuotientTwoClosedPointChart
open RationalPointsN25QuotientTwoClosedPointEvaluation
open RationalPointsN25QuotientTwoClosedPointPrime
open RationalPointsN25QuotientTwoConormal
open RationalPointsN25QuotientTwoFrobeniusOrbits
open RationalPointsN25QuotientTwoFullClosedPoints

/-- The intermediate field generated by affine evaluation at a point on its
canonical chart. -/
def chartPointCoordinateField
    (d : ℕ) (i : Fin 4)
    (P : CurvePointOnChart i (CommonField 2 d)) :
    IntermediateField (ZMod 2) (CommonField 2 d) := by
  let S := (chartQuotientEvalAlgHom i P).range
  letI : Finite S := Finite.of_injective Subtype.val Subtype.val_injective
  exact S.toIntermediateField' (Finite.isField_of_domain S)

/-- Membership in the coordinate field is membership in the evaluation
range. -/
theorem mem_chartPointCoordinateField_iff
    (d : ℕ) (i : Fin 4)
    (P : CurvePointOnChart i (CommonField 2 d))
    (x : CommonField 2 d) :
    x ∈ chartPointCoordinateField d i P ↔
      x ∈ (chartQuotientEvalAlgHom i P).range := by
  rfl

/-- Every normalized homogeneous coordinate belongs to the coordinate field.
The pivot coordinate is one; every other coordinate is the evaluation of an
affine variable. -/
theorem normalizedCoordinate_mem_chartPointCoordinateField
    (d : ℕ) (i : Fin 4)
    (P : CurvePointOnChart i (CommonField 2 d)) (j : Fin 4) :
    coordinates4ToFun (normalizedCoordinates25 P.1.1) j ∈
      chartPointCoordinateField d i P := by
  rw [mem_chartPointCoordinateField_iff]
  by_cases hji : j = i
  · subst j
    have hcoord :
        coordinates4ToFun (normalizedCoordinates25 P.1.1) i = 1 := by
      exact (congrArg
        (coordinates4ToFun (normalizedCoordinates25 P.1.1)) P.2.symm).trans
          (normalizedCoordinates25_pivot P.1.1)
    rw [hcoord]
    exact (chartQuotientEvalAlgHom i P).range.one_mem
  · let j' : OtherCoordinate i := ⟨j, hji⟩
    refine ⟨Ideal.Quotient.mk (chartAffineEquationIdeal i)
      (MvPolynomial.X j'), ?_⟩
    change chartQuotientEval i P
        (Ideal.Quotient.mk (chartAffineEquationIdeal i)
          (MvPolynomial.X j')) =
      coordinates4ToFun (normalizedCoordinates25 P.1.1) j
    rw [chartQuotientEval_mk, chartPointAffineEval_X]

/-- The coordinate field has cardinality two to its binary extension
degree. -/
theorem chartPointCoordinateField_card
    (d : ℕ) (i : Fin 4)
    (P : CurvePointOnChart i (CommonField 2 d)) :
    Nat.card (chartPointCoordinateField d i P) =
      2 ^ Module.finrank (ZMod 2) (chartPointCoordinateField d i P) := by
  simpa using
    (Module.natCard_eq_pow_finrank
      (K := ZMod 2) (V := chartPointCoordinateField d i P))

/-- The Frobenius iterate indexed by the coordinate-field degree fixes every
element of that coordinate field inside the ambient common field. -/
theorem commonFrobenius_pow_coordinateFieldDegree_apply
    (d : ℕ) (i : Fin 4)
    (P : CurvePointOnChart i (CommonField 2 d))
    (x : CommonField 2 d)
    (hx : x ∈ chartPointCoordinateField d i P) :
    (commonFrobenius 2 d ^
        Module.finrank (ZMod 2) (chartPointCoordinateField d i P)) x = x := by
  rw [commonFrobenius_pow_apply]
  let y : chartPointCoordinateField d i P := ⟨x, hx⟩
  letI := Fintype.ofFinite (chartPointCoordinateField d i P)
  have hy := FiniteField.pow_card y
  rw [← Nat.card_eq_fintype_card,
    chartPointCoordinateField_card d i P] at hy
  exact congrArg Subtype.val hy

/-- A coordinatewise field endomorphism fixes a normalized projective point
when it fixes all four normalized homogeneous coordinates. -/
theorem normalizedProjective4_map_eq_of_coordinates_fixed
    {K : Type} [Field K] (f : K →+* K)
    (P : NormalizedProjective4 K)
    (hfix : ∀ j : Fin 4,
      f (coordinates4ToFun (normalizedCoordinates25 P) j) =
        coordinates4ToFun (normalizedCoordinates25 P) j) :
    NormalizedProjective4.map f P = P := by
  cases P with
  | xChart y z w =>
      have hy : f y = y := by
        simpa [normalizedCoordinates25,
          NormalizedProjective4.coordinates, fieldBinaryOperations,
          coordinates4ToFun] using hfix (1 : Fin 4)
      have hz : f z = z := by
        simpa [normalizedCoordinates25,
          NormalizedProjective4.coordinates, fieldBinaryOperations,
          coordinates4ToFun] using hfix (2 : Fin 4)
      have hw : f w = w := by
        simpa [normalizedCoordinates25,
          NormalizedProjective4.coordinates, fieldBinaryOperations,
          coordinates4ToFun] using hfix (3 : Fin 4)
      simp [NormalizedProjective4.map, hy, hz, hw]
  | yChart z w =>
      have hz : f z = z := by
        simpa [normalizedCoordinates25,
          NormalizedProjective4.coordinates, fieldBinaryOperations,
          coordinates4ToFun] using hfix (2 : Fin 4)
      have hw : f w = w := by
        simpa [normalizedCoordinates25,
          NormalizedProjective4.coordinates, fieldBinaryOperations,
          coordinates4ToFun] using hfix (3 : Fin 4)
      simp [NormalizedProjective4.map, hz, hw]
  | zChart w =>
      have hw : f w = w := by
        simpa [normalizedCoordinates25,
          NormalizedProjective4.coordinates, fieldBinaryOperations,
          coordinates4ToFun] using hfix (3 : Fin 4)
      simp [NormalizedProjective4.map, hw]
  | wChart =>
      rfl

/-- The Frobenius iterate indexed by the coordinate-field degree fixes the
underlying canonical curve point. -/
theorem pointFrobenius_coordinateFieldDegree_fixed
    (d : ℕ) (i : Fin 4)
    (P : CurvePointOnChart i (CommonField 2 d)) :
    ((pointFrobeniusFun canonicalTwoModel 2 d : _ → _)^[
        Module.finrank (ZMod 2) (chartPointCoordinateField d i P)]) P.1 =
      P.1 := by
  apply Subtype.ext
  rw [pointFrobenius_iterate_val]
  apply normalizedProjective4_map_eq_of_coordinates_fixed
  intro j
  exact commonFrobenius_pow_coordinateFieldDegree_apply d i P _
    (normalizedCoordinate_mem_chartPointCoordinateField d i P j)

/-- The exact Frobenius period divides the binary extension degree of the
coordinate field. -/
theorem exactPeriod_dvd_coordinateFieldDegree
    (d : ℕ)
    (Q : ExactPeriodicPoint (degreePointFrobeniusTwo d) d) :
    d ∣ Module.finrank (ZMod 2)
      (chartPointCoordinateField d (normalizedPivot Q.1.1)
        ⟨Q.1, rfl⟩) := by
  let P : CurvePointOnChart (normalizedPivot Q.1.1) (CommonField 2 d) :=
    ⟨Q.1, rfl⟩
  have hfix := pointFrobenius_coordinateFieldDegree_fixed
    d (normalizedPivot Q.1.1) P
  have hperiodic : IsPeriodicPt (degreePointFrobeniusTwo d)
      (Module.finrank (ZMod 2)
        (chartPointCoordinateField d (normalizedPivot Q.1.1) P)) Q.1 := by
    change ((pointFrobeniusFun canonicalTwoModel 2 d : _ → _)^[
        Module.finrank (ZMod 2)
          (chartPointCoordinateField d (normalizedPivot Q.1.1) P)]) Q.1 = Q.1
    change ((pointFrobeniusFun canonicalTwoModel 2 d : _ → _)^[
        Module.finrank (ZMod 2)
          (chartPointCoordinateField d (normalizedPivot Q.1.1) P)]) Q.1 = Q.1
      at hfix
    exact hfix
  simpa only [Q.2] using hperiodic.minimalPeriod_dvd

/-- The coordinate-field degree divides the ambient common-field degree. -/
theorem coordinateFieldDegree_dvd
    (d : ℕ) (hd : 0 < d) (i : Fin 4)
    (P : CurvePointOnChart i (CommonField 2 d)) :
    Module.finrank (ZMod 2) (chartPointCoordinateField d i P) ∣ d := by
  refine ⟨Module.finrank (chartPointCoordinateField d i P)
    (CommonField 2 d), ?_⟩
  rw [Module.finrank_mul_finrank, GaloisField.finrank 2 hd.ne']

/-- For an exact-period point, the coordinate field has exactly the orbit
degree over the binary prime field. -/
theorem coordinateFieldDegree_eq_exactPeriod
    (d : ℕ) (hd : 0 < d)
    (Q : ExactPeriodicPoint (degreePointFrobeniusTwo d) d) :
    Module.finrank (ZMod 2)
        (chartPointCoordinateField d (normalizedPivot Q.1.1)
          ⟨Q.1, rfl⟩) = d := by
  apply Nat.dvd_antisymm
  · exact coordinateFieldDegree_dvd d hd _ ⟨Q.1, rfl⟩
  · exact exactPeriod_dvd_coordinateFieldDegree d Q

/-- The ring-hom range used by the kernel quotient and the corresponding
intermediate coordinate field have the same underlying elements. -/
def chartPointEvalRangeEquivCoordinateField
    (d : ℕ) (i : Fin 4)
    (P : CurvePointOnChart i (CommonField 2 d)) :
    (chartQuotientEval i P).range ≃
      chartPointCoordinateField d i P where
  toFun x := ⟨x.1, by
    rw [mem_chartPointCoordinateField_iff]
    rcases x.2 with ⟨a, ha⟩
    exact ⟨a, ha⟩⟩
  invFun x := ⟨x.1, by
    have hx := x.2
    rw [mem_chartPointCoordinateField_iff] at hx
    rcases hx with ⟨a, ha⟩
    exact ⟨a, ha⟩⟩
  left_inv x := Subtype.ext rfl
  right_inv x := Subtype.ext rfl

/-- The chart residue ring and the coordinate field have the same finite
cardinality. -/
theorem chartPointResidue_card_eq_coordinateField_card
    (d : ℕ) (i : Fin 4)
    (P : CurvePointOnChart i (CommonField 2 d)) :
    Nat.card (ChartPointResidue i P) =
      Nat.card (chartPointCoordinateField d i P) := by
  exact Nat.card_congr
    ((chartPointResidueEquivRange i P).toEquiv.trans
      (chartPointEvalRangeEquivCoordinateField d i P))

/-- The residue field attached to an exact-period point has cardinality
`2^d`, so its residue degree is the orbit degree. -/
theorem exactPeriodicPoint_residue_card
    (d : ℕ) (hd : 0 < d)
    (Q : ExactPeriodicPoint (degreePointFrobeniusTwo d) d) :
    Nat.card
        (ChartPointResidue (normalizedPivot Q.1.1) ⟨Q.1, rfl⟩) =
      2 ^ d := by
  rw [chartPointResidue_card_eq_coordinateField_card,
    chartPointCoordinateField_card,
    coordinateFieldDegree_eq_exactPeriod d hd Q]

/-! ## Canonical residue ring on the four-chart product -/

/-- The residue ring of the fixed product-ring prime attached to a geometric
point. -/
abbrev CanonicalChartProductResidue
    {K : Type} [Field K] [Algebra (ZMod 2) K]
    (P : CurvePointTwo K) :=
  CanonicalChartProductTwo ⧸
    RingHom.ker (canonicalChartProductEval P)

/-- The residue ring of product evaluation into a finite coordinate field is
a finite field. -/
theorem canonicalChartProductResidue_isField
    (d : ℕ) (P : CurvePointTwo (CommonField 2 d)) :
    IsField (CanonicalChartProductResidue P) := by
  letI : (RingHom.ker (canonicalChartProductEval P)).IsPrime :=
    RingHom.ker_isPrime (canonicalChartProductEval P)
  letI : Finite (canonicalChartProductEval P).range :=
    Finite.of_injective Subtype.val Subtype.val_injective
  letI : Finite (CanonicalChartProductResidue P) :=
    Finite.of_equiv (canonicalChartProductEval P).range
      (RingHom.quotientKerEquivRange
        (canonicalChartProductEval P)).symm.toEquiv
  exact Finite.isField_of_domain (CanonicalChartProductResidue P)

/-- The product-evaluation range and the pivot-chart evaluation range have
the same underlying elements of the coordinate field. -/
def canonicalChartProductEvalRangeEquivChartRange
    (d : ℕ) (P : CurvePointTwo (CommonField 2 d)) :
    (canonicalChartProductEval P).range ≃
      (chartQuotientEval (normalizedPivot P.1)
        (pointOnCanonicalChart P)).range where
  toFun x := ⟨x.1, by
    rcases x.2 with ⟨f, hf⟩
    refine ⟨f (normalizedPivot P.1), ?_⟩
    exact hf⟩
  invFun x := ⟨x.1, by
    rcases x.2 with ⟨a, ha⟩
    obtain ⟨f, hf⟩ :=
      (Pi.evalRingHom (fun j : Fin 4 => ChartQuotient j)
        (normalizedPivot P.1)).surjective a
    refine ⟨f, ?_⟩
    change chartQuotientEval (normalizedPivot P.1)
        (pointOnCanonicalChart P)
        (f (normalizedPivot P.1)) = x.1
    change f (normalizedPivot P.1) = a at hf
    rw [hf, ha]⟩
  left_inv x := Subtype.ext rfl
  right_inv x := Subtype.ext rfl

/-- Product-ring residue and pivot-chart residue have equal cardinality. -/
theorem canonicalChartProductResidue_card_eq_chartPointResidue_card
    (d : ℕ) (P : CurvePointTwo (CommonField 2 d)) :
    Nat.card (CanonicalChartProductResidue P) =
      Nat.card (ChartPointResidue (normalizedPivot P.1)
        (pointOnCanonicalChart P)) := by
  exact Nat.card_congr
    ((RingHom.quotientKerEquivRange
        (canonicalChartProductEval P)).toEquiv.trans
      ((canonicalChartProductEvalRangeEquivChartRange d P).trans
        (chartPointResidueEquivRange (normalizedPivot P.1)
          (pointOnCanonicalChart P)).symm.toEquiv))

/-- The canonical product-ring residue of an exact-period point has
cardinality `2^d`. -/
theorem exactPeriodicPoint_productResidue_card
    (d : ℕ) (hd : 0 < d)
    (Q : ExactPeriodicPoint (degreePointFrobeniusTwo d) d) :
    Nat.card (CanonicalChartProductResidue Q.1) = 2 ^ d := by
  rw [canonicalChartProductResidue_card_eq_chartPointResidue_card
    d Q.1]
  exact exactPeriodicPoint_residue_card d hd Q

/-- The representative-independent residue ring of a full positive-degree
closed point. -/
abbrev FullClosedPointChartResidue
    (d : ℕ) (hd : 0 < d)
    (P : fullClosedPointGrading25Two.Closed d) :=
  CanonicalChartProductTwo ⧸
    (fullClosedPointChartPrime d hd P).asIdeal

/-- The canonical residue field of a full degree-`d` closed point has exactly
`2^d` elements. -/
theorem fullClosedPointChartResidue_card
    (d : ℕ) (hd : 0 < d)
    (P : fullClosedPointGrading25Two.Closed d) :
    Nat.card (FullClosedPointChartResidue d hd P) = 2 ^ d := by
  revert hd P
  cases d with
  | zero =>
      intro hd
      omega
  | succ n =>
      intro hd P
      induction P using Quotient.inductionOn with
      | _ Q =>
          change Nat.card (CanonicalChartProductResidue Q.1) = 2 ^ (n + 1)
          exact exactPeriodicPoint_productResidue_card (n + 1) hd Q

/-- Every full positive-degree closed-point residue ring is a field. -/
theorem fullClosedPointChartResidue_isField
    (d : ℕ) (hd : 0 < d)
    (P : fullClosedPointGrading25Two.Closed d) :
    IsField (FullClosedPointChartResidue d hd P) := by
  revert hd P
  cases d with
  | zero =>
      intro hd
      omega
  | succ n =>
      intro _ P
      induction P using Quotient.inductionOn with
      | _ Q =>
          exact canonicalChartProductResidue_isField (n + 1) Q.1

/-- The descended product-ring ideal of a full closed point is maximal. -/
theorem fullClosedPointChartPrime_isMaximal
    (d : ℕ) (hd : 0 < d)
    (P : fullClosedPointGrading25Two.Closed d) :
    (fullClosedPointChartPrime d hd P).asIdeal.IsMaximal :=
  Ideal.Quotient.maximal_of_isField _
    (fullClosedPointChartResidue_isField d hd P)

end MazurProof.RationalPointsN25QuotientTwoClosedPointResidueDegree
