import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoWBoundaryChartArtin
import Mathlib.RingTheory.LocalRing.Length
import Mathlib.RingTheory.OrderOfVanishing.Basic

/-!
# The X-boundary quotient in the local curve ring

This file localizes the actual `X != 0` curve chart at the rational point
`[1:0:0:0]`.  Every denominator outside the point prime becomes a unit after
quotienting by `W/X`, so the chart quotient extends to the local ring.  Its
kernel is exactly the germ ideal generated by `W/X`; consequently the local
quotient is the length-three Artin algebra `F₂[t]/(t³)`.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false
noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoWBoundaryXLocal

open Polynomial
open RationalPointsN25QuotientTwoAffineCharts
open RationalPointsN25QuotientTwoAffineChartsSmooth
open RationalPointsN25QuotientTwoConormal
open RationalPointsN25QuotientTwoHyperplaneArtin
open RationalPointsN25QuotientTwoWBoundaryChartArtin

local notation "k₂" => ZMod 2

abbrev XAffineRing := AffineChart (0 : Fin 4)

private def xAffineEval : XAffineRing →+* k₂ :=
  MvPolynomial.eval₂Hom (RingHom.id k₂) (fun _ => 0)

private noncomputable def xAffineEvalAlg : XAffineRing →ₐ[k₂] k₂ where
  __ := xAffineEval
  commutes' c := by simp [xAffineEval]

private theorem xAffineEval_quadric :
    xAffineEval (chartAffineQuadric (0 : Fin 4)) = 0 := by
  simp [xAffineEval, chartAffineQuadric, ambientDehomogenize,
    dehomogenizedVariable, canonicalQuadricPolynomial25Two]

private theorem xAffineEval_cubic :
    xAffineEval (chartAffineCubic (0 : Fin 4)) = 0 := by
  simp [xAffineEval, chartAffineCubic, ambientDehomogenize,
    dehomogenizedVariable, canonicalCubicPolynomial25Two]

private theorem xEquationIdeal_le_ker :
    chartAffineEquationIdeal (0 : Fin 4) ≤ RingHom.ker xAffineEval := by
  rw [chartAffineEquationIdeal, Ideal.span_le]
  rintro f ⟨r, rfl⟩
  fin_cases r
  · exact RingHom.mem_ker.mpr xAffineEval_quadric
  · exact RingHom.mem_ker.mpr xAffineEval_cubic

/-- Evaluation of the actual `X`-chart curve ring at `[1:0:0:0]`. -/
noncomputable def xChartEval : XChartRing →ₐ[k₂] k₂ :=
  Ideal.Quotient.liftₐ
    (chartAffineEquationIdeal (0 : Fin 4)) xAffineEvalAlg
    (fun _ ha => RingHom.mem_ker.mp (xEquationIdeal_le_ker ha))

theorem xChartEval_surjective : Function.Surjective xChartEval := by
  intro c
  refine ⟨algebraMap k₂ XChartRing c, ?_⟩
  simp [xChartEval]

/-- The maximal ideal of `[1:0:0:0]` in the actual `X` chart. -/
def xPrime : Ideal XChartRing := RingHom.ker xChartEval.toRingHom

theorem xPrime_isMaximal : xPrime.IsMaximal :=
  RingHom.ker_isMaximal_of_surjective
    xChartEval.toRingHom xChartEval_surjective

local instance : xPrime.IsMaximal := xPrime_isMaximal
local instance : xPrime.IsPrime := xPrime_isMaximal.isPrime

@[simp] theorem xChartEval_xW : xChartEval xW = 0 := by
  simp [xChartEval, xAffineEvalAlg, xAffineEval, xW, chartMap,
    ambientDehomogenize, dehomogenizedVariable]

theorem xWIdeal_le_xPrime : xWIdeal ≤ xPrime := by
  rw [xWIdeal, Ideal.span_le]
  intro z hz
  simp only [Set.mem_singleton_iff] at hz
  subst z
  exact RingHom.mem_ker.mpr xChartEval_xW

private noncomputable def xBoundaryQuot : XChartRing →ₐ[k₂] XBoundaryRing :=
  Ideal.Quotient.mkₐ k₂ xWIdeal

private def xBarPrime : Ideal XBoundaryRing :=
  xPrime.map (Ideal.Quotient.mk xWIdeal)

private noncomputable def xBoundaryEval : XBoundaryRing →ₐ[k₂] k₂ :=
  Ideal.Quotient.liftₐ xWIdeal xChartEval
    (fun _ ha => RingHom.mem_ker.mp (xWIdeal_le_xPrime ha))

private theorem xBoundaryEval_surjective : Function.Surjective xBoundaryEval := by
  intro c
  obtain ⟨a, ha⟩ := xChartEval_surjective c
  refine ⟨Ideal.Quotient.mk xWIdeal a, ?_⟩
  change xChartEval a = c
  exact ha

private theorem xBoundaryEval_ker :
    RingHom.ker xBoundaryEval.toRingHom = xBarPrime := by
  change RingHom.ker
      (Ideal.Quotient.lift xWIdeal xChartEval.toRingHom _) =
    xPrime.map (Ideal.Quotient.mk xWIdeal)
  rw [Ideal.ker_quotient_lift]
  rfl

private theorem xBarPrime_isMaximal : xBarPrime.IsMaximal := by
  rw [← xBoundaryEval_ker]
  exact RingHom.ker_isMaximal_of_surjective
    xBoundaryEval.toRingHom xBoundaryEval_surjective

private theorem triplePolynomialIdeal_le_evalKer :
    Ideal.span {(Polynomial.X : k₂[X]) ^ 3} ≤
      RingHom.ker (Polynomial.evalRingHom 0) := by
  refine Ideal.span_le.2 ?_
  intro p hp
  simp only [Set.mem_singleton_iff] at hp
  subst p
  simp [RingHom.mem_ker]

private noncomputable def tripleResidue : TripleArtin →+* k₂ :=
  Ideal.Quotient.lift
    (Ideal.span {(Polynomial.X : k₂[X]) ^ 3})
    (Polynomial.evalRingHom 0)
    (fun _ hp => RingHom.mem_ker.mp (triplePolynomialIdeal_le_evalKer hp))

private theorem tripleResidue_surjective : Function.Surjective tripleResidue := by
  intro c
  refine ⟨Ideal.Quotient.mk _ (Polynomial.C c), ?_⟩
  change Polynomial.eval 0 (Polynomial.C c) = c
  simp

private theorem tripleResidue_ker :
    RingHom.ker tripleResidue = Ideal.span {tripleRoot} := by
  change RingHom.ker
    (Ideal.Quotient.lift
      (Ideal.span {(Polynomial.X : k₂[X]) ^ 3})
      (Polynomial.evalRingHom 0) _) = _
  rw [Ideal.ker_quotient_lift, Polynomial.ker_evalRingHom]
  simp only [Ideal.map_span, Set.image_singleton]
  simp [tripleRoot, AdjoinRoot.root, AdjoinRoot.mk]
  rfl

private theorem tripleRootIdeal_isMaximal :
    (Ideal.span {tripleRoot} : Ideal TripleArtin).IsMaximal := by
  rw [← tripleResidue_ker]
  exact RingHom.ker_isMaximal_of_surjective
    tripleResidue tripleResidue_surjective

private theorem tripleRootIdeal_isNilpotent
    {z : TripleArtin} (hz : z ∈ Ideal.span {tripleRoot}) : IsNilpotent z := by
  rw [Ideal.mem_span_singleton] at hz
  rcases hz with ⟨a, rfl⟩
  refine ⟨3, ?_⟩
  rw [mul_pow, tripleRoot_cube, zero_mul]

private theorem xBarPrime_isNilpotent
    {z : XBoundaryRing} (hz : z ∈ xBarPrime) : IsNilpotent z := by
  let J : Ideal TripleArtin :=
    xBarPrime.map xBoundaryAlgEquivTripleArtin.toRingEquiv.toRingHom
  letI : xBarPrime.IsMaximal := xBarPrime_isMaximal
  haveI : J.IsMaximal := by
    dsimp [J]
    exact Ideal.map_isMaximal_of_equiv
      xBoundaryAlgEquivTripleArtin.toRingEquiv
  letI : J.IsPrime := (inferInstance : J.IsMaximal).isPrime
  have hroot : tripleRoot ∈ J := by
    apply (inferInstance : J.IsPrime).mem_of_pow_mem 3
    rw [tripleRoot_cube]
    exact J.zero_mem
  have hle : Ideal.span {tripleRoot} ≤ J := by
    rw [Ideal.span_le]
    simpa using hroot
  have hEq : (Ideal.span {tripleRoot} : Ideal TripleArtin) = J :=
    tripleRootIdeal_isMaximal.eq_of_le
      (inferInstance : J.IsMaximal).ne_top hle
  have hzJ : xBoundaryAlgEquivTripleArtin z ∈ J :=
    Ideal.mem_map_of_mem xBoundaryAlgEquivTripleArtin.toRingEquiv.toRingHom hz
  have hzRoot : xBoundaryAlgEquivTripleArtin z ∈
      (Ideal.span {tripleRoot} : Ideal TripleArtin) := by
    rw [hEq]
    exact hzJ
  rcases tripleRootIdeal_isNilpotent hzRoot with ⟨n, hn⟩
  refine ⟨n, ?_⟩
  apply xBoundaryAlgEquivTripleArtin.injective
  simpa using hn

private theorem xBoundaryQuot_isUnit_of_primeCompl (s : xPrime.primeCompl) :
    IsUnit (xBoundaryQuot (s : XChartRing)) := by
  have hsnot : (s : XChartRing) ∉ xPrime :=
    Ideal.mem_primeCompl_iff.mp s.2
  have hres_ne : xChartEval (s : XChartRing) ≠ 0 := by
    intro hzero
    exact hsnot (RingHom.mem_ker.mpr hzero)
  let u : XBoundaryRing := xBoundaryQuot
    (algebraMap k₂ XChartRing (xChartEval (s : XChartRing)))
  have hu : IsUnit u :=
    (isUnit_iff_ne_zero.mpr hres_ne).map
      (xBoundaryQuot.toRingHom.comp
        (algebraMap k₂ XChartRing : k₂ →+* XChartRing))
  have hdiff_mem : xBoundaryQuot (s : XChartRing) - u ∈ xBarPrime := by
    rw [← xBoundaryEval_ker, RingHom.mem_ker]
    change xBoundaryEval (xBoundaryQuot (s : XChartRing) - u) = 0
    rw [map_sub]
    change xChartEval (s : XChartRing) -
      xChartEval (algebraMap k₂ XChartRing
        (xChartEval (s : XChartRing))) = 0
    rw [xChartEval.commutes]
    exact sub_self _
  have hnil : IsNilpotent (xBoundaryQuot (s : XChartRing) - u) :=
    xBarPrime_isNilpotent hdiff_mem
  have hunit : IsUnit (u + (xBoundaryQuot (s : XChartRing) - u)) :=
    hnil.isUnit_add_left_of_commute hu
      (Commute.all (xBoundaryQuot (s : XChartRing) - u) u)
  convert hunit using 1
  ring

/-- The local ring of the actual `X` chart at `[1:0:0:0]`. -/
abbrev XLocalRing := Localization.AtPrime xPrime

local instance xLocalRingCommRing : CommRing XLocalRing :=
  OreLocalization.instCommRing

private noncomputable def xLocalToBoundary : XLocalRing →ₐ[k₂] XBoundaryRing :=
  IsLocalization.liftAlgHom
    (A := k₂) (R := XChartRing) (S := XLocalRing)
    (P := XBoundaryRing) (f := xBoundaryQuot)
    xBoundaryQuot_isUnit_of_primeCompl

private theorem xLocalToBoundary_surjective :
    Function.Surjective xLocalToBoundary := by
  intro z
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mkₐ_surjective k₂ xWIdeal z
  refine ⟨algebraMap XChartRing XLocalRing a, ?_⟩
  simp [xLocalToBoundary, xBoundaryQuot]

/-- The kernel of a localization lift is the extension of the original
kernel when every denominator maps to a unit. -/
theorem ker_liftAlgHom_eq_map
    {A R S B : Type*}
    [CommRing A] [CommRing R] [CommRing S] [CommRing B]
    [Algebra A R] [Algebra A S] [Algebra A B]
    [Algebra R S] [IsScalarTower A R S]
    (M : Submonoid R) [IsLocalization M S]
    (f : R →ₐ[A] B)
    (hf : ∀ m : M, IsUnit (f m)) :
    RingHom.ker
        (IsLocalization.liftAlgHom (S := S) (f := f) hf).toRingHom =
      (RingHom.ker f.toRingHom).map (algebraMap R S) := by
  ext z
  obtain ⟨r, m, rfl⟩ := IsLocalization.exists_mk'_eq M z
  constructor
  · intro hz
    rw [RingHom.mem_ker] at hz
    change IsLocalization.lift
      (g := f.toRingHom) hf (IsLocalization.mk' S r m) = 0 at hz
    have hr : f r = 0 := by
      have h := (IsLocalization.lift_mk'_spec
        (S := S) (g := f.toRingHom) hf r 0 m).1 hz
      simpa using h
    rw [IsLocalization.mk'_mem_map_algebraMap_iff]
    exact ⟨1, M.one_mem, by
      rw [RingHom.mem_ker]
      simpa using hr⟩
  · intro hz
    rw [IsLocalization.mk'_mem_map_algebraMap_iff] at hz
    rcases hz with ⟨s, hsM, hsr⟩
    have hsr0 : f (s * r) = 0 := RingHom.mem_ker.mp hsr
    have hmul : f r * f s = 0 := by simpa [mul_comm] using hsr0
    have hr : f r = 0 :=
      (IsUnit.mul_left_eq_zero (hf ⟨s, hsM⟩)).1 hmul
    rw [RingHom.mem_ker]
    change IsLocalization.lift
      (g := f.toRingHom) hf (IsLocalization.mk' S r m) = 0
    apply (IsLocalization.lift_mk'_spec
      (S := S) (g := f.toRingHom) hf r 0 m).2
    simp [hr]

private theorem xLocalToBoundary_ker :
    RingHom.ker xLocalToBoundary.toRingHom =
      xWIdeal.map (algebraMap XChartRing XLocalRing) := by
  have h := ker_liftAlgHom_eq_map
    (A := k₂) (R := XChartRing) (B := XBoundaryRing)
    (M := xPrime.primeCompl) (S := XLocalRing)
    (f := xBoundaryQuot) xBoundaryQuot_isUnit_of_primeCompl
  have hker : RingHom.ker xBoundaryQuot.toRingHom = xWIdeal := by
    change RingHom.ker
      (Ideal.Quotient.mkₐ k₂ xWIdeal : XChartRing →ₐ[k₂] XBoundaryRing).toRingHom =
        xWIdeal
    exact Ideal.Quotient.mkₐ_ker (R₁ := k₂) xWIdeal
  rw [hker] at h
  exact h

/-- The germ of `W/X` in the local curve ring. -/
noncomputable def xWGerm : XLocalRing :=
  algebraMap XChartRing XLocalRing xW

/-- The principal ideal generated by the germ of `W/X`. -/
def xWGermIdeal : Ideal XLocalRing := Ideal.span {xWGerm}

private theorem xWGermIdeal_eq_map :
    xWGermIdeal = xWIdeal.map (algebraMap XChartRing XLocalRing) := by
  rw [xWGermIdeal, xWIdeal, Ideal.map_span]
  simp [xWGerm]

/-- The local quotient by the germ of `W/X` is `F₂[t]/(t³)`. -/
noncomputable def xLocalBoundaryAlgEquivTripleArtin :
    (XLocalRing ⧸ xWGermIdeal) ≃ₐ[k₂] TripleArtin :=
  (Ideal.quotientEquivAlgOfEq k₂
      (xWGermIdeal_eq_map.trans xLocalToBoundary_ker.symm)).trans
    ((Ideal.quotientKerAlgEquivOfSurjective
      xLocalToBoundary_surjective).trans xBoundaryAlgEquivTripleArtin)

/-- The local intersection quotient by `W/X` has `F₂`-length three. -/
theorem xLocalBoundary_f2_length :
    Module.length k₂ (XLocalRing ⧸ xWGermIdeal) = 3 := by
  rw [xLocalBoundaryAlgEquivTripleArtin.toLinearEquiv.length_eq]
  letI : Module.Finite k₂ TripleArtin :=
    (Polynomial.monic_X_pow 3).finite_adjoinRoot
  rw [Module.length_eq_finrank, tripleArtin_finrank]
  norm_num

private noncomputable def xPrimeQuotientAlgEquivF2 :
    (XChartRing ⧸ xPrime) ≃ₐ[k₂] k₂ := by
  change (XChartRing ⧸ RingHom.ker xChartEval.toRingHom) ≃ₐ[k₂] k₂
  exact Ideal.quotientKerAlgEquivOfSurjective xChartEval_surjective

private noncomputable def xPrimeLocalResidueAlgEquiv :
    (XChartRing ⧸ xPrime) ≃ₐ[k₂] IsLocalRing.ResidueField XLocalRing := by
  let e := IsLocalization.AtPrime.equivQuotMaximalIdeal xPrime XLocalRing
  exact
    { e with
      commutes' := by
        intro c
        change e (Ideal.Quotient.mk xPrime
          (algebraMap k₂ XChartRing c)) =
            Ideal.Quotient.mk (IsLocalRing.maximalIdeal XLocalRing)
              (algebraMap k₂ XLocalRing c)
        rw [IsLocalization.AtPrime.equivQuotMaximalIdeal_apply_mk]
        rfl }

private noncomputable def xLocalResidueAlgEquivF2 :
    IsLocalRing.ResidueField XLocalRing ≃ₐ[k₂] k₂ :=
  xPrimeLocalResidueAlgEquiv.symm.trans xPrimeQuotientAlgEquivF2

private theorem xLocalResidue_algebraMap_surjective :
    Function.Surjective
      (algebraMap k₂ (IsLocalRing.ResidueField XLocalRing)) := by
  intro y
  refine ⟨xLocalResidueAlgEquivF2 y, ?_⟩
  apply xLocalResidueAlgEquivF2.injective
  simp

private theorem xResidueExtension_algebraMap_surjective :
    Function.Surjective
      (algebraMap (IsLocalRing.ResidueField k₂)
        (IsLocalRing.ResidueField XLocalRing)) := by
  intro y
  obtain ⟨c, rfl⟩ := xLocalResidue_algebraMap_surjective y
  refine ⟨algebraMap k₂ (IsLocalRing.ResidueField k₂) c, ?_⟩
  exact IsScalarTower.algebraMap_apply k₂
    (IsLocalRing.ResidueField k₂)
    (IsLocalRing.ResidueField XLocalRing) c

private theorem xResidueExtension_length_one :
    Module.length (IsLocalRing.ResidueField k₂)
      (IsLocalRing.ResidueField XLocalRing) = 1 := by
  let e : IsLocalRing.ResidueField k₂ ≃ₐ[IsLocalRing.ResidueField k₂]
      IsLocalRing.ResidueField XLocalRing :=
    AlgEquiv.ofBijective (Algebra.ofId _ _)
      ⟨RingHom.injective _, xResidueExtension_algebraMap_surjective⟩
  exact e.toLinearEquiv.length_eq.symm.trans (Module.length_eq_one _ _)

/-- The quotient by the germ of `W/X` has local-ring length three. -/
theorem xLocalBoundary_local_length :
    Module.length XLocalRing (XLocalRing ⧸ xWGermIdeal) = 3 := by
  have h := IsLocalRing.length_restrictScalars
    k₂ XLocalRing (XLocalRing ⧸ xWGermIdeal)
  rw [xResidueExtension_length_one, mul_one] at h
  exact h.symm.trans xLocalBoundary_f2_length

/-- The order of vanishing of the hyperplane section `W` at
`[1:0:0:0]` is three. -/
theorem xWGerm_ord_eq_three : Ring.ord XLocalRing xWGerm = 3 := by
  unfold Ring.ord
  change Module.length XLocalRing (XLocalRing ⧸ xWGermIdeal) = 3
  exact xLocalBoundary_local_length

end MazurProof.RationalPointsN25QuotientTwoWBoundaryXLocal
