import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoRegularSequence
import Mathlib.Tactic

/-!
# The Koszul resolution of the N25 binary canonical cone

The proved regular sequence gives more than a codimension label.  This file
constructs the two-equation Koszul maps explicitly and proves exactness at
both nontrivial terms.  The resulting resolution is the algebraic source of
the four shifts in the complete-intersection Hilbert numerator.
-/

noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoKoszul

open MazurProof.RationalPointsN25QuotientTwoConormal
open MazurProof.RationalPointsN25QuotientTwoRegularSequence

/-- The four-variable binary homogeneous coordinate ring. -/
abbrev R := BinaryHomogeneousRing

/-- The left Koszul map sends `r` to `(C*r,-Q*r)`. -/
def koszulTop : R →ₗ[R] R × R :=
  (LinearMap.lsmul R R canonicalCubicPolynomial25Two).prod
    (-(LinearMap.lsmul R R canonicalQuadricPolynomial25Two))

/-- The middle Koszul map sends `(a,b)` to `Q*a+C*b`. -/
def koszulMiddle : R × R →ₗ[R] R :=
  (LinearMap.lsmul R R canonicalQuadricPolynomial25Two).coprod
    (LinearMap.lsmul R R canonicalCubicPolynomial25Two)

/-- The right map is the canonical projection to the quadric-cubic quotient. -/
def canonicalConeProjection : R →ₗ[R] CanonicalConeRing25Two :=
  (Ideal.Quotient.mkₐ R canonicalCurveIdeal25Two).toLinearMap

/-- The first Koszul differential has the advertised coordinate formula. -/
@[simp]
theorem koszulTop_apply (r : R) :
    koszulTop r =
      (canonicalCubicPolynomial25Two * r,
        -(canonicalQuadricPolynomial25Two * r)) := by
  rfl

/-- The second Koszul differential is the defining linear combination of the
quadric and cubic. -/
@[simp]
theorem koszulMiddle_apply (p : R × R) :
    koszulMiddle p =
      canonicalQuadricPolynomial25Two * p.1 +
        canonicalCubicPolynomial25Two * p.2 := by
  rfl

/-- The rightmost differential is the quotient map modulo the curve ideal. -/
@[simp]
theorem canonicalConeProjection_apply (r : R) :
    canonicalConeProjection r =
      Ideal.Quotient.mk canonicalCurveIdeal25Two r := by
  rfl

/-- The first Koszul map is injective because the quadric is a non-zero
divisor in the ambient polynomial ring. -/
theorem koszulTop_injective : Function.Injective koszulTop := by
  intro a b hab
  have hsecond := congrArg Prod.snd hab
  simp only [koszulTop_apply] at hsecond
  have hquadric : canonicalQuadricPolynomial25Two * (a - b) = 0 := by
    rw [mul_sub]
    linear_combination -hsecond
  have habZero :=
    canonicalQuadricPolynomial25Two_isSMulRegular.right_eq_zero_of_smul
      (by simpa [smul_eq_mul] using hquadric)
  exact sub_eq_zero.mp habZero

/-- The two explicit Koszul maps compose to zero. -/
theorem koszulMiddle_comp_koszulTop :
    koszulMiddle.comp koszulTop = 0 := by
  apply LinearMap.ext
  intro r
  simp only [LinearMap.comp_apply, koszulMiddle_apply, koszulTop_apply,
    LinearMap.zero_apply]
  ring

/-- Exactness at `R²`: every syzygy between `Q` and `C` is the standard
Koszul syzygy because `C` is a non-zero divisor modulo `Q`. -/
theorem koszul_exact_top_middle :
    Function.Exact koszulTop koszulMiddle := by
  intro p
  constructor
  · intro hp
    have hCmem : canonicalCubicPolynomial25Two * p.2 ∈
        Ideal.span {canonicalQuadricPolynomial25Two} :=
      Ideal.mem_span_singleton.mpr ⟨-p.1, by
        simp only [koszulMiddle_apply] at hp
        linear_combination hp⟩
    have hp2mem := mem_quadricIdeal_of_cubic_mul_mem p.2 hCmem
    rcases Ideal.mem_span_singleton.mp hp2mem with ⟨s, hs⟩
    refine ⟨-s, ?_⟩
    apply Prod.ext
    · rw [koszulTop_apply]
      dsimp only [Prod.fst]
      have hquadric :
          canonicalQuadricPolynomial25Two *
              (p.1 + s * canonicalCubicPolynomial25Two) = 0 := by
        simp only [koszulMiddle_apply] at hp
        rw [hs] at hp
        linear_combination hp
      have hzero :=
        canonicalQuadricPolynomial25Two_isSMulRegular.right_eq_zero_of_smul
          (by simpa [smul_eq_mul] using hquadric)
      rw [mul_neg]
      linear_combination -hzero
    · rw [koszulTop_apply]
      dsimp only [Prod.snd]
      rw [hs]
      ring
  · rintro ⟨r, rfl⟩
    simp only [koszulMiddle_apply, koszulTop_apply]
    ring

/-- The range of the middle Koszul map is the ideal generated by the two
canonical equations. -/
theorem koszulMiddle_range_eq_curveIdeal :
    LinearMap.range koszulMiddle = canonicalCurveIdeal25Two := by
  ext p
  constructor
  · rintro ⟨⟨a, b⟩, rfl⟩
    refine Ideal.mem_span_pair.mpr ⟨a, b, ?_⟩
    rw [koszulMiddle_apply]
    ring
  · intro hp
    rcases Ideal.mem_span_pair.mp hp with ⟨a, b, hab⟩
    exact ⟨(a, b), by simpa only [koszulMiddle_apply, mul_comm] using hab⟩

/-- Exactness at the ambient ring identifies the cokernel of the middle
Koszul map with the canonical cone quotient. -/
theorem koszul_exact_middle_projection :
    Function.Exact koszulMiddle canonicalConeProjection := by
  rw [LinearMap.exact_iff]
  rw [show LinearMap.ker canonicalConeProjection = canonicalCurveIdeal25Two by
    change RingHom.ker (Ideal.Quotient.mk canonicalCurveIdeal25Two) = _
    exact Ideal.mk_ker]
  exact koszulMiddle_range_eq_curveIdeal.symm

/-- The canonical projection is surjective, completing the right end of the
Koszul resolution. -/
theorem canonicalConeProjection_surjective :
    Function.Surjective canonicalConeProjection :=
  Ideal.Quotient.mk_surjective

end MazurProof.RationalPointsN25QuotientTwoKoszul
