import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoClosedPointEvaluation
import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoWBoundaryClosedPoints

/-!
# The actual Y-chart boundary quotient at W = 0

The standard `Y != 0` chart contains only the boundary point
`[0:1:1:0]`.  After quotienting the actual curve chart ring by `W/Y`, the
quadric and cubic relations force `Z/Y = 1` and `X/Y = 0`.  Thus the boundary
quotient is exactly the binary ground field.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false
noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoWBoundaryYZChartArtin

open RationalPointsN25QuotientF2
open RationalPointsN25QuotientSmoothF2
open RationalPointsN25QuotientWeil
open RationalPointsN25QuotientTwoAffineCharts
open RationalPointsN25QuotientTwoAffineChartsSmooth
open RationalPointsN25QuotientTwoCanonicalDivisor
open RationalPointsN25QuotientTwoClosedPointEvaluation
open RationalPointsN25QuotientTwoConormal
open RationalPointsN25QuotientTwoStructuralJacobian

local notation "k₂" => ZMod 2

/-- The actual curve coordinate ring on the standard projective `Y` chart. -/
abbrev YChartRing := ChartQuotient (1 : Fin 4)

private def yX : YChartRing := chartMap 1 (MvPolynomial.X 0)
private def yZ : YChartRing := chartMap 1 (MvPolynomial.X 2)
/-- The restriction `W/Y` of the homogeneous coordinate `W`. -/
def yzW : YChartRing := chartMap 1 (MvPolynomial.X 3)

/-- The principal boundary ideal generated by `W/Y`. -/
def yzWIdeal : Ideal YChartRing := Ideal.span {yzW}

/-- The actual `Y`-chart curve ring cut by `W = 0`. -/
abbrev YZBoundaryRing := YChartRing ⧸ yzWIdeal

private def qX : YZBoundaryRing := Ideal.Quotient.mk yzWIdeal yX
private def qZ : YZBoundaryRing := Ideal.Quotient.mk yzWIdeal yZ
private def qW : YZBoundaryRing := Ideal.Quotient.mk yzWIdeal yzW

private theorem qW_eq_zero : qW = 0 := by
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  exact Ideal.subset_span (Set.mem_singleton yzW)

private theorem y_quadric_relation :
    yX * yZ + yX * yzW + 1 + yZ + yZ * yzW = 0 := by
  have h := chartQuotientPoint_quadric (1 : Fin 4)
  simpa [canonicalQuadric25CharTwo, chartQuotientPoint,
    mappedAmbientPoint, yX, yZ, yzW, chartMap_X_pivot] using h

private theorem y_cubic_relation :
    yX ^ 2 * yzW + yX * yZ + yX * yzW + yX * yZ * yzW +
      yZ * yzW + yZ ^ 2 * yzW + yZ * yzW ^ 2 = 0 := by
  have h := chartQuotientPoint_cubic (1 : Fin 4)
  simpa [canonicalCubic25CharTwo, chartQuotientPoint,
    mappedAmbientPoint, yX, yZ, yzW, chartMap_X_pivot] using h

private theorem q_quadric_relation : qX * qZ + 1 + qZ = 0 := by
  have h := congrArg (Ideal.Quotient.mk yzWIdeal) y_quadric_relation
  change qX * qZ + qX * qW + 1 + qZ + qZ * qW = 0 at h
  rw [qW_eq_zero] at h
  linear_combination h

private theorem q_cubic_relation : qX * qZ = 0 := by
  have h := congrArg (Ideal.Quotient.mk yzWIdeal) y_cubic_relation
  change qX ^ 2 * qW + qX * qZ + qX * qW + qX * qZ * qW +
    qZ * qW + qZ ^ 2 * qW + qZ * qW ^ 2 = 0 at h
  rw [qW_eq_zero] at h
  linear_combination h

private theorem qZ_eq_one : qZ = 1 := by
  have h : 1 + qZ = 0 := by
    linear_combination q_quadric_relation - q_cubic_relation
  have htwoCoeff : (2 : k₂) = 0 := CharP.cast_eq_zero k₂ 2
  have htwoAffine : (2 : AffineChart (1 : Fin 4)) = 0 := by
    change MvPolynomial.C (2 : k₂) = 0
    rw [htwoCoeff, map_zero]
  have htwoChart : (2 : YChartRing) = 0 := by
    change Ideal.Quotient.mk (chartAffineEquationIdeal 1)
      (2 : AffineChart (1 : Fin 4)) = 0
    rw [htwoAffine, map_zero]
  have htwo : (2 : YZBoundaryRing) = 0 := by
    change Ideal.Quotient.mk yzWIdeal (2 : YChartRing) = 0
    rw [htwoChart, map_zero]
  linear_combination h - htwo

private theorem qX_eq_zero : qX = 0 := by
  have h := q_cubic_relation
  rw [qZ_eq_one] at h
  linear_combination h

private def yzChartPoint : CurvePointOnChart (1 : Fin 4) k₂ :=
  ⟨hyperplanePointYZ, rfl⟩

private noncomputable def yzChartEval : YChartRing →ₐ[k₂] k₂ :=
  chartQuotientEvalAlgHom 1 yzChartPoint

@[simp]
private theorem yzChartEval_yX : yzChartEval yX = 0 := by
  rw [yzChartEval, yX, chartMap]
  change chartPointAffineEval 1 yzChartPoint
    (ambientDehomogenize 1 (MvPolynomial.X 0)) = 0
  simp [ambientDehomogenize, dehomogenizedVariable, chartPointAffineEval,
    yzChartPoint, hyperplanePointYZ, coordinates4ToFun,
    normalizedCoordinates25, NormalizedProjective4.coordinates,
    fieldBinaryOperations]

@[simp]
private theorem yzChartEval_yZ : yzChartEval yZ = 1 := by
  rw [yzChartEval, yZ, chartMap]
  change chartPointAffineEval 1 yzChartPoint
    (ambientDehomogenize 1 (MvPolynomial.X 2)) = 1
  simp [ambientDehomogenize, dehomogenizedVariable, chartPointAffineEval,
    yzChartPoint, hyperplanePointYZ, coordinates4ToFun,
    normalizedCoordinates25, NormalizedProjective4.coordinates,
    fieldBinaryOperations]

@[simp]
private theorem yzChartEval_yW : yzChartEval yzW = 0 := by
  rw [yzChartEval, yzW, chartMap]
  change chartPointAffineEval 1 yzChartPoint
    (ambientDehomogenize 1 (MvPolynomial.X 3)) = 0
  simp [ambientDehomogenize, dehomogenizedVariable, chartPointAffineEval,
    yzChartPoint, hyperplanePointYZ, coordinates4ToFun,
    normalizedCoordinates25, NormalizedProjective4.coordinates,
    fieldBinaryOperations]

private theorem yzWIdeal_le_evalKer :
    yzWIdeal ≤ RingHom.ker yzChartEval.toRingHom := by
  refine Ideal.span_le.2 ?_
  intro z hz
  simp only [Set.mem_singleton_iff] at hz
  subst z
  exact RingHom.mem_ker.mpr yzChartEval_yW

private noncomputable def yzBoundaryToF2 : YZBoundaryRing →ₐ[k₂] k₂ :=
  Ideal.Quotient.liftₐ yzWIdeal yzChartEval
    (fun _ hz => RingHom.mem_ker.mp (yzWIdeal_le_evalKer hz))

@[simp]
private theorem yzBoundaryToF2_qX : yzBoundaryToF2 qX = 0 := by
  simp [yzBoundaryToF2, qX]

@[simp]
private theorem yzBoundaryToF2_qZ : yzBoundaryToF2 qZ = 1 := by
  simp [yzBoundaryToF2, qZ]

@[simp]
private theorem yzBoundaryToF2_qW : yzBoundaryToF2 qW = 0 := by
  simp [yzBoundaryToF2, qW]

private noncomputable def f2ToYZBoundary : k₂ →ₐ[k₂] YZBoundaryRing :=
  Algebra.ofId k₂ YZBoundaryRing

private theorem yzBoundaryToF2_comp_f2ToYZBoundary :
    yzBoundaryToF2.comp f2ToYZBoundary = AlgHom.id k₂ k₂ := by
  ext

private theorem otherCoordinate_one_cases (j : OtherCoordinate (1 : Fin 4)) :
    j = ⟨0, by decide⟩ ∨ j = ⟨2, by decide⟩ ∨
      j = ⟨3, by decide⟩ := by
  rcases j with ⟨j, hj⟩
  fin_cases j
  · exact Or.inl (Subtype.ext rfl)
  · exact (hj rfl).elim
  · exact Or.inr (Or.inl (Subtype.ext rfl))
  · exact Or.inr (Or.inr (Subtype.ext rfl))

private theorem f2ToYZBoundary_comp_yzBoundaryToF2 :
    f2ToYZBoundary.comp yzBoundaryToF2 =
      AlgHom.id k₂ YZBoundaryRing := by
  apply Ideal.Quotient.algHom_ext
  apply Ideal.Quotient.algHom_ext
  ext j
  rcases otherCoordinate_one_cases j with rfl | rfl | rfl
  · simp only [AlgHom.comp_apply, AlgHom.id_apply]
    have hgen :
        (Ideal.Quotient.mkₐ k₂ yzWIdeal)
            ((Ideal.Quotient.mkₐ k₂ (chartAffineEquationIdeal 1))
              (MvPolynomial.X (⟨0, by decide⟩ : OtherCoordinate 1))) = qX := by
      simp [qX, yX, chartMap, ambientDehomogenize,
        dehomogenizedVariable]
    rw [hgen, yzBoundaryToF2_qX, map_zero, qX_eq_zero]
  · simp only [AlgHom.comp_apply, AlgHom.id_apply]
    have hgen :
        (Ideal.Quotient.mkₐ k₂ yzWIdeal)
            ((Ideal.Quotient.mkₐ k₂ (chartAffineEquationIdeal 1))
              (MvPolynomial.X (⟨2, by decide⟩ : OtherCoordinate 1))) = qZ := by
      simp [qZ, yZ, chartMap, ambientDehomogenize,
        dehomogenizedVariable]
    rw [hgen, yzBoundaryToF2_qZ, map_one, qZ_eq_one]
  · simp only [AlgHom.comp_apply, AlgHom.id_apply]
    have hgen :
        (Ideal.Quotient.mkₐ k₂ yzWIdeal)
            ((Ideal.Quotient.mkₐ k₂ (chartAffineEquationIdeal 1))
              (MvPolynomial.X (⟨3, by decide⟩ : OtherCoordinate 1))) = qW := by
      simp [qW, yzW, chartMap, ambientDehomogenize,
        dehomogenizedVariable]
    rw [hgen, yzBoundaryToF2_qW, map_zero, qW_eq_zero]

/-- The actual `Y`-chart curve quotient by `W/Y` is the ground field. -/
noncomputable def yzBoundaryAlgEquivF2 : YZBoundaryRing ≃ₐ[k₂] k₂ :=
  AlgEquiv.ofAlgHom yzBoundaryToF2 f2ToYZBoundary
    yzBoundaryToF2_comp_f2ToYZBoundary
    f2ToYZBoundary_comp_yzBoundaryToF2

/-- The actual `Y`-chart boundary quotient has `F₂`-length one. -/
theorem yzBoundaryRing_f2_length :
    Module.length k₂ YZBoundaryRing = 1 := by
  rw [yzBoundaryAlgEquivF2.toLinearEquiv.length_eq]
  exact Module.length_eq_one _ _

end MazurProof.RationalPointsN25QuotientTwoWBoundaryYZChartArtin
