import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoProper

/-!
# Local equations on the N25 projective coordinate charts

On the standard chart where the coordinate `X i` is invertible, the degree-two
and degree-three equations become the degree-zero fractions `Q/(X i)^2` and
`C/(X i)^3`.  This module places those two elements in Mathlib's homogeneous
`Away` ring and proves that they generate the kernel of the affine chart map.
The proof first lifts a vanishing fraction to a saturated homogeneous Koszul
relation and then cancels the inverted chart coordinate inside localization.
-/

noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoChartIdeal

open RationalPointsN25QuotientTwoConormal
open RationalPointsN25QuotientTwoGradedKoszul
open RationalPointsN25QuotientTwoQuotientGrading
open HomogeneousLocalization

attribute [local instance] MvPolynomial.gradedAlgebra

/-- The standard total-degree pieces of the four-variable polynomial ring. -/
abbrev standardConePiece :=
  MvPolynomial.homogeneousSubmodule (Fin 4) k

/-- Every projective coordinate has degree one. -/
theorem coordinate_isHomogeneous (i : Fin 4) :
    MvPolynomial.X i ∈ standardConePiece 1 :=
  MvPolynomial.isHomogeneous_X k i

/-- The quadric dehomogenized on the coordinate chart `D₊(X i)`. -/
def dehomogenizedQuadric (i : Fin 4) :
    Away standardConePiece (MvPolynomial.X i) :=
  Away.mk standardConePiece (coordinate_isHomogeneous i) 2
    canonicalQuadricPolynomial25Two (by
      simpa using canonicalQuadricPolynomial25Two_isHomogeneous)

/-- The cubic dehomogenized on the coordinate chart `D₊(X i)`. -/
def dehomogenizedCubic (i : Fin 4) :
    Away standardConePiece (MvPolynomial.X i) :=
  Away.mk standardConePiece (coordinate_isHomogeneous i) 3
    canonicalCubicPolynomial25Two (by
      simpa using canonicalCubicPolynomial25Two_isHomogeneous)

/-- The affine ring map on the coordinate chart induced by the homogeneous
coordinate quotient. -/
def canonicalConeChartMap (i : Fin 4) :
    Away standardConePiece (MvPolynomial.X i) →+*
      Away literalConePiece
        (canonicalConeGradedProjection (MvPolynomial.X i)) :=
  Away.map canonicalConeGradedProjection (MvPolynomial.X i)

/-- The defining quadric vanishes in the homogeneous coordinate quotient. -/
theorem canonicalConeGradedProjection_quadric_eq_zero :
    canonicalConeGradedProjection canonicalQuadricPolynomial25Two = 0 := by
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  apply Ideal.subset_span
  simp

/-- The defining cubic vanishes in the homogeneous coordinate quotient. -/
theorem canonicalConeGradedProjection_cubic_eq_zero :
    canonicalConeGradedProjection canonicalCubicPolynomial25Two = 0 := by
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  apply Ideal.subset_span
  simp

/-- The dehomogenized quadric lies in the kernel of every coordinate-chart
ring map. -/
theorem canonicalConeChartMap_dehomogenizedQuadric_eq_zero (i : Fin 4) :
    canonicalConeChartMap i (dehomogenizedQuadric i) = 0 := by
  rw [canonicalConeChartMap, dehomogenizedQuadric, Away.map_mk]
  apply HomogeneousLocalization.val_injective
  simp only [Away.val_mk, HomogeneousLocalization.val_zero]
  rw [canonicalConeGradedProjection_quadric_eq_zero]
  exact (Localization.mkAddMonoidHom _).map_zero

/-- The dehomogenized cubic lies in the kernel of every coordinate-chart
ring map. -/
theorem canonicalConeChartMap_dehomogenizedCubic_eq_zero (i : Fin 4) :
    canonicalConeChartMap i (dehomogenizedCubic i) = 0 := by
  rw [canonicalConeChartMap, dehomogenizedCubic, Away.map_mk]
  apply HomogeneousLocalization.val_injective
  simp only [Away.val_mk, HomogeneousLocalization.val_zero]
  rw [canonicalConeGradedProjection_cubic_eq_zero]
  exact (Localization.mkAddMonoidHom _).map_zero

/-- The ideal generated by the dehomogenized quadric and cubic is contained
in the kernel of the affine coordinate-chart map. -/
theorem chartEquationIdeal_le_kernel (i : Fin 4) :
    Ideal.span ({dehomogenizedQuadric i, dehomogenizedCubic i} :
      Set (Away standardConePiece (MvPolynomial.X i))) ≤
        RingHom.ker (canonicalConeChartMap i) := by
  rw [Ideal.span_le]
  intro z hz
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
  rcases hz with rfl | rfl
  · exact canonicalConeChartMap_dehomogenizedQuadric_eq_zero i
  · exact canonicalConeChartMap_dehomogenizedCubic_eq_zero i

/-- A chart-kernel element admits a homogeneous numerator whose product by a
power of the chart coordinate is a Koszul relation.  This is the saturation
phenomenon hidden in localization: a fraction can vanish after quotienting
even when its original numerator does not yet lie in the defining ideal. -/
theorem chartKernel_has_saturated_koszul_relation (i : Fin 4)
    (z : Away standardConePiece (MvPolynomial.X i))
    (hz : z ∈ RingHom.ker (canonicalConeChartMap i)) :
    ∃ (n m : ℕ) (p : S) (hp : p ∈ standardConePiece n)
        (a : shiftedPiece 2 (m + n)) (b : shiftedPiece 3 (m + n)),
      z = Away.mk standardConePiece (coordinate_isHomogeneous i) n p (by
        simpa using hp) ∧
      MvPolynomial.X i ^ m * p =
        canonicalQuadricPolynomial25Two * (a : S) +
          canonicalCubicPolynomial25Two * (b : S) := by
  obtain ⟨n, p, hp, rfl⟩ :=
    Away.mk_surjective standardConePiece (coordinate_isHomogeneous i) z
  have hp' : p ∈ standardConePiece n := by
    simpa using hp
  rw [RingHom.mem_ker, canonicalConeChartMap, Away.map_mk] at hz
  have hzval := congrArg HomogeneousLocalization.val hz
  simp only [Away.val_mk, HomogeneousLocalization.val_zero] at hzval
  rw [Localization.mk_eq_mk'_apply,
    IsLocalization.mk'_eq_zero_iff] at hzval
  obtain ⟨t, ht⟩ := hzval
  obtain ⟨m, hm⟩ := t.property
  have hm' : canonicalConeGradedProjection (MvPolynomial.X i) ^ m =
      (t : CanonicalConeRing25Two) := by
    simpa only using hm
  have ht' : canonicalConeGradedProjection (MvPolynomial.X i) ^ m *
      canonicalConeGradedProjection p = 0 := by
    rw [hm']
    exact ht
  have hquotient :
      canonicalConeGradedProjection (MvPolynomial.X i ^ m * p) = 0 := by
    simpa only [map_mul, map_pow] using ht'
  let r : shiftedPiece 0 (m + n) := ⟨MvPolynomial.X i ^ m * p, by
    rw [shiftedPiece, if_pos (Nat.zero_le (m + n))]
    exact (MvPolynomial.isHomogeneous_X_pow i m).mul hp'⟩
  have hr : r ∈ LinearMap.ker (literalConeProjection (m + n)) := by
    rw [LinearMap.mem_ker]
    apply Subtype.ext
    exact hquotient
  rw [literalConeProjection_ker_eq_range] at hr
  obtain ⟨q, hq⟩ := hr
  refine ⟨n, m, p, hp', q.1, q.2, rfl, ?_⟩
  have hqValue := congrArg Subtype.val hq
  simpa only [r, gradedKoszulMiddle_coe] using hqValue.symm

/-- Multiplying a shifted coefficient by the missing power of the chart
coordinate packages it as a degree-zero homogeneous fraction.  The same
formula also covers degrees below the shift, where the coefficient is zero. -/
def shiftedCoefficientAway (i : Fin 4) (debt N : ℕ)
    (a : shiftedPiece debt N) :
    Away standardConePiece (MvPolynomial.X i) :=
  Away.mk standardConePiece (coordinate_isHomogeneous i) N
    ((a : S) * MvPolynomial.X i ^ debt) (by
      by_cases hdebt : debt ≤ N
      · simpa [Nat.sub_add_cancel hdebt] using
          (shiftedPiece_isHomogeneous a).mul
            (MvPolynomial.isHomogeneous_X_pow i debt)
      · have ha0 : (a : S) = 0 := by
          simpa [shiftedPiece, hdebt] using a.property
        rw [ha0, zero_mul]
        simp)

/-- A saturated cone relation becomes an ordinary two-generator relation
after passing to the degree-zero chart localization.  The inserted coordinate
powers make both shifted coefficients degree zero; those powers cancel because
the chart coordinate is invertible. -/
theorem awayMk_eq_dehomogenizedCombination (i : Fin 4)
    (n m : ℕ) (p : S) (hp : p ∈ standardConePiece n)
    (a : shiftedPiece 2 (m + n)) (b : shiftedPiece 3 (m + n))
    (hrelation : MvPolynomial.X i ^ m * p =
      canonicalQuadricPolynomial25Two * (a : S) +
        canonicalCubicPolynomial25Two * (b : S)) :
    Away.mk standardConePiece (coordinate_isHomogeneous i) n p (by
        simpa using hp) =
      shiftedCoefficientAway i 2 (m + n) a * dehomogenizedQuadric i +
        shiftedCoefficientAway i 3 (m + n) b * dehomogenizedCubic i := by
  apply HomogeneousLocalization.val_injective
  simp only [HomogeneousLocalization.val_add, HomogeneousLocalization.val_mul,
    Away.val_mk, shiftedCoefficientAway, dehomogenizedQuadric,
    dehomogenizedCubic, Localization.mk_mul, Localization.add_mk]
  rw [Localization.mk_eq_mk_iff, Localization.r_iff_exists]
  use 1
  simp only [OneMemClass.coe_one, one_mul, Submonoid.coe_mul]
  calc
    _ = MvPolynomial.X i ^ (m + 2 * n + 5) *
        (MvPolynomial.X i ^ m * p) := by
          simp only [pow_add]
          ring
    _ = MvPolynomial.X i ^ (m + 2 * n + 5) *
        (canonicalQuadricPolynomial25Two * (a : S) +
          canonicalCubicPolynomial25Two * (b : S)) := by
            rw [hrelation]
    _ = _ := by
      simp only [pow_add]
      ring

/-- Every element killed by the quotient chart map is generated by the two
dehomogenized defining equations. -/
theorem kernel_le_chartEquationIdeal (i : Fin 4) :
    RingHom.ker (canonicalConeChartMap i) ≤
      Ideal.span ({dehomogenizedQuadric i, dehomogenizedCubic i} :
        Set (Away standardConePiece (MvPolynomial.X i))) := by
  intro z hz
  obtain ⟨n, m, p, hp, a, b, hzFraction, hrelation⟩ :=
    chartKernel_has_saturated_koszul_relation i z hz
  rw [hzFraction, Ideal.mem_span_pair]
  refine ⟨shiftedCoefficientAway i 2 (m + n) a,
    shiftedCoefficientAway i 3 (m + n) b, ?_⟩
  exact (awayMk_eq_dehomogenizedCombination i n m p hp a b hrelation).symm

/-- On each standard projective chart, the kernel of the canonical quotient
map is exactly the ideal generated by the dehomogenized quadric and cubic. -/
theorem chartKernel_eq_equationIdeal (i : Fin 4) :
    RingHom.ker (canonicalConeChartMap i) =
      Ideal.span ({dehomogenizedQuadric i, dehomogenizedCubic i} :
        Set (Away standardConePiece (MvPolynomial.X i))) :=
  le_antisymm (kernel_le_chartEquationIdeal i)
    (chartEquationIdeal_le_kernel i)

/-- The two explicit equations regarded as an ideal in a standard chart. -/
def chartEquationIdeal (i : Fin 4) :
    Ideal (Away standardConePiece (MvPolynomial.X i)) :=
  Ideal.span {dehomogenizedQuadric i, dehomogenizedCubic i}

/-- The quotient map on each standard projective chart is surjective. -/
theorem canonicalConeChartMap_surjective (i : Fin 4) :
    Function.Surjective (canonicalConeChartMap i) := by
  exact Away.map_surjective canonicalConeGradedProjection
    canonicalConeGradedProjection_surjective (MvPolynomial.X i)
      (coordinate_isHomogeneous i)

/-- The affine chart of the projective quotient has the expected explicit
coordinate ring: the ambient chart modulo its dehomogenized equations. -/
def chartCoordinateRingEquiv (i : Fin 4) :
    (Away standardConePiece (MvPolynomial.X i) ⧸ chartEquationIdeal i) ≃+*
      Away literalConePiece
        (canonicalConeGradedProjection (MvPolynomial.X i)) :=
  (Ideal.quotEquivOfEq (show chartEquationIdeal i =
      RingHom.ker (canonicalConeChartMap i) from
        (chartKernel_eq_equationIdeal i).symm)).trans
    (RingHom.quotientKerEquivOfSurjective
      (canonicalConeChartMap_surjective i))

/-- The chart coordinate-ring equivalence is induced by the canonical chart
map, not merely an abstract ring isomorphism. -/
@[simp]
theorem chartCoordinateRingEquiv_mk (i : Fin 4)
    (z : Away standardConePiece (MvPolynomial.X i)) :
    chartCoordinateRingEquiv i (Ideal.Quotient.mk _ z) =
      canonicalConeChartMap i z := by
  rfl

end MazurProof.RationalPointsN25QuotientTwoChartIdeal
