import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoWBoundaryArtinLocal

/-!
# The actual X-chart boundary quotient at W = 0

On the standard projective chart `X != 0`, the homogeneous section `W`
restricts to the affine coordinate `W/X`.  This file computes the quotient
of the actual curve chart ring by that coordinate and identifies it with
`F₂[t]/(t³)`.  Unlike the isolated plane calculation, the source here is the
ordinary coordinate ring `ChartQuotient 0` of the curve on `D₊(X)`.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false
noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoWBoundaryChartArtin

open RationalPointsN25QuotientF2
open RationalPointsN25QuotientTwoAffineChartsSmooth
open RationalPointsN25QuotientSmoothF2
open RationalPointsN25QuotientTwoStructuralJacobian
open RationalPointsN25QuotientTwoAffineCharts
open RationalPointsN25QuotientTwoWBoundaryArtinLocal
open RationalPointsN25QuotientTwoHyperplaneArtin
open RationalPointsN25QuotientTwoConormal

/-- The actual curve coordinate ring on the standard projective `X` chart. -/
abbrev XChartRing := ChartQuotient (0 : Fin 4)

/-- The `Y/X` coordinate in the actual `X`-chart curve ring. -/
private def xY : XChartRing := chartMap 0 (MvPolynomial.X 1)
/-- The `Z/X` coordinate in the actual `X`-chart curve ring. -/
private def xZ : XChartRing := chartMap 0 (MvPolynomial.X 2)
/-- The restriction `W/X` of the homogeneous coordinate `W` to `D₊(X)`. -/
def xW : XChartRing := chartMap 0 (MvPolynomial.X 3)

/-- The principal ideal generated by the restricted hyperplane section. -/
def xWIdeal : Ideal XChartRing := Ideal.span {xW}

/-- The actual `X`-chart curve ring cut by `W = 0`. -/
abbrev XBoundaryRing := XChartRing ⧸ xWIdeal

private def qY : XBoundaryRing := Ideal.Quotient.mk xWIdeal xY
private def qZ : XBoundaryRing := Ideal.Quotient.mk xWIdeal xZ
private def qW : XBoundaryRing := Ideal.Quotient.mk xWIdeal xW

private theorem qW_eq_zero : qW = 0 := by
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  exact Ideal.subset_span (Set.mem_singleton xW)

private theorem x_quadric_relation : xZ + xW + xY ^ 2 + xY * xZ + xZ * xW = 0 := by
  have h := chartQuotientPoint_quadric (0 : Fin 4)
  simpa [canonicalQuadric25CharTwo, chartQuotientPoint,
    mappedAmbientPoint, xY, xZ, xW, chartMap_X_pivot] using h

private theorem x_cubic_relation :
    xW + xY * xZ + xY * xW + xZ * xW + xY * xZ * xW +
      xZ ^ 2 * xW + xZ * xW ^ 2 = 0 := by
  have h := chartQuotientPoint_cubic (0 : Fin 4)
  simpa [canonicalCubic25CharTwo, chartQuotientPoint,
    mappedAmbientPoint, xY, xZ, xW, chartMap_X_pivot] using h

private theorem q_quadric_relation : qY ^ 2 + qZ + qY * qZ = 0 := by
  have h := congrArg (Ideal.Quotient.mk xWIdeal) x_quadric_relation
  change qZ + qW + qY ^ 2 + qY * qZ + qZ * qW = 0 at h
  rw [qW_eq_zero] at h
  linear_combination h

private theorem q_cubic_relation : qY * qZ = 0 := by
  have h := congrArg (Ideal.Quotient.mk xWIdeal) x_cubic_relation
  change qW + qY * qZ + qY * qW + qZ * qW + qY * qZ * qW +
    qZ ^ 2 * qW + qZ * qW ^ 2 = 0 at h
  rw [qW_eq_zero] at h
  linear_combination h

private theorem qZ_eq_qY_sq : qZ = qY ^ 2 := by
  have hsum : qZ + qY ^ 2 = 0 := by
    linear_combination q_quadric_relation - q_cubic_relation
  have htwo : (2 : XBoundaryRing) = 0 := by
    have htwoCoeff : (2 : ZMod 2) = 0 := CharP.cast_eq_zero (ZMod 2) 2
    have htwoAffine : (2 : AffineChart (0 : Fin 4)) = 0 := by
      change MvPolynomial.C (2 : ZMod 2) = 0
      rw [htwoCoeff, map_zero]
    have htwoChart : (2 : XChartRing) = 0 := by
      change Ideal.Quotient.mk (chartAffineEquationIdeal 0)
        (2 : AffineChart (0 : Fin 4)) = 0
      rw [htwoAffine, map_zero]
    change Ideal.Quotient.mk xWIdeal (2 : XChartRing) = 0
    rw [htwoChart, map_zero]
  have hself : qY ^ 2 + qY ^ 2 = 0 := by
    linear_combination htwo * qY ^ 2
  exact (eq_neg_of_add_eq_zero_left hsum).trans
    (neg_eq_iff_add_eq_zero.mpr hself)

private theorem qY_cube : qY ^ 3 = 0 := by
  calc
    qY ^ 3 = qY * qY ^ 2 := by ring
    _ = qY * qZ := by rw [qZ_eq_qY_sq]
    _ = 0 := q_cubic_relation

private def xArtinCoordinates : Coordinates4 TripleArtin :=
  ⟨1, tripleRoot, tripleRoot ^ 2, 0⟩

private def xArtinAffineEval : AffineChart (0 : Fin 4) →ₐ[ZMod 2] TripleArtin :=
  MvPolynomial.aeval
    (fun j => coordinates4ToFun xArtinCoordinates j.1)

private theorem xArtinAffineEval_comp_dehomogenize :
    xArtinAffineEval.toRingHom.comp (ambientDehomogenize 0) =
      MvPolynomial.eval₂Hom (algebraMap (ZMod 2) TripleArtin)
        (coordinates4ToFun xArtinCoordinates) := by
  apply MvPolynomial.ringHom_ext
  · intro r
    simp [xArtinAffineEval, ambientDehomogenize]
  · intro j
    fin_cases j <;>
      simp [xArtinAffineEval, ambientDehomogenize,
        dehomogenizedVariable, xArtinCoordinates, coordinates4ToFun]

private theorem mappedAmbientPoint_xArtinEval :
    mappedAmbientPoint
        (MvPolynomial.eval₂Hom (algebraMap (ZMod 2) TripleArtin)
          (coordinates4ToFun xArtinCoordinates)) =
      xArtinCoordinates := by
  simp [mappedAmbientPoint, xArtinCoordinates, coordinates4ToFun]

private theorem xArtinAffineEval_quadric :
    xArtinAffineEval (chartAffineQuadric 0) = 0 := by
  change xArtinAffineEval (ambientDehomogenize 0
    canonicalQuadricPolynomial25Two) = 0
  change (xArtinAffineEval.toRingHom.comp (ambientDehomogenize 0))
    canonicalQuadricPolynomial25Two = 0
  rw [xArtinAffineEval_comp_dehomogenize]
  rw [map_canonicalQuadric]
  rw [mappedAmbientPoint_xArtinEval]
  dsimp [canonicalQuadric25CharTwo, xArtinCoordinates]
  have htwo : (2 : TripleArtin) = 0 := CharP.cast_eq_zero TripleArtin 2
  linear_combination tripleRoot_cube + tripleRoot ^ 2 * htwo

private theorem xArtinAffineEval_cubic :
    xArtinAffineEval (chartAffineCubic 0) = 0 := by
  change xArtinAffineEval (ambientDehomogenize 0
    canonicalCubicPolynomial25Two) = 0
  change (xArtinAffineEval.toRingHom.comp (ambientDehomogenize 0))
    canonicalCubicPolynomial25Two = 0
  rw [xArtinAffineEval_comp_dehomogenize]
  rw [map_canonicalCubic]
  rw [mappedAmbientPoint_xArtinEval]
  dsimp [canonicalCubic25CharTwo, xArtinCoordinates]
  simp
  calc
    tripleRoot * tripleRoot ^ 2 = tripleRoot ^ 3 := by ring
    _ = 0 := tripleRoot_cube

private theorem chartAffineEquationIdeal_le_xArtinAffineEval_ker :
    chartAffineEquationIdeal 0 ≤ RingHom.ker xArtinAffineEval.toRingHom := by
  rw [chartAffineEquationIdeal, chartAffineRelation_range]
  refine Ideal.span_le.2 ?_
  intro p hp
  rcases hp with rfl | rfl
  · exact xArtinAffineEval_quadric
  · exact xArtinAffineEval_cubic

private def xChartToArtin : XChartRing →ₐ[ZMod 2] TripleArtin :=
  Ideal.Quotient.liftₐ (chartAffineEquationIdeal 0) xArtinAffineEval
    (fun _ hp => chartAffineEquationIdeal_le_xArtinAffineEval_ker hp)

@[simp]
private theorem xChartToArtin_xY : xChartToArtin xY = tripleRoot := by
  simp [xChartToArtin, xY, chartMap, xArtinAffineEval,
    ambientDehomogenize, dehomogenizedVariable, coordinates4ToFun,
    xArtinCoordinates]

@[simp]
private theorem xChartToArtin_xZ : xChartToArtin xZ = tripleRoot ^ 2 := by
  simp [xChartToArtin, xZ, chartMap, xArtinAffineEval,
    ambientDehomogenize, dehomogenizedVariable, coordinates4ToFun,
    xArtinCoordinates]

@[simp]
private theorem xChartToArtin_xW : xChartToArtin xW = 0 := by
  simp [xChartToArtin, xW, chartMap, xArtinAffineEval,
    ambientDehomogenize, dehomogenizedVariable, coordinates4ToFun,
    xArtinCoordinates]

private theorem xWIdeal_le_xChartToArtin_ker :
    xWIdeal ≤ RingHom.ker xChartToArtin.toRingHom := by
  refine Ideal.span_le.2 ?_
  intro p hp
  simp only [Set.mem_singleton_iff] at hp
  simp [hp]

private def xBoundaryToArtin : XBoundaryRing →ₐ[ZMod 2] TripleArtin :=
  Ideal.Quotient.liftₐ xWIdeal xChartToArtin
    (fun _ hp => xWIdeal_le_xChartToArtin_ker hp)

@[simp]
private theorem xBoundaryToArtin_qY : xBoundaryToArtin qY = tripleRoot := by
  simp [xBoundaryToArtin, qY]

@[simp]
private theorem xBoundaryToArtin_qZ : xBoundaryToArtin qZ = tripleRoot ^ 2 := by
  simp [xBoundaryToArtin, qZ]

@[simp]
private theorem xBoundaryToArtin_qW : xBoundaryToArtin qW = 0 := by
  simp [xBoundaryToArtin, qW]

private def tripleArtinToXBoundary : TripleArtin →ₐ[ZMod 2] XBoundaryRing :=
  AdjoinRoot.liftAlgHom ((Polynomial.X : Polynomial (ZMod 2)) ^ 3)
    (Algebra.ofId (ZMod 2) XBoundaryRing) qY (by simpa using qY_cube)

@[simp]
private theorem tripleArtinToXBoundary_tripleRoot :
    tripleArtinToXBoundary tripleRoot = qY := by
  rw [tripleArtinToXBoundary, tripleRoot, AdjoinRoot.liftAlgHom_root]

private theorem xBoundaryToArtin_comp_tripleArtinToXBoundary :
    xBoundaryToArtin.comp tripleArtinToXBoundary =
      AlgHom.id (ZMod 2) TripleArtin := by
  apply AdjoinRoot.algHom_ext
  simp only [AlgHom.comp_apply, tripleArtinToXBoundary,
    AdjoinRoot.liftAlgHom_root, AlgHom.id_apply]
  exact xBoundaryToArtin_qY

private theorem otherCoordinate_zero_cases (j : OtherCoordinate (0 : Fin 4)) :
    j = ⟨1, by decide⟩ ∨ j = ⟨2, by decide⟩ ∨ j = ⟨3, by decide⟩ := by
  rcases j with ⟨j, hj⟩
  fin_cases j
  · exact (hj rfl).elim
  · exact Or.inl (Subtype.ext rfl)
  · exact Or.inr (Or.inl (Subtype.ext rfl))
  · exact Or.inr (Or.inr (Subtype.ext rfl))

private theorem tripleArtinToXBoundary_comp_xBoundaryToArtin :
    tripleArtinToXBoundary.comp xBoundaryToArtin =
      AlgHom.id (ZMod 2) XBoundaryRing := by
  apply Ideal.Quotient.algHom_ext
  apply Ideal.Quotient.algHom_ext
  ext j
  rcases otherCoordinate_zero_cases j with rfl | rfl | rfl
  · simp only [AlgHom.comp_apply, AlgHom.id_apply]
    have hgen :
        (Ideal.Quotient.mkₐ (ZMod 2) xWIdeal)
            ((Ideal.Quotient.mkₐ (ZMod 2) (chartAffineEquationIdeal 0))
              (MvPolynomial.X (⟨1, by decide⟩ : OtherCoordinate 0))) = qY := by
      simp [qY, xY, chartMap, ambientDehomogenize,
        dehomogenizedVariable]
    rw [hgen, xBoundaryToArtin_qY,
      tripleArtinToXBoundary_tripleRoot]
  · simp only [AlgHom.comp_apply, AlgHom.id_apply]
    have hgen :
        (Ideal.Quotient.mkₐ (ZMod 2) xWIdeal)
            ((Ideal.Quotient.mkₐ (ZMod 2) (chartAffineEquationIdeal 0))
              (MvPolynomial.X (⟨2, by decide⟩ : OtherCoordinate 0))) = qZ := by
      simp [qZ, xZ, chartMap, ambientDehomogenize,
        dehomogenizedVariable]
    rw [hgen, xBoundaryToArtin_qZ, map_pow,
      tripleArtinToXBoundary_tripleRoot, qZ_eq_qY_sq]
  · simp only [AlgHom.comp_apply, AlgHom.id_apply]
    have hgen :
        (Ideal.Quotient.mkₐ (ZMod 2) xWIdeal)
            ((Ideal.Quotient.mkₐ (ZMod 2) (chartAffineEquationIdeal 0))
              (MvPolynomial.X (⟨3, by decide⟩ : OtherCoordinate 0))) = qW := by
      simp [qW, xW, chartMap, ambientDehomogenize,
        dehomogenizedVariable]
    rw [hgen, xBoundaryToArtin_qW, map_zero, qW_eq_zero]

/-- The actual curve chart quotient by `W/X` is the length-three Artin
algebra `F₂[t]/(t³)`. -/
def xBoundaryAlgEquivTripleArtin :
    XBoundaryRing ≃ₐ[ZMod 2] TripleArtin :=
  AlgEquiv.ofAlgHom xBoundaryToArtin tripleArtinToXBoundary
    xBoundaryToArtin_comp_tripleArtinToXBoundary
    tripleArtinToXBoundary_comp_xBoundaryToArtin

/-- The quotient of the actual `X`-chart curve ring by `W/X` has
`F₂`-length three. -/
theorem xBoundaryRing_f2_length :
    Module.length (ZMod 2) XBoundaryRing = 3 := by
  rw [xBoundaryAlgEquivTripleArtin.toLinearEquiv.length_eq]
  letI : Module.Finite (ZMod 2) TripleArtin :=
    (Polynomial.monic_X_pow 3).finite_adjoinRoot
  rw [Module.length_eq_finrank, tripleArtin_finrank]
  norm_num

end MazurProof.RationalPointsN25QuotientTwoWBoundaryChartArtin
