import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoWBoundaryXLocal
import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoWBoundaryYZChartArtin

/-!
# The YZ-boundary quotient in the local curve ring

This file localizes the actual `Y != 0` chart at `[0:1:1:0]`.  Since its
quotient by `W/Y` is already `F₂`, every denominator outside the point prime
maps to a unit.  The local quotient is therefore `F₂`, and the germ of `W/Y`
has order one.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false
noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoWBoundaryYZLocal

open RationalPointsN25QuotientTwoWBoundaryXLocal
open RationalPointsN25QuotientTwoWBoundaryYZChartArtin

local notation "k₂" => ZMod 2

private noncomputable def yzBoundaryQuot :
    YChartRing →ₐ[k₂] YZBoundaryRing :=
  Ideal.Quotient.mkₐ k₂ yzWIdeal

/-- Evaluation at `[0:1:1:0]`, obtained from the computed boundary factor. -/
noncomputable def yzPointEval : YChartRing →ₐ[k₂] k₂ :=
  yzBoundaryAlgEquivF2.toAlgHom.comp yzBoundaryQuot

theorem yzPointEval_surjective : Function.Surjective yzPointEval := by
  intro c
  refine ⟨algebraMap k₂ YChartRing c, ?_⟩
  exact yzPointEval.commutes c

/-- The maximal ideal of `[0:1:1:0]` in the actual `Y` chart. -/
def yzPrime : Ideal YChartRing := RingHom.ker yzPointEval.toRingHom

theorem yzPrime_isMaximal : yzPrime.IsMaximal :=
  RingHom.ker_isMaximal_of_surjective
    yzPointEval.toRingHom yzPointEval_surjective

local instance : yzPrime.IsMaximal := yzPrime_isMaximal
local instance : yzPrime.IsPrime := yzPrime_isMaximal.isPrime

private theorem yzWIdeal_le_yzPrime : yzWIdeal ≤ yzPrime := by
  intro z hz
  rw [yzPrime, RingHom.mem_ker]
  change yzBoundaryAlgEquivF2 (yzBoundaryQuot z) = 0
  have hzero : yzBoundaryQuot z = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr hz
  rw [hzero, map_zero]

private theorem yzBoundaryQuot_isUnit_of_primeCompl
    (s : yzPrime.primeCompl) :
    IsUnit (yzBoundaryQuot (s : YChartRing)) := by
  have hsnot : (s : YChartRing) ∉ yzPrime :=
    Ideal.mem_primeCompl_iff.mp s.2
  have hres_ne : yzPointEval (s : YChartRing) ≠ 0 := by
    intro hzero
    exact hsnot (RingHom.mem_ker.mpr hzero)
  have htarget :
      IsUnit (yzBoundaryAlgEquivF2 (yzBoundaryQuot (s : YChartRing))) :=
    isUnit_iff_ne_zero.mpr hres_ne
  exact (MulEquiv.isUnit_map yzBoundaryAlgEquivF2.toRingEquiv).mp htarget

/-- The local ring of the actual `Y` chart at `[0:1:1:0]`. -/
abbrev YZLocalRing := Localization.AtPrime yzPrime

local instance yzLocalRingCommRing : CommRing YZLocalRing :=
  OreLocalization.instCommRing

private noncomputable def yzLocalToBoundary :
    YZLocalRing →ₐ[k₂] YZBoundaryRing :=
  IsLocalization.liftAlgHom
    (A := k₂) (R := YChartRing) (S := YZLocalRing)
    (P := YZBoundaryRing) (f := yzBoundaryQuot)
    yzBoundaryQuot_isUnit_of_primeCompl

private theorem yzLocalToBoundary_surjective :
    Function.Surjective yzLocalToBoundary := by
  intro z
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mkₐ_surjective k₂ yzWIdeal z
  refine ⟨algebraMap YChartRing YZLocalRing a, ?_⟩
  simp [yzLocalToBoundary, yzBoundaryQuot]

private theorem yzLocalToBoundary_ker :
    RingHom.ker yzLocalToBoundary.toRingHom =
      yzWIdeal.map (algebraMap YChartRing YZLocalRing) := by
  have h := ker_liftAlgHom_eq_map
    (A := k₂) (R := YChartRing) (B := YZBoundaryRing)
    (M := yzPrime.primeCompl) (S := YZLocalRing)
    (f := yzBoundaryQuot) yzBoundaryQuot_isUnit_of_primeCompl
  have hker : RingHom.ker yzBoundaryQuot.toRingHom = yzWIdeal := by
    change RingHom.ker
      (Ideal.Quotient.mkₐ k₂ yzWIdeal :
        YChartRing →ₐ[k₂] YZBoundaryRing).toRingHom = yzWIdeal
    exact Ideal.Quotient.mkₐ_ker (R₁ := k₂) yzWIdeal
  rw [hker] at h
  exact h

/-- The germ of `W/Y` in the local curve ring. -/
noncomputable def yzWGerm : YZLocalRing :=
  algebraMap YChartRing YZLocalRing yzW

/-- The principal ideal generated by the germ of `W/Y`. -/
def yzWGermIdeal : Ideal YZLocalRing := Ideal.span {yzWGerm}

private theorem yzWGermIdeal_eq_map :
    yzWGermIdeal = yzWIdeal.map (algebraMap YChartRing YZLocalRing) := by
  rw [yzWGermIdeal, yzWIdeal, Ideal.map_span]
  simp [yzWGerm]

/-- The local quotient by the germ of `W/Y` is the ground field. -/
noncomputable def yzLocalBoundaryAlgEquivF2 :
    (YZLocalRing ⧸ yzWGermIdeal) ≃ₐ[k₂] k₂ :=
  (Ideal.quotientEquivAlgOfEq k₂
      (yzWGermIdeal_eq_map.trans yzLocalToBoundary_ker.symm)).trans
    ((Ideal.quotientKerAlgEquivOfSurjective
      yzLocalToBoundary_surjective).trans yzBoundaryAlgEquivF2)

/-- The local quotient has `F₂`-length one. -/
theorem yzLocalBoundary_f2_length :
    Module.length k₂ (YZLocalRing ⧸ yzWGermIdeal) = 1 := by
  rw [yzLocalBoundaryAlgEquivF2.toLinearEquiv.length_eq]
  exact Module.length_eq_one _ _

private noncomputable def yzPrimeQuotientAlgEquivF2 :
    (YChartRing ⧸ yzPrime) ≃ₐ[k₂] k₂ := by
  change (YChartRing ⧸ RingHom.ker yzPointEval.toRingHom) ≃ₐ[k₂] k₂
  exact Ideal.quotientKerAlgEquivOfSurjective yzPointEval_surjective

private noncomputable def yzPrimeLocalResidueAlgEquiv :
    (YChartRing ⧸ yzPrime) ≃ₐ[k₂]
      IsLocalRing.ResidueField YZLocalRing := by
  let e := IsLocalization.AtPrime.equivQuotMaximalIdeal yzPrime YZLocalRing
  exact
    { e with
      commutes' := by
        intro c
        change e (Ideal.Quotient.mk yzPrime
          (algebraMap k₂ YChartRing c)) =
            Ideal.Quotient.mk (IsLocalRing.maximalIdeal YZLocalRing)
              (algebraMap k₂ YZLocalRing c)
        rw [IsLocalization.AtPrime.equivQuotMaximalIdeal_apply_mk]
        rfl }

private noncomputable def yzLocalResidueAlgEquivF2 :
    IsLocalRing.ResidueField YZLocalRing ≃ₐ[k₂] k₂ :=
  yzPrimeLocalResidueAlgEquiv.symm.trans yzPrimeQuotientAlgEquivF2

private theorem yzLocalResidue_algebraMap_surjective :
    Function.Surjective
      (algebraMap k₂ (IsLocalRing.ResidueField YZLocalRing)) := by
  intro y
  refine ⟨yzLocalResidueAlgEquivF2 y, ?_⟩
  apply yzLocalResidueAlgEquivF2.injective
  simp

private theorem yzResidueExtension_algebraMap_surjective :
    Function.Surjective
      (algebraMap (IsLocalRing.ResidueField k₂)
        (IsLocalRing.ResidueField YZLocalRing)) := by
  intro y
  obtain ⟨c, rfl⟩ := yzLocalResidue_algebraMap_surjective y
  refine ⟨algebraMap k₂ (IsLocalRing.ResidueField k₂) c, ?_⟩
  exact IsScalarTower.algebraMap_apply k₂
    (IsLocalRing.ResidueField k₂)
    (IsLocalRing.ResidueField YZLocalRing) c

private theorem yzResidueExtension_length_one :
    Module.length (IsLocalRing.ResidueField k₂)
      (IsLocalRing.ResidueField YZLocalRing) = 1 := by
  let e : IsLocalRing.ResidueField k₂ ≃ₐ[IsLocalRing.ResidueField k₂]
      IsLocalRing.ResidueField YZLocalRing :=
    AlgEquiv.ofBijective (Algebra.ofId _ _)
      ⟨RingHom.injective _, yzResidueExtension_algebraMap_surjective⟩
  exact e.toLinearEquiv.length_eq.symm.trans (Module.length_eq_one _ _)

/-- The quotient by the germ of `W/Y` has local-ring length one. -/
theorem yzLocalBoundary_local_length :
    Module.length YZLocalRing (YZLocalRing ⧸ yzWGermIdeal) = 1 := by
  have h := IsLocalRing.length_restrictScalars
    k₂ YZLocalRing (YZLocalRing ⧸ yzWGermIdeal)
  rw [yzResidueExtension_length_one, mul_one] at h
  exact h.symm.trans yzLocalBoundary_f2_length

/-- The order of vanishing of `W` at `[0:1:1:0]` is one. -/
theorem yzWGerm_ord_eq_one : Ring.ord YZLocalRing yzWGerm = 1 := by
  unfold Ring.ord
  change Module.length YZLocalRing (YZLocalRing ⧸ yzWGermIdeal) = 1
  exact yzLocalBoundary_local_length

end MazurProof.RationalPointsN25QuotientTwoWBoundaryYZLocal
