import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoKoszul
import Mathlib.LinearAlgebra.Basis.Prod

/-!
# The conormal basis of the N25 binary complete intersection

Let `I = (Q,C)` be the homogeneous ideal of the binary canonical model.
This file proves that `I/I²` is free of rank two over `S/I`, with the
classes of the quadric and cubic as its distinguished generators.

The injectivity argument is structural.  A relation modulo `I²` is first
corrected by elements of `I`; the remaining relation between `Q` and `C`
then lies in the kernel of the middle Koszul differential.  Its proved
exactness forces the standard Koszul syzygy, so both original coefficients
vanish in `S/I`.  This is the affine-cone algebra underlying the future
graded identification `I/I² ≅ O_C(-2) ⊕ O_C(-3)` after sheafification.
-/

noncomputable section

namespace MazurProof.RationalPointsN25QuotientTwoConormalBasis

open MazurProof.RationalPointsN25QuotientTwoConormal
open MazurProof.RationalPointsN25QuotientTwoKoszul

/-! ## The two distinguished conormal classes -/

/-- The four-variable homogeneous coordinate ring. -/
abbrev R := BinaryHomogeneousRing

/-- The homogeneous ideal generated by the canonical quadric and cubic. -/
abbrev I := canonicalCurveIdeal25Two

/-- The homogeneous coordinate quotient `S/I`. -/
abbrev B := CanonicalConeRing25Two

/-- The class of the canonical quadric in the conormal module `I/I²`. -/
def quadricClass : I.Cotangent :=
  I.toCotangent ⟨canonicalQuadricPolynomial25Two,
    Ideal.subset_span (by simp)⟩

/-- The class of the canonical cubic in the conormal module `I/I²`. -/
def cubicClass : I.Cotangent :=
  I.toCotangent ⟨canonicalCubicPolynomial25Two,
    Ideal.subset_span (by simp)⟩

/-- The `S/I`-linear map sending a coefficient pair to the corresponding
linear combination of the two conormal classes. -/
def conormalGenerators : B × B →ₗ[B] I.Cotangent :=
  ((LinearMap.id : B →ₗ[B] B).smulRight quadricClass).coprod
    ((LinearMap.id : B →ₗ[B] B).smulRight cubicClass)

/-- The generator map has the expected coordinate formula. -/
@[simp] theorem conormalGenerators_apply (a b : B) :
    conormalGenerators (a, b) = a • quadricClass + b • cubicClass := rfl

/-- Scalar multiplication through the quotient agrees with multiplication
by a representative before passage to `I/I²`. -/
@[simp] theorem quotient_smul_toCotangent (a : R) (p : I) :
    Ideal.Quotient.mk I a • I.toCotangent p = I.toCotangent (a • p) := by
  rfl

/-! ## Relations modulo the square of the ideal -/

/-- Every element of `I²` is a combination `Q*a + C*b` whose two
coefficients already lie in `I`.  This is the form needed to remove a
relation modulo `I²` before applying Koszul exactness. -/
theorem curveIdeal_sq_decomposition {t : R} (ht : t ∈ I ^ 2) :
    ∃ a ∈ I, ∃ b ∈ I,
      t = canonicalQuadricPolynomial25Two * a +
        canonicalCubicPolynomial25Two * b := by
  have hI : I =
      Ideal.span {canonicalQuadricPolynomial25Two} ⊔
        Ideal.span {canonicalCubicPolynomial25Two} := by
    rw [show I = Ideal.span
      {canonicalQuadricPolynomial25Two, canonicalCubicPolynomial25Two} by rfl]
    exact Ideal.span_insert _ _
  rw [pow_two, hI, Ideal.sup_mul] at ht
  rcases Submodule.mem_sup.mp ht with ⟨u, hu, v, hv, rfl⟩
  rw [Ideal.mem_span_singleton_mul] at hu hv
  rcases hu with ⟨a, ha, rfl⟩
  rcases hv with ⟨b, hb, rfl⟩
  have haI : a ∈ I := by rw [hI]; exact ha
  have hbI : b ∈ I := by rw [hI]; exact hb
  exact ⟨a, haI, b, hbI, rfl⟩

/-! ## The conormal equivalence -/

/-- The quadric and cubic classes span `I/I²` over `S/I`. -/
theorem conormalGenerators_surjective :
    Function.Surjective conormalGenerators := by
  intro x
  rcases I.toCotangent_surjective x with ⟨p, rfl⟩
  rcases Ideal.mem_span_pair.mp p.2 with ⟨a, b, hab⟩
  refine ⟨(Ideal.Quotient.mk I a, Ideal.Quotient.mk I b), ?_⟩
  rw [conormalGenerators_apply]
  change I.toCotangent ⟨a * canonicalQuadricPolynomial25Two,
      Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp))⟩ +
    I.toCotangent ⟨b * canonicalCubicPolynomial25Two,
      Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp))⟩ = _
  rw [← map_add]
  apply congrArg I.toCotangent
  apply Subtype.ext
  simpa [mul_comm] using hab

/-- The quadric and cubic classes are independent over `S/I`.

After lifting the two coefficients to `S`, a relation in `I/I²` differs
from zero by `Q*u + C*v` with `u,v ∈ I`.  Exactness of the already-proved
Koszul complex identifies the corrected coefficient pair with
`(C*r,-Q*r)`, which puts both original coefficients in `I`. -/
theorem conormalGenerators_injective :
    Function.Injective conormalGenerators := by
  rw [← LinearMap.ker_eq_bot]
  apply (Submodule.eq_bot_iff _).mpr
  rintro ⟨a, b⟩ hab
  rcases Ideal.Quotient.mk_surjective a with ⟨a, rfl⟩
  rcases Ideal.Quotient.mk_surjective b with ⟨b, rfl⟩
  rw [LinearMap.mem_ker, conormalGenerators_apply] at hab
  change Ideal.Quotient.mk I a • quadricClass +
      Ideal.Quotient.mk I b • cubicClass = 0 at hab
  rw [quadricClass, cubicClass, quotient_smul_toCotangent,
    quotient_smul_toCotangent, ← map_add] at hab
  have habSqRaw := (I.toCotangent_eq_zero _).mp hab
  have habSq :
      a * canonicalQuadricPolynomial25Two +
          b * canonicalCubicPolynomial25Two ∈ I ^ 2 :=
    by simpa [smul_eq_mul] using habSqRaw
  rcases curveIdeal_sq_decomposition habSq with ⟨u, hu, v, hv, huv⟩
  have hsyzygy : koszulMiddle (a - u, b - v) = 0 := by
    rw [koszulMiddle_apply]
    rw [mul_sub, mul_sub]
    linear_combination huv
  rcases (koszul_exact_top_middle (a - u, b - v)).mp hsyzygy with ⟨r, hr⟩
  have haI : a ∈ I := by
    have hcoord := congrArg Prod.fst hr
    rw [koszulTop_apply] at hcoord
    dsimp only [Prod.fst] at hcoord
    have hCr : canonicalCubicPolynomial25Two * r ∈ I :=
      Ideal.mul_mem_right _ _ (Ideal.subset_span (by simp))
    have ha : a = canonicalCubicPolynomial25Two * r + u := by
      simpa [sub_eq_iff_eq_add] using hcoord.symm
    rw [ha]
    exact I.add_mem hCr hu
  have hbI : b ∈ I := by
    have hcoord := congrArg Prod.snd hr
    rw [koszulTop_apply] at hcoord
    dsimp only [Prod.snd] at hcoord
    have hQr : canonicalQuadricPolynomial25Two * r ∈ I :=
      Ideal.mul_mem_right _ _ (Ideal.subset_span (by simp))
    have hb : b = -(canonicalQuadricPolynomial25Two * r) + v := by
      simpa [sub_eq_iff_eq_add] using hcoord.symm
    rw [hb]
    exact I.add_mem (I.neg_mem hQr) hv
  apply Prod.ext <;> simp [Ideal.Quotient.eq_zero_iff_mem.mpr, haI, hbI]

/-- The distinguished generators identify `(S/I)²` with the conormal
module `I/I²`. -/
noncomputable def conormalLinearEquiv :=
  LinearEquiv.ofBijective conormalGenerators
    ⟨conormalGenerators_injective, conormalGenerators_surjective⟩

/-- A concrete two-element basis of `I/I²`, transported from the standard
basis of `(S/I) × (S/I)` along `conormalLinearEquiv`. -/
noncomputable def conormalBasis :
    Module.Basis (Fin 1 ⊕ Fin 1) B I.Cotangent :=
  ((Module.Basis.singleton (Fin 1) B).prod
    (Module.Basis.singleton (Fin 1) B)).map conormalLinearEquiv

/-- The conormal module is free over the homogeneous coordinate quotient. -/
noncomputable instance conormalCotangent_free : Module.Free B I.Cotangent :=
  Module.Free.of_basis conormalBasis

/-- The conormal module is finite over the homogeneous coordinate quotient. -/
noncomputable instance conormalCotangent_finite : Module.Finite B I.Cotangent :=
  Module.Finite.of_basis conormalBasis

end MazurProof.RationalPointsN25QuotientTwoConormalBasis
