import FLT.Assumptions.MazurProof.SexticMumfordRepresentative

/-!
# Primitive content of an integral sextic ideal

Every integral ideal in the quadratic coordinate ring has a polynomial
content: the common principal ideal generated by all of its `Y`
coefficients.  Dividing by that content is implemented as a colon ideal.
This gives a primitive integral ideal structurally, without enumeration or
Riemann--Roch.
-/

open Polynomial
open scoped nonZeroDivisors

namespace MazurProof.SexticMumford

noncomputable section

universe u

variable {K : Type u} [Field K]
variable (M : Model K)

/-! ## The coefficient-content ideal -/

/-- The ideal of all `Y` coefficients of elements of an integral ideal. -/
def yCoeffIdeal (J : Ideal (CoordinateRing M)) : Ideal K[X] where
  carrier :=
    { b | ∃ z : CoordinateRing M, z ∈ J ∧ coeffY M z = b }
  zero_mem' := ⟨0, J.zero_mem, map_zero (coeffY M)⟩
  add_mem' := by
    rintro b₁ b₂ ⟨z₁, hz₁, rfl⟩ ⟨z₂, hz₂, rfl⟩
    exact ⟨z₁ + z₂, J.add_mem hz₁ hz₂, map_add (coeffY M) z₁ z₂⟩
  smul_mem' := by
    rintro r b ⟨z, hz, rfl⟩
    refine ⟨xClass M r * z, J.mul_mem_left (xClass M r) hz, ?_⟩
    exact coeffY_xClass_mul M r z

@[simp] theorem mem_yCoeffIdeal
    (J : Ideal (CoordinateRing M)) (b : K[X]) :
    b ∈ yCoeffIdeal M J ↔
      ∃ z : CoordinateRing M, z ∈ J ∧ coeffY M z = b :=
  Iff.rfl

theorem coeffY_mem_yCoeffIdeal
    (J : Ideal (CoordinateRing M)) {z : CoordinateRing M}
    (hz : z ∈ J) :
    coeffY M z ∈ yCoeffIdeal M J :=
  ⟨z, hz, rfl⟩

/-- Multiplication by `Y` exchanges the two coefficients, up to the
quadratic equation in the constant coefficient. -/
@[simp] theorem coeffY_yClass_mul (z : CoordinateRing M) :
    coeffY M (yClass M * z) = coeff0 M z := by
  conv_lhs =>
    rw [← recompose M z]
  rw [mul_add, map_add]
  have hfirst :
      coeffY M (yClass M * xClass M (coeff0 M z)) =
        coeff0 M z := by
    rw [mul_comm, coeffY_xClass_mul, coeffY_yClass, mul_one]
  have hsecond :
      coeffY M
          (yClass M *
            (xClass M (coeffY M z) * yClass M)) = 0 := by
    calc
      coeffY M
          (yClass M *
            (xClass M (coeffY M z) * yClass M)) =
          coeffY M
            (xClass M (coeffY M z) * yClass M ^ 2) := by
              congr 1
              ring
      _ = coeffY M
            (xClass M (coeffY M z) * xClass M M.f) := by
              rw [yClass_sq]
      _ = coeffY M (xClass M (coeffY M z * M.f)) := by
              rw [xClass_mul]
      _ = 0 := coeffY_xClass M _
  rw [hfirst, hsecond, add_zero]

/-- Ideal stability under multiplication by `Y` puts the constant
coefficient in the same content ideal. -/
theorem coeff0_mem_yCoeffIdeal
    (J : Ideal (CoordinateRing M)) {z : CoordinateRing M}
    (hz : z ∈ J) :
    coeff0 M z ∈ yCoeffIdeal M J := by
  refine ⟨yClass M * z, J.mul_mem_left (yClass M) hz, ?_⟩
  exact coeffY_yClass_mul M z

theorem yCoeffIdeal_ne_bot
    (J : Ideal (CoordinateRing M)) (hJ : J ≠ ⊥) :
    yCoeffIdeal M J ≠ ⊥ := by
  obtain ⟨z, hzJ, hz⟩ :=
    Submodule.exists_mem_ne_zero_of_ne_bot hJ
  intro hbot
  have hY : coeffY M z = 0 := by
    rw [← Ideal.mem_bot, ← hbot]
    exact coeffY_mem_yCoeffIdeal M J hzJ
  have h0 : coeff0 M z = 0 := by
    rw [← Ideal.mem_bot, ← hbot]
    exact coeff0_mem_yCoeffIdeal M J hzJ
  apply hz
  rw [← recompose M z, h0, hY, xClass_zero, zero_mul, add_zero]

/-- A canonical (not prematurely normalized) generator of the coefficient
content. -/
def contentGenerator (J : Ideal (CoordinateRing M)) : K[X] :=
  Submodule.IsPrincipal.generator (yCoeffIdeal M J)

theorem span_contentGenerator (J : Ideal (CoordinateRing M)) :
    Ideal.span ({contentGenerator M J} : Set K[X]) =
      yCoeffIdeal M J :=
  Ideal.span_singleton_generator (yCoeffIdeal M J)

theorem contentGenerator_ne_zero
    (J : Ideal (CoordinateRing M)) (hJ : J ≠ ⊥) :
    contentGenerator M J ≠ 0 := by
  intro hzero
  apply yCoeffIdeal_ne_bot M J hJ
  exact
    (Submodule.IsPrincipal.eq_bot_iff_generator_eq_zero
      (yCoeffIdeal M J)).2 hzero

/-- Every element of `J` is visibly divisible in the coordinate ring by
the coefficient-content generator. -/
theorem exists_content_factor
    (J : Ideal (CoordinateRing M)) {z : CoordinateRing M}
    (hz : z ∈ J) :
    ∃ q : CoordinateRing M,
      xClass M (contentGenerator M J) * q = z := by
  have h0 := coeff0_mem_yCoeffIdeal M J hz
  have hY := coeffY_mem_yCoeffIdeal M J hz
  rw [← span_contentGenerator M J, Ideal.mem_span_singleton] at h0 hY
  obtain ⟨a, ha⟩ := h0
  obtain ⟨b, hb⟩ := hY
  refine ⟨xClass M a + xClass M b * yClass M, ?_⟩
  calc
    xClass M (contentGenerator M J) *
          (xClass M a + xClass M b * yClass M) =
        xClass M (contentGenerator M J * a) +
          xClass M (contentGenerator M J * b) * yClass M := by
            simp only [mul_add, xClass_mul]
            ring
    _ = xClass M (coeff0 M z) +
          xClass M (coeffY M z) * yClass M := by
            rw [← ha, ← hb]
    _ = z := recompose M z

/-! ## Division by content as a colon ideal -/

/-- The integral colon ideal `{z | d z ∈ J}`. -/
def primitivePart
    (J : Ideal (CoordinateRing M)) (d : K[X]) :
    Ideal (CoordinateRing M) where
  carrier := {z | xClass M d * z ∈ J}
  zero_mem' := by simp
  add_mem' := by
    intro z w hz hw
    simpa [mul_add] using J.add_mem hz hw
  smul_mem' := by
    intro a z hz
    simpa [mul_assoc, mul_left_comm, mul_comm] using
      J.mul_mem_left a hz

@[simp] theorem mem_primitivePart
    (J : Ideal (CoordinateRing M)) (d : K[X])
    (z : CoordinateRing M) :
    z ∈ primitivePart M J d ↔ xClass M d * z ∈ J :=
  Iff.rfl

/-- Exact content factorization of the original integral ideal. -/
theorem span_content_mul_primitivePart
    (J : Ideal (CoordinateRing M)) :
    Ideal.span
          ({xClass M (contentGenerator M J)} :
            Set (CoordinateRing M)) *
        primitivePart M J (contentGenerator M J) =
      J := by
  apply le_antisymm
  · rw [Ideal.mul_le]
    intro r hr z hz
    rw [Ideal.mem_span_singleton'] at hr
    obtain ⟨a, rfl⟩ := hr
    simpa [mul_assoc, mul_left_comm, mul_comm] using
      J.mul_mem_left a hz
  · rw [Ideal.le_span_singleton_mul_iff]
    intro z hz
    obtain ⟨q, hq⟩ := exists_content_factor M J hz
    refine ⟨q, ?_, hq⟩
    change xClass M (contentGenerator M J) * q ∈ J
    rw [hq]
    exact hz

/-- The divided ideal contains an element with `Y` coefficient one. -/
theorem primitivePart_isPrimitive
    (J : Ideal (CoordinateRing M)) :
    IdealIsPrimitive M
      (primitivePart M J (contentGenerator M J)) := by
  have hd :
      contentGenerator M J ∈ yCoeffIdeal M J :=
    Submodule.IsPrincipal.generator_mem (yCoeffIdeal M J)
  obtain ⟨z, hzJ, hzY⟩ := hd
  have h0 := coeff0_mem_yCoeffIdeal M J hzJ
  rw [← span_contentGenerator M J, Ideal.mem_span_singleton] at h0
  obtain ⟨c, hc⟩ := h0
  let q : CoordinateRing M := xClass M c + yClass M
  have hdq :
      xClass M (contentGenerator M J) * q = z := by
    calc
      xClass M (contentGenerator M J) * q =
          xClass M (contentGenerator M J * c) +
            xClass M (contentGenerator M J) * yClass M := by
              simp only [q, mul_add, xClass_mul]
      _ = xClass M (coeff0 M z) +
            xClass M (coeffY M z) * yClass M := by
              rw [← hc, hzY]
      _ = z := recompose M z
  refine ⟨q, ?_, ?_⟩
  · change xClass M (contentGenerator M J) * q ∈ J
    rw [hdq]
    exact hzJ
  · simp [q]

theorem yCoeffIdeal_primitivePart_eq_top
    (J : Ideal (CoordinateRing M)) :
    yCoeffIdeal M
      (primitivePart M J (contentGenerator M J)) = ⊤ := by
  rw [Ideal.eq_top_iff_one]
  obtain ⟨z, hz, hY⟩ := primitivePart_isPrimitive M J
  exact ⟨z, hz, hY⟩

/-! ## Fractional invertibility -/

theorem primitivePart_fractional_isUnit
    (J : Ideal (CoordinateRing M))
    (hJ :
      IsUnit
        (J :
          FractionalIdeal (CoordinateRing M)⁰ (FunctionField M))) :
    IsUnit
      (primitivePart M J (contentGenerator M J) :
        FractionalIdeal (CoordinateRing M)⁰ (FunctionField M)) := by
  have hmul :
      IsUnit (
        ((Ideal.span
              ({xClass M (contentGenerator M J)} :
                Set (CoordinateRing M)) :
              Ideal (CoordinateRing M)) :
            FractionalIdeal
              (CoordinateRing M)⁰ (FunctionField M)) *
          (primitivePart M J (contentGenerator M J) :
            FractionalIdeal
              (CoordinateRing M)⁰ (FunctionField M))) := by
    rw [← FractionalIdeal.coeIdeal_mul,
      span_content_mul_primitivePart M J]
    exact hJ
  exact (IsUnit.mul_iff.mp hmul).2

theorem primitivePart_fractional_eq
    (J : Ideal (CoordinateRing M)) (hJ : J ≠ ⊥) :
    (primitivePart M J (contentGenerator M J) :
        FractionalIdeal (CoordinateRing M)⁰ (FunctionField M)) =
      ((Ideal.span
            ({xClass M (contentGenerator M J)} :
              Set (CoordinateRing M)) :
            Ideal (CoordinateRing M)) :
          FractionalIdeal
            (CoordinateRing M)⁰ (FunctionField M))⁻¹ *
        (J :
          FractionalIdeal
            (CoordinateRing M)⁰ (FunctionField M)) := by
  let d := contentGenerator M J
  let P : Ideal (CoordinateRing M) :=
    Ideal.span ({xClass M d} : Set (CoordinateRing M))
  let J₀ : Ideal (CoordinateRing M) := primitivePart M J d
  have hd : d ≠ 0 := contentGenerator_ne_zero M J hJ
  have hbase : xClass M d ≠ 0 := xClass_ne_zero M hd
  have hPJ : P * J₀ = J := by
    exact span_content_mul_primitivePart M J
  calc
    (J₀ : FractionalIdeal
        (CoordinateRing M)⁰ (FunctionField M)) =
        1 * (J₀ : FractionalIdeal
          (CoordinateRing M)⁰ (FunctionField M)) := by simp
    _ = ((P :
            FractionalIdeal
              (CoordinateRing M)⁰ (FunctionField M))⁻¹ *
          (P :
            FractionalIdeal
              (CoordinateRing M)⁰ (FunctionField M))) *
        (J₀ :
          FractionalIdeal
            (CoordinateRing M)⁰ (FunctionField M)) := by
      rw [FractionalIdeal.coe_ideal_span_singleton_inv_mul
        (FunctionField M) hbase]
    _ = (P :
            FractionalIdeal
              (CoordinateRing M)⁰ (FunctionField M))⁻¹ *
        ((P :
            FractionalIdeal
              (CoordinateRing M)⁰ (FunctionField M)) *
          (J₀ :
            FractionalIdeal
              (CoordinateRing M)⁰ (FunctionField M))) := by
      rw [mul_assoc]
    _ = (P :
            FractionalIdeal
              (CoordinateRing M)⁰ (FunctionField M))⁻¹ *
        (J :
          FractionalIdeal
            (CoordinateRing M)⁰ (FunctionField M)) := by
      rw [← FractionalIdeal.coeIdeal_mul, hPJ]

/-! ## Oriented primitive representatives -/

def contentFunctionUnit
    (d : K[X]) (hd : d ≠ 0) :
    (FunctionField M)ˣ :=
  Units.mk0
    (algebraMap (CoordinateRing M) (FunctionField M)
      (xClass M d))
    (by
      simpa using
        (IsFractionRing.injective
          (CoordinateRing M) (FunctionField M)).ne
          (xClass_ne_zero M hd))

@[simp] theorem coe_contentFunctionUnit
    (d : K[X]) (hd : d ≠ 0) :
    (contentFunctionUnit M d hd : FunctionField M) =
      algebraMap (CoordinateRing M) (FunctionField M)
        (xClass M d) := rfl

namespace IntegralOrientedRep

variable (O : InfinityOrder M)

def primitivePartUnit (R : IntegralOrientedRep M) : InvFrac M :=
  (primitivePart_fractional_isUnit M R.ideal
    (R.ideal_isUnit M)).unit

@[simp] theorem coe_primitivePartUnit
    (R : IntegralOrientedRep M) :
    (R.primitivePartUnit M :
        FractionalIdeal (CoordinateRing M)⁰ (FunctionField M)) =
      primitivePart M R.ideal (contentGenerator M R.ideal) :=
  (primitivePart_fractional_isUnit M R.ideal
    (R.ideal_isUnit M)).unit_spec

def contentUnit (R : IntegralOrientedRep M) :
    (FunctionField M)ˣ :=
  contentFunctionUnit M (contentGenerator M R.ideal)
    (contentGenerator_ne_zero M R.ideal (R.ideal_ne_bot M))

/-- Divide the integral ideal by its polynomial content and adjust the
stored orientation by the exact `ordPlus` of that principal factor. -/
def primitivePartRep (R : IntegralOrientedRep M) :
    IntegralOrientedRep M where
  ideal := primitivePart M R.ideal (contentGenerator M R.ideal)
  unit := R.primitivePartUnit M
  coe_unit := coe_primitivePartUnit M R
  atInfinity :=
    R.atInfinity -
      Multiplicative.toAdd (O.ordPlus (R.contentUnit M))

@[simp] theorem primitivePartRep_ideal
    (R : IntegralOrientedRep M) :
    (R.primitivePartRep M O).ideal =
      primitivePart M R.ideal (contentGenerator M R.ideal) := rfl

@[simp] theorem primitivePartRep_atInfinity
    (R : IntegralOrientedRep M) :
    (R.primitivePartRep M O).atInfinity =
      R.atInfinity -
        Multiplicative.toAdd (O.ordPlus (R.contentUnit M)) := rfl

theorem primitivePartRep_isPrimitive
    (R : IntegralOrientedRep M) :
    IdealIsPrimitive M (R.primitivePartRep M O).ideal :=
  primitivePart_isPrimitive M R.ideal

theorem primitivePartUnit_mul_contentUnit
    (R : IntegralOrientedRep M) :
    R.primitivePartUnit M *
        toPrincipalIdeal (CoordinateRing M) (FunctionField M)
          (R.contentUnit M) =
      R.unit := by
  apply Units.ext
  simp only [Units.val_mul, coe_primitivePartUnit,
    coe_toPrincipalIdeal, contentUnit,
    coe_contentFunctionUnit]
  calc
    (primitivePart M R.ideal (contentGenerator M R.ideal) :
          FractionalIdeal
            (CoordinateRing M)⁰ (FunctionField M)) *
        FractionalIdeal.spanSingleton
          (CoordinateRing M)⁰
          (algebraMap (CoordinateRing M) (FunctionField M)
            (xClass M (contentGenerator M R.ideal))) =
      (primitivePart M R.ideal (contentGenerator M R.ideal) :
          FractionalIdeal
            (CoordinateRing M)⁰ (FunctionField M)) *
        (Ideal.span
            ({xClass M (contentGenerator M R.ideal)} :
              Set (CoordinateRing M)) :
          FractionalIdeal
            (CoordinateRing M)⁰ (FunctionField M)) := by
              rw [FractionalIdeal.coeIdeal_span_singleton]
    _ =
        ((Ideal.span
              ({xClass M (contentGenerator M R.ideal)} :
                Set (CoordinateRing M)) :
            Ideal (CoordinateRing M)) *
          primitivePart M R.ideal (contentGenerator M R.ideal) :
          Ideal (CoordinateRing M)) := by
            rw [FractionalIdeal.coeIdeal_mul]
            ac_rfl
    _ = (R.ideal :
          FractionalIdeal
            (CoordinateRing M)⁰ (FunctionField M)) := by
              rw [span_content_mul_primitivePart M R.ideal]
    _ = (R.unit :
          FractionalIdeal
            (CoordinateRing M)⁰ (FunctionField M)) := R.coe_unit.symm

/-- Removing content is an exact principal equivalence in the oriented
quotient, not merely an equality of unoriented ideal classes. -/
theorem primitivePartRep_picClass
    (R : IntegralOrientedRep M) :
    (R.primitivePartRep M O).picClass M O =
      R.picClass M O := by
  change
    QuotientGroup.mk' (principalOriented M O).range
        ((R.primitivePartRep M O).raw M) =
      QuotientGroup.mk' (principalOriented M O).range (R.raw M)
  rw [QuotientGroup.mk'_eq_mk']
  refine ⟨principalOriented M O (R.contentUnit M),
    MonoidHom.mem_range.mpr ⟨R.contentUnit M, rfl⟩, ?_⟩
  apply Prod.ext
  · exact primitivePartUnit_mul_contentUnit M R
  · change
      Multiplicative.ofAdd
          (R.atInfinity -
            Multiplicative.toAdd
              (O.ordPlus (R.contentUnit M))) *
        O.ordPlus (R.contentUnit M) =
      Multiplicative.ofAdd R.atInfinity
    change
      R.atInfinity -
          Multiplicative.toAdd
            (O.ordPlus (R.contentUnit M)) +
        Multiplicative.toAdd
          (O.ordPlus (R.contentUnit M)) =
      R.atInfinity
    omega

end IntegralOrientedRep

/-- Every oriented Picard class has a primitive integral representative.
This closes the missing bridge between denominator clearing and Mumford
graph extraction. -/
theorem exists_primitiveIntegralRepresentative
    (O : InfinityOrder M) (c : ConcretePic M O) :
    ∃ R : IntegralOrientedRep M,
      IdealIsPrimitive M R.ideal ∧ R.picClass M O = c := by
  obtain ⟨R, hR⟩ := exists_integralRepresentative M O c
  refine ⟨R.primitivePartRep M O,
    R.primitivePartRep_isPrimitive M O, ?_⟩
  exact (R.primitivePartRep_picClass M O).trans hR

end

end MazurProof.SexticMumford
