import FLT.Assumptions.MazurProof.X017FormalTwoReduction
import FLT.Assumptions.MazurProof.X017FourTorsion
import FLT.Assumptions.MazurProof.X017SecondCoset

/-!
# Rational points on the standard X₀(17) model

The exact `{0,T}` cover modulo doubling makes `4P` divisible by every power
of two.  On the integral good model, four times every rational point is
formal, and the formal filtration is separated.  Transporting these two facts
through the explicit model equivalence proves `4P=0` for every rational point.
The four-torsion calculation then gives exactly the visible points
`0`, `K`, `T`, and `-T`.
-/

open scoped WeierstrassCurve.Affine

namespace MazurProof.X017RationalPoints

open WeierstrassCurve.Affine
open MazurProof.X017FormalTwoCore
open MazurProof.X017FormalTwoReduction
open MazurProof.X017FourTorsion
open MazurProof.X017Model
open MazurProof.X017RankZero
open MazurProof.X017SecondCoset

noncomputable section

/-- Iterating the two-coset cover makes four times any standard-model point
divisible by every power of two.  The representative term disappears because
`T` has order four. -/
theorem four_nsmul_two_power_divisible
    (P : Point standard) (n : ℕ) :
    ∃ Q : Point standard,
      4 • P = (2 ^ n : ℕ) • (4 • Q) := by
  induction n with
  | zero =>
      exact ⟨P, by simp⟩
  | succ n ih =>
      obtain ⟨Q, hQ⟩ := ih
      obtain ⟨R, hQR | hQR⟩ := double_twoCosetExhaustion Q
      · refine ⟨R, ?_⟩
        change Q = 2 • R at hQR
        rw [hQ, hQR]
        rw [pow_succ]
        simp only [← mul_nsmul]
        congr 1
        ring
      · refine ⟨R, ?_⟩
        change Q = T + 2 • R at hQR
        rw [hQ, hQR, nsmul_add, four_nsmul_T, zero_add]
        rw [pow_succ]
        simp only [← mul_nsmul]
        congr 1
        ring

/-- Every rational point on the standard model is killed by four.  This is
the completed good-reduction/formal-kernel arithmetic input. -/
theorem four_nsmul_eq_zero (P : Point standard) :
    4 • P = 0 := by
  let P0 : Point X017 := X017ToStandard.symm P
  have hP0formal : FormalAtTwo (4 • P0) :=
    four_nsmul_formal P0
  have hdiv : ∀ n : ℕ, ∃ Q0 : Point X017,
      FormalAtTwo Q0 ∧ 4 • P0 = (2 ^ n : ℕ) • Q0 := by
    intro n
    obtain ⟨Q, hQ⟩ := four_nsmul_two_power_divisible P n
    refine ⟨4 • X017ToStandard.symm Q,
      four_nsmul_formal (X017ToStandard.symm Q), ?_⟩
    have hm := congrArg X017ToStandard.symm hQ
    simpa only [map_nsmul, AddEquiv.symm_apply_apply, P0] using hm
  have hzero : 4 • P0 = 0 :=
    formal_separated (4 • P0) hP0formal hdiv
  have hm := congrArg X017ToStandard hzero
  simpa only [map_nsmul, AddEquiv.apply_symm_apply, map_zero, P0] using hm

/-- The complete rational-point classification on the standard model. -/
theorem eq_zero_or_K_or_T_or_neg_T (P : Point standard) :
    P = 0 ∨ P = K ∨ P = T ∨ P = -T :=
  eq_zero_or_K_or_T_or_neg_T_of_four_nsmul_eq_zero
    P (four_nsmul_eq_zero P)

/-- Every rational point lies in the cyclic subgroup generated by the visible
point `T` of order four. -/
theorem mem_zmultiples_T (P : Point standard) :
    P ∈ AddSubgroup.zmultiples T := by
  rcases eq_zero_or_K_or_T_or_neg_T P with hP | hP | hP | hP
  · rw [hP]
    exact (AddSubgroup.zmultiples T).zero_mem
  · rw [hP, ← two_nsmul_T_eq_K]
    exact (AddSubgroup.zmultiples T).nsmul_mem
      (AddSubgroup.mem_zmultiples T) 2
  · rw [hP]
    exact AddSubgroup.mem_zmultiples T
  · rw [hP]
    exact (AddSubgroup.zmultiples T).neg_mem
      (AddSubgroup.mem_zmultiples T)

/-- The rational-point group of the standard model is generated by `T`. -/
theorem zmultiples_T_eq_top :
    AddSubgroup.zmultiples T = ⊤ := by
  apply eq_top_iff.mpr
  intro P _
  exact mem_zmultiples_T P

/-- The standard `X₀(17)` model has exactly four rational points. -/
theorem natCard_standardPoint :
    Nat.card (Point standard) = 4 := by
  rw [← AddSubgroup.card_top, ← zmultiples_T_eq_top,
    Nat.card_zmultiples, T_order_four]

end

end MazurProof.X017RationalPoints
