import FLT.Assumptions.MazurProof.N25F_PolynomialBoundaryOrders
import FLT.Assumptions.MazurProof.N25F_WChartBaseNorm

#print axioms MazurProof.N25F_PolynomialBoundaryOrders.xLocalFractionOrder_aeval_qz
#print axioms MazurProof.N25F_PolynomialBoundaryOrders.yzLocalFractionOrder_aeval_qz
#print axioms MazurProof.N25F_PolynomialBoundaryOrders.zLocalFractionOrder_aeval_qz
#print axioms MazurProof.N25F_NonBoundaryPrincipalDivisor.wChart_finrank_polynomial_eq_four
#print axioms MazurProof.N25F_NonBoundaryPrincipalDivisor.wChart_norm_algebraMap_eq_pow_four
#print axioms MazurProof.N25F_NonBoundaryPrincipalDivisor.wChart_quotient_finrank_base_polynomial
