import FLT.Assumptions.MazurProof.N25F_ZeroDegreeConstants

#print axioms MazurProof.N25F_BinaryResidueOrder.log_ordFrac_sub_one_pos
#print axioms MazurProof.N25F_ZeroDegreeConstants.one_mem_fullRiemannRochSpace25Two_zero
#print axioms MazurProof.N25F_ZeroDegreeConstants.xBoundaryOrder_eq_zero_of_mem_zero
#print axioms MazurProof.N25F_ZeroDegreeConstants.mem_fullRiemannRochSpace25Two_zero_iff
#print axioms MazurProof.N25F_ZeroDegreeConstants.fullRiemannRochSpace25Two_zero_eq_span_one
#print axioms MazurProof.N25F_ZeroDegreeConstants.fullRiemannRochSpace25Two_zero_finite
#print axioms MazurProof.N25F_ZeroDegreeConstants.finrank_fullRiemannRochSpace25Two_zero
#print axioms MazurProof.N25F_ZeroDegreeConstants.fullPrincipalDivisor_eq_zero_iff
#print axioms MazurProof.N25F_ZeroDegreeConstants.fullPrincipalDivisor_injective
