import FLT.Assumptions.MazurProof.N25F_FullPicardSectionRank

#print axioms MazurProof.N25F_SectionPrincipalTransport.mul_mem_fullRiemannRochSpace25Two
#print axioms MazurProof.N25F_SectionPrincipalTransport.principalSectionLinearEquiv25Two
#print axioms MazurProof.N25F_SectionPrincipalTransport.finrank_fullRiemannRochSpace25Two_eq_of_classOf_eq
#print axioms MazurProof.N25F_SectionPrincipalTransport.fullClassSectionRank25Two
#print axioms MazurProof.N25F_SectionPrincipalTransport.fullClassSectionRank25Two_classOf
#print axioms MazurProof.N25F_FullPicardSectionRank.fullPicardSectionRank25Two
#print axioms MazurProof.N25F_FullPicardSectionRank.fullEffectiveClassFiberEquiv25Two
#print axioms MazurProof.N25F_FullPicardSectionRank.fullEffectiveClass_fiber_card25Two
#print axioms MazurProof.N25F_FullPicardSectionRank.fullEffectiveClass_fiber_linearSystemCard25Two
