from sage.all import *
R.<X> = PolynomialRing(QQ)
E = EllipticCurve(QQ,[1,-1,1,-5,5])
P = E(1,0)
print('E',E.ainvs(),'Porder',P.order())
phi = E.isogeny(P)
print('PHI_CODOMAIN',phi.codomain().ainvs())
print('PHI_MAPS',phi.rational_maps())
phid = phi.dual()
print('DUAL_DOMAIN',phid.domain().ainvs())
print('DUAL_CODOMAIN',phid.codomain().ainvs())
print('DUAL_MAPS',phid.rational_maps())
Em = phi.codomain().global_minimal_model()
print('CODOMAIN_MIN',Em.ainvs(),Em.discriminant(),Em.conductor())
iso = phi.codomain().isomorphism_to(Em)
print('ISO_TO_MIN',iso)
print('COMPOSED_PHI_MAPS',(iso*phi).rational_maps())
phim = iso*phi
phidm = phim.dual()
print('DUAL_MIN_MAPS',phidm.rational_maps())
K.<a> = NumberField(X^3-3*X-1)
print('KDISC',K.discriminant(),'CLASS',K.class_number())
print('UNITS',K.unit_group().gens_values())
print('PRIMES2',K.primes_above(2))
print('PRIMES3',K.primes_above(3))
EL = E.change_ring(K)
E2L = Em.change_ring(K)
print('E_LOCAL2',EL.local_data(K.primes_above(2)[0]))
print('E2_LOCAL2',E2L.local_data(K.primes_above(2)[0]))
print('E_LOCAL3',EL.local_data(K.primes_above(3)[0]))
print('E2_LOCAL3',E2L.local_data(K.primes_above(3)[0]))
print('TORSION_E',EL.torsion_subgroup())
print('TORSION_E2',E2L.torsion_subgroup())
