Qx.<z> = PolynomialRing(QQ)
K.<a> = NumberField(z^3-3*z-1)
OK = K.ring_of_integers()
print('Q4517_BEGIN')
print('FIELD_POLY', K.defining_polynomial())
print('DISC', K.discriminant())
print('OK_BASIS', OK.basis())
print('CLASS_GROUP', K.class_group())
UG = K.unit_group()
print('UNIT_GROUP', UG)
try: print('UNIT_GENS_VALUES', UG.gens_values())
except Exception as ex: print('UNIT_GENS_VALUES_ERR',repr(ex))
print('FACTOR_2', K.ideal(2).factor())
print('FACTOR_3', K.ideal(3).factor())
pi=a-1
print('PI_NORM', K.norm(pi), 'PI_MINPOLY', pi.minpoly())
print('PI_IDEAL_FACTOR', K.ideal(pi).factor())
E=EllipticCurve(K,[1,-1,1,-5,5])
P=E(1,0)
print('E_AINVS',E.a_invariants())
print('E_DISC_J',E.discriminant(),E.j_invariant())
try: print('P_DATA',P,P.order(),-P)
except Exception as ex: print('P_DATA_ERR',repr(ex))
try:
    isos=E.isogenies_prime_degree(3)
    print('ISOS_LEN',len(isos))
    for i,phi in enumerate(isos):
        print('ISO',i,'DEG',phi.degree(),'KERNEL',phi.kernel_polynomial(),'COD',phi.codomain().a_invariants())
        try: print('ISO_RATMAPS',i,phi.rational_maps())
        except Exception as ex: print('ISO_RATMAPS_ERR',i,repr(ex))
        try:
            dh=phi.dual()
            print('DUAL',i,'COD',dh.codomain().a_invariants(),'KERNEL',dh.kernel_polynomial())
            print('DUAL_RATMAPS',i,dh.rational_maps())
        except Exception as ex: print('DUAL_ERR',i,repr(ex))
except Exception as ex: print('ISOS_ERR',repr(ex))
Ep=EllipticCurve(K,[-3,0,2,30,26])
print('EVELU',Ep.a_invariants(),Ep.discriminant(),Ep.j_invariant())
try: print('E_ISOG_EVELU',E.is_isogenous(Ep))
except Exception as ex: print('E_ISOG_EVELU_ERR',repr(ex))
Epin=EllipticCurve(K,[1,a^2+a-3,a^2+a-1,4-a^2,-a-2])
print('EPIN',Epin.a_invariants(),Epin.discriminant(),Epin.j_invariant())
try:
    print('EVELU_ISOM_EPIN',Ep.is_isomorphic(Epin))
    if Ep.is_isomorphic(Epin):
        iso=Ep.isomorphism_to(Epin)
        print('EVELU_TO_EPIN',iso)
        try: print('EVELU_TO_EPIN_URST',iso.tuple())
        except Exception as ex: print('URST_ERR',repr(ex))
        try: print('EVELU_TO_EPIN_RATMAPS',iso.rational_maps())
        except Exception as ex: print('ISO_MAP_ERR',repr(ex))
except Exception as ex: print('EVELU_EPIN_ERR',repr(ex))
S=[fac[0] for fac in K.ideal(2).factor()]+[fac[0] for fac in K.ideal(3).factor()]
print('S_PRIMES',S)
try:
    SG=K.S_unit_group(S=S)
    print('SUNIT_GROUP',SG)
    print('SUNIT_GENS_VALUES',SG.gens_values())
except Exception as ex: print('SUNIT_ERR',repr(ex))
try: print('SELMER_3',K.selmer_group(S,3))
except Exception as ex: print('SELMER_ERR',repr(ex))
print('Q4517_END')