import FLT.Assumptions.MazurProof.N25F_InfinityFunctionField

#print axioms MazurProof.N25F_InfinityFunctionField.affinePolynomialBaseToField
#print axioms MazurProof.N25F_InfinityFunctionField.affinePolynomialBaseToField_injective
#print axioms MazurProof.N25F_InfinityFunctionField.affineRationalBaseToField
#print axioms MazurProof.N25F_InfinityFunctionField.affineRationalBaseToField_algebraMap
#print axioms MazurProof.N25F_InfinityFunctionField.affineRationalBaseToField_variable
#print axioms MazurProof.N25F_InfinityFunctionField.infinityRationalBaseToField
#print axioms MazurProof.N25F_InfinityFunctionField.infinityRationalBaseToField_comp_algebraMap
#print axioms MazurProof.N25F_InfinityFunctionField.infinityRationalBaseToField_algebraMap
#print axioms MazurProof.N25F_InfinityFunctionField.affineRationalBaseToField_finrank
#print axioms MazurProof.N25F_InfinityFunctionField.infinityRationalBaseToField_finite_finrank
