import FLT.Assumptions.MazurProof.N25F_InfinityNormalization
import FLT.Assumptions.MazurProof.N25F_IntegralBoundaryFactor

#print axioms MazurProof.N25F_InfinityNormalization.infinityPolynomialAlgebra
#print axioms MazurProof.N25F_InfinityNormalization.infinityRationalAlgebra
#print axioms MazurProof.N25F_InfinityNormalization.InfinityNormalization
#print axioms MazurProof.N25F_InfinityNormalization.infinityNormalization_finite
#print axioms MazurProof.N25F_InfinityNormalization.infinityNormalization_isFractionRing
#print axioms MazurProof.N25F_InfinityNormalization.infinityNormalization_isDedekindDomain
#print axioms MazurProof.N25F_InfinityNormalization.infinityNormalization_finrank_eq_four
#print axioms MazurProof.N25F_IntegralBoundaryFactor.exists_preimage
#print axioms MazurProof.N25F_IntegralBoundaryFactor.integralClosureToRing
#print axioms MazurProof.N25F_IntegralBoundaryFactor.algebraMap_integralClosureToRing
#print axioms MazurProof.N25F_IntegralBoundaryFactor.toAlgHom_comp_integralClosureToRing
#print axioms MazurProof.N25F_IntegralBoundaryFactor.integralClosureToRing_injective
#print axioms MazurProof.N25F_IntegralBoundaryFactor.integralClosureToRing_unique
