import FLT.Assumptions.MazurProof.N25F_ProjectivePrincipalAddition

#print axioms MazurProof.N25F_PrincipalOrderAddition.log_ordFrac_add_ge_min
#print axioms MazurProof.N25F_PrincipalOrderAddition.count_spanSingleton_eq_log_ordFrac
#print axioms MazurProof.N25F_PrincipalOrderAddition.count_spanSingleton_add_ge_min
#print axioms MazurProof.N25F_ProjectivePrincipalCoefficients.projectivePrincipalDivisor_apply_X
#print axioms MazurProof.N25F_ProjectivePrincipalCoefficients.projectivePrincipalDivisor_apply_YZ
#print axioms MazurProof.N25F_ProjectivePrincipalCoefficients.projectivePrincipalDivisor_apply_Z
#print axioms MazurProof.N25F_ProjectivePrincipalCoefficients.projectivePrincipalDivisor_apply_nonBoundary
#print axioms MazurProof.N25F_ProjectivePrincipalAddition.projectivePrincipalDivisor_add_ge_min
