from pathlib import Path
import re, json, hashlib, shutil

root = Path('/workspace/shared/flt-n25-xlocal-dvr')
iso = Path('/workspace/shared/flt-n25-xchart-iso')
fmap = Path('/workspace/shared/flt-n25-xchart-map')
for p in (iso / 'sources').glob('*.lean'):
    shutil.copyfile(p, root / 'sources' / p.name)

s = (iso / 'XChartEquivCheck.lean').read_text().split('namespace MazurProof.N25F_XChartWChartEquiv')[0]
s = 'import Mathlib.RingTheory.DedekindDomain.Dvr\nimport Mathlib.Algebra.Field.ZMod\n' + s
for directory, file, namespace in [
    (iso, 'N25F_XChartWChartEquiv.lean', 'N25F_XChartWChartEquiv'),
    (fmap, 'N25F_XChartFractionMap.lean', 'N25F_XChartFractionMap')]:
    raw = (directory / file).read_text()
    body = raw[raw.index('namespace MazurProof.' + namespace):]
    anchor = ('/-- The actual X-chart ring is a domain' if namespace == 'N25F_XChartWChartEquiv'
              else '/-- The X/W coordinate stays nonzero')
    body = body.replace(anchor, 'variable [IsDedekindDomain W]\n\n' + anchor)
    s += body + '\n\n'

src = (root / 'sources/RationalPointsN25QuotientTwoWBoundaryXLocal.lean').read_text()
ns = 'MazurProof.RationalPointsN25QuotientTwoWBoundaryXLocal'
s += 'namespace ' + ns + '\n\n'
for name in ['RationalPointsN25QuotientTwoAffineCharts',
             'RationalPointsN25QuotientTwoAffineChartsSmooth',
             'RationalPointsN25QuotientTwoConormal',
             'RationalPointsN25QuotientTwoWBoundaryChartArtin']:
    s += 'open MazurProof.' + name + '\n'
s += '\nlocal notation "k₂" => ZMod 2\n\n'
ranges = [(src.index('abbrev XAffineRing'), src.index('theorem xWIdeal_le_xPrime')),
          (src.index('abbrev XLocalRing'), src.index('private noncomputable def xLocalToBoundary')),
          (src.index('noncomputable def xWGerm :'), src.index('/-- The principal ideal generated by the germ'))]
copied = json.loads((iso / 'copied-declarations.json').read_text())
for a, b in ranges:
    raw = src[a:b]
    s += raw + '\n'
    copied.append(dict(file='RationalPointsN25QuotientTwoWBoundaryXLocal.lean',
                       start_line=src[:a].count('\n') + 1,
                       end_line=src[:b].count('\n') + 1,
                       sha256=hashlib.sha256(raw.encode()).hexdigest()))
s += 'end ' + ns + '\n\n'
prod = (root / 'N25F_XLocalDVR.lean').read_text()
body = prod[prod.index('namespace MazurProof.N25F_XLocalDVR'):]
body = body.replace('/-- The actual X chart inherits Dedekind structure',
                    'variable [IsDedekindDomain W]\n\n/-- The actual X chart inherits Dedekind structure')
s += body + '\n\n'
for name in ['xChartRing_isDedekindDomain', 'xW_ne_zero', 'xW_mem_xPrime',
             'xPrime_ne_bot', 'xLocalRing_isDiscreteValuationRing', 'xWGerm_ne_zero']:
    s += '#check @MazurProof.N25F_XLocalDVR.' + name + '\n'
    s += '#print axioms MazurProof.N25F_XLocalDVR.' + name + '\n'
(root / 'XLocalDVRCheck.lean').write_text(s)
(root / 'copied-declarations.json').write_text(json.dumps(copied, indent=2) + '\n')
print('Generated', len(s), 'bytes')
