import FLT.Assumptions.MazurProof.N25F_InfinityPrimeContraction
import FLT.Assumptions.MazurProof.N25F_InfinityParameterOrders

#print axioms MazurProof.N25F_InfinityBoundaryAlgebras.xInfinityBaseAlgebra
#print axioms MazurProof.N25F_InfinityBoundaryAlgebras.yzInfinityBaseAlgebra
#print axioms MazurProof.N25F_InfinityBoundaryAlgebras.zInfinityBaseAlgebra
#print axioms MazurProof.N25F_InfinityBoundaryAlgebras.xInfinityNormalizationAlgebra
#print axioms MazurProof.N25F_InfinityBoundaryAlgebras.yzInfinityNormalizationAlgebra
#print axioms MazurProof.N25F_InfinityBoundaryAlgebras.zInfinityNormalizationAlgebra
#print axioms MazurProof.N25F_InfinityPrimeContraction.contraction_eq_span_X
#print axioms MazurProof.N25F_InfinityPrimeContraction.infinityBasePrime
#print axioms MazurProof.N25F_InfinityPrimeContraction.infinityBasePrime_isMaximal
#print axioms MazurProof.N25F_InfinityPrimeContraction.xInfinityPrime_under
#print axioms MazurProof.N25F_InfinityPrimeContraction.xInfinityPrime_liesOver
#print axioms MazurProof.N25F_InfinityPrimeContraction.yzInfinityPrime_under
#print axioms MazurProof.N25F_InfinityPrimeContraction.yzInfinityPrime_liesOver
#print axioms MazurProof.N25F_InfinityPrimeContraction.zInfinityPrime_under
#print axioms MazurProof.N25F_InfinityPrimeContraction.zInfinityPrime_liesOver
#print axioms MazurProof.N25F_InfinityParameterOrders.infinityNormalizationToX_parameter
#print axioms MazurProof.N25F_InfinityParameterOrders.xInfinityParameter_order
#print axioms MazurProof.N25F_InfinityParameterOrders.infinityNormalizationToYZ_parameter
#print axioms MazurProof.N25F_InfinityParameterOrders.yzInfinityParameter_order
#print axioms MazurProof.N25F_InfinityParameterOrders.infinityNormalizationToZ_parameter
#print axioms MazurProof.N25F_InfinityParameterOrders.zInfinityParameter_order
#print axioms MazurProof.N25F_InfinityParameterOrders.xInfinityPrime_ne_zInfinityPrime
#print axioms MazurProof.N25F_InfinityParameterOrders.yzInfinityPrime_ne_zInfinityPrime
