import FLT.Assumptions.MazurProof.N25F_XSectionDimension

#print axioms MazurProof.N25F_BinaryResidueCancellation.log_ordFrac_sub_gt_of_log_eq
#print axioms MazurProof.N25F_XSectionFiltration.fullRiemannRochSpace25Two_sub_X_le
#print axioms MazurProof.N25F_XSectionFiltration.mem_fullRiemannRochSpace25Two_sub_X_iff
#print axioms MazurProof.N25F_XSectionFiltration.xBoundaryOrder_eq_neg_of_not_mem_sub_X
#print axioms MazurProof.N25F_XSectionFiltration.sub_mem_fullRiemannRochSpace25Two_sub_X
#print axioms MazurProof.N25F_XSectionDimension.fullRiemannRochSpace25Two_eq_sub_X_sup_span
#print axioms MazurProof.N25F_XSectionDimension.finrank_fullRiemannRochSpace25Two_le_sub_X_add_one
#print axioms MazurProof.N25F_XSectionDimension.finrank_fullRiemannRochSpace25Two_le_degree_add_one
#print axioms MazurProof.N25F_XSectionDimension.finrank_fullRiemannRochSpace25Two_X_quotient_le_one
