import FLT.Assumptions.MazurProof.N25F_InfinityResidueFields
import FLT.Assumptions.MazurProof.N25F_InfinityRamificationIndices

#print axioms MazurProof.N25F_InfinityResidueFields.residueRingEquivOfQuotient
#print axioms MazurProof.N25F_InfinityResidueFields.residueRingEquivOfEq
#print axioms MazurProof.N25F_InfinityResidueFields.finrank_eq_one_of_binary_ringEquivs
#print axioms MazurProof.N25F_InfinityResidueFields.inertiaDeg_eq_one_of_binary_ringEquivs
#print axioms MazurProof.N25F_InfinityResidueFields.xLocalResidueRingEquivF2
#print axioms MazurProof.N25F_InfinityResidueFields.xInfinityResidueRingEquivF2
#print axioms MazurProof.N25F_InfinityResidueFields.yzLocalResidueRingEquivF2
#print axioms MazurProof.N25F_InfinityResidueFields.yzInfinityResidueRingEquivF2
#print axioms MazurProof.N25F_InfinityResidueFields.zLocalResidueRingEquivF2
#print axioms MazurProof.N25F_InfinityResidueFields.zInfinityResidueRingEquivF2
#print axioms MazurProof.N25F_InfinityResidueFields.infinityBaseResidueRingEquivF2
#print axioms MazurProof.N25F_InfinityResidueFields.xInfinityPrime_inertiaDeg_eq_one
#print axioms MazurProof.N25F_InfinityResidueFields.yzInfinityPrime_inertiaDeg_eq_one
#print axioms MazurProof.N25F_InfinityResidueFields.zInfinityPrime_inertiaDeg_eq_one
#print axioms MazurProof.N25F_InfinityRamificationIndices.ramificationIdx_eq_of_parameter_order
#print axioms MazurProof.N25F_InfinityRamificationIndices.xInfinityPrime_ramificationIdx_eq_one
#print axioms MazurProof.N25F_InfinityRamificationIndices.yzInfinityPrime_ramificationIdx_eq_one
#print axioms MazurProof.N25F_InfinityRamificationIndices.zInfinityPrime_ramificationIdx_eq_two
