import FLT.Assumptions.MazurProof.N25F_InfinityBoundaryMaps
import FLT.Assumptions.MazurProof.N25F_LocalValuationRigidity

#print axioms MazurProof.N25F_InfinityBoundaryMaps.infinityNormalizationToX
#print axioms MazurProof.N25F_InfinityBoundaryMaps.xLocalToFraction_infinityNormalizationToX
#print axioms MazurProof.N25F_InfinityBoundaryMaps.infinityNormalizationToX_injective
#print axioms MazurProof.N25F_InfinityBoundaryMaps.infinityNormalizationToYZ
#print axioms MazurProof.N25F_InfinityBoundaryMaps.yzLocalToFraction_infinityNormalizationToYZ
#print axioms MazurProof.N25F_InfinityBoundaryMaps.infinityNormalizationToYZ_injective
#print axioms MazurProof.N25F_InfinityBoundaryMaps.infinityNormalizationToZ
#print axioms MazurProof.N25F_InfinityBoundaryMaps.zLocalToFraction_infinityNormalizationToZ
#print axioms MazurProof.N25F_InfinityBoundaryMaps.infinityNormalizationToZ_injective
#print axioms MazurProof.N25F_LocalValuationRigidity.bijective_of_local_same_fraction_field
