import FLT.Assumptions.MazurProof.N25F_WAffineConditionCost

#print axioms MazurProof.N25F_DedekindOrderMembership.fractionalIdeal_le_one_of_count_nonneg
#print axioms MazurProof.N25F_DedekindOrderMembership.fractionalIdeal_le_of_count_le
#print axioms MazurProof.N25F_DedekindOrderMembership.existsUnique_algebraMap_eq_of_count_nonneg
#print axioms MazurProof.N25F_DedekindOrderMembership.mem_fractionalIdeal_iff_count_le
#print axioms MazurProof.N25F_WRegularSectionLift.existsUnique_wChart_lift_of_mem_basePole_space
#print axioms MazurProof.N25F_WRegularSectionLift.wRegularSectionLift25Two
#print axioms MazurProof.N25F_WRegularSectionLift.algebraMap_wRegularSectionLift25Two
#print axioms MazurProof.N25F_WRegularSectionLift.wRegularSectionLiftLinearMap25Two
#print axioms MazurProof.N25F_WRegularSectionLift.wRegularSectionLiftLinearMap25Two_injective
#print axioms MazurProof.N25F_WAffineConditionCost.wSectionIdealQuotient25Two
#print axioms MazurProof.N25F_WAffineConditionCost.wSectionIdealQuotient25Two_eq_zero_iff
#print axioms MazurProof.N25F_WAffineConditionCost.wSectionIdealQuotient25Two_eq_zero_iff_orders
#print axioms MazurProof.N25F_WAffineConditionCost.finrank_basePole_le_kernel_add_ideal_quotient
#print axioms MazurProof.N25F_WAffineConditionCost.finrank_basePole_le_kernel_add_weighted_affine_cost
