import Mathlib.RingTheory.DedekindDomain.Factorization

/-!
# Divisors from Dedekind-domain factorization

For a Dedekind domain, every nonzero fractional ideal has a finite height-one
valuation vector.  This file packages that vector as a `Finsupp`, proves that
it determines the fractional ideal, and constructs the subgroup of principal
divisors from nonzero elements of the fraction field.

This is the affine algebra underlying the divisor-class input used by the
curve zeta argument.  Applying it to a projective curve still requires the
geometric comparison between its closed points and height-one local data,
including the points outside any chosen affine chart.
-/

open scoped nonZeroDivisors

open IsDedekindDomain

noncomputable section

namespace MazurProof.CurveDedekindDivisor

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
variable {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]

/-- A Weil divisor on the spectrum of a Dedekind domain is a finite integer
combination of its height-one prime ideals. -/
abbrev Divisor := HeightOneSpectrum R →₀ ℤ

/-- The height-one valuation vector of a fractional ideal.  The finite support
is supplied by Dedekind factorization. -/
def fractionalIdealDivisor (I : FractionalIdeal R⁰ K) : Divisor (R := R) := by
  let support : Set (HeightOneSpectrum R) :=
    {v | FractionalIdeal.count K v I ≠ 0}
  have hsupport : support.Finite := by
    exact Filter.eventually_cofinite.mp (FractionalIdeal.finite_factors (K := K) I)
  exact Finsupp.onFinset hsupport.toFinset
    (fun v ↦ FractionalIdeal.count K v I)
    (fun v hv ↦ hsupport.mem_toFinset.mpr hv)

@[simp]
theorem fractionalIdealDivisor_apply (I : FractionalIdeal R⁰ K)
    (v : HeightOneSpectrum R) :
    fractionalIdealDivisor I v = FractionalIdeal.count K v I := by
  rfl

/-- Multiplication of nonzero fractional ideals adds their valuation vectors. -/
theorem fractionalIdealDivisor_mul {I J : FractionalIdeal R⁰ K}
    (hI : I ≠ 0) (hJ : J ≠ 0) :
    fractionalIdealDivisor (I * J) =
      fractionalIdealDivisor I + fractionalIdealDivisor J := by
  ext v
  simp only [fractionalIdealDivisor_apply, Finsupp.add_apply]
  exact FractionalIdeal.count_mul K v hI hJ

/-- Nonzero fractional ideals are determined by their height-one valuation
vectors.  This is the uniqueness half of Dedekind factorization in divisor
form. -/
theorem fractionalIdealDivisor_injectiveOn_nonzero
    {I J : FractionalIdeal R⁰ K} (hI : I ≠ 0) (hJ : J ≠ 0)
    (hdiv : fractionalIdealDivisor I = fractionalIdealDivisor J) : I = J := by
  calc
    I = ∏ᶠ v : HeightOneSpectrum R,
        (v.asIdeal : FractionalIdeal R⁰ K) ^ FractionalIdeal.count K v I :=
      (FractionalIdeal.finprod_heightOneSpectrum_factorization' K hI).symm
    _ = ∏ᶠ v : HeightOneSpectrum R,
        (v.asIdeal : FractionalIdeal R⁰ K) ^ FractionalIdeal.count K v J := by
      apply finprod_congr
      intro v
      congr 1
      simpa only [fractionalIdealDivisor_apply] using DFunLike.congr_fun hdiv v
    _ = J := FractionalIdeal.finprod_heightOneSpectrum_factorization' K hJ

/-- Principal fractional ideals define an additive homomorphism from nonzero
functions under multiplication to height-one divisors. -/
def principalDivisor : Additive Kˣ →+ Divisor (R := R) where
  toFun x := fractionalIdealDivisor
    (FractionalIdeal.spanSingleton R⁰ (x.toMul : K))
  map_zero' := by
    ext v
    change FractionalIdeal.count K v
      (FractionalIdeal.spanSingleton R⁰ (1 : K)) = 0
    rw [FractionalIdeal.spanSingleton_one, FractionalIdeal.count_one]
  map_add' x y := by
    change fractionalIdealDivisor
      (FractionalIdeal.spanSingleton R⁰ ((x.toMul * y.toMul : Kˣ) : K)) = _
    rw [Units.val_mul, ← FractionalIdeal.spanSingleton_mul_spanSingleton]
    apply fractionalIdealDivisor_mul
    · exact FractionalIdeal.spanSingleton_ne_zero_iff.mpr x.toMul.ne_zero
    · exact FractionalIdeal.spanSingleton_ne_zero_iff.mpr y.toMul.ne_zero

/-- The subgroup generated by divisors of nonzero fraction-field elements. -/
def principalDivisors : AddSubgroup (Divisor (R := R)) :=
  (principalDivisor (R := R) (K := K)).range

end MazurProof.CurveDedekindDivisor
