import Mathlib.RingTheory.DedekindDomain.Factorization
import Mathlib.Algebra.Order.BigOperators.Group.Finset
open scoped nonZeroDivisors

open IsDedekindDomain

noncomputable section

namespace MazurProof.CurveDedekindDivisor

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
variable {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]

/-- A Weil divisor on the spectrum of a Dedekind domain is a finite integer
combination of its height-one prime ideals. -/
abbrev Divisor := HeightOneSpectrum R →₀ ℤ

/-- The height-one valuation vector of a fractional ideal.  The finite support
is supplied by Dedekind factorization. -/
def fractionalIdealDivisor (I : FractionalIdeal R⁰ K) : Divisor (R := R) := by
  let support : Set (HeightOneSpectrum R) :=
    {v | FractionalIdeal.count K v I ≠ 0}
  have hsupport : support.Finite := by
    exact Filter.eventually_cofinite.mp (FractionalIdeal.finite_factors (K := K) I)
  exact Finsupp.onFinset hsupport.toFinset
    (fun v ↦ FractionalIdeal.count K v I)
    (fun v hv ↦ hsupport.mem_toFinset.mpr hv)

@[simp]
theorem fractionalIdealDivisor_apply (I : FractionalIdeal R⁰ K)
    (v : HeightOneSpectrum R) :
    fractionalIdealDivisor I v = FractionalIdeal.count K v I := by
  rfl

/-- Multiplication of nonzero fractional ideals adds their valuation vectors. -/
theorem fractionalIdealDivisor_mul {I J : FractionalIdeal R⁰ K}
    (hI : I ≠ 0) (hJ : J ≠ 0) :
    fractionalIdealDivisor (I * J) =
      fractionalIdealDivisor I + fractionalIdealDivisor J := by
  ext v
  simp only [fractionalIdealDivisor_apply, Finsupp.add_apply]
  exact FractionalIdeal.count_mul K v hI hJ

/-- Nonzero fractional ideals are determined by their height-one valuation
vectors.  This is the uniqueness half of Dedekind factorization in divisor
form. -/
theorem fractionalIdealDivisor_injectiveOn_nonzero
    {I J : FractionalIdeal R⁰ K} (hI : I ≠ 0) (hJ : J ≠ 0)
    (hdiv : fractionalIdealDivisor I = fractionalIdealDivisor J) : I = J := by
  calc
    I = ∏ᶠ v : HeightOneSpectrum R,
        (v.asIdeal : FractionalIdeal R⁰ K) ^ FractionalIdeal.count K v I :=
      (FractionalIdeal.finprod_heightOneSpectrum_factorization' K hI).symm
    _ = ∏ᶠ v : HeightOneSpectrum R,
        (v.asIdeal : FractionalIdeal R⁰ K) ^ FractionalIdeal.count K v J := by
      apply finprod_congr
      intro v
      congr 1
      simpa only [fractionalIdealDivisor_apply] using DFunLike.congr_fun hdiv v
    _ = J := FractionalIdeal.finprod_heightOneSpectrum_factorization' K hJ

/-- Principal fractional ideals define an additive homomorphism from nonzero
functions under multiplication to height-one divisors. -/
def principalDivisor : Additive Kˣ →+ Divisor (R := R) where
  toFun x := fractionalIdealDivisor
    (FractionalIdeal.spanSingleton R⁰ (x.toMul : K))
  map_zero' := by
    ext v
    change FractionalIdeal.count K v
      (FractionalIdeal.spanSingleton R⁰ (1 : K)) = 0
    rw [FractionalIdeal.spanSingleton_one, FractionalIdeal.count_one]
  map_add' x y := by
    change fractionalIdealDivisor
      (FractionalIdeal.spanSingleton R⁰ ((x.toMul * y.toMul : Kˣ) : K)) = _
    rw [Units.val_mul, ← FractionalIdeal.spanSingleton_mul_spanSingleton]
    apply fractionalIdealDivisor_mul
    · exact FractionalIdeal.spanSingleton_ne_zero_iff.mpr x.toMul.ne_zero
    · exact FractionalIdeal.spanSingleton_ne_zero_iff.mpr y.toMul.ne_zero

/-- The subgroup generated by divisors of nonzero fraction-field elements. -/
def principalDivisors : AddSubgroup (Divisor (R := R)) :=
  (principalDivisor (R := R) (K := K)).range

end MazurProof.CurveDedekindDivisor
/-! Exact affine integrality and ideal membership from all genuine Dedekind orders. -/
set_option synthInstance.maxHeartbeats 200000
set_option autoImplicit false
set_option relaxedAutoImplicit false
noncomputable section
open scoped nonZeroDivisors
namespace MazurProof.N25F_DedekindOrderMembership
open CurveDedekindDivisor

variable {R K : Type*} [CommRing R] [IsDedekindDomain R]
  [Field K] [Algebra R K] [IsFractionRing R K]

/-- Nonnegative coefficients force a genuine fractional ideal to be integral. -/
theorem fractionalIdeal_le_one_of_count_nonneg (I : FractionalIdeal R⁰ K) (hI : I ≠ 0)
    (hc : ∀ v : IsDedekindDomain.HeightOneSpectrum R, 0 ≤ FractionalIdeal.count K v I) :
    I ≤ 1 := by
  classical
  let d := fractionalIdealDivisor I
  let J : FractionalIdeal R⁰ K := d.prod fun v m => (v.asIdeal : FractionalIdeal R⁰ K) ^ m
  have hJ : J ≠ 0 := by
    apply Finsupp.prod_ne_zero_iff.mpr
    intro v hv
    exact zpow_ne_zero _ (FractionalIdeal.coeIdeal_ne_zero.mpr v.ne_bot)
  have he : I = J := by
    apply fractionalIdealDivisor_injectiveOn_nonzero hI hJ
    ext v
    exact (FractionalIdeal.count_finsuppProd K v d).symm
  rw [he]
  change d.prod (fun v m => (v.asIdeal : FractionalIdeal R⁰ K) ^ m) ≤ 1
  rw [Finsupp.prod]
  apply Finset.prod_le_one'
  intro v hv
  have hd : 0 ≤ d v := hc v
  have hn : d v = ((d v).toNat : ℤ) := (Int.natCast_toNat_eq_self.mpr hd).symm
  rw [hn, zpow_natCast, ← FractionalIdeal.coeIdeal_pow]
  exact FractionalIdeal.coeIdeal_le_one

/-- The converse to order monotonicity, proved from actual fractional-ideal factorization. -/
theorem fractionalIdeal_le_of_count_le (I J : FractionalIdeal R⁰ K)
    (hI : I ≠ 0) (hJ : J ≠ 0)
    (hc : ∀ v : IsDedekindDomain.HeightOneSpectrum R,
      FractionalIdeal.count K v J ≤ FractionalIdeal.count K v I) : I ≤ J := by
  have hprod : I * J⁻¹ ≤ 1 :=
    fractionalIdeal_le_one_of_count_nonneg _ (mul_ne_zero hI (inv_ne_zero hJ)) (by
      intro v
      rw [FractionalIdeal.count_mul K v hI (inv_ne_zero hJ), FractionalIdeal.count_inv]
      exact sub_nonneg.mpr (hc v))
  have h := mul_le_mul_right' hprod J
  simpa only [mul_assoc, inv_mul_cancel₀ hJ, mul_one, one_mul] using h

/-- All nonnegative affine orders recover a unique real element of the original ring. -/
theorem existsUnique_algebraMap_eq_of_count_nonneg (f : K)
    (hc : ∀ v : IsDedekindDomain.HeightOneSpectrum R,
      0 ≤ FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ f)) :
    ∃! a : R, algebraMap R K a = f := by
  have hex : ∃ a : R, algebraMap R K a = f := by
    by_cases hf : f = 0
    · exact ⟨0, by rw [map_zero, hf]⟩
    apply (FractionalIdeal.mem_one_iff R⁰).mp
    exact fractionalIdeal_le_one_of_count_nonneg _
      (FractionalIdeal.spanSingleton_ne_zero_iff.mpr hf) hc
      (FractionalIdeal.mem_spanSingleton_self R⁰ f)
  obtain ⟨a, ha⟩ := hex
  exact ⟨a, ha, fun b hb => IsFractionRing.injective R K (hb.trans ha.symm)⟩

/-- Membership in a genuine nonzero fractional ideal is exactly the full set of order inequalities. -/
theorem mem_fractionalIdeal_iff_count_le (I : FractionalIdeal R⁰ K) (hI : I ≠ 0)
    (f : K) (hf : f ≠ 0) : f ∈ I ↔
      ∀ v : IsDedekindDomain.HeightOneSpectrum R,
        FractionalIdeal.count K v I ≤
          FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ f) := by
  rw [← FractionalIdeal.spanSingleton_le_iff_mem]
  constructor
  · intro h v
    exact FractionalIdeal.count_mono K v (FractionalIdeal.spanSingleton_ne_zero_iff.mpr hf) h
  · exact fractionalIdeal_le_of_count_le _ I (FractionalIdeal.spanSingleton_ne_zero_iff.mpr hf) hI

end MazurProof.N25F_DedekindOrderMembership

#print axioms MazurProof.N25F_DedekindOrderMembership.fractionalIdeal_le_one_of_count_nonneg
#print axioms MazurProof.N25F_DedekindOrderMembership.fractionalIdeal_le_of_count_le
#print axioms MazurProof.N25F_DedekindOrderMembership.existsUnique_algebraMap_eq_of_count_nonneg
#print axioms MazurProof.N25F_DedekindOrderMembership.mem_fractionalIdeal_iff_count_le
