import FLT.Assumptions.MazurProof.N25F_WPolynomialWindow

#print axioms MazurProof.N25F_PolynomialBasisWindow.polynomial_basis_window_linearIndependent
#print axioms MazurProof.N25F_SectionMultiplication.fullRiemannRochSpace25Two_mono
#print axioms MazurProof.N25F_SectionMultiplication.mul_mem_fullRiemannRochSpace25Two
#print axioms MazurProof.N25F_BasePolePowers.basePoleDivisor25Two_nonneg
#print axioms MazurProof.N25F_BasePolePowers.qz_mem_basePole_section_space
#print axioms MazurProof.N25F_BasePolePowers.qz_pow_mem_basePole_section_space
#print axioms MazurProof.N25F_WPolynomialWindow.wPolynomialWindow25Two
#print axioms MazurProof.N25F_WPolynomialWindow.wPolynomialWindow25Two_linearIndependent
#print axioms MazurProof.N25F_WPolynomialWindow.wPolynomialWindow25Two_mem
#print axioms MazurProof.N25F_WPolynomialWindow.four_mul_succ_le_finrank_basePole_space
#print axioms MazurProof.N25F_WPolynomialWindow.four_mul_le_finrank_basePole_add_constant
