import FLT.Assumptions.MazurProof.N25F_ProjectiveProductFormula

#print axioms MazurProof.N25F_NormBaseTwist.norm_twist
#print axioms MazurProof.N25F_InfinityAffineNormComparison.affineFieldNorm
#print axioms MazurProof.N25F_InfinityAffineNormComparison.infinity_norm_eq_baseInversion_affine_norm
#print axioms MazurProof.N25F_BaseInversionOrder.baseVariable_inverse_fractionOrder
#print axioms MazurProof.N25F_BaseInversionOrder.baseInversion_polynomial_order
#print axioms MazurProof.N25F_AffineNormPolynomial.affineFieldNorm_algebraMap
#print axioms MazurProof.N25F_ProjectiveProductFormula.projectivePrincipalDivisor_degree_regular
#print axioms MazurProof.N25F_ProjectiveProductFormula.projectivePrincipalDivisor_degree_eq_zero
