import FLT.Assumptions.MazurProof.N25F_ProjectivePrincipalDivisor

#print axioms MazurProof.N25F_ProjectivePrincipalDivisor.boundaryPrincipalOrders
#print axioms MazurProof.N25F_ProjectivePrincipalDivisor.projectivePrincipalDivisor
#print axioms MazurProof.N25F_ProjectivePrincipalDivisor.projectivePrincipalDivisor_split
#print axioms MazurProof.N25F_ProjectivePrincipalDivisor.projectivePrincipalDivisor_degree
#print axioms MazurProof.N25F_ProjectivePrincipalDivisor.basePolynomial_inFunctionField
#print axioms MazurProof.N25F_ProjectivePrincipalDivisor.projectivePrincipalDivisor_degree_base_polynomial
