import FLT.Assumptions.MazurProof.N25F_BoundarySectionFiltration
#print axioms MazurProof.N25F_BoundarySectionFiltration.boundary_principal_sub_gt_of_eq
#print axioms MazurProof.N25F_BoundarySectionFiltration.fullRiemannRochSpace25Two_sub_boundary_le
#print axioms MazurProof.N25F_BoundarySectionFiltration.mem_fullRiemannRochSpace25Two_sub_boundary_iff
#print axioms MazurProof.N25F_BoundarySectionFiltration.boundary_principal_eq_neg_of_not_mem
#print axioms MazurProof.N25F_BoundarySectionFiltration.sub_mem_fullRiemannRochSpace25Two_sub_boundary
#print axioms MazurProof.N25F_BoundarySectionFiltration.finrank_fullRiemannRochSpace25Two_le_sub_boundary_add_one
#print axioms MazurProof.N25F_BoundarySectionFiltration.finrank_fullRiemannRochSpace25Two_le_sub_boundary_multiple
