import FLT.Assumptions.MazurProof.N25F_AffineNonpositiveRepresentative

#print axioms MazurProof.N25F_DedekindPrincipalMajorant.exists_nonzero_regular_with_count_ge
#print axioms MazurProof.N25F_AffineNonpositiveRepresentative.exists_principal_affine_majorant25Two
#print axioms MazurProof.N25F_AffineNonpositiveRepresentative.affineNonpositiveRepresentative25Two
#print axioms MazurProof.N25F_AffineNonpositiveRepresentative.affineNonpositiveRepresentative25Two_nonBoundary
#print axioms MazurProof.N25F_AffineNonpositiveRepresentative.affineNonpositiveRepresentative25Two_degree
#print axioms MazurProof.N25F_AffineNonpositiveRepresentative.affineNonpositiveRepresentative25Two_classOf
#print axioms MazurProof.N25F_AffineNonpositiveRepresentative.affineNonpositiveRepresentative25Two_finrank
#print axioms MazurProof.N25F_AffineNonpositiveRepresentative.affineNonpositiveRepresentative25Two_le_basePole_multiple
#print axioms MazurProof.N25F_AffineNonpositiveRepresentative.affineRepresentative_complement_degree
