-- TASK: Prove this lemma (the last axiom in DescentN12.lean):
--
-- theorem N12_quartic (a b : Z) (ha : a^2 >= 2) :
--     b^2 = 3*a^4 + 2*a^2 - 1 -> False
--
-- REFERENCE: see scratch/DescentN14.lean, the lemma no_sol_2a4_a2_m1.
-- That proves b^2 = 2a^4+a^2-1 -> False using:
--   rcases Int.even_or_odd a with <c, rfl> | <c, rfl> <;>
--   rcases Int.even_or_odd b with <d, rfl> | <d, rfl>
--   then nlinarith to expand, omega to close.
--
-- For THIS quartic 3a^4+2a^2-1:
-- a even: 3*(2c)^4+2*(2c)^2-1 = 48c^4+8c^2-1. Mod 4: 0+0-1 = 3. Not QR mod 4.
-- a odd: 3*(2c+1)^4+2*(2c+1)^2-1. Expand and check mod 4 or mod 8.
--
-- Write COMPLETE self-contained Lean 4 file. 0 sorry, 0 axiom.
-- import Mathlib.