-- TASK: Prove int_solutions_N12 for the curve w² = (u-1)(u-2)(u+2).
-- Degenerate set: {-2, 0, 1, 2, 4}.
--
-- REFERENCE: see scratch/Descent20a4.lean in this repo for the pattern.
-- That file proves int_solutions_20a4 for w² = u(u²+u-1) using:
--   1. IsCoprime via Bezout witness
--   2. Int.sq_of_isCoprime to decompose coprime product = square
--   3. Squeeze between consecutive squares (nlinarith [sq_nonneg ...])
--
-- For N=12: three rational roots, so split on gcd(u-1, -3).
-- Small cases u in {-2,-1,0,1,2,3,4} check directly.
-- u <= -3: product of three negatives < 0.
-- u >= 5: coprime descent.