import Mathlib

#check AdjoinRoot.root
#check AdjoinRoot.mk
#check AdjoinRoot.of
#check AdjoinRoot.lift
#check AdjoinRoot.powerBasis'
#check AdjoinRoot.isDomain_of_prime
#check Polynomial.SplittingField
#check IsPrimitiveRoot
#check IsPrimitiveRoot.pow_eq_one_iff_dvd
#check WeierstrassCurve.VariableChange
#check WeierstrassCurve.variableChange_Δ
#check WeierstrassCurve.map_variableChange
#check ClassGroup
#check ClassGroup.mk
#check ClassGroup.mk_eq_mk
#check ClassGroup.mk_eq_one_iff
#check FractionalIdeal.mk0
#check ClassGroup.mk0
#check ClassGroup.extendedHom
#check ClassGroup.extendedHom_mk
#check ClassGroup.equivPic
#check WeierstrassCurve.Affine.CoordinateRing.XYIdeal'
#check WeierstrassCurve.Affine.Point.toClass
#check WeierstrassCurve.Affine.Point.toClass_injective
#check WeierstrassCurve.Affine.Point.map
#check WeierstrassCurve.Affine.Point.map_injective
#check AddMonoidHom.id
#check AddMonoidHom.comp
#check AddMonoidHom.ker
#check AddSubgroup
#check ZMod
#check ZMod.charP
#check WeierstrassCurve.Ψ₃
#check WeierstrassCurve.ψ
#check WeierstrassCurve.Φ
#check FormalGroup
#check FormalGroup.map
#check WeierstrassCurve.IsIntegral
#check WeierstrassCurve.IsMinimal
#check WeierstrassCurve.reduction
#check WeierstrassCurve.HasGoodReduction
#check WeierstrassCurve.hasGoodReduction_iff_isElliptic_reduction
#check NumberField.FinitePlace.embedding
#check IsDedekindDomain.HeightOneSpectrum.valuation
#check IsDedekindDomain.HeightOneSpectrum.valuation_exists_uniformizer
#check padicValRat
#check padicValRat.mul
#check Set.Finite
#check Finite.of_injective
#check Fintype.ofFinite
#check AddMonoid.ExponentExists
#check AddMonoid.exponent
#check AddMonoid.exponent_nsmul_eq_zero
#check AddMonoid.exponent_dvd_iff_forall_nsmul_eq_zero
#check is_add_torsion_of_finite
#check IsAddTorsion.exponentExists
#check AddCommMonoid.primaryComponent
#check AddCommMonoid.mem_primaryComponent
#check Ideal.primaryComponent
#check Ideal.iSup_primaryComponent_eq_top
