import FLT.Assumptions.MazurProof.RationalPointsN25CanonicalSourceBridge
import FLT.Assumptions.MazurProof.RationalPointsN25QuotientF2
import FLT.Assumptions.MazurProof.RationalPointsN25QuotientTwoMiddleRiemannRoch
import FLT.Assumptions.MazurProof.RationalPointsN25DegreeTwoPullback
import FLT.Assumptions.MazurProof.CyclicExclusion25

#print axioms MazurProof.RationalPointsN25CanonicalPoints.canonical_point_with_zero_coordinate_is_cusp
#print axioms MazurProof.RationalPointsN25CanonicalPoints.all_coordinates_ne_zero_of_not_cusp
#print axioms MazurProof.RationalPointsN25CanonicalPoints.noncuspidal_point_to_plane_sextic
#print axioms MazurProof.RationalPointsN25CanonicalSourceBridge.tateCanonicalCoordinates25_nonzero
#print axioms MazurProof.RationalPointsN25CanonicalSourceBridge.tateCanonicalCoordinates25_onCanonical
#print axioms MazurProof.RationalPointsN25CanonicalSourceBridge.tateCanonicalCoordinates25_not_isCusp
#print axioms MazurProof.RationalPointsN25QuotientF2.canonical_point25F2_iff_cusp
#print axioms MazurProof.RationalPointsN25QuotientMiddleRiemannRoch.picardZero_card_eq_seventy_one_of_two_hyperplane_rr
#print axioms MazurProof.RationalPointsN25ReductionCardinality.natCard_dvd_seventy_one_of_two_reductions
#print axioms MazurProof.RationalPointsN25DegreeTwoPullback.pull_injective_of_two_reductions_and_norm_comp_eq_two
#print axioms MazurProof.CyclicExclusion25.no_explicit_order25_obstruction
#print axioms MazurProof.CyclicExclusion25.no_rational_point_of_order_25
