module

public import Mathlib.NumberTheory.EllipticDivisibilitySequence
public import Mathlib.Tactic

namespace FLT.EDS

variable {R : Type*} [CommRing R]

/-- The adjacent Somos relation at an integer index. -/
@[expose] public def AdjRel (b c d : R) (m : ℤ) : Prop :=
  normEDS b c d (m + 2) * normEDS b c d (m - 2)
    = b ^ 2 * normEDS b c d (m + 1) * normEDS b c d (m - 1)
        - c * normEDS b c d m ^ 2

private lemma h5_eq (b c d : R) : normEDS b c d 5 = d * b ^ 4 - c ^ 3 := by
  have h := normEDS_odd b c d 2
  norm_num [normEDS_one, normEDS_two, normEDS_three, normEDS_four] at h
  linear_combination h

public lemma adjRel_zero (b c d : R) : AdjRel b c d 0 := by
  unfold AdjRel
  norm_num [normEDS_zero, normEDS_one, normEDS_two, normEDS_neg] <;> ring

public lemma adjRel_one (b c d : R) : AdjRel b c d 1 := by
  unfold AdjRel
  norm_num [normEDS_zero, normEDS_one, normEDS_two, normEDS_three, normEDS_neg] <;> ring

public lemma adjRel_two (b c d : R) : AdjRel b c d 2 := by
  unfold AdjRel
  norm_num [normEDS_zero, normEDS_one, normEDS_two, normEDS_three, normEDS_four] <;> ring

public lemma adjRel_three (b c d : R) : AdjRel b c d 3 := by
  unfold AdjRel
  norm_num [normEDS_one, normEDS_two, normEDS_three, normEDS_four, h5_eq] <;> ring

public lemma adjRel_four (b c d : R) : AdjRel b c d 4 := by
  unfold AdjRel
  have e6 := normEDS_even b c d 3
  norm_num [normEDS_one, normEDS_two, normEDS_three, normEDS_four, h5_eq] at e6 ⊢
  linear_combination e6

/-- Odd recurrence step, direct in any `CommRing` (LHS is odd·odd, no `b`-factor to clear).
Cofactors generated by Gröbner reduction (sympy, remainder 0). -/
public lemma oddStep (b c d : R) (M : ℤ)
    (h2 : AdjRel b c d (M + 2)) (h3 : AdjRel b c d (M + 3)) :
    AdjRel b c d (2 * M + 5) := by
  unfold AdjRel at h2 h3 ⊢
  simp only [show (M+2+2:ℤ)=M+4 by ring, show (M+2-2:ℤ)=M by ring, show (M+2+1:ℤ)=M+3 by ring,
    show (M+2-1:ℤ)=M+1 by ring, show (M+3+2:ℤ)=M+5 by ring, show (M+3-2:ℤ)=M+1 by ring,
    show (M+3+1:ℤ)=M+4 by ring, show (M+3-1:ℤ)=M+2 by ring,
    show (2*M+5+2:ℤ)=2*M+7 by ring, show (2*M+5-2:ℤ)=2*M+3 by ring,
    show (2*M+5+1:ℤ)=2*M+6 by ring, show (2*M+5-1:ℤ)=2*M+4 by ring] at h2 h3 ⊢
  have o7 : normEDS b c d (2*M+7)
      = normEDS b c d (M+5) * normEDS b c d (M+3)^3 - normEDS b c d (M+2) * normEDS b c d (M+4)^3 := by
    rw [show (2*M+7:ℤ) = 2*(M+3)+1 by ring, normEDS_odd b c d (M+3),
        show ((M+3)+2:ℤ)=M+5 by ring, show ((M+3)-1:ℤ)=M+2 by ring, show ((M+3)+1:ℤ)=M+4 by ring]
  have o3 : normEDS b c d (2*M+3)
      = normEDS b c d (M+3) * normEDS b c d (M+1)^3 - normEDS b c d M * normEDS b c d (M+2)^3 := by
    rw [show (2*M+3:ℤ) = 2*(M+1)+1 by ring, normEDS_odd b c d (M+1),
        show ((M+1)+2:ℤ)=M+3 by ring, show ((M+1)-1:ℤ)=M by ring, show ((M+1)+1:ℤ)=M+2 by ring]
  have o5 : normEDS b c d (2*M+5)
      = normEDS b c d (M+4) * normEDS b c d (M+2)^3 - normEDS b c d (M+1) * normEDS b c d (M+3)^3 := by
    rw [show (2*M+5:ℤ) = 2*(M+2)+1 by ring, normEDS_odd b c d (M+2),
        show ((M+2)+2:ℤ)=M+4 by ring, show ((M+2)-1:ℤ)=M+1 by ring, show ((M+2)+1:ℤ)=M+3 by ring]
  have e6 : normEDS b c d (2*M+6) * b
      = normEDS b c d (M+2)^2 * normEDS b c d (M+3) * normEDS b c d (M+5)
        - normEDS b c d (M+1) * normEDS b c d (M+3) * normEDS b c d (M+4)^2 := by
    rw [show (2*M+6:ℤ) = 2*(M+3) by ring, normEDS_even b c d (M+3),
        show ((M+3)-1:ℤ)=M+2 by ring, show ((M+3)-2:ℤ)=M+1 by ring, show ((M+3)+2:ℤ)=M+5 by ring,
        show ((M+3)+1:ℤ)=M+4 by ring]
  have e4 : normEDS b c d (2*M+4) * b
      = normEDS b c d (M+1)^2 * normEDS b c d (M+2) * normEDS b c d (M+4)
        - normEDS b c d M * normEDS b c d (M+2) * normEDS b c d (M+3)^2 := by
    rw [show (2*M+4:ℤ) = 2*(M+2) by ring, normEDS_even b c d (M+2),
        show ((M+2)-1:ℤ)=M+1 by ring, show ((M+2)-2:ℤ)=M by ring, show ((M+2)+2:ℤ)=M+4 by ring,
        show ((M+2)+1:ℤ)=M+3 by ring]
  linear_combination
      (normEDS b c d (2*M+3)) * o7
    + (- normEDS b c d (M+2) * normEDS b c d (M+4)^3 + normEDS b c d (M+3)^3 * normEDS b c d (M+5)) * o3
    + (- b * normEDS b c d (2*M+4)) * e6
    + (normEDS b c d (M+1) * normEDS b c d (M+3) * normEDS b c d (M+4)^2
        - normEDS b c d (M+2)^2 * normEDS b c d (M+3) * normEDS b c d (M+5)) * e4
    + (- c * normEDS b c d (M+1) * normEDS b c d (M+3)^3 + c * normEDS b c d (M+2)^3 * normEDS b c d (M+4)
        + c * normEDS b c d (2*M+5)) * o5
    + (- normEDS b c d (M+1) * normEDS b c d (M+2) * normEDS b c d (M+3)^3 * normEDS b c d (M+4)
        + normEDS b c d (M+2)^4 * normEDS b c d (M+4)^2) * h2
    + (normEDS b c d (M+1)^2 * normEDS b c d (M+3)^4
        - normEDS b c d (M+1) * normEDS b c d (M+2)^3 * normEDS b c d (M+3) * normEDS b c d (M+4)) * h3

/-- Even recurrence step, b²-SCALED.  The LHS is even·even, so each factor carries an intrinsic
`b` (from `normEDS_even`) that does not cancel over a general `CommRing`.  Cofactors generated by
Gröbner reduction (sympy, remainder 0). -/
public lemma evenStepScaled (b c d : R) (M : ℤ)
    (h2 : AdjRel b c d (M + 2)) (h3 : AdjRel b c d (M + 3)) (h4 : AdjRel b c d (M + 4)) :
    b ^ 2 * (normEDS b c d (2*M+8) * normEDS b c d (2*M+4)
      - (b ^ 2 * normEDS b c d (2*M+7) * normEDS b c d (2*M+5) - c * normEDS b c d (2*M+6) ^ 2)) = 0 := by
  unfold AdjRel at h2 h3 h4
  simp only [show (M+2+2:ℤ)=M+4 by ring, show (M+2-2:ℤ)=M by ring, show (M+2+1:ℤ)=M+3 by ring,
    show (M+2-1:ℤ)=M+1 by ring, show (M+3+2:ℤ)=M+5 by ring, show (M+3-2:ℤ)=M+1 by ring,
    show (M+3+1:ℤ)=M+4 by ring, show (M+3-1:ℤ)=M+2 by ring, show (M+4+2:ℤ)=M+6 by ring,
    show (M+4-2:ℤ)=M+2 by ring, show (M+4+1:ℤ)=M+5 by ring, show (M+4-1:ℤ)=M+3 by ring] at h2 h3 h4
  have e8 : normEDS b c d (2*M+8) * b
      = normEDS b c d (M+3)^2 * normEDS b c d (M+4) * normEDS b c d (M+6)
        - normEDS b c d (M+2) * normEDS b c d (M+4) * normEDS b c d (M+5)^2 := by
    rw [show (2*M+8:ℤ) = 2*(M+4) by ring, normEDS_even b c d (M+4),
        show ((M+4)-1:ℤ)=M+3 by ring, show ((M+4)+2:ℤ)=M+6 by ring, show ((M+4)-2:ℤ)=M+2 by ring,
        show ((M+4)+1:ℤ)=M+5 by ring]
  have e6 : normEDS b c d (2*M+6) * b
      = normEDS b c d (M+2)^2 * normEDS b c d (M+3) * normEDS b c d (M+5)
        - normEDS b c d (M+1) * normEDS b c d (M+3) * normEDS b c d (M+4)^2 := by
    rw [show (2*M+6:ℤ) = 2*(M+3) by ring, normEDS_even b c d (M+3),
        show ((M+3)-1:ℤ)=M+2 by ring, show ((M+3)-2:ℤ)=M+1 by ring, show ((M+3)+2:ℤ)=M+5 by ring,
        show ((M+3)+1:ℤ)=M+4 by ring]
  have e4 : normEDS b c d (2*M+4) * b
      = normEDS b c d (M+1)^2 * normEDS b c d (M+2) * normEDS b c d (M+4)
        - normEDS b c d M * normEDS b c d (M+2) * normEDS b c d (M+3)^2 := by
    rw [show (2*M+4:ℤ) = 2*(M+2) by ring, normEDS_even b c d (M+2),
        show ((M+2)-1:ℤ)=M+1 by ring, show ((M+2)-2:ℤ)=M by ring, show ((M+2)+2:ℤ)=M+4 by ring,
        show ((M+2)+1:ℤ)=M+3 by ring]
  have o7 : normEDS b c d (2*M+7)
      = normEDS b c d (M+5) * normEDS b c d (M+3)^3 - normEDS b c d (M+2) * normEDS b c d (M+4)^3 := by
    rw [show (2*M+7:ℤ) = 2*(M+3)+1 by ring, normEDS_odd b c d (M+3),
        show ((M+3)+2:ℤ)=M+5 by ring, show ((M+3)-1:ℤ)=M+2 by ring, show ((M+3)+1:ℤ)=M+4 by ring]
  have o5 : normEDS b c d (2*M+5)
      = normEDS b c d (M+4) * normEDS b c d (M+2)^3 - normEDS b c d (M+1) * normEDS b c d (M+3)^3 := by
    rw [show (2*M+5:ℤ) = 2*(M+2)+1 by ring, normEDS_odd b c d (M+2),
        show ((M+2)+2:ℤ)=M+4 by ring, show ((M+2)-1:ℤ)=M+1 by ring, show ((M+2)+1:ℤ)=M+3 by ring]
  linear_combination
      (b * normEDS b c d (2*M+4)) * e8
    + (b * c * normEDS b c d (2*M+6) - c * normEDS b c d (M+1) * normEDS b c d (M+3) * normEDS b c d (M+4)^2
        + c * normEDS b c d (M+2)^2 * normEDS b c d (M+3) * normEDS b c d (M+5)) * e6
    + (- normEDS b c d (M+2) * normEDS b c d (M+4) * normEDS b c d (M+5)^2
        + normEDS b c d (M+3)^2 * normEDS b c d (M+4) * normEDS b c d (M+6)) * e4
    + (- b^4 * normEDS b c d (2*M+5)) * o7
    + (b^4 * normEDS b c d (M+2) * normEDS b c d (M+4)^3 - b^4 * normEDS b c d (M+3)^3 * normEDS b c d (M+5)) * o5
    + (normEDS b c d (M+2)^2 * normEDS b c d (M+3)^2 * normEDS b c d (M+5)^2
        - normEDS b c d (M+2) * normEDS b c d (M+3)^4 * normEDS b c d (M+6)) * h2
    + (b^2 * normEDS b c d (M+1) * normEDS b c d (M+3)^3 * normEDS b c d (M+4)^2
        - b^2 * normEDS b c d (M+2)^3 * normEDS b c d (M+4)^3
        + b^2 * normEDS b c d (M+2)^2 * normEDS b c d (M+3)^3 * normEDS b c d (M+5)
        - c * normEDS b c d (M+2)^2 * normEDS b c d (M+3)^2 * normEDS b c d (M+4)^2
        - normEDS b c d (M+1) * normEDS b c d (M+2)^2 * normEDS b c d (M+4)^2 * normEDS b c d (M+5)) * h3
    + (- b^2 * normEDS b c d (M+1) * normEDS b c d (M+3)^5
        + c * normEDS b c d (M+2)^2 * normEDS b c d (M+3)^4
        + normEDS b c d (M+1)^2 * normEDS b c d (M+3)^2 * normEDS b c d (M+4)^2) * h4

/-- Even step over a domain with `b ≠ 0`: cancel the intrinsic `b²`. -/
public lemma evenStep_of_regular {S : Type*} [CommRing S] [NoZeroDivisors S]
    (b c d : S) (hb : b ≠ 0) (M : ℤ)
    (h2 : AdjRel b c d (M + 2)) (h3 : AdjRel b c d (M + 3)) (h4 : AdjRel b c d (M + 4)) :
    AdjRel b c d (2 * M + 6) := by
  have hsc := evenStepScaled b c d M h2 h3 h4
  have hb2 : (b ^ 2 : S) ≠ 0 := pow_ne_zero 2 hb
  have hdiff : normEDS b c d (2*M+8) * normEDS b c d (2*M+4)
      - (b ^ 2 * normEDS b c d (2*M+7) * normEDS b c d (2*M+5) - c * normEDS b c d (2*M+6) ^ 2) = 0 :=
    (mul_eq_zero.mp hsc).resolve_left hb2
  unfold AdjRel
  simp only [show (2*M+6+2:ℤ)=2*M+8 by ring, show (2*M+6-2:ℤ)=2*M+4 by ring,
    show (2*M+6+1:ℤ)=2*M+7 by ring, show (2*M+6-1:ℤ)=2*M+5 by ring]
  linear_combination hdiff

/-- Adjacent Somos over the universal ring `MvPolynomial (Fin 3) ℤ`, where `b = X 0` is a
non-zero-divisor — so the even step's `b²` cancels.  Transported to general `R` below. -/
private lemma adjRel_univ (n : ℕ) :
    AdjRel (MvPolynomial.X (0 : Fin 3) : MvPolynomial (Fin 3) ℤ)
      (MvPolynomial.X 1) (MvPolynomial.X 2) (n : ℤ) := by
  set b : MvPolynomial (Fin 3) ℤ := MvPolynomial.X 0 with hb_def
  set c : MvPolynomial (Fin 3) ℤ := MvPolynomial.X 1
  set d : MvPolynomial (Fin 3) ℤ := MvPolynomial.X 2
  refine normEDSRec (P := fun n => AdjRel b c d (n : ℤ))
    (adjRel_zero b c d) (adjRel_one b c d) (adjRel_two b c d) (adjRel_three b c d)
    (adjRel_four b c d) ?heven ?hodd n
  · intro m h1 h2 h3 h4 h5
    have hb : b ≠ 0 := by rw [hb_def]; exact MvPolynomial.X_ne_zero 0
    have hc2 : ((m+2:ℕ):ℤ) = (m:ℤ)+2 := by push_cast; ring
    have hc3 : ((m+3:ℕ):ℤ) = (m:ℤ)+3 := by push_cast; ring
    have hc4 : ((m+4:ℕ):ℤ) = (m:ℤ)+4 := by push_cast; ring
    have hcg : ((2*(m+3):ℕ):ℤ) = 2*(m:ℤ)+6 := by push_cast; ring
    rw [hc2] at h2; rw [hc3] at h3; rw [hc4] at h4; rw [hcg]
    exact evenStep_of_regular b c d hb (m:ℤ) h2 h3 h4
  · intro m h1 h2 h3 h4
    have hc2 : ((m+2:ℕ):ℤ) = (m:ℤ)+2 := by push_cast; ring
    have hc3 : ((m+3:ℕ):ℤ) = (m:ℤ)+3 := by push_cast; ring
    have hcg : ((2*(m+2)+1:ℕ):ℤ) = 2*(m:ℤ)+5 := by push_cast; ring
    rw [hc2] at h2; rw [hc3] at h3; rw [hcg]
    exact oddStep b c d (m:ℤ) h2 h3

/-- Natural-index adjacent Somos relation: transport `adjRel_univ` along the evaluation hom
`MvPolynomial (Fin 3) ℤ →+* R`, `X 0,1,2 ↦ b,c,d`, using `map_normEDS`. -/
public theorem normEDS_adjacent_somos_nat (b c d : R) (n : ℕ) :
    AdjRel b c d (n : ℤ) := by
  have huniv := adjRel_univ n
  let f : MvPolynomial (Fin 3) ℤ →+* R := MvPolynomial.eval₂Hom (Int.castRingHom R) ![b, c, d]
  have hX0 : f (MvPolynomial.X 0) = b := by simp [f]
  have hX1 : f (MvPolynomial.X 1) = c := by simp [f]
  have hX2 : f (MvPolynomial.X 2) = d := by simp [f]
  unfold AdjRel at huniv ⊢
  have hmap := congrArg f huniv
  simpa only [map_mul, map_sub, map_pow, map_normEDS, hX0, hX1, hX2] using hmap

public lemma adjRel_neg_iff (b c d : R) (m : ℤ) :
    AdjRel b c d (-m) ↔ AdjRel b c d m := by
  unfold AdjRel
  have e1 : normEDS b c d (-m + 2) = -normEDS b c d (m - 2) := by
    rw [show -m + 2 = -(m - 2) by ring, normEDS_neg]
  have e2 : normEDS b c d (-m - 2) = -normEDS b c d (m + 2) := by
    rw [show -m - 2 = -(m + 2) by ring, normEDS_neg]
  have e3 : normEDS b c d (-m + 1) = -normEDS b c d (m - 1) := by
    rw [show -m + 1 = -(m - 1) by ring, normEDS_neg]
  have e4 : normEDS b c d (-m - 1) = -normEDS b c d (m + 1) := by
    rw [show -m - 1 = -(m + 1) by ring, normEDS_neg]
  have e5 : normEDS b c d (-m) = -normEDS b c d m := normEDS_neg b c d m
  rw [e1, e2, e3, e4, e5]
  constructor <;> intro h <;> linear_combination h

/-- Full integer-index adjacent Somos relation, conditional only on `adjRelRecSteps`. -/
public theorem normEDS_adjacent_somos (b c d : R) (m : ℤ) :
    normEDS b c d (m + 2) * normEDS b c d (m - 2)
      = b ^ 2 * normEDS b c d (m + 1) * normEDS b c d (m - 1)
          - c * normEDS b c d m ^ 2 := by
  change AdjRel b c d m
  rcases le_total 0 m with hm | hm
  · have hnat : AdjRel b c d ((m.toNat : ℕ) : ℤ) :=
      normEDS_adjacent_somos_nat b c d m.toNat
    have hcast : ((m.toNat : ℕ) : ℤ) = m := Int.toNat_of_nonneg hm
    simpa [hcast] using hnat
  · have hneg_nonneg : 0 ≤ -m := by omega
    have hnat : AdjRel b c d (((-m).toNat : ℕ) : ℤ) :=
      normEDS_adjacent_somos_nat b c d (-m).toNat
    have hcast : (((-m).toNat : ℕ) : ℤ) = -m := Int.toNat_of_nonneg hneg_nonneg
    have hneg : AdjRel b c d (-m) := by
      simpa [hcast] using hnat
    exact (adjRel_neg_iff b c d m).mp hneg

end FLT.EDS
