import FLT.Assumptions.MazurProof.N25F_InfinityBoundaryCenters

#print axioms MazurProof.N25F_InfinityBoundaryCenters.infinityParameter
#print axioms MazurProof.N25F_InfinityBoundaryCenters.infinityParameter_ne_zero
#print axioms MazurProof.N25F_InfinityBoundaryCenters.xInfinityPrime
#print axioms MazurProof.N25F_InfinityBoundaryCenters.xInfinityPrime_isPrime
#print axioms MazurProof.N25F_InfinityBoundaryCenters.infinityParameter_mem_xInfinityPrime
#print axioms MazurProof.N25F_InfinityBoundaryCenters.xInfinityPrime_ne_bot
#print axioms MazurProof.N25F_InfinityBoundaryCenters.xInfinityPrime_isMaximal
#print axioms MazurProof.N25F_InfinityBoundaryCenters.yzInfinityPrime
#print axioms MazurProof.N25F_InfinityBoundaryCenters.yzInfinityPrime_isPrime
#print axioms MazurProof.N25F_InfinityBoundaryCenters.infinityParameter_mem_yzInfinityPrime
#print axioms MazurProof.N25F_InfinityBoundaryCenters.yzInfinityPrime_ne_bot
#print axioms MazurProof.N25F_InfinityBoundaryCenters.yzInfinityPrime_isMaximal
#print axioms MazurProof.N25F_InfinityBoundaryCenters.zInfinityPrime
#print axioms MazurProof.N25F_InfinityBoundaryCenters.zInfinityPrime_isPrime
#print axioms MazurProof.N25F_InfinityBoundaryCenters.infinityParameter_mem_zInfinityPrime
#print axioms MazurProof.N25F_InfinityBoundaryCenters.zInfinityPrime_ne_bot
#print axioms MazurProof.N25F_InfinityBoundaryCenters.zInfinityPrime_isMaximal
