import Mathlib.RingTheory.DedekindDomain.Factorization
import Mathlib.RingTheory.Ideal.Norm.AbsNorm
import Mathlib.RingTheory.Finiteness.Cardinality
import Mathlib.FieldTheory.Finiteness


/-!
# Divisors from Dedekind-domain factorization

For a Dedekind domain, every nonzero fractional ideal has a finite height-one
valuation vector.  This file packages that vector as a `Finsupp`, proves that
it determines the fractional ideal, and constructs the subgroup of principal
divisors from nonzero elements of the fraction field.

This is the affine algebra underlying the divisor-class input used by the
curve zeta argument.  Applying it to a projective curve still requires the
geometric comparison between its closed points and height-one local data,
including the points outside any chosen affine chart.
-/

open scoped nonZeroDivisors

open IsDedekindDomain

noncomputable section

namespace MazurProof.CurveDedekindDivisor

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
variable {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]

/-- A Weil divisor on the spectrum of a Dedekind domain is a finite integer
combination of its height-one prime ideals. -/
abbrev Divisor := HeightOneSpectrum R →₀ ℤ

/-- The height-one valuation vector of a fractional ideal.  The finite support
is supplied by Dedekind factorization. -/
def fractionalIdealDivisor (I : FractionalIdeal R⁰ K) : Divisor (R := R) := by
  let support : Set (HeightOneSpectrum R) :=
    {v | FractionalIdeal.count K v I ≠ 0}
  have hsupport : support.Finite := by
    exact Filter.eventually_cofinite.mp (FractionalIdeal.finite_factors (K := K) I)
  exact Finsupp.onFinset hsupport.toFinset
    (fun v ↦ FractionalIdeal.count K v I)
    (fun v hv ↦ hsupport.mem_toFinset.mpr hv)

@[simp]
theorem fractionalIdealDivisor_apply (I : FractionalIdeal R⁰ K)
    (v : HeightOneSpectrum R) :
    fractionalIdealDivisor I v = FractionalIdeal.count K v I := by
  rfl

/-- Multiplication of nonzero fractional ideals adds their valuation vectors. -/
theorem fractionalIdealDivisor_mul {I J : FractionalIdeal R⁰ K}
    (hI : I ≠ 0) (hJ : J ≠ 0) :
    fractionalIdealDivisor (I * J) =
      fractionalIdealDivisor I + fractionalIdealDivisor J := by
  ext v
  simp only [fractionalIdealDivisor_apply, Finsupp.add_apply]
  exact FractionalIdeal.count_mul K v hI hJ

/-- Nonzero fractional ideals are determined by their height-one valuation
vectors.  This is the uniqueness half of Dedekind factorization in divisor
form. -/
theorem fractionalIdealDivisor_injectiveOn_nonzero
    {I J : FractionalIdeal R⁰ K} (hI : I ≠ 0) (hJ : J ≠ 0)
    (hdiv : fractionalIdealDivisor I = fractionalIdealDivisor J) : I = J := by
  calc
    I = ∏ᶠ v : HeightOneSpectrum R,
        (v.asIdeal : FractionalIdeal R⁰ K) ^ FractionalIdeal.count K v I :=
      (FractionalIdeal.finprod_heightOneSpectrum_factorization' K hI).symm
    _ = ∏ᶠ v : HeightOneSpectrum R,
        (v.asIdeal : FractionalIdeal R⁰ K) ^ FractionalIdeal.count K v J := by
      apply finprod_congr
      intro v
      congr 1
      simpa only [fractionalIdealDivisor_apply] using DFunLike.congr_fun hdiv v
    _ = J := FractionalIdeal.finprod_heightOneSpectrum_factorization' K hJ

/-- Principal fractional ideals define an additive homomorphism from nonzero
functions under multiplication to height-one divisors. -/
def principalDivisor : Additive Kˣ →+ Divisor (R := R) where
  toFun x := fractionalIdealDivisor
    (FractionalIdeal.spanSingleton R⁰ (x.toMul : K))
  map_zero' := by
    ext v
    change FractionalIdeal.count K v
      (FractionalIdeal.spanSingleton R⁰ (1 : K)) = 0
    rw [FractionalIdeal.spanSingleton_one, FractionalIdeal.count_one]
  map_add' x y := by
    change fractionalIdealDivisor
      (FractionalIdeal.spanSingleton R⁰ ((x.toMul * y.toMul : Kˣ) : K)) = _
    rw [Units.val_mul, ← FractionalIdeal.spanSingleton_mul_spanSingleton]
    apply fractionalIdealDivisor_mul
    · exact FractionalIdeal.spanSingleton_ne_zero_iff.mpr x.toMul.ne_zero
    · exact FractionalIdeal.spanSingleton_ne_zero_iff.mpr y.toMul.ne_zero

/-- The subgroup generated by divisors of nonzero fraction-field elements. -/
def principalDivisors : AddSubgroup (Divisor (R := R)) :=
  (principalDivisor (R := R) (K := K)).range

end MazurProof.CurveDedekindDivisor



set_option autoImplicit false
set_option relaxedAutoImplicit false

open scoped BigOperators

namespace MazurProof.DedekindQuotientDegree

open UniqueFactorizationMonoid

variable {S : Type*} [CommRing S] [IsDedekindDomain S]

/-- A nonzero ideal's quotient dimension is the sum of its factor multiplicities
weighted by the actual finite-field residue dimensions. -/
theorem finrank_quotient_eq_sum_factors (k : Type*) [Field k] [Finite k]
    [Algebra k S] (I : Ideal S) (hI : I ≠ ⊥) [Module.Finite k (S ⧸ I)] :
    Module.finrank k (S ⧸ I) =
      ∑ P ∈ (factors I).toFinset,
        (factors I).count P * Module.finrank k (S ⧸ P) := by
  classical
  haveI : Finite (S ⧸ I) := Module.finite_of_finite k
  apply Nat.pow_right_injective (Finite.one_lt_card : 2 ≤ Nat.card k)
  dsimp only
  rw [← Module.natCard_eq_pow_finrank]
  calc
    Nat.card (S ⧸ I) =
        Nat.card (∀ P : (factors I).toFinset,
          S ⧸ (P : Ideal S) ^ (factors I).count (P : Ideal S)) :=
      Nat.card_congr (IsDedekindDomain.quotientEquivPiFactors hI).toEquiv
    _ = ∏ P : (factors I).toFinset,
        Nat.card (S ⧸ (P : Ideal S) ^ (factors I).count (P : Ideal S)) := Nat.card_pi
    _ = ∏ P : (factors I).toFinset,
        Nat.card k ^ ((factors I).count (P : Ideal S) *
          Module.finrank k (S ⧸ (P : Ideal S))) := by
      apply Finset.prod_congr rfl
      intro P _
      have hmem : (P : Ideal S) ∈ factors I := Multiset.mem_toFinset.mp P.property
      have hprime : Prime (P : Ideal S) := prime_of_factor _ hmem
      haveI : (P : Ideal S).IsPrime := Ideal.isPrime_of_prime hprime
      have hle : I ≤ (P : Ideal S) := Ideal.dvd_iff_le.mp (dvd_of_mem_factors hmem)
      haveI : Finite (S ⧸ (P : Ideal S)) :=
        Finite.of_surjective (Ideal.Quotient.factor hle)
          (Ideal.Quotient.factor_surjective hle)
      calc
        Nat.card (S ⧸ (P : Ideal S) ^ (factors I).count (P : Ideal S)) =
            Nat.card (S ⧸ (P : Ideal S)) ^ (factors I).count (P : Ideal S) :=
          cardQuot_pow_of_prime hprime.ne_zero
        _ = Nat.card k ^ ((factors I).count (P : Ideal S) *
            Module.finrank k (S ⧸ (P : Ideal S))) := by
          rw [Module.natCard_eq_pow_finrank (K := k), ← pow_mul, Nat.mul_comm]
    _ = Nat.card k ^ (∑ P : (factors I).toFinset,
        (factors I).count (P : Ideal S) * Module.finrank k (S ⧸ (P : Ideal S))) :=
      Finset.prod_pow_eq_pow_sum _ _ _
    _ = Nat.card k ^ (∑ P ∈ (factors I).toFinset,
        (factors I).count P * Module.finrank k (S ⧸ P)) := by
      exact congrArg (fun n : ℕ => Nat.card k ^ n)
        ((factors I).toFinset.sum_coe_sort
          (fun P => (factors I).count P * Module.finrank k (S ⧸ P)))

/-- The normalized-factor version uses exactly the canonical multiplicities
appearing in Dedekind valuations. -/
theorem finrank_quotient_eq_sum_normalizedFactors (k : Type*) [Field k] [Finite k]
    [Algebra k S] (I : Ideal S) (hI : I ≠ ⊥) [Module.Finite k (S ⧸ I)] :
    Module.finrank k (S ⧸ I) =
      ∑ P ∈ (normalizedFactors I).toFinset,
        (normalizedFactors I).count P * Module.finrank k (S ⧸ P) := by
  simpa only [factors_eq_normalizedFactors] using finrank_quotient_eq_sum_factors k I hI

end MazurProof.DedekindQuotientDegree


set_option autoImplicit false
set_option relaxedAutoImplicit false

open scoped nonZeroDivisors

namespace MazurProof.DedekindQuotientDegree

variable {S : Type*} [CommRing S] [IsDedekindDomain S]
variable (K : Type*) [Field K] [Algebra S K] [IsFractionRing S K]

/-- The fractional-ideal valuation of a nonzero regular function is exactly
its principal ideal's normalized-factor multiplicity. -/
theorem count_spanSingleton_eq_normalizedFactors
    (a : S) (ha : a ≠ 0) (v : IsDedekindDomain.HeightOneSpectrum S) :
    FractionalIdeal.count K v
        (FractionalIdeal.spanSingleton S⁰ (algebraMap S K a)) =
      ((UniqueFactorizationMonoid.normalizedFactors
        (Ideal.span ({a} : Set S))).count v.asIdeal : ℤ) := by
  have hI : Ideal.span ({a} : Set S) ≠ 0 :=
    Ideal.span_singleton_eq_bot.not.mpr ha
  rw [← FractionalIdeal.coeIdeal_span_singleton,
    FractionalIdeal.count_coe K v hI,
    Ideal.count_associates_factors_eq hI v.isPrime v.ne_bot]

end MazurProof.DedekindQuotientDegree


set_option autoImplicit false
set_option relaxedAutoImplicit false

open scoped nonZeroDivisors BigOperators

namespace MazurProof.CurveDedekindDivisor

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
variable {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]

/-- The existing principal-divisor coefficient of a nonzero regular function
is its actual principal ideal's normalized-factor multiplicity. -/
theorem principalDivisor_regular_apply (a : R) (ha : a ≠ 0)
    (f : Additive Kˣ) (hf : (f.toMul : K) = algebraMap R K a)
    (v : IsDedekindDomain.HeightOneSpectrum R) :
    principalDivisor f v =
      ((UniqueFactorizationMonoid.normalizedFactors
        (Ideal.span ({a} : Set R))).count v.asIdeal : ℤ) := by
  change FractionalIdeal.count K v
    (FractionalIdeal.spanSingleton R⁰ (f.toMul : K)) = _
  rw [hf]
  exact MazurProof.DedekindQuotientDegree.count_spanSingleton_eq_normalizedFactors K a ha v

/-- The weighted degree of the existing affine principal divisor of a regular
function is the dimension of its quotient algebra over the finite base field. -/
theorem principalDivisor_degree_eq_quotient_finrank
    (k : Type*) [Field k] [Finite k] [Algebra k R]
    (a : R) (ha : a ≠ 0) [Module.Finite k (R ⧸ Ideal.span ({a} : Set R))]
    (f : Additive Kˣ) (hf : (f.toMul : K) = algebraMap R K a) :
    (principalDivisor f).sum
        (fun v n => n * (Module.finrank k (R ⧸ v.asIdeal) : ℤ)) =
      (Module.finrank k (R ⧸ Ideal.span ({a} : Set R)) : ℤ) := by
  classical
  let I : Ideal R := Ideal.span ({a} : Set R)
  have hI : I ≠ ⊥ := Ideal.span_singleton_eq_bot.not.mpr ha
  have hcoeff (v : IsDedekindDomain.HeightOneSpectrum R) :
      principalDivisor f v =
        ((UniqueFactorizationMonoid.normalizedFactors I).count v.asIdeal : ℤ) :=
    principalDivisor_regular_apply a ha f hf v
  calc
    (principalDivisor f).sum
        (fun v n => n * (Module.finrank k (R ⧸ v.asIdeal) : ℤ)) =
      ∑ P ∈ (UniqueFactorizationMonoid.normalizedFactors I).toFinset,
        ((UniqueFactorizationMonoid.normalizedFactors I).count P : ℤ) *
          (Module.finrank k (R ⧸ P) : ℤ) := by
      unfold Finsupp.sum
      apply Finset.sum_bij (fun v _ => v.asIdeal)
      · intro v hv
        have hne := Finsupp.mem_support_iff.mp hv
        rw [hcoeff] at hne
        simp only [Multiset.mem_toFinset, ← Multiset.count_pos, Nat.pos_iff_ne_zero]
        exact_mod_cast hne
      · intro v hv w hw h
        exact IsDedekindDomain.HeightOneSpectrum.ext h
      · intro P hP
        have hmem := Multiset.mem_toFinset.mp hP
        have hp := UniqueFactorizationMonoid.prime_of_normalized_factor P hmem
        let v : IsDedekindDomain.HeightOneSpectrum R :=
          ⟨P, Ideal.isPrime_of_prime hp, hp.ne_zero⟩
        refine ⟨v, ?_, rfl⟩
        rw [Finsupp.mem_support_iff, hcoeff]
        exact_mod_cast (ne_of_gt (Multiset.count_pos.mpr hmem))
      · intro v hv
        rw [hcoeff]
    _ = (Module.finrank k (R ⧸ I) : ℤ) := by
      exact_mod_cast
        (MazurProof.DedekindQuotientDegree.finrank_quotient_eq_sum_normalizedFactors
          k I hI).symm

end MazurProof.CurveDedekindDivisor

#print axioms MazurProof.CurveDedekindDivisor.principalDivisor_degree_eq_quotient_finrank
