import FLT.Assumptions.MazurProof.N25F_InfinityLocalizations
import FLT.Assumptions.MazurProof.N25F_OrderRingEquiv

#print axioms MazurProof.N25F_CenterLocalization.centerLocalizationMap
#print axioms MazurProof.N25F_CenterLocalization.centerLocalizationMap_algebraMap
#print axioms MazurProof.N25F_CenterLocalization.centerLocalizationMap_isLocalHom
#print axioms MazurProof.N25F_CenterLocalization.centerLocalizationMap_bijective
#print axioms MazurProof.N25F_CenterLocalization.centerLocalizationEquiv
#print axioms MazurProof.N25F_InfinityLocalizations.xInfinityLocalizationEquiv
#print axioms MazurProof.N25F_InfinityLocalizations.xInfinityLocalizationEquiv_algebraMap
#print axioms MazurProof.N25F_InfinityLocalizations.xLocalToFraction_localization_algebraMap
#print axioms MazurProof.N25F_InfinityLocalizations.yzInfinityLocalizationEquiv
#print axioms MazurProof.N25F_InfinityLocalizations.yzInfinityLocalizationEquiv_algebraMap
#print axioms MazurProof.N25F_InfinityLocalizations.yzLocalToFraction_localization_algebraMap
#print axioms MazurProof.N25F_InfinityLocalizations.zInfinityLocalizationEquiv
#print axioms MazurProof.N25F_InfinityLocalizations.zInfinityLocalizationEquiv_algebraMap
#print axioms MazurProof.N25F_InfinityLocalizations.zLocalToFraction_localization_algebraMap
#print axioms MazurProof.N25F_OrderRingEquiv.ord_map_ringEquiv
